### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by nWidart** [mcamara/laravel-localization#146]
Hi,

Is there any ETA you could give us on a laravel 5 compatible version?

Thank you,

**Comment by mcamara** [comment]
Hi guys,
I have started updating the package to the latest version of Laravel 5 (check the development branch).

Still a lot to do, I have to create middlewares and rewrite the documentation for the new ConfigServiceProvider functions but I will appreciate any help or guidance.

Thanks for your patience, I promise it will be ready when Laravel 5 is released but this is a good start :)

**Comment by mcamara** [comment]
v 1.0 has been released! Enjoy!
