### ISSUE TITLE
Unit testing localized routes

### ISSUE THREAD

**Issue by leonardoalifraco** [mcamara/laravel-localization#161]
Hello,

I'm trying to unit test calling to localized routes with a very simple test, but it is not working. I guess it is because the routes are loaded with the default prefix just one time on the testing flow.

On a browser, when the routes.php is excecuted for every request, everything works fine.

Is this an expected behaviour?
Am i doing something wrong?
Am i supposed to test this?

Here is the code of the test:

``` php
class ExampleTest extends TestCase {

    /**
     * A basic functional test example.
     *
     * @return void
     */
    public function testBasicExample()
    {
        $crawler = $this->client->request('GET', '/');

        $this->assertTrue($this->client->getResponse()->isOk());
    }

    /**
     * A basic functional test example with language.
     *
     * @return void
     */
    public function testBasicExampleWithLanguage()
    {
        $crawler = $this->client->request('GET', '/es');

        $this->assertTrue($this->client->getResponse()->isOk());
    }

}
```

And here is the error i'm getting when excecuting phpunit:

![image](https://cloud.githubusercontent.com/assets/2942943/5602970/2cfbf042-934e-11e4-8ed2-dfdb68fa243c.png)

My routes.php is:

``` php
Route::group(array('prefix' => LaravelLocalization::setLocale(), 
                   'before' => 'LaravelLocalizationRedirectFilter'), function()
{
    Route::get('/', function() {
        return 'home';
    });

    Route::get('test',function(){
        return 'test';
    });
});
```

**Comment by cariboufute** [comment]
Had the same problem too. Maybe I'm wrong but what I see in the vendor tests is that you have to reproduce all the route mapping in the test class to make it work. With this, you don't test the actual route mapping but a replica, which is not what you need to do. We need to test the actual route map.

Wonder how we could do this though...

**Comment by acaron** [comment]
+1 same problem with Behat! Behat just ran out of memory because of this... I will try to figure out what is happening!

**Comment by acaron** [comment]
+1 same problem with Behat.

**Comment by acaron** [comment]
After looking into the code, the function `LaravelLocalization::setLocale()` can return `null` or a `locale`. In the test case, it return `null`. If you force a value to always be return (from the `currentLocale`), all tests are ok but the redirection middleware is not working anymore (since it's not `null` anymore).

So, I looked in the `request` object and the test case was returning:
```
pathInfo: "/"
requestUri: "/"
```
instead of:
```
pathInfo: "/en/login"
requestUri: "/en/login"
```

So, the segment can never be fetch. We need a solution for testing!

**Comment by cariboufute** [comment]
+1 for testing solution. I abandoned this package for the moment and made my own, which is less elegant, but can be tested.

**Comment by osaris** [comment]
+1 this is really annoying to have all tests broken due to this package :-(

**Comment by okaufmann** [comment]
+1 have the same problem here. Is there already a fix fo this ?

**Comment by dsamojlenko** [comment]
Anyone have any further thoughts/suggestions on this?  Same problem here...

**Comment by cariboufute** [comment]
I made an alternate solution to this package but I did not package it yet. I may try to publish an alpha version of a package soon. The routes of my solution *are* unit testable.

**Comment by Mastergalen** [comment]
+1 Testability is quite important

**Comment by jaumeavila** [comment]
+1 I have the same problem. No solution yet?

**Comment by zachleigh** [comment]
+1 Anybody found a solution to this yet? This package seems great, but if its going to break all my tests, its pretty worthless.

**Comment by da-n** [comment]
+1 Shame that there is no solution to this, has anybody found a workaround? This is an awesome package but totally breaks all tests.

**Comment by wtom** [comment]
https://github.com/wtom/laravel-localization/commit/452a1c2992b96580e14a5f8ada58d2a16262dc59

is this a possible solution?

I call it in my createApplication() method in my TestCase.php.


```
public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
        app('laravellocalization')->setUnitTestingRoutes();

        return $app;
    }
```


I my test it's like this:
```
app('laravellocalization')->setLocale('en');
$url = app('laravellocalization')->getLocalizedURL('en', 'api/v1/test');
$this->json('GET', $url)
             ->seeJson([
                 'msg' => 'Hello World!',
             ]);
```

**Comment by cariboufute** [comment]
I am making my own localization routing project for Laravel here : https://github.com/cariboufute/locale-route. Their routes will be fully testable. It should be ready in a few weeks.

**Comment by JensJI** [comment]
This is a major problem. Using the localization plugin just broke our test suite for all http tests, and no of the proposed solutions seems applicable.

Maybe you, @mcamara , could take a look at this issue as you can see the big picture of the code?

**Comment by cariboufute** [comment]
I have mostly finished making my own localization routing package for Laravel : https://github.com/cariboufute/locale-route. The version is an alpha, but is already functional and should be set to beta really soon. Please check it... and this one is fully testable with the usual testing methods.

**Comment by aurawindsurfing** [comment]
For me different solution works:

Set: 'hideDefaultLocaleInURL' => env('LOCALIZATION_HIDE_DEFAULT_LOCALE', false)

And then in phpunit.xml:

<env name="LOCALIZATION_HIDE_DEFAULT_LOCALE" value="true"/>

Hope it helps someone!

**Comment by zedee** [comment]
That workaround is not working for me :(

I guess there's still no updates on this?

**Comment by marufmax** [comment]
+1 Having the same issue

**Comment by bertheyman** [comment]
Would love to find out if/when someone has a fix or workaround for this.
Tried [the one above](https://github.com/mcamara/laravel-localization/issues/161#issuecomment-381367191) with no luck.

**Comment by cariboufute** [comment]
Try my package : https://github.com/cariboufute/locale-route

It offers a testable alternate to this package and works well.

**Comment by V35CH** [comment]
Does anyone have a solution for this issue?

**Comment by mgralikowski** [comment]
For me (`useAcceptLanguageHeader = true`, `hideDefaultLocaleInURL = false`) it's works:

`'prefix' => !App::runningUnitTests() ? LaravelLocalization::setLocale(null) : config('app.locale'),`

Of course, we need to use route helper in out tests:

`$this->get(route('login'));`

**Comment by V35CH** [comment]
I have found a solution:
The route prefix is only called once when the test case is setup. In this point the route doesnt know of the requested url (It is empty). So I added an function to my test cases: `$this->refreshApplicationWithLocale($locale);` in this function I set the env variable for the route key to the assumed language. Now this seems to work. Or do I have an misconception?
```
private function refreshApplicationWithLocale($locale)
    {
        self::tearDown();
        putenv(LaravelLocalization::ENV_ROUTE_KEY . '=' . $locale);
        self::setUp();
    }
```

**Comment by bertheyman** [comment]
Works for me, thanks @V35CH !

I've made a pull request to add this to the docs:
https://github.com/mcamara/laravel-localization/pull/655

**Comment by jartaud** [comment]
```
in config/localization.php

'hide-default-in-url'    => env('LOCALIZATION_HIDE_DEFAULT_LOCALE', false),
```

```
in phpunit.xml

<php>
    ...
    <server name="LOCALIZATION_HIDE_DEFAULT_LOCALE" value="true" />
</php>
```

**Comment by mperezsc** [comment]
Hello,

When I apply the solution stated at the docs I get:
Undefined constant Mcamara\LaravelLocalization\Facades\LaravelLocalization::ENV_ROUTE_KEY

This is my test

```
class ExampleTest extends TestCase
{
    public function testBasicTest()
    {
        $this->refreshApplicationWithLocale('en');
        $response = $this->get('/en');

        $response->assertStatus(200);
    }
}
```
and this is my TestCase

```<?php

namespace Tests;

use App\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    public function signIn($user = null)
    {
        $user = $user ?: User::factory()->create();
        $this->actingAs($user);
        return $user;
    }

    protected function refreshApplicationWithLocale($locale)
    {
        self::tearDown();
        putenv(LaravelLocalization::ENV_ROUTE_KEY . '=' . $locale);
        self::setUp();
    }

    protected function tearDown(): void
    {
        putenv(LaravelLocalization::ENV_ROUTE_KEY);
        parent::tearDown();
    }
    protected function setUp(): void
    {
        parent::setUp();
    }

}`

Any idea on it?
Thank

**Comment by mperezsc** [comment]
Solved:
```
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;//Wrong import
use Mcamara\LaravelLocalization\LaravelLocalization;//Correct import
```

**Comment by chokchai** [comment]
the official option is only for PHPUnit test cases. 
How about the Pest test cases. Can anyone make it work with pests?

Thanks.
