### ISSUE TITLE
Undefined index: path

### ISSUE THREAD

**Issue by goranata** [mcamara/laravel-localization#162]
Hi, 

I've just updated my L4 composer with the newest laravel-localization version, and I keep on continue getting this error on my online site, while it works just fine on localhost.

Undefined index: path (View: /home/mysite/app/views/home/index.blade.php)

However, if I keep my default config as provide
true
true
true
false, it works fine, but when I do the oposiste, e.g.: 
false
false
false
true it gives me this error.

My routes are set as previously:

Route::group(
array(
        'prefix' => LaravelLocalization::setLocale(),
		'before' => array('LaravelLocalizationRedirectFilter', 'LaravelLocalizationRoutes'),
    ), 
	
	function() {

**Comment by goranata** [comment]
Hi,

could you please help me out here a bit.
I was using 1.4.x version on a 4.2 version of Laravel, and I've updated it to the current 1.5.* version and I still have this error.

Here's routes:
![routes](https://cloud.githubusercontent.com/assets/6684817/6255657/290b2e3e-b7b2-11e4-9b8e-a1fa2b78b380.jpg)

In my config I must set hideDefaultLocaleInURL => false, in order to avoid the Undefined index: path error I get. I would love to have it set to true, as the default locale is not required in my URL.
Here's my config:
'useAcceptLanguageHeader' => true,
'useSessionLocale' => true,
'useCookieLocale' => true,
'hideDefaultLocaleInURL' => false,

Here's an example of the links I am using: LaravelLocalization::getLocalizedURL(LaravelLocalization::getCurrentLocale(), route('homepage'))

**Comment by mcamara** [comment]
Which package have you updated to 1.5.* version?

**Comment by goranata** [comment]
L 4.2.* this should make the last 4.2.17, the current version of this package is "version": "0.15.1", according to the composer.json in the vendor/mcamara/laravel-localization/

**Comment by tbuteler** [comment]
This happens when the URL you are trying to localize doesn't have a trailing slash. So if you attempt to localize "http://example.com" it will fail, but "http://example.com/" or "http://example.com/path" will go through fine.

**Comment by goranata** [comment]
Could be, but still, I have been using this package (for at least 5 websites so far), and I still continue to use, but have to mention that before the update to 0.15.*, everything was working just fine before updating to the latest version for laravel 4.2.*.

Just tested again and downgraded to version 0.14.9 of this package it works just fine (without the error of LOCALE that I had previously in IE.

But with the package 0.15.1, it still shows errors, with the same structure of all the links in the views. Tried almost everything, but I believe that there might be some bug in the 0.15.1 version.

**Comment by mcamara** [comment]
I think I know where the error is, is m_index an empty path? "/"

If so, I will try to fix it asap.

**Comment by goranata** [comment]
Yes,  that the index, e. g.  homepage,  route('m_index') or url('/').  Makes the same error to both. 

Yesterday i started a laravel 5 website,  with this package,  this is definetely the issue. Only on that route or url.
