### ISSUE TITLE
Getting localized urls for nested route groups not working beyond first level of depth

### ISSUE THREAD

**Issue by dyial** [mcamara/laravel-localization#163]
I have an issue where I cannot get nested route groups translated beyond the first level of depth:
```
Route::group([
    'prefix' => LaravelLocalization::setlocale(),
    'before' => 'LaravelLocalizationRoutes|LaravelLocalizationRedirectFilter'
], function () {

	Route::group(['prefix' => LaravelLocalization::transRoute('routes.store')], function () {
		// LaravelLocalization::getLocalizedURL($localeCode, route('store.home')) gives:
		// example.com/en/store and example.com/es/tienda, works perfectly.
	    Route::get('/', ['as' => 'store.home', 'uses' => 'Controller@home']);

	    Route::group(['prefix' => LaravelLocalization::transRoute('routes.products')], function () {

			// LaravelLocalization::getLocalizedURL($localeCode, route('store.items')) gives:
			// example.com/en/store/products and example.com/es/store/products
			// does not give proper translation for nested groups.
	        Route::get('/', ['as' => 'store.items', 'uses' => 'Controller@products']);
	    });
	});

});
```
Can anyone reproduce this or is it just me?

**Comment by mcamara** [comment]
This wouldn't work with the actual version of the package, I've never though in this situation!

Let me think about it and I would solve it for the next version of the package.

**Comment by vsuta** [comment]
I love this package but I have same problem too.
Im kind of suck here.

Problem i have is when visitor change language from product detail page it  trows exception
Http://exampe.com/en/products/7 or slug

Cant change language to
Http://example.com/de/produkte/7 or slug

Products prefix is not translated. Even slug is not translated if used instead of id-s.
Locale prefix works fine.
For  now my solution is if user change language it is redirected to homepage.
Would like to find solution to stay on same page.

**Comment by dyial** [comment]
Any updates on this @mcamara?

**Comment by jorenvanhee** [comment]
I'm having the same issue.
It used to work in version 0.13.7 with laravel 4. I noticed it while upgrading a project to laravel 5.1.

**Comment by arcanedev-maroc** [comment]
Hi everybody,

Sorry about that, i'm feeling like i'm spamming here but it's for a good reason.

You can try my new package : https://github.com/ARCANEDEV/Localization

For translated routes usage : https://github.com/ARCANEDEV/Localization/blob/master/_docs/4-Usage.md#translated-routes

And for you case:
```php
Route::localizedGroup(function () {
    Route::group([
        'prefix' => trans('routes.store')
    ], function () {

        Route::get('/', ['as' => 'store.home', 'uses' => 'Controller@home']);

        Route::group([
            'prefix' => trans('routes.products')
        ], function () {

            Route::get('/', ['as' => 'store.items', 'uses' => 'Controller@products']);

        });
        
    });
});
```

**Comment by ovvessem** [comment]
@arcanedev-maroc,

Your suggested solution does not work for me when using you package.

```php
Route::localizedGroup(function () {
    Route::transGet('routes.webhosting.colocation', ['as' => 'webhosting.colocation', 'uses' => 'WebhostIngcontroller@colocatie']);
    Route::group(['prefix' => trans('routes.webhosting')], function () {
    Route::transGet('routes.webhosting.colocation', ['as' => 'webhosting.colocation', 'uses' => 'WebhostIngcontroller@colocatie']);
    });
}); 
```

The first route within the localizedGroup does the job, but the one in the group doest first not translate the group prefix and second does not translate the route name when I want to switch the language.

Am I missing something? 

The same goes for the Localization package from @mcamara 

Would love to hear for you!

**Comment by arcanedev-maroc** [comment]
Please show me your `routes.php` files.

And also check the `trans('routes.webhosting')`, try to `dd()` and see what you get.

**Comment by ovvessem** [comment]
```php
languages/en/routes.php
    'webhosting'  =? 'hosting',
    'webhosting.colocation'       => 'colocation',

languages/nl/routes.php --> dutch
    'webhosting'  => 'webhosting',
    'webhosting.colocation'       => 'colocatie',
```

I would assume the following routes when I change from one to the other language in the language switcher:

nl --> domain.app/nl/webhosting/colocatie
en --> domain.app/en/hosting/colocation

But I get the following switching from NL to EN

nl --> domain.app/nl/webhosting/colocatie
en --> domain.app/en/webhosting/colocatie

**Comment by arcanedev-maroc** [comment]
Have you tried this `dd(trans('routes.webhosting'));` to see what you're going to get.

**Comment by ovvessem** [comment]
Yes I did and it gives me the right value for the selected language if I dump it outside of the route group. Inside it keeps the value of the current language.

**Comment by ovvessem** [comment]
@arcanedev-maroc I have created an issue on your own repo :)

**Comment by arcanedev-maroc** [comment]
In your `routes.php` fore each locale, like this:
```php
return [
    //...
    'webhosting' => [
        'prefix'     => 'webhosting',
        'colocation' => 'colocatie',
    ],
];
```

And replace `'routes.webhosting'` by `'routes.webhosting.prefix'` like this :

```php
Route::localizedGroup(function () {
    Route::group(['prefix' => trans('routes.webhosting.prefix')], function () {
        Route::transGet('routes.webhosting.colocation', [
            'as'   => 'webhosting.colocation', // Dont duplicate routes with the same name
            'uses' => 'WebhostIngcontroller@colocatie'
        ]);
    });
}); 
```

**Comment by hgokturk** [comment]
This must be fixed urgently, doesn't it?

**Comment by hgokturk** [comment]
i have some locale routes:

"about"      => "hakkimizda",
"career"       =>  "kariyer",
"contact"        =>  "iletisim",

default locale is 'tr'.

website.dev/hakkimizda is translated to website.dev/en/about without any problem.
but website.dev/hakkimizda/kariyer is translated to website.dev/en/hakkimizda/kariyer while it is supposed to be translated as website.dev/en/about/career
This is a big problem. Did you come up with any solution about this?

**Comment by BrunoMCTeixeira** [comment]
I'm having this issue as well, can't get the translated URL to contain the first level of depth if the route is defined inside a group
