### ISSUE TITLE
Event::fire passes empty attributes

### ISSUE THREAD

**Issue by subdesign** [mcamara/laravel-localization#166]
I want to use the Event handler functionality, but the fire() method passes always empty $attributes array to the listener. It's just me or.. ?

**Comment by goranata** [comment]
I'm experiencing more or less same problem, related with the attributes.

I have multilanguage site, and I am trying to pass attributes to be saved if the visitor tries to save to language, to he will be redirected to the same resulsts page, but in different language.

When I do this:
LaravelLocalization::getLocalizedURL($localeCode, route('accommodation', array('location' => $city->urlid, 'page' => Input::get('page'), 'arrival_date' => Input::get('arrival_date'), 'departure_date' => Input::get('departure_date'), 'rooms_available' => Input::get('rooms_available'), 'guest_qty' => Input::get('guest_qty'), 'children_qty' => Input::get('children_qty'), 'max_persons' => Input::get('max_persons'), 'minrate' => Input::get('minrate'), 'maxrate' => Input::get('maxrate'), 'categories' => Input::get('categories'), 'stars' => Input::get('stars'), 'facilities' => Input::get('facilities'))))
I get what I need, except the URL is taken from the default language and it not being Translit.

With this:
LaravelLocalization::getLocalizedURL($localeCode, route('accommodation'), array('location' => $city->urlid, 'page' => Input::get('page'), 'arrival_date' => Input::get('arrival_date'), 'departure_date' => Input::get('departure_date'), 'rooms_available' => Input::get('rooms_available'), 'guest_qty' => Input::get('guest_qty'), 'children_qty' => Input::get('children_qty'), 'max_persons' => Input::get('max_persons'), 'minrate' => Input::get('minrate'), 'maxrate' => Input::get('maxrate'), 'categories' => Input::get('categories'), 'stars' => Input::get('stars'), 'facilities' => Input::get('facilities')))
The url is localized well, but no attributes are passed as parameters to the URL.

Please advice ...

**Comment by goranata** [comment]
I'm experiencing more or less same problem, related with the attributes.

I have multilanguage site, and I am trying to pass attributes to be saved if the visitor tries to save to language, to he will be redirected to the same resulsts page, but in different language.

When I do this:
LaravelLocalization::getLocalizedURL($localeCode, route('accommodation', array('location' => $city->urlid, 'page' => Input::get('page'), 'arrival_date' => Input::get('arrival_date'), 'departure_date' => Input::get('departure_date'), 'rooms_available' => Input::get('rooms_available'), 'guest_qty' => Input::get('guest_qty'), 'children_qty' => Input::get('children_qty'), 'max_persons' => Input::get('max_persons'), 'minrate' => Input::get('minrate'), 'maxrate' => Input::get('maxrate'), 'categories' => Input::get('categories'), 'stars' => Input::get('stars'), 'facilities' => Input::get('facilities'))))
I get what I need, except the URL is taken from the default language and it not being Translit.

With this:
LaravelLocalization::getLocalizedURL($localeCode, route('accommodation'), array('location' => $city->urlid, 'page' => Input::get('page'), 'arrival_date' => Input::get('arrival_date'), 'departure_date' => Input::get('departure_date'), 'rooms_available' => Input::get('rooms_available'), 'guest_qty' => Input::get('guest_qty'), 'children_qty' => Input::get('children_qty'), 'max_persons' => Input::get('max_persons'), 'minrate' => Input::get('minrate'), 'maxrate' => Input::get('maxrate'), 'categories' => Input::get('categories'), 'stars' => Input::get('stars'), 'facilities' => Input::get('facilities')))
The url is localized well, but no attributes are passed as parameters to the URL.

Please advice ...

**Comment by GregoryClaeyssens** [comment]
Having same issue... 
Actually, the docs say:
     Event::listen('routes.translation', function($locale, $attributes){
          return $attributes
     });

but seems the $locale is never passed...?

**Comment by arcanedev-maroc** [comment]
Yep you're right @GregoryClaeyssens 

.To fix that:
```php
Event::listen('routes.translation', function ($attributes) {
    $locale = LaravelLocalization::getCurrentLocale();

    // Translate your attributes...

    return $attributes;
});
```

**Comment by GregoryClaeyssens** [comment]
Wouldn't getCurrentLocale() return the current locale (as is the name of the function). This would give me 'nl'.(translating from nl to fr). You need 2 locales to be able to translate a parameter. The current locale and the locale you are translating to. (except for the situation where you only have 2).

**Comment by arcanedev-maroc** [comment]
The first locale is always the default locale (From) and the second locale is gonna be the current locale (To) selected by the user. 

So you only need one locale to translate to a specific language.

By the way, i've found the bug : https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/LaravelLocalization.php#L836

As you can see, there is not locale passed here.
