### ISSUE TITLE
Can't make it work with L5

### ISSUE THREAD

**Issue by mimow7** [mcamara/laravel-localization#169]
when I add this:
"mcamara/laravel-localization": "dev-master"

 into composer.json I got:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel/framework[5.0.x-dev, 4.2.x-dev].
    - Can only install one of: laravel/framework[4.2.x-dev, 5.0.x-dev].
    - mcamara/laravel-localization dev-master requires laravel/framework 4.2.* -> satisfiable by laravel/framework[4.2.x-dev].
    - Installation request for mcamara/laravel-localization dev-master -> satisfiable by mcamara/laravel-localization[dev-master].
    - Installation request for laravel/framework 5.0.*@dev -> satisfiable by laravel/framework[5.0.x-dev].

**Comment by mcamara** [comment]
Hi,

I've changed the version number (Laravel has changed it) into the composer.json file. It should work now.
