### ISSUE TITLE
How to set language based on users personal info

### ISSUE THREAD

**Issue by s-coder** [mcamara/laravel-localization#17]
Hello, 

is it possible to set the default language based on users personal info? For example, when user logs in, we will check his default language (from user table) and set that  language as default?

thank you

**Comment by Samuel-Bie** [comment]
> 
> 
> If I were you, I would do the language change through the user setup menu (like facebook). If you don't want to do that, you should change the database value of the user language every time the user defines a new language.

Is there a way to listen when a user changes the preffered language, so that we can keep the record for the next login.
