### ISSUE TITLE
getNonLocalizedURL broken

### ISSUE THREAD

**Issue by Thomas-Jensen** [mcamara/laravel-localization#170]
Hello, have used laravel-localization for a while now and I love it.

I'm in the process of updating my app to laravel 5 and I have just yesterday started that and got the new update from laravel-localization as well, only problem I have had is that now the getNonLocalizedURL function seems to be broken. I'm using translated the translated routes filter and redirect (        'middleware' => [ 'localize', 'localizationRedirect' ] // LaravelLocalization routes and filter) it worked/works in the 4.2 app with the old library but with the new update it spits out" http://host-5:8888/en/home" for the function where it used to say "http://host-5:8888/" not a huge thing just a minor thing for us who uses this function for page specific navigation.

Kind regards,
Thomas

**Comment by Thomas-Jensen** [comment]
Also I forgot to say it gives "http://host-5:8888/en/home" for other languages as well apart from en

**Comment by oriceon** [comment]
yes, i confirm that too and i found where should be the problem..


vendor\mcamara\laravel-localization\src\Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes.php

$routeName = $app[ 'laravellocalization' ]->getRouteNameFromAPath($request->getUri());

If you have a route with optional parameter here, route name will be incorect filled.

**Comment by mcamara** [comment]
Fixed in the latest version 1.0.4

Thanks for your feedback!
