### ISSUE TITLE
Arabic Routes are being stuck

### ISSUE THREAD

**Issue by mkwsra** [mcamara/laravel-localization#174]
I've app with 5 different languages, only in **Arabic** routes the app is being stuck using this route chaning to different language will change the language code only:
##### i.e:
``` xxx.com/en/hotels ```

works just fine, chaning it into:
``` xxx.com/ar/فنادق   ```

works fine but:

when I try to change language into **Netherlands** :
``` xxx.com/nl/فنادق ```

When I changed the value of hotels key inside ``` resources/lang/ar/routes.php ``` into latin characters the problem went away!!

I have no idea why, perhabs you could help me because I've a lot of slugs in Arabic.

my routes.php hotels section:

``` 
Route::group(
	array( 'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localizationRedirect' ]),
         function() {
	       Route::resource(LaravelLocalization::transRoute('routes.hotels'),
                            'HotelsController' , array('as'=>'hotelsPath'));
});
 ```

**Comment by armababy** [comment]
Same problem over here, by the looks all translated routes are not utf-8 character friendly.

**Comment by mkwsra** [comment]
@mcamara What are your thoughts about this? any tip that could help me here?

**Comment by mcamara** [comment]
Hi! I've never though in non-utf-8 characters, let me think about this and I will patch the package.

I would appreciate any help! :)

Thanks!

**Comment by mkwsra** [comment]
Hey, @mcamara Thanks a lot, and I read the code trying to figure it out, I guess it's located in this function [getURLFromRouteNameTranslated] ( https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/LaravelLocalization.php#L326 )

The problem appears in the language chooser, when I click in translated route with Arabic character, i.e: `فنادق` all the links in the language chooser will stick with this value as translated route: `nl/فنادق` `de/فنادق` ..etc nothing new here, but what I'd like to say is UTF-8 supports the Unicode, which means Arabic is supported in your code it's not about characterset/characterCoding.

Working on it hopefully to solve this out since my project is suspended because of this issue, I hope you could help me solving it.

Thanks for the great and clean code.

**Comment by FDiskas** [comment]
I have same problem. I suggest you to use some helper http://laravel.com/docs/5.0/helpers#strings
```
str_slug()
```
I suggest the plugin author to use this function before returning translated url

**Comment by FDiskas** [comment]
@mcamara I tryed to fix that problem but - tests not passed. So the best solution for this is in your language file add the helper
```php
<?php

return [
	'admin.home' => str_slug('فنادق')
];
```
Then localized url will return something like ```http://localhost/nl/admin/fndk```

**Comment by armababy** [comment]
@FDiskas i do not think the issue here is with sanitizing user translation, package should be able find any translation user has set up even if it's incorrect and return it. That is more on the user side to pass correct url translations.
Will check source later this week to see whats up.

**Comment by mkwsra** [comment]
@armababy Thanks a lot worked like a charm!!

**Comment by mkwsra** [comment]
I'm sorry to re-open this, but I'm facing the same problem again, IFF I've `hotels/{id}`, the links will stuck for Arabic only!

changin from to the following links 100% works:
`de/zentren/3`
`en/centers/3`
`nl/gezondheidscentra/3`
`tr/merkezleri/3`
Except this one:
`ar/المراكز/3`

btw the order of the link above is automatically changed since Arabic is RTL language, so I'm guessing if you change the order of URI segments when you testing such language you can avoid such error.

Appreciate any help guys @mcamara @armababy

**Comment by mkwsra** [comment]
btw mcamara, in the language choose it didn't work for hotels/{id} like this:
`href="{{LaravelLocalization::getLocalizedURL($localeCode)}}"`
until I made it like this:
`href="{{LaravelLocalization::getLocalizedURL($localeCode,Request::url())}}"`

is this normal ? or I"m missing something ?

routs.php
```
Route::group([
        'prefix' => LaravelLocalization::setLocale(),
        'middleware'=>['localizationRedirect', 'localeSessionRedirect']
    ],function() {
        get('/', 'Front\HomeController@index');
        get(LaravelLocalization::transRoute('routes.centersID'), 'Front\CentersController@show');
        get(LaravelLocalization::transRoute('routes.centers'),'Front\CentersController@index');
 });
```

where routes.php in en folder:
```
    'centers'       => 'centers',
    'centersID'    =>'centers/{id}',
```

**Comment by mkwsra** [comment]
@mcamara  I'd appreciate if you have any idea, or just let me know that you saw my issue

**Comment by mkwsra** [comment]
@fisharebest Do you think this issue is related with your edits in #130 ?

**Comment by fisharebest** [comment]
> @fisharebest Do you think this issue is related with your edits in #130 ?

It would seem unlikely.  My change was simply in the derivation of the "ltr" or "rtl" attribute.  This is normally just used to create the `<html lang="ar" dir="rtl">` tag.

**Comment by mkwsra** [comment]
Okay thanks! its just that I'm desperate and I don't have time to take closer look, sorry for bothering

**Comment by mkwsra** [comment]
@mcamara Should I open a new issue ? please see this link, and try to change the language from English into Arabic and back then from Arabic to English 
http://ht5.dev/en/packages/female-check-up-packages-under-40-years-old-1

**Comment by fisharebest** [comment]
This problem does not affect just arabic routes.  I see the same problem any any route with non-ascii characters.  e.g.

en/hotel/4
fr/hôtel/4

Looking at the generated routes, it seems to be missing a `url_decode()` somewhere...

**Comment by fisharebest** [comment]
> btw the order of the link above is automatically changed since Arabic is RTL language, so I'm guessing if you change the order of URI segments when you testing such language you can avoid such error.

This is NOT a problem with the order of segments.  The URL is in the correct (byte) order - your browser is displaying it in a different (visual) order.

Consider the URL `/ar/ARABIC/3`, where ARABIC is written in arabic text.

The browser's bidi (directional) algorithm breaks this into two "directional runs".

`/ar/` (left to right) followed by `ARABIC/3` (right to left)

So, you get the following visual order:
`/ar/` followed by `3/CIBARA`

(The bidi algorithm is actually more complicated than this, but you get the idea).

**Comment by fisharebest** [comment]
I can't debug this any further until I have a solution for #212 

If I have the URL `http://localhost/fr/hôtel/4`, and a route `hotel/{id}`, then the attributes are being parsed as

`'id' => 'hôtel'`

instead of 

`'id' => '4'`

**Comment by mkwsra** [comment]
I've solve it using `urldecode()` when I've to compare values other wise it won't find the intended value 

```
$arrayOrm = Route::current()->parameters();
            $orm = reset($arrayOrm);
            $ex = explode("/",Request::url());
            $lastElement = end($ex);
            $link = LaravelLocalization::getLocalizedURL($localeCode, Request::url(), Route::current()->parameters());
            if(count($ex) >= 2){
                foreach($ex as $e)
                {
                    if(urldecode($e) == trans('routes.packages') && $e != $lastElement){
                        $link = Request::root() ."/". $localeCode ."/". trans('routes.packages',[],'',$localeCode) ."/". $orm->translations()->t($localeCode)->slug;
                        break;
                    }elseif(urldecode($e) == trans('routes.centers') && $e != $lastElement){
                        $link = Request::root() ."/". $localeCode ."/". trans('routes.centers',[],'',$localeCode) ."/". $orm->translations()->t($localeCode)->slug;
                        break;
                    }
                }
            }

echo $links
```

**Comment by vinalys** [comment]
I believe this issue should be reopened?

**Comment by mkwsra** [comment]
Indeed it should I still have problem

**Comment by Krato** [comment]
@mkwsra Hi! Do you try with `urlencode`?

I fix some russian url translations with that fix. 

I made a function that encodes the url after pass to `getLocalizedURL` function and works:

This is an example. Hope you get it!  !أتمنى أن تفعل جيدا

```php
function translateRoute($locale){

	//Get the path type
	//http://www.example.com/en/hotels -> get hotels
	$req = \URL::getRequest();
    $type = urldecode($req->segment(2));

	//Get the route translated for current locale
	$hotels = Lang::get('routes.menu.hotels');

	if(mb_strtolower($type) == mb_strtolower($products)){
		//Get the localized route
	    $hotelsLocalized = Lang::get('routes.menu.hotels', [], $locale);
	    //Make the magic with urlencode php function ;)
	    return url(LaravelLocalization::getLocalizedURL($locale, urlencode($hotelsLocalized)));
	}
	//IF not hotel return normal translated route
	return urldecode(LaravelLocalization::getLocalizedURL($locale));
}
```

**Comment by mkwsra** [comment]
@Krato Thanks a lot for your answer, now I'm now working in that project anymore, and I'm using the other library that was forked out of this one, and so far I didn't reach a level where I've to implement same features in my current projects, but thanks again :smile: specially the translation, :+1: большое спасибо
