### ISSUE TITLE
Localized Dates

### ISSUE THREAD

**Issue by antondomratchev** [mcamara/laravel-localization#176]
I noticed that this package is missing one of the most important localization settings. There seems to be no presence of [`setlocale()`](http://php.net/setlocale) method which us used to format dates to string with localization. I've added my own wrapper class which extends the LaralvelLocalization class to include the `setlocale()` method. I would think this is a pretty important feature which might have been overlooked.

**Comment by mcamara** [comment]
You can just have the date format for every language in the language file and use it in the date() function like this:
```date(trans('date.format'))```

**Comment by antondomratchev** [comment]
This will not work for Carbon generated dates. When I get around to extracting my implementation from my project I will fork and make a PR for this. Its useful even if you dont use Carbon.
