### ISSUE TITLE
Save last language selected?

### ISSUE THREAD

**Issue by Luddinus** [mcamara/laravel-localization#182]
I'm trying to save the last language selected with the Cookie option.

if my page is "page.com" and my last visit is to "page.com/es/perfil", I want redirect to profile (spanish) if I go to page.com again, but this doesn't seem to work. It is always getting the default language (english in this case) so it's redirecting to page.com/en/profile.

**Comment by mcamara** [comment]
There are some issues with the session helper, I will try to sort it soon.

**Comment by sangar82** [comment]
+1!

**Comment by jojimoreau** [comment]
+1, same issue here :/

**Comment by anasbud** [comment]
I think we have the same problem.

The user language is not saved into the cookie / session.

**Comment by intrepidtr** [comment]
I think we have the same problem.

**Comment by tanshiqi** [comment]
+1 , same issue

**Comment by TeviSiat** [comment]
+1
same problem in Laravel 5

**Comment by MarcGuay** [comment]
Looks like 'prefix' => LaravelLocalization::setLocale() is firing before the session starts...

**Comment by TeviSiat** [comment]
@MarcGuay sorry, I don't understand how

**Comment by mcamara** [comment]
@MarcGuay You're totally right and I don't know how to handle it in laravel 5. I think the only way to solve this is creating a new middleware (as middleware is fired after the session has been initialized). What do you think about that solution?

**Comment by sangar82** [comment]
Hi @mcamara ! I think that is the solution ;)

**Comment by MarcGuay** [comment]
@mcamara Honestly I'm very new to Laravel and don't know enough to say.  Would it be possible to add the prefix inside the existing middleware?

**Comment by MarcGuay** [comment]
@mcamara Something like this seems to partially work, although it creates a huge pile of duplicate routes...

```
foreach (LaravelLocalization::getSupportedLocales() as $localecode=>$data){
    Route::group(
        [
            'prefix' => $localecode,
            'middleware' => [ 'localizationRedirect' ]
```

**Comment by intrepidtr** [comment]
My Route    
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localizationRedirect' ]
    ],
    function()
    {

          Route::get('/', 'HomeController@index');
          Route::get('/{slug}/{slug2?}', 'MainController@getview');
    });

What is the problem?
Need to work session

**Comment by MarcGuay** [comment]
Not a solution to the technical problem itself, but a functional fix for those looking for it is to use getLocalizedURL() inside your templates like so

`<a href="{{ LaravelLocalization::getLocalizedURL(null, '/') }}">`

Where '/' is your route path.

**Comment by MarcGuay** [comment]
Just realized that this really isn't a feasible solution as anytime there's a `redirect()` in the code we want it to figure out the lang for us automatically...

**Comment by MarcGuay** [comment]
@mcamara Might be some useful ideas in this thread: https://laracasts.com/discuss/channels/tips/example-on-how-to-use-multiple-locales-in-your-laravel-5-website in regards to how the routes are set up...

**Comment by mcamara** [comment]
Check the README, it should be fixed in version 1.0.7 :dancer:

**Comment by intrepidtr** [comment]
thanks good job

**Comment by intrepidtr** [comment]
it works very well
admin panel creates problems
http://127.0.0.1/public/en/admin/setting

**Comment by mcamara** [comment]
Which problem?

**Comment by intrepidtr** [comment]
administration panel URLs adds language
therefore gives the error page not found

**Comment by MarcGuay** [comment]
@mcamara Looks good to me. Thank you.

**Comment by tanshiqi** [comment]
@intrepidtr 
Same problem, the route not in group also add language:
    
    Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localizationRedirect' ]
    ],
    function()
    {
        Route::get('/', 'HomeController@index');
        Route::controllers([
            'auth'     => 'Auth\AuthController',
            'password' => 'Auth\PasswordController',
        ]);

    });


    Route::get('/test', function(){
        return 'Just Test';
    });

1. Visit http://localhost/     OK, English language
2. Visit http://localhost/fr   Also OK
3. Visit http://localhost/test  => Redirect to: http://localhost/fr/test  404 error

PS: hideDefaultLocaleInURL=true

**Comment by mcamara** [comment]
The session middleware should be inside the middleware key

**Comment by tanshiqi** [comment]
It's my kernel.php:

    protected $middleware = [
        'Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode',
        'Illuminate\Cookie\Middleware\EncryptCookies',
        'Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse',
        'Illuminate\Session\Middleware\StartSession',
        'Illuminate\View\Middleware\ShareErrorsFromSession',
        'App\Http\Middleware\VerifyCsrfToken',
        'Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect'
    ];

    protected $routeMiddleware = [
        'auth' => 'App\Http\Middleware\Authenticate',
        'auth.basic' => 'Illuminate\Auth\Middleware\AuthenticateWithBasicAuth',
        'guest' => 'App\Http\Middleware\RedirectIfAuthenticated',

        'localize' => 'Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes',
        'localizationRedirect' => 'Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter',
    ];

**Comment by MarcGuay** [comment]
Can reproduce.  All routes are being redirected to /lang/ URLs by `LocaleSessionRedirect.php` line 34, regardless of whether or not they're in the group.  What works is moving the middleware to the $routeMiddleware array and then adding it to the group's middleware.  I'll post a fix for the docs.

**Comment by oguzcicek** [comment]
is there any fix for this issue ? it doesnt work if i dont add it to ``` $middleware  ```

**Comment by MarcGuay** [comment]
@oguzcicek Have you looked at the updated docs?  You need to add it to the $routeMiddleware array and then include it in the route group's middleware.

**Comment by AlexVonB** [comment]
Hi,
I use 1.0.7 on Laravel 5.0.27, with this in my `$routeMiddleware`

```php
'localize' => 'Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes',
'localizationRedirect' => 'Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter',
'localeSessionRedirect' => 'Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect'
```
this as my route:
```php
Route::group(
[
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localizationRedirect', 'localeSessionRedirect' ]
], function()
{
    Route::get('/', 'FrontendController@index');
    Route::get('/about', 'FrontendController@about');
    ...
}
```
and this config:
```php
config([
	'laravellocalization.supportedLocales' => [
	    'de' => ['name' => 'German', 'script' => 'Latn', 'native' => 'Deutsch'],
	    'en' => ['name' => 'English', 'script' => 'Latn', 'native' => 'English'],
	],
]);
```
However, when I go to `domain.com/en` and then to `domain.com`, it redirects me to my default locale, `domain.com/de`. It seems that the locale is neither stored in a cookie nor a session.
I also testet changing my preferred locale in Firefox, but it gets ignored.

I also tried visiting `domain.com/about`, which redirects (301) me to `/`, which redirects me to `/about` which redirects me to `/` and so on. Firefox will finally stop following the redirects and show an error message.

Any updates or ideas?

**Comment by MarcGuay** [comment]
@AlexVonB For the first issue, try switching the order of the middleware in your route declaration like so  `'middleware' => [ 'localeSessionRedirect', 'localizationRedirect']`.  I cannot reproduce the second issue.

**Comment by AlexVonB** [comment]
That solved all problems, merge request regarding Readme here: #210

**Comment by illuminate3** [comment]
Issue https://github.com/mcamara/laravel-localization/issues/192  shows the steps that I took to debug the issue I was having.

Here is the code that I'm using for the middleware.
Crude and Ugly but it works.

```
<?php
namespace Mcamara\LaravelLocalization\Middleware;

use Illuminate\Http\RedirectResponse;
use Illuminate\Contracts\Routing\Middleware;

use Closure;
use Config;
use Session;

class LocaleSessionRedirect implements Middleware {

/**
 * Handle an incoming request.
 *
 * @param  \Illuminate\Http\Request $request
 * @param  \Closure $next
 * @return mixed
 */
public function handle(
	$request,
	Closure $next
	)
{

// explode and grab URL data
		$params = explode('/', $request->path());

// Check for hideDefaultLocaleInURL and if we have not Locale in the url
		if ( (app('laravellocalization')->hideDefaultLocaleInURL() == true) && (count($params) > 0) ) {
// Use Larvel to set locale for session
			Session::put('locale', Config::get('app.locale'));
			return $next($request);
		}

// grab locale from URL
		if ( app('laravellocalization')->checkLocaleInSupportedLocales($params[0]) == true ) {
// put URL locale into session
			Session::put('locale', $params[0]);
			return $next($request);
		}
}

}
```

I hope that this works for some of you!

**Comment by sangar82** [comment]
Hola @mcamara !!

This is not yet working, there are some problem with the session, it's not saved properly.

I change the language when an users clicks the link of change language:

````php
LaravelLocalization::setLocale($locale)
````
````php
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'localeSessionRedirect']],  function()
{
    //Route::get('/', array('as' => 'index', 'uses' => 'HomeController@index'));
    Route::get('/', array('as' => 'index', 'uses' => 'HomeController@home'));
````

````php
	/**
	 * The application's route middleware.
	 *
	 * @var array
	 */
	protected $routeMiddleware = [
		'auth' => 'App\Http\Middleware\Authenticate',
		'auth.basic' => 'Illuminate\Auth\Middleware\AuthenticateWithBasicAuth',
		'guest' => 'App\Http\Middleware\RedirectIfAuthenticated',
        'csrf' => 'App\Http\Middleware\VerifyCsrfToken',
        'localize' => 'Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes',
        'localizationRedirect' => 'Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter',
        'localeSessionRedirect' => 'Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect'
	];
````

when clicks the link to change the language, it doesn't make nothing. continues with the last language. 

@mcamara I need your help, please!! I'm updating my platform to L5

**Comment by AlexVonB** [comment]
Do you use `<a rel="alternate" hreflang="en" href="{{LaravelLocalization::getLocalizedURL('en') }}">EN</a>` as link to the other language? Maybe try adding the second middleware, `'localizationRedirect'`, after `'localeSessionRedirect'`:

```php
Route::group(
[
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]
], function()
{

    Route::get(...
```

**Comment by sangar82** [comment]
I use this function

````php
    public function changeLanguage($locale)
    {
        $supported = LaravelLocalization::getSupportedLocales();

        if (array_key_exists($locale,$supported))
        {
            LaravelLocalization::setLocale($locale);
        }

        return Redirect::to(LaravelLocalization::getNonLocalizedURL(URL::previous()));
    }
`````
Because i don't want that the users see the language in the url

**Comment by MarcGaumont** [comment]
this still seems broken

**Comment by samiles** [comment]
Has this been fixed? Everything works as expected for site.com/en and site.com/de, but when a user clicks a link on site.com/de to site.com/home, it redirects to site.com/en/home not site.com/de/home. Is this fixed, am I doing something wrong? How can I stop links breaking the user's selected option...?

**Comment by samiles** [comment]
[This commit](https://github.com/mcamara/laravel-localization/commit/3c14c66df8de72b612d9eaffba23438ee52f5e67) fixed this for me. It wasn't reflected in my Composer installed version, but I manually changed the file as specified in the commit and everything worked.

**Comment by yaofong** [comment]
@samiles your way works for me too!
wonder why this commit is reflected in composer

**Comment by snyper3xs** [comment]
Got the same problem. All middlewares in kernel, both middlewares in route group and in correct order ('localeSessionRedirect', 'localizationRedirect'). Seem to continually default to the app.local rather than the last select language. Checked the commit above and it is apparent in the code. No idea.

**Comment by k-zakhariy** [comment]
Anyone has problem in 2018 that @shane3xsds described above ? :)
