### ISSUE TITLE
Force localized routes

### ISSUE THREAD

**Issue by ntopulos** [mcamara/laravel-localization#185]
I need to always have the locale in my URLs.
Setting `'hideDefaultLocaleInURL’ = false`, only allows the default locale to be part of the URL, but does not forbid its absence.
Is there a way the fix it?

**Comment by Thomas-Jensen** [comment]
Not sure I understand the problem, setting hideDefaultLocaleInURL to false should always show the locale in the urls ie: homepage.com/en with english being the default locale in this case. If you use manual links etc I understand you can end up with homepage.com but if you look there is a filter/middleware to account for this called localizationRedirect, if you use this it will always redirect to a localized version of the page. You should give it a go it's awesome, and it's great for SEO as well, as it can be quite tricky on multilingual apps. :)

**Comment by ntopulos** [comment]
All my routes use this filter: `'before' => 'LaravelLocalizationRedirectFilter'`.
Is that what you meant?

Nevertheless, assuming English is my default locale, when I go to */contact* Laravel is not redirecting me to */en/contact*.

In addition, without changing the locale on the page, none of the generated URLs is prefixed. Thus, user navigates the whole website without the locale in the URL.

**Comment by Thomas-Jensen** [comment]
Are you using laravel 5 or 4.2? and are you using 1.0 of laravel-localization or the sub 1.0 versions?

**Comment by ntopulos** [comment]
Laravel 5 with laravel-localization 1.0

**Comment by Thomas-Jensen** [comment]
Then you do it like this: 

// app/Http/routes.php

    Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localizationRedirect' ]
    ],
    function()
    {
        /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
        Route::get('/', function()
        {
            return View::make('hello');
        });

        Route::get('test',function(){
            return View::make('test');
        });
    });

    /** OTHER PAGES THAT SHOULD NOT BE LOCALIZED **/

The code changed some for laravel 5 and 1.0, imo it's cleaner and better now :)

**Comment by ntopulos** [comment]
Thanks, it works perfectly!

**Comment by Thomas-Jensen** [comment]
No problem, I'm happy to hear it, glad to help :)

**Comment by core45** [comment]
when I add 'middleware' => [ 'localizationRedirect' ]
I have an error
Class localizationRedirect does not exist
