### ISSUE TITLE
Route::resource creates routes that cannot be referenced without lang prefix

### ISSUE THREAD

**Issue by MarcGuay** [mcamara/laravel-localization#191]
Sort of a weird issue that can be worked around by declaring the routes explicitly, but to reproduce, create a resource in routes.php that is inside the group with ` 'prefix' => LaravelLocalization::setLocale()`

`Route::resource('user', 'UserController');`

Then in your controller do something like

`return redirect()->route('user.edit', ['id' => $user->id])`

or in a view

`{{ route ('user.update' }}`

And you'll get an error saying the route cannot be found.  Adding the prefix solves the problem, for example:

`{{ route (LaravelLocalization::getCurrentLocale().'.user.update') }}`

And as said above, if you declare them explicitly, you don't need to add this to your controllers and views...

`Route::get('user/{user}/edit', ['uses' => 'UserController@edit', 'as' => 'user.edit']);
Route::put('user/{user}', ['uses' => 'UserController@update', 'as' => 'user.update']);`

Edit:

A quicker fix is to simply declare the names for the routes in the `resource` declaration like so

`Route::resource('user', 'UserController', ['names' => ['edit' => 'user.edit', 'update' => 'user.update']]);`

**Comment by Riesjart** [comment]
+1

**Comment by arcanedev-maroc** [comment]
I've fixed my localization package [ARCANEDEV/Localization](https://github.com/ARCANEDEV/Localization) issue by editing this method : https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/ResourceRegistrar.php#L212-L221

The issue: https://github.com/ARCANEDEV/Localization/issues/5

**Comment by jp7carlos** [comment]
This is closed. Does it mean it's fixed? I still have the same problem. Error when calling route('foo.bar')

**Comment by vahidahmad** [comment]
same problem in laravel 5.3 when changing route from "/"  to "/fr"  french language
