### ISSUE TITLE
Language selector not working if hideDefaultLocaleInURL = TRUE

### ISSUE THREAD

**Issue by neysi** [mcamara/laravel-localization#192]
Hello, 
Language selector not working when the option hideDefaultLocaleInURL  is true. 
It is automatically redirected to the language selected previously.
Example: 
ES:  http://local.com/es/acerca (its work ) 
DE:  http://local.com/de/uber  (its work ) 
EN:  http://local.com/about ( Redirect to http://local.com/es/acerca  )  , It only works if I go to this url: http://local.com/en/about (duplicate content for SEO)

Using: Laravel 5

:( 

Is there any solution? thanks.

**Comment by jaumesala** [comment]
What do you have in your config files? `app.locale`, `app.fallback_locale` package config file, translation routes? etc...

**Comment by neysi** [comment]
My app config file:
-------------------
<pre>
'locale' => 'en',
'fallback_locale' => 'en',
</pre>
![config](https://cloud.githubusercontent.com/assets/8596436/6765002/7a643f54-cf9b-11e4-8a5a-197a1b531c48.png)

My routes.php file: 
-------------------
<pre>
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localizationRedirect' ]
    ],
    function()
    {
        Route::get('/', function()
        {
        	return View::make('home');
        });
        Route::get('test',function(){
            return "Test";
        });
 });

 Route::group(
		    [
		        'prefix' => LaravelLocalization::setLocale(),
		        'middleware' => [ 'localize' ] 
		    ],
		    function()
		    {
		      Route::get(LaravelLocalization::transRoute('routes.about'),function(){
		      		//return View::make('about');
		        	return View::make('languageselector');
		      });
		      Route::get(LaravelLocalization::transRoute('routes.view'),function($id){
		        	// return View::make('view');
		        	 return View::make('languageselector');
		      });
 });
</pre>

Using: php artisan --version  ( Laravel Framework version 5.0.17) 

Thanks.

**Comment by jaumesala** [comment]
Well, first of all, get rid of the configServiceProvider code, use `artisan vendor:publish` instead (and check the config folder). Then in your routes.php, I'm not sure if this can be the problem, but I'd suggest to have only one `Route::group()`, just place both middlewares together, like so:
```PHP
Route::group(
   [
      'prefix' => LaravelLocalization::setLocale(),
      'middleware' => [ 'localizationRedirect','localize' ]
   ],
   function(){
      ...
   }
```
Btw, I assume your routes are correctly translated...
Let us know if this solves your problem.

**Comment by neysi** [comment]
Ok, 
I have applied this:
<pre>php artisan vendor:publish</pre>
and
<pre>php artisan cache:clear --env=local</pre>

Now it does not show all languages.

![notshows](https://cloud.githubusercontent.com/assets/8596436/6765282/03b3ded0-cfa7-11e4-86c3-7386406a92a3.png)

Config.php
![langs](https://cloud.githubusercontent.com/assets/8596436/6765287/40b14d86-cfa7-11e4-9bac-3fba4502c7c0.png)

My routes.php file: 

<pre>
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localizationRedirect',  'localize' ] 
    ],
    
    function()
    {
        Route::get('/', function()
        {
        	return View::make('home');
        });

        Route::get('test',function(){
                return "Testing";
        });

        Route::get(LaravelLocalization::transRoute('routes.about'),function(){
		        return "About";
		});
		
        Route::get(LaravelLocalization::transRoute('routes.view'),function($id){
		          return "Show: ".$id;
	   });

 });
</pre>

And lang/en/routes,php
<pre>
<?php 

return [
      "about"       =>  "about",
      "view"        =>  "view/{id}", 
];</pre>

**Comment by Stonos** [comment]
The problem seems to be in [line 278 of LaravelLocalization.php](https://github.com/mcamara/laravel-localization/blob/912e25c6c9d84cfb30fffb8320e5ef5c87766be4/src/Mcamara/LaravelLocalization/LaravelLocalization.php#L278-L281).

If you change it from:
```php
if ( !empty( $locale ) && ( $locale != $this->defaultLocale || !$this->hideDefaultLocaleInURL() ) )
{
	$parsed_url[ 'path' ] = $locale . '/' . ltrim($parsed_url[ 'path' ], '/');
}
```
to:
```php
if ( !empty( $locale ) )
{
	$parsed_url[ 'path' ] = $locale . '/' . ltrim($parsed_url[ 'path' ], '/');
}
```
it works fine.

**Comment by mcamara** [comment]
@Stonos This breaks other functionalities, like hiding the default locale.

I'm going to try to replicate the error and solve it.

**Comment by illuminate3** [comment]
Hi!

Note: neysi's code above is not the same as the readme. Possibly changes have been made to the readme.

I'm getting similar issues with latest update.
I'm using middleware and have only activated "en" and "es".
I'm also only looking at what the language selector is doing. I haven't even changed the CSS for what is posted in the readme. I followed the readme and not the code above.

```
	'hideDefaultLocaleInURL' => true,
```
I can't get out of Espanol ..

```
		"barryvdh/laravel-debugbar": "~2.0",
```
reports local as "es"


```
	'hideDefaultLocaleInURL' => false,
```
link shows "/en" and debug bar shows locale as "en"

Yes, I have also turned off debugging to see if Barry's debug bar is an issue.

**Comment by illuminate3** [comment]
I tried forcing the en/es to the url

```
<ul class="language_bar_chooser">
    @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
        <li>
            <a rel="alternate" hreflang="{{ $localeCode }}" href="/{{{ $localeCode }}}/">
                {{{ $properties['native'] }}} 123
            </a>
        </li>
    @endforeach
</ul>
```

Still stuck in spanish.

I will keep digging.

**Comment by illuminate3** [comment]
Somewhere there is a conflict!

config/app.php
```
	'locale' => 'ca',
```
Blocks me from returning to Catalan. When set to any language, session locale is not being set.

**Comment by illuminate3** [comment]
Lavel 5.0.28

Fresh install of laravel and laravel-localization

I set the language to "es" using the selector code in the readme. Try to return to English and Even tried to hard code as below.

```
LaravelLocalization::setLocale('en');
dd(Session::all());
```

locale still in "es" ... :frowning:

**Comment by illuminate3** [comment]
Here is the code that I'm using for the middleware.
Crude and Ugly but it works.

```
<?php
namespace Mcamara\LaravelLocalization\Middleware;

use Illuminate\Http\RedirectResponse;
use Illuminate\Contracts\Routing\Middleware;

use Closure;
use Config;
use Session;

class LocaleSessionRedirect implements Middleware {

/**
 * Handle an incoming request.
 *
 * @param  \Illuminate\Http\Request $request
 * @param  \Closure $next
 * @return mixed
 */
public function handle(
	$request,
	Closure $next
	)
{

// explode and grab URL data
		$params = explode('/', $request->path());

// Check for hideDefaultLocaleInURL and if we have not Locale in the url
		if ( (app('laravellocalization')->hideDefaultLocaleInURL() == true) && (count($params) > 0) ) {
// Use Larvel to set locale for session
			Session::put('locale', Config::get('app.locale'));
			return $next($request);
		}

// grab locale from URL
		if ( app('laravellocalization')->checkLocaleInSupportedLocales($params[0]) == true ) {
// put URL locale into session
			Session::put('locale', $params[0]);
			return $next($request);
		}
}

}
```

I hope that this works for some of you!

**Comment by rbngzlv** [comment]
Hi,

I'm newbie in Laravel development, but I want to share a little change that worked fine for me.

I have added an `else` condition to the first `if` in the LocaleSessionRedirect middleware.

```
/src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php
```
From:
```php
// ln 20
if ( count($params) > 0 && $locale = app('laravellocalization')->checkLocaleInSupportedLocales($params[ 0 ]) )
{
    session([ 'locale' => $params[ 0 ] ]);

    return $next($request);
}
```

to:

```php
// ln 20
if ( count($params) > 0 && $locale = app('laravellocalization')->checkLocaleInSupportedLocales($params[ 0 ]) )
{
    session([ 'locale' => $params[ 0 ] ]);

    return $next($request);
}
else if(app('laravellocalization')->hideDefaultLocaleInURL()) { // Added
    session([ 'locale' => app('laravellocalization')->getDefaultLocale() ]); // Added
} // Added
```

Someone have any thoughts if this change can break other functionalities?

**Comment by jartaud** [comment]
@rbngzlv this works for me!

**Comment by kaidoj** [comment]
@rbngzlv this works for me too! +1

**Comment by hotgeart** [comment]
This bug is still present. Why this issue is closed?

**Comment by dnisk** [comment]
Hi, don't know if someone still has this problem, I'm working on a project at the moment and this is my fix, maybe will help someone, I commented the changes I made, the edited file is: LaravelLocalization\Middleware\LocaleSessionRedirect.php
I'll past the whole file but the changes are in the last if block

`
        if ($locale && app('laravellocalization')->checkLocaleInSupportedLocales($locale) && !(app('laravellocalization')->getDefaultLocale() === $locale && app('laravellocalization')->hideDefaultLocaleInURL())) {
            app('session')->reflash();
            $new_locale = app('laravellocalization')->getDefaultLocale(); //New Local (Default)
            session(['locale' => app('laravellocalization')->getDefaultLocale()]); //Setting the session locale to Default
            $redirection = app('laravellocalization')->getLocalizedURL($new_locale); //Getting the Localized URL for the default locale
//            $redirection = app('laravellocalization')->getLocalizedURL($locale); //Old URL
            return new RedirectResponse($redirection, 302, ['Vary' => 'Accept-Language']);
        }
`

**Comment by k-s-i** [comment]
Hi there,

I had the same problem and used @dnisk solution to make it work. Is there any reason why this isn't fix on the master branch?

Many thanks!
Kevin
