### ISSUE TITLE
Can't install sous laravel 5.1

### ISSUE THREAD

**Issue by almaweb** [mcamara/laravel-localization#193]
how to make it work with laravel 5.1 ? merci

**Comment by Bouhnosaure** [comment]
Hello !

Yes i thing about the same thing, 
Is it possible to change the composer.json to accept the version 5.1 of laravel ?
in another branch or in the current branch,
that would be cool ! 

I think the current version of laravel-localization work on Laravel 5.1

Thank you for your great work with translations !

**Comment by monkeyC** [comment]
Hi,
I will also be glad if composer.json could be change to accept this version of laravel.
Thank you very much and keep up the good work !

**Comment by fisharebest** [comment]
What happens if you use:

```json
"require": {
  "laravel/framework": "5.0.x-dev",
  "mcamara/laravel-localzation": "1.*"
}
```

**Comment by Bouhnosaure** [comment]
Hello !
i'ts for Laravel 5.1
in the composer.json of laravel develop its 5.1 

```json
        "name": "laravel/laravel",
         ....
	"require": {
		"laravel/framework": "5.1.*"
	}
```

your proposition would be: 

```json
"require": {
  "laravel/framework": "5.x-dev",
  "mcamara/laravel-localzation": "1.*"
}
```

**Comment by fisharebest** [comment]
`5.0.x-dev` is an alias for `dev-master`.  It gives me the latest commit.

**Comment by Bouhnosaure** [comment]
For master branch, you will use a ```dev-master``` version. For develop branch, you will use ```dev-develop``` version
5.1 is on develop not master :/

**Comment by fisharebest** [comment]
> 5.1 is on develop not master :/

develop?  I only see master at https://github.com/laravel/framework

**Comment by Bouhnosaure** [comment]
See here ! 
https://github.com/laravel/laravel

**Comment by Bouhnosaure** [comment]
Laravel/framework is the core
Laravel/Laravel is the framework

of course laravel/laravel needs laravel/framework

**Comment by fisharebest** [comment]
> Laravel/Laravel is the framework for build app 

laravel/laravel is a template application.  You install this once and then modify it.  You do not update it with composer-update.

1) `composer create-project laravel/laravel my-project dev-develop`
2) edit `composer.json` as above
3) `composer update`

You now have the latest template application, the latest laravel/framework, and stable versions of everything else.

**Comment by rbruhn** [comment]
Looking for this to work with 5.1 as well.
