### ISSUE TITLE
Sub-Domain based Localization?

### ISSUE THREAD

**Issue by irazasyed** [mcamara/laravel-localization#194]
Hi,

Is it possible we could use this package and have sub-domain based localization?

For example:

The default would be: `www.domain.com` this would be English and if the user visits `fr.domain.com` then it'll set to French?

I tried doing but it kept appending the locale to the url at the end which doesn't seem to work.

Let me know!

Thanks!

**Comment by KIVagant** [comment]
I vote for this too.

**Comment by dennisoderwald** [comment]
+1

**Comment by canfiax** [comment]
I definitely vote for this too. @mcamara what do you think?
