### ISSUE TITLE
Route [***.index] not defined when set language in url

### ISSUE THREAD

**Issue by tutNichts** [mcamara/laravel-localization#195]
Hey,
I've grouped all routes with the prefix "LaravelLocalization::setLocale()" and the "LaravelLocalizationRedirectFilter"-filter:

```php
Route::group(array('prefix'=>LaravelLocalization::setLocale(), 'before'=>'LaravelLocalizationRedirectFilter'), function() {
    Route::get('/', 'HomeController@showIndex');
    Route::resource('battle', 'BattleController');
    /* ... */
});
```

Now, when I would like to change the language, like:
http://localhost/battle/en

I get the error:
Route [battle.index] not defined. (View: C:\xampp\htdocs\battle\app\views\includes\navigation.blade.php) (View: C:\xampp\htdocs\battle\app\views\includes\navigation.blade.php)

In the navigation.blade.php I create the link like this:
```html
<li><a href="{{ URL::route('battle.index') }}">@lang('menus.main.battle')</a></li>
```

What do I must change? I think I should use "LaravelLocalization::getLocalizedURL()" in case of  "URL::route()"?! But do I realy have to go through all the files and change the function-call? Is there any other way?

Or did I missunterstand the laravel localization? Can someone help me?
Thanks a lot!

Sorry for my bad english,
best regards,
V.

**Comment by MarcGuay** [comment]
See https://github.com/mcamara/laravel-localization/issues/191
