### ISSUE TITLE
Non-static method setLocale() called statically

### ISSUE THREAD

**Issue by AlexVonB** [mcamara/laravel-localization#197]
Hi,

I'm using Laravel 5.0.23 and your 1.0.7. When writing

    Route::group(['prefix' => LaravelLocalization::setLocale()], function()
    {
        Route::get('/', 'WelcomeController@index');
    });

I get

    Non-static method Mcamara\LaravelLocalization\LaravelLocalization::setLocale() should not be called statically, assuming $this from incompatible context

which seems reasonable, because `setLocale()` uses `$this`. What am I missing?

Best, Alex

**Comment by mcamara** [comment]
Have you created the alias in the app.php file?

**Comment by AlexVonB** [comment]
Yep, when i deliberately misspell `LaravelLocalization` it says `Class LaravelLocalizatio not found`.

**Comment by AlexVonB** [comment]
Well, nevermind, did not use the Facade, but the normal class. My bad, thank you!

**Comment by mcamara** [comment]
Don't worry, happy to see it's working for you! :)

**Comment by amir-habibi-dev** [comment]
hi
i got problem in laravel 8 and php 8

  Non-static method Mcamara\LaravelLocalization\LaravelLocalization::setLocale() cannot be called statically

i used:

**Comment by amir-habibi-dev** [comment]
use Mcamara\LaravelLocalization\LaravelLocalization;

**Comment by piotrku** [comment]
The same problem here.
And I don't see `setLocale()` being static [here](https://github.com/mcamara/laravel-localization/blob/afe2e677f280dfdb19ceebb5f8cfe894fb036c17/src/Mcamara/LaravelLocalization/LaravelLocalization.php#L156).

**Comment by piotrku** [comment]
OK, you should use:
`use \Mcamara\LaravelLocalization\Facades\LaravelLocalization`
instead of
`use Mcamara\LaravelLocalization\LaravelLocalization`
the documentation could be better.
