### ISSUE TITLE
Event routes.translation

### ISSUE THREAD

**Issue by GregoryClaeyssens** [mcamara/laravel-localization#200]
2 issues with this event listener.

1. the $locale variable is no longer passed, so it is impossible to know to which language the parameters need to be translated. (also doc's still say this is passed, so I presume this is an error)

2. If set up the event listener, and it's called as expected. I have tried translating them with a fixed locale ( since this isn't passed anymore, see 1).
I'v checked and the parameters are perfectly translated, but the url's don't seem to use them?

Routes.php 
```
Route::get(LaravelLocalization::transRoute('routes.page.show'), array('as' => 'page', 'uses' => 'PageController@show'));
```

nl/routes.php 
```
'page'      => [
        'show'      => '{slug}',
],
```
fr/routes.php 
```
'page'      => [
        'show'      => '{slug}',
],
```

EventServiceProvider.php, boot function
```
        Event::listen('routes.translation', function($attributes)
        {
            $locale = 'fr';
            foreach( $attributes as $k => $v ){
                if($k === 'slug'){
                    $attributes[$k] = RouteTranslator::translateSlug($v, $locale);
                }
            }
            return $attributes;
        });
```

Results
nl: http://mydomain.com/nl/bedrijven
fr: http://mydomain.com/fr/bedrijven

What i expected
nl: http://mydomain.com/nl/bedrijven
fr: http://mydomain.com/fr/entreprises

The thing is the Event is called and the $attributes array is returned with a translated slug.
var dumb gives me:
```
array(1) {
  ["slug"]=>
  string(11) "entreprises"
}
```

**Comment by arcanedev-maroc** [comment]
Replace `$locale = 'fr';` by `$locale = LaravelLocalization::getCurrentLocale();`.

**Comment by GregoryClaeyssens** [comment]
Wouldn't getCurrentLocale() return the current locale (as is the name of the function). This would give me 'nl'.(translating from nl to fr). You need 2 locales to be able to translate a parameter. The current locale and the locale you are translating to. (except for the situation where you only have 2).

**Comment by arcanedev-maroc** [comment]
Check : https://github.com/mcamara/laravel-localization/issues/166

**Comment by arcanedev-maroc** [comment]
I'm going to test your case and try to find out a solution because i'm working on my own localization package.

You can look at it and try if it solves your problem: https://github.com/ARCANEDEV/Localization

Bon week end (French speaker here :+1: )

**Comment by arcanedev-maroc** [comment]
Hello @GregoryClaeyssens,

Check out my new translation event : https://github.com/ARCANEDEV/Localization/blob/master/_docs/4-Usage.md#events

Hope this helps you.
