### ISSUE TITLE
Not working with cached routes

### ISSUE THREAD

**Issue by Casinelli** [mcamara/laravel-localization#201]
Any way to make it work with cached routes? (using ```php artisan route:cache```)

**Comment by christiaan-lombard** [comment]
Not sure if it will work with sessions and route translations, but try this:

In your *routes.php*, set the localized group prefix to '{locale?}', instead of Localization::setLocale(), and add **set_locale** middleware before other localization middlewares:

```php

Route::group(

  [
    'middleware' => ['set_locale', 'localizationRedirect', 'localeSessionRedirect'],
    'prefix' => '{locale?}'
  ],

  function()
  {
      Route::get('/',         'HomeController@getIndex');
  }
);

```

The **set_locale** middleware, added to your kernel, will grab the **locale?** parameter and set it as the current locale:

``` php

class SetLocale implements Middleware {


  public function handle($request, Closure $next)
  {

    $locale = $request->route('locale');
    Localization::setLocale($locale);
    return $next($request);
  }
}

```

**Comment by Casinelli** [comment]
Thanks! It works for setting up the routes correctly, but now using ```URL::route()``` gives the link without including the locale. For example using the 'it' language, and doing ```URL::route('profile')```, I get ```/profile```, instead of ```/it/profile```. Trying to override the UrlGenerator now, though not sure it's the best way to go about it.

**Comment by christiaan-lombard** [comment]
Yeah, I can see how this solution could break a few things. A workaround is to send the current locale as a parameter to the url generator.

```php

URL::route( 'profile', [ 'locale' => LaravelLocalization::getCurrentLocale() ] )

```

I made this helper function to get a localized URL:

``` php

function route_local($name, $parameters = array(), $absolute = true, $route = null)
  {

    $parameters = array_merge($parameters, ['locale' => (string) LaravelLocalization::getCurrentLocale()]);

    return app('url')->route($name, $parameters, $absolute, $route);
  }


```

**Comment by arjankapteijn** [comment]
I'm having the same problem but change the route generates an error. "Class set_locale does not exist".

**Comment by Cyrille37** [comment]
For cross reference :
- https://github.com/mcamara/laravel-localization#caching-routes
- https://github.com/czim/laravel-localization-route-cache
