### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by rbruhn** [mcamara/laravel-localization#202]
Is there a way this can work with Annotations?
http://laravelcollective.com/docs/5.0/annotations

Using annotations allows comments in Controllers to build a scanned routes file.

**Comment by mcamara** [comment]
As Annotations are finally an external feature of Laravel and not a core one I haven't worried about them (and I'm also in the group that hates annotations).

If you find a way to make the plugin work with annotations, I would be more than happy to merge your code and write it into the README.

**Comment by rbruhn** [comment]
Actually, the solution I found is not difficult at all. It also allows continuing use of existing routes in the routes.php file if you like. I can keep my normal routes until I upgrade everything.

Example of my /HTTP/routes.php
```php
$router->pattern('id', '[0-9]+');
$router->group([ 'prefix' => Local::setLocale(), 'before' => 'LocalRedirectFilter'], function ($router) {

        if (File::exists(storage_path('framework/routes.scanned.php')))
            require_once storage_path('framework/routes.scanned.php');

        $router->get('phpinfo', ['as' => 'phpinfo', 'uses' => 'ServerInfoController@showPhpInfo']);
        /** ... continuation of other routes **/
    }
);
```
