### ISSUE TITLE
Validation message are not translated

### ISSUE THREAD

**Issue by timbertens** [mcamara/laravel-localization#203]
Hi,
I have a working setup of your module with multiple language enabled for a site.  The 'regular' language files are working fine to show translated content, however the validation messages (although present in multiple languages) are only shown in 1 language.  Any idea? 
rg,
Tim

**Comment by mcamara** [comment]
Check laravel documentation for localization http://laravel.com/docs/master/localization

**Comment by antsliivat** [comment]
Hello!

I am experiencing the same issue. Checked the documentation but no help. I am using Laravel Spark (bought license). Still having trouble with getting validation lines translated - everything else works fine.

Could you please help?

**Comment by timbertens** [comment]
I'm can't recall exactly, but I believe adding 

use lang;

to your requests does the trick.  With 'lang' being an alias to Illuminate\Support\Facades\Lang

**Comment by antsliivat** [comment]
Hello!

Thank you for your answer!

Actually, adding PUT routes under Localized Routes Group in routes.php did the trick. Also, I activated the hiding of abbreviation of default language in the URL. I hope that this answer helps somebody else as well with this kind of issue.
