### ISSUE TITLE
application multilingual

### ISSUE THREAD

**Issue by saraswathik** [mcamara/laravel-localization#205]
our former developer has  placed all the labels and other text elements in the code, instead of proper reference to a language file. also we do not yet have a mechanism in front-end nor back-end to switch languages. 

replacing the labels ,tool tips, text-fields is not a matter in localization,

The problem i am facing is,

I want to change the error messages and email text( which text we are sending to the client), and text area data based on selected language.

Please please anybody help me 

Thanks in advance

**Comment by mcamara** [comment]
Check Laravel documentation for localization http://laravel.com/docs/master/localization
