### ISSUE TITLE
Making work LocaleCookieRedirect middleware

### ISSUE THREAD

**Issue by iaguilera** [mcamara/laravel-localization#206]
Hello, I cant make work LocaleCookieRedirect middleware properly.

I revised code and i finally get it working, doing these changes:
1. Add before class declaration:
use Cookie;
2. Change
cookie('locale', $params[ 0 ]);

by

Cookie::queue('locale', $params[ 0 ], 30 * 24 * 60);

because created cookie was not being assigned to a response. Queueing it is a way to put it in the response. No lifetime for the cookie was established, too, so the cookie only would live until explorer closes. I want cookie live for some days, 30 for example (30 * 24 * 60 minutes), so added time (maybe ii would be nice to add it as configuration parameter).

So Im new with the use of this pluggin, I wanted to ask if this middleware was working properly and maybe im not setting up it correctly, or if these changes are really needed.

Thanks

**Comment by mkwsra** [comment]
:+1:

**Comment by elv1ss** [comment]
Hello, may as well use this code
```
if ( count($params) > 0 && app('laravellocalization')->checkLocaleInSupportedLocales($params[ 0 ]) )
        {
            return $next($request)->withCookie(cookie()->forever('locale', $params[ 0 ]));
        }
```
if you need cookie live long time.
