### ISSUE TITLE
Why lowercase only some native language names?

### ISSUE THREAD

**Issue by goyote** [mcamara/laravel-localization#211]
In laravellocalization.php is there a reason why "**E**nglish" is written with first letter uppercase but "**e**spañol" starts with lowercase letter?

**Comment by fisharebest** [comment]
It is because English language rules are to capitalise the names of languages - while Spanish language rules are to use lower case.

"english" would be wrong in English
"Espanol" would be wrong in Spanish

**Comment by mkwsra** [comment]
@fisharebest  Good to know
