### ISSUE TITLE
Make short helper-functions

### ISSUE THREAD

**Issue by KIVagant** [mcamara/laravel-localization#218]
Why localisation helpers is so long?

My eyes bleed when I see it:
```php
//Should be called in a view like this:
{{ LaravelLocalization::getLocalizedURL
```

And especially when I trying to get URL in real template:
```php
<form action="{{ LaravelLocalization::getLocalizedURL(LaravelLocalization::getCurrentLocale(), '/auth/register') }}" > </form>
```

Please, add a default short helper functions, something like:
```
<a href="{{ locale_url('/home', ['param1' => 1]) }}">Welcome home</a>
```

**Comment by mkwsra** [comment]
:+1:   but first I wish the other problems to be fixed

**Comment by jaumesala** [comment]
@KIVagant you can always generate a URL for a given named route using `route()` helper.
It will localize the route (with the current app.locale) according to the translation in the routes.php file
```PHP
<form action="{{ route('name.route') }}" > ... </form>
```

**Comment by tyler36** [comment]
@jaumesala that doesn't seem to work for me.

I have the following in my view
```
<a href="{{ route('news.index) }}">link</a>
```

If I visit the page, '/home', no problem; if I visit '/en/home' I get an error:
```
Route [news.show] not defined
```

I'm not sure why, but the following works:
```
<a href="{{ action('NewsController@index) }}">link</a>
```

Does this mean I have to change all my 'route' commands to ugly 'action' commands to use this plugin?

**Comment by MarcGuay** [comment]
@tyler36 See https://github.com/mcamara/laravel-localization/issues/191
