### ISSUE TITLE
Laravel 5.1 support

### ISSUE THREAD

**Issue by Rikcon** [mcamara/laravel-localization#224]
Taylor Otwell released Laravel 5.1 today, looking forward to see laravel-localization updated so i can upgrade my website to 5.1 !

**Comment by dennisoderwald** [comment]
+1

**Comment by Rikcon** [comment]
There is a commit 
https://github.com/mcamara/laravel-localization/commit/1ea7695cc7cc36914b2b8ff0dbb05929f17f63b8

But composer still wants version 5.0.x

**Comment by dennisoderwald** [comment]
Yes, I can confirm.

**Comment by DarkaOnLine** [comment]
You need to change dist to dev-master (hope temporally), because  where are no release with this commit :(

```
"mcamara/laravel-localization": "dev-master"
```

@mcamara  can you make new release with 5.1 support ?

**Comment by dennisoderwald** [comment]
dev-master dont change the issue, same message.

**Comment by DarkaOnLine** [comment]
strange, for me worked perfectly

**Comment by Rikcon** [comment]
"mcamara/laravel-localization": "dev-master"

Worked for me ! 

But there is still a need for a release @mcamara

**Comment by dennisoderwald** [comment]
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

> Problem 1
>    - Installation request for mcamara/laravel-localization dev-master -> satisfiable by mcamara/laravel-localization[dev-master].

**Comment by DarkaOnLine** [comment]
Try to add these two lines at the end of coposer.json
```
"minimum-stability" : "dev",
"prefer-stable": true
```

**Comment by dennisoderwald** [comment]
Thanks @DarkaOnLine so far.

**Comment by mcamara** [comment]
The latest version (1.0.8) should have support for 5.1 version, I cannot check it as I have too much work to do.

Sorry for the delay in all new features and fixing some bugs, but I will not have time to solve them until end of August. I can promise I will check pull requests more often and tag new versions faster than now.

**Comment by dennisoderwald** [comment]
Thanks @mcamara! :) :+1:

**Comment by acacha** [comment]
Please update README.met to clarify Laravel 5.1 support

**Comment by bogdan8** [comment]
![2015-12-29 10 53 46](https://cloud.githubusercontent.com/assets/12710600/12031875/923b2436-ae1a-11e5-891c-4e6f3469f223.png)
What shall I do?

**Comment by rtucek** [comment]
@bogdan8 
```composer require mcamara/laravel-localization 1.0.*```
rather than
```composer require mcamara/laravel-localization 1.1.*```

v1.1 and above drops compatibility to older Laravel versions [see Laravel compatibility](https://github.com/mcamara/laravel-localization#laravel-compatibility).

**Comment by bogdan8** [comment]
@rtucek 
![2015-12-29 12 02 00](https://cloud.githubusercontent.com/assets/12710600/12032724/27d482ae-ae24-11e5-9670-93bd6f0a4f33.png)

**Comment by bogdan8** [comment]
@rtucek thank you

**Comment by rtucek** [comment]
@bogdan8 
Once again... don't user version 1.1.* **IF** you're not running Laravel 5.2
```
composer remove mcamara/laravel-localization 1.1.*
composer require mcamara/laravel-localization 1.0.*
composer install
```
