### ISSUE TITLE
It is not working properly with composed language codes, e. g. pt-BR

### ISSUE THREAD

**Issue by jhonatan-hulse** [mcamara/laravel-localization#233]
Overview
------------

When accessed by a browser with pt-BR locale, the Accept-Language sent to server is lowercased (pt-br) causing problem when it is trying to find matches (in LanguageNegotiator -> getMatchesFromAcceptedLanguages).

Improvement
-----------------

Another point is that the redirector could work when using similar language code, for example, using pt-br, pt_BR or pT_Br should redirect to the correct one (pt-BR).

How to verify it
-------------------

I am using google Chrome with Quick Language Switcher extension that allow changing between languages. When using portuguese (Brazil) the Accept-language is pt-br causing no match found.

**Comment by meduzen** [comment]
I think a full support of the `language_TERROTORY` format would be great to match with the [Open Graph Protocol](http://ogp.me/#optional). The [config file] (https://github.com/mcamara/laravel-localization/blob/master/src/config/config.php) is properly built to host one more column with that.
