### ISSUE TITLE
negotiateLanguage throws when no header info is submit

### ISSUE THREAD

**Issue by jeroenbourgois** [mcamara/laravel-localization#234]
Hi!

We were testing our application with Phantomjs and it threw an error for an `null` value inside the `negotiateLanguage` function. 

Probably an edge case, but when the `matches` array has a '*' value, it returns a `$array` that is never set, and thus null. We suspect that it should return the `$matches` instead? We forked it and that does seems to fix it.

This is the actual problem, inside `vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LanguageNegotiator.php`

```
if(isset($mathes[ '*' ])) {
  reset($this->supportedLanguages);
  return key($array); // $array is never set 
}
```

We will submit a PR shortly. Thank you any way for this great package!

**Comment by fzhan** [comment]
@jeroenbourgois I've tried your fix, however it will raise another issuer with 
Mcamara\LaravelLocalization\Exceptions\UnsupportedLocaleException
on line 218 where $locale is actually null/empty on:
```
        #line 216  vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LanguageNegotiator.php
        if ( !$this->checkLocaleInSupportedLocales($locale) )
```
Error message:
```
ERROR: exception 'Mcamara\LaravelLocalization\Exceptions\UnsupportedLocaleException' with message 'Locale '' is not in the list of supported locales.' 
```
