### ISSUE TITLE
set supported locales?

### ISSUE THREAD

**Issue by carlituxman** [mcamara/laravel-localization#237]
is possible to change the supported locales without editing the config file? for example having the locales on my database and setting with a function?

**Comment by rafamds** [comment]
I wanted to know this too, anyone?

**Comment by gjportegies** [comment]
I'm looking for a solution too on this. I have a table with Languages that can be managed from the admin panel. It would be great to have the option to load/set the supported locales from this database table. Does someone already have a workaround for this?

**Comment by gjportegies** [comment]
I found a workaround for this. I did the following things. 

### Created a language service class
```php
namespace Admin\Services;

use App\Repositories\Contracts\LanguageRepository;

class LanguageService
{
    /**
     * @var LanguageRepository
     */
    protected $repository;

    public function __construct(LanguageRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Get the supported locales/languages
     *
     * @return mixed
     */
    public function getSupportedLocales()
    {
        $locales = [];
        $languages = $this->repository->findByField('active', 1);

        foreach ($languages as $lang) {
            $locales[$lang->code] = [
                'name' => $lang->name,
                'script' => 'Latn',
                'native' => $lang->translate($lang->code)->name
            ];
        }

        return $locales;
    }
}
```

### Created a facade
```php
namespace Admin\Facades;

use Illuminate\Support\Facades\Facade;

class LanguageFacade extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'language';
    }
}
```

### Binding with ServiceProvider
```php
namespace Admin\Providers;

use Illuminate\Support\ServiceProvider;

class LanguageServiceProvider extends ServiceProvider
{
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind('language', 'Admin\\Services\\LanguageService');
    }
}
```

### Configuration
```php
'providers' => [
    ...
    'App\Providers\AppServiceProvider',
    ...
    'Admin\Providers\LanguageServiceProvider',
],
```

```php
'aliases' => [
    ...
    'Locale' => Admin\Facades\LanguageFacade::class,
],
```

### Setup/configuration for localization
I created a config service provider like mentioned in [the description](https://github.com/mcamara/laravel-localization#service-providers) of laravel-localization.

```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Locale;

class ConfigServiceProvider extends ServiceProvider
{
    public function boot()
    {
        config([
            'laravellocalization.supportedLocales' => Locale::getSupportedLocales(),
            'laravellocalization.useAcceptLanguageHeader' => true,
            'hideDefaultLocaleInURL' => true
        ]);
    }

    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

**Comment by arcanedev-maroc** [comment]
Yes this can solve your problem, but the issue is you must store all supported locales attributes into your database instead of using only the locales keys. 

And also, the config may change also (like the new regional attribute).

**Try to check this package :** https://github.com/ARCANEDEV/Localization

To set the supported locales, you only need to specify the locales keys : https://github.com/ARCANEDEV/Localization/blob/master/config/localization.php#L8

**Bonus :** You can also use the [locales entities](https://github.com/ARCANEDEV/Localization/tree/master/src/Entities) to retrieve the locale attributes based on the config file.

**Comment by Mallariel** [comment]
> @gjportegies, Yes this can solve your problem, but the issue is you must store all supported locales attributes into your database instead of using only the locales keys.

Yes, but we don't have to store all attributes, all we need is a short code, and then just subtract from config.

For example below:
```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use LanguageService;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

class LocaleServiceProvider extends ServiceProvider
{

    public function boot()
    {
        $configLocales = LaravelLocalization::getSupportedLocales();
        $siteLocales = LanguageService::getSupportedLocales();

        $supportedLocales = array_reduce($siteLocales, function ($acc, $locale) use ($configLocales) {
            if(array_key_exists($locale, $configLocales)) {
                $acc[$locale] = $configLocales[$locale];
            }
            return $acc;
        }, []);

        LaravelLocalization::setSupportedLocales($supportedLocales);
    }

    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
//
    }
}
```
