### ISSUE TITLE
LaravelLocalization::getLocalizedURL return wrong host when proxy server is used

### ISSUE THREAD

**Issue by scil** [mcamara/laravel-localization#239]
I use nginx to respone to static files, and other using a swoole web server which listen to localhost:9501.
```
    location / {
        try_files $uri $uri/ @other;
    }

    location @other {
                proxy_http_version 1.1;
                proxy_set_header Connection "keep-alive";
                proxy_pass http://127.0.0.1:9501;
    }
```

so  when i visit `  http://server/backend `,   i was redirected to ` http://127.0.0.1:9501/en/backend `

Is there any way to get ` http://server/en/backend `

**Comment by fisharebest** [comment]
Normally, you would set the `HTTP_X_FORWARDED_*` headers in your nginx config.  e.g.

```
proxy_param HTTP_X_FORWARDED_PORT 80;
proxy_param HTTP_X_FORWARDED_PROTO http;
proxy_param HTTP_X_FORWARDED_HOST server;
```

This allows the symfony `Reqeust` component to generate the correct URL.

**Comment by scil** [comment]
Thank you. I use `proxy_set_header ` and everything is ok.

**Comment by g4b0** [comment]
I'm having the same issue with apache, which Proxy directive can solve? Thanks
