### ISSUE TITLE
404 localization

### ISSUE THREAD

**Issue by DanielNetoP** [mcamara/laravel-localization#241]
I have the automatic prefix on so when I go to example.com/home it redirects to example.com/en/home, but in the case of using example.com/asdasd it doesn't redirect to example.com/en/asdasd (The page doesn't exist, is a 404 example).

**Comment by CreativityKills** [comment]
+1

**Comment by mkwsra** [comment]
+1 indeed I just gave it a try, it will fallback to the default locale
www.healthtour.com
