### ISSUE TITLE
Language Negotiator - Might habe a Bug for * Accept Language Headers

### ISSUE THREAD

**Issue by superdummy** [mcamara/laravel-localization#245]
I will most likely use the library in my project so I looked at the source to understand in more detailed what the library does. In Language Negotiator: 
https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/LanguageNegotiator.php, there are these tow Lines: 

reset($this->supportedLanguages);
return key($array);

And the variable $array is never defined in the whole class. This could be a bug. Just guessing but I assume it could correctly mean: 
return key($this->supportedLanguages) ?

As stated I do not use the library, just spotted this from looking at the source and I might completely be wrong.

Thanks

**Comment by arcanedev-maroc** [comment]
Yeah, i totally agree with you @superdummy.

The source code is super messy, hard to read or to understand how it's work 

I loved this package but i'm a little bit 'OCD' about how the code is written and maintained, so i decided to made my own (inspired from mcamara/laravel-localization).

The repo : https://github.com/ARCANEDEV/Localization (Still WIP)
