### ISSUE TITLE
New laravel localization package

### ISSUE THREAD

**Issue by arcanedev-maroc** [mcamara/laravel-localization#248]
Hi everyone and especially @mcamara.

I love this package a lot but i was disappointed when i want to contribute to it ***(Me implements CancerInterface)***.

So i decided to create my own package (for my future L5 projects) and hope @mcamara and the laravel artisans to look at it and test it.

Repo : https://github.com/ARCANEDEV/Localization (WIP, NSFW for the time being)

May wish to get feedback from you to improve it.

Thanks,

**Comment by mkwsra** [comment]
I'm going to test it in my next project, which is close.
You did the best by this move,  please keep improving it and stay open to others' pull requests.... eventually it's open source community. 
:+1:

**Comment by arcanedev-maroc** [comment]
Of course i'm going to imporve it and i'm open to hear your suggestions and your pull requests. 

Hope this package helps you in your projets.

**Comment by nWidart** [comment]
Interesting! Will take a look at this asap For [AsgardCms](https://asgardcms.com/en). Since this package isn't maintained anymore it seems.
