### ISSUE TITLE
Ajax Post - 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by galhardi** [mcamara/laravel-localization#257]
I'm using laravel-localization and I have the erro 405 (Method Not Allowed) only in ajax Post methods.
Please, someone could help?

**Comment by rtucek** [comment]
Having the same issue here.

I guess you and I are trying to send a post request to an unlocalized URL and hopping for the proper redirection. Well, it took me an hour to remember that we can't "just redirect" post requests. Especially not with a HTTP 301/302.

Redirecting a POST request requires a HTTP 307 (which isn't technically a "follow the rabbit" redirect. It tells the client to **resend** his request to different URI).

By glancing over the source code and the issues, this package had support for 307 HTTP responses at some point as mentioned in the [Changelog v0.12.0](https://github.com/mcamara/laravel-localization/blob/master/CHANGELOG.md#0120), #62, #63 and #215, but now it's missing for some reason.

@mcamara may you bring back HTTP 307 response support. Why has it been removed?

**Comment by rtucek** [comment]
Ok, I did some research on [W3.org](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html).

You may mind this quote:
"If the 307 status code is received in response to a request other than GET or HEAD, the user agent **MUST NOT automatically redirect the request unless it can be confirmed by the user**, since this might change the conditions under which the request was issued."

**Comment by BojanKogoj** [comment]
Is there a reason why you would want to POST to unlocalized URL?

**Comment by rtucek** [comment]
No it's definitely not a must have and the workaround is simple (at least it was for me in Laravel).
However, I believe it's worth mentioning in the documentation at least. There are enough issues here, complaining about broken post requests.

**Comment by commandantp** [comment]
what was your work around @rtucek ? Sending the POST with a /en/  ?

**Comment by clifmo** [comment]
Simple workaround? please share.

My AJAX POSTs just turned in to GETs.

**Comment by rtucek** [comment]
From Drupal, I was able to pass PHP variables to JavaScript on pageload.
So ported this functionality into my Laravel app.

So in Javascript prefixed all my urls with settings.language (no matter what request type they perform) in order to match the route.
```javascript
url = settings.language + '/ajax/...';
```

Unfortunately, I haven't noticed an already existing repo on Github by the time.
https://github.com/laracasts/PHP-Vars-To-Js-Transformer

**Comment by camel-chased** [comment]
same here, all ajax request are 405 Method Not Allowed

**Comment by galhardi** [comment]
POST method dont need localization
Em 05/07/2016 12:30, "camel-chased" <notifications@github.com> escreveu:

**Comment by camel-chased** [comment]
@galhardi yes but ```Moreover, this package includes a middleware object to redirect all "non-localized" routes to the corresponding "localized".```

**Comment by galhardi** [comment]
I dont remember exactly but I think that I used two differents midlewares
in route config
Em 05/07/2016 13:03, "camel-chased" <notifications@github.com> escreveu:

@galhardi <https://github.com/galhardi> yes but Moreover, this package
includes a middleware object to redirect all "non-localized" routes to the
corresponding "localized".

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mcamara/laravel-localization/issues/257#issuecomment-230522839>,
or mute the thread
<https://github.com/notifications/unsubscribe/ANImSYU71UdkOIwYL2RyHmGhOIEyyuT1ks5qSoA6gaJpZM4Ggc3F>
.

**Comment by shy7lo** [comment]
The easiest way to fix it is to use full url in your ajax request. To do so, define a JS variable called url like below 

`var url "{!! url('/').'/'.\Mcamara\LaravelLocalization\Facades\LaravelLocalization::getCurrentLocale() !!}"`

And then in your JS (also works in Vue.js components), use them as below 

`url + '/customer/login'`

I am using it this way in vue.js components in Laravel 5.3 and it works like a charm.

**Comment by altafhussain10** [comment]
The easiest way to fix it is to use full url in your ajax request. To do so, define a JS variable called url like below  

`var url "{!! url('/').'/'.\Mcamara\LaravelLocalization\Facades\LaravelLocalization::getCurrentLocale() !!}"  `

And then in your JS (also works in Vue.js components), use them as below 

` url + '/customer/login' `

 I am using it this way in vue.js components in Laravel 5.3 and it works like a charm.
