### ISSUE TITLE
Carbon not using correct locale

### ISSUE THREAD

**Issue by BojanKogoj** [mcamara/laravel-localization#261]
The long description and possibly solution is on StackOverflow [Carbon with Laravellocalization not using correct locale](http://stackoverflow.com/questions/33919730/carbon-with-laravellocalization-not-using-correct-locale).

The main issue is that Carbon needs LC_TIME locale like 'de_DE.utf8' to be able to use it, but I only have 'de' right now. 

I intend (for now) to extend the class as I said on StackOverflow, but should I fix and create a pull request?

**Comment by mcamara** [comment]
Hi Bojan,

I think your solution is good, if you create a pull request I will be more than glad to review it,create a new version and push it.

PS: Just one thing, can you put the regional key the last one for any language?
```
'de' => ['name' => 'German','script' => 'Latn', 'native' => 'Deutsch', 'regional' => 'de_DE.utf8']
```

**Comment by BojanKogoj** [comment]
Hi mcamara, I only put regional key as the first one for StackOverflow users since it would be partially hidden there.

I also need to make sure it works correctly on windows devices, no idea how locale works there

**Comment by mcamara** [comment]
I have also replied another solution on yout stackoverflow issue. Let me know what do you think.

**Comment by BojanKogoj** [comment]
Let me know if you like the changes before I make a pull request https://github.com/BojanKogoj/laravel-localization/commit/12dad5d93c8245738a19face8a5d2f4b6b1a8b85

**Comment by mcamara** [comment]
I have commented it, it looks good!

**Comment by BojanKogoj** [comment]
Test added, replied on the default issue

**Comment by fisharebest** [comment]
If it is helpful, I have created a localization database - https://github.com/fisharebest/localization

Instead of `'regional' => 'de_DE.utf8'`, you could use a `LocaleDe` object.

As well as locale codes (de_DE), language tags (de), etc., it provides lots of other useful services, such as localization for numbers.

One way you could use it is

```
'supported_locales' = [
  new LocaleDe,
  new LocaleEnUs,
  new LocaleFr,
]
```

**Comment by mcamara** [comment]
@fisharebest Thanks for your package, I really like the idea and it would be great to have it on this package.

@BojanKogoj Merged to master branch. Thanks!
