### ISSUE TITLE
LaravelLocalization::localizeURL with variable

### ISSUE THREAD

**Issue by pionas** [mcamara/laravel-localization#264]
Hi,

i used your script.
I have got some problem.
I create edit form - http://localhost/article/edit/{id}.
This form redirect to http://localhost/article/edit/{id} with POST method.
```{!! Form::open(array('route' => array('article_edit', $article->id))) !!}```
If something was wrong redirecto to edit form with:
```return redirect()->back()->withErrors($validator)
                        ->withInput();```

but when everything is okay i would like redirect to article show
```
		return redirect(
			LaravelLocalization::localizeURL(
				LaravelLocalization::transRoute('routes.article_show')
			)
		)->with('slug', $slug);
```
but this not work.

What i should do?

My router file:
```
Route::group(['prefix' => LaravelLocalization::setLocale()], function()
{
	Route::get(
		LaravelLocalization::transRoute('routes.article_edit'),
		array(
			'as' => 'article_edit',
			'uses' => 'ArticlesController@edit'
		)
	)->where('id', '[0-9]+');
	Route::post(
		LaravelLocalization::transRoute('routes.article_edit'),
		array(
			'as' => 'article_edit',
			'uses' => 'ArticlesController@update'
		)
	)->where('id', '[0-9]+');
	Route::get(
		LaravelLocalization::transRoute('routes.article_show'),
		array(
			'as' => 'article_show',
			'uses' => 'ArticlesController@showByString'
		)
	)->where('slug', '[A-Za-z]+');
}
```

lang router:
```
return [
	"article_edit"	=>  "article/edit/{id}",
	"article_show"  =>  "article/show/{slug}",
];
```
Thanks for answer

**Comment by BojanKogoj** [comment]
Doesn't work? What doesn't work? What happens? Any errors?

**Comment by pionas** [comment]
Hi.

I'm sorry, but I was in the hospital.
I forgot about example.
when i'm editing article ( http://locahost/en/article/edit/1 )
and if no any errors they should redirect to:
http://localhost/en/article/show/first-article
but now redirect to:
http://localhost/en/article/show/{slug}

**Comment by pionas** [comment]
I found an answer ;)
I should change it:
```
		return redirect(
			LaravelLocalization::localizeURL(
				LaravelLocalization::transRoute('routes.article_show')
			)
		)->with('slug', $slug);
```

to:

```
		return redirect()->route('article_show', ['slug' => $slug]);
```
It works for routes with the name

Closed,

Thanks
