### ISSUE TITLE
Post request does not work

### ISSUE THREAD

**Issue by binalfew** [mcamara/laravel-localization#265]
Here is what i put in my routes file:

```
Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', 'localizationRedirect']
], function () {
    // Authentication routes...
    Route::get('auth/login', 'Auth\AuthController@getLogin');
    Route::post('auth/login', 'Auth\AuthController@postLogin');
});
```

If I request http://app-url/en/auth/login, it works fine and presents the login form but it fails to post to
http://app-url/en/auth/login.

Any, ideas?

Thanks.

**Comment by rtucek** [comment]
I guess this is related to my [comment](https://github.com/mcamara/laravel-localization/issues/257#issuecomment-162742522) in #257
