### ISSUE TITLE
Route Translation with directories?

### ISSUE THREAD

**Issue by JimLfe** [mcamara/laravel-localization#267]
How can I translate a route with directories, like:
en: /company/profile/view
de: /firma/profil/ansicht

How would the routes.php look for something like this?
I can't find something like this in the examples.

**Comment by BojanKogoj** [comment]
Under 'Translated Routes' you can find an example

**Comment by JimLfe** [comment]
Hmm no? which one do you mean?

**Comment by BojanKogoj** [comment]
```
// resources/lang/es/routes.php
    return [
      "about"       =>  "acerca",
      "view"        =>  "ver/{id}", //we add a route parameter
      // other translated routes
    ];
```

**Comment by JimLfe** [comment]
So for my example I would use in lang/en/routes.php:
>    return [
      "view"       =>  "/company/profile/view",
    ];
and in my lang/de/routes.php:
>    return [
      "view"       =>  "/firma/profil/ansicht",
    ];

and in my route File
Route::get(LaravelLocalization::transRoute('routes.view')

Not really? I'm soory if I'am a bit obtuse.

**Comment by BojanKogoj** [comment]
I think that should be it, yeah. 

Except maybe I saw somewhere that route should not start with /, unless for root (index). So it should be
`"view" => "firma/profil/ansicht",`

**Comment by JimLfe** [comment]
Wow, you're right.. that works. Thank you very much.
