### ISSUE TITLE
Route Translation with Model Binding not working

### ISSUE THREAD

**Issue by JimLfe** [mcamara/laravel-localization#268]
I have a issue with route translation with Model Binding, the route translation isn't working then:

Http/routes.php
> Route::get(LaravelLocalization::transRoute('routes.firma/abdeckung/id'), ['uses' => 'FirmaController@abdeckung']);

en/routes.php
> "firma/abdeckung/id"    =>  "company/coverage/{firma}",

de/routes.php
> "firma/abdeckung/id"    =>  "firma/abdeckung/{firma}",

I use Model Binding in app/Providers/RouteServiceProvider.php
> $router->model('firma', '\App\Firma');

Now if I am on the German site and push the link for English, it redirects me from:
> de/firma/abdeckung/2

to
> en/firma/abdeckung/2

instead of 
> en/company/coverage/2

It looks like its a Problem of the model binding, because if i take the model binding out, it works perfectly. Does anyone know something about this?

(I know there is also the possibility to translate the attributes, but I thought I will first get this to work without it)

**Comment by BojanKogoj** [comment]
```
@foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
<a  href="{{LaravelLocalization::getLocalizedURL($localeCode) }}">{{$localeCode}} </a><br />
@endforeach
```

This should translate current URL completely

**Comment by JimLfe** [comment]
Great thanks a lot, works like a charm

**Comment by JimLfe** [comment]
sorry, I was to fast.. I forgot to reactivate the model binding in the service provider.. It's still not working..

**Comment by JimLfe** [comment]
Does no one of you guys use model binding?

**Comment by arcanedev-maroc** [comment]
I don't know if the problem is caused by using the model binding.

You need to edit your `routes.php` in lang folders, instead of using keys with `/`, try to do something like this :
```php
// resources/lang/de/routes.php

return [
    'firma-abdeckung-id' => 'firma/abdeckung/{firma}',
    // LaravelLocalization::transRoute('routes.firma-abdeckung-id')
];

// OR like this (I don't know if this package support it or not)
return [
    'firma-id' => [
        'abdeckung' => [
            'show' => 'firma/abdeckung/{firma}',
            // LaravelLocalization::transRoute('routes.firma.abdeckung.show')
        ],
    ],
];

// Same thing for other locales
```

You can also check your model binding by doing this:

```php
$router->bind('firma', function($id) {
    $record = \App\Firma::where('id', $id)->first();

    dd($record); // This is only to see if everything is OK.

    return $record;
});
```

Bonus : https://github.com/ARCANEDEV/Localization/issues/17

**Comment by JimLfe** [comment]
Thanks for your response, I appreciate it.

I'm pretty shure that it's caused by the model binding, because if I take it out, it all works great.. I tried your suggestion with using keys without '/', but it doesn't matter. And if I take the model binding out, it also works with keys with '/'.

Thanks for your check code for the model binding. Yes it works all great. 

It's just that this function:
```
@foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
<a href="{{LaravelLocalization::getLocalizedURL($localeCode) }}">{{$localeCode}}</a><br />
@endforeach
```

returns the false URL:
en/firma/abdeckung/2
instead of the translated
en/company/coverage/2

**Comment by JimLfe** [comment]
I tried something..

If I call 

     LaravelLocalization::getURLFromRouteNameTranslated('en', 'routes.firma-abdeckung-bindFirma')

Result:
>http://torebuild1.local/en/company/coverage/{firma} 

So this translation works, even with model binding.. this one not:

    LaravelLocalization::getLocalizedURL('en')

Result:
>URL: http://torebuild1.local/en/firma/abdeckung/2 

So perhaps I can make a work-around with other functions from the package..

**Comment by BojanKogoj** [comment]
How about 
```
LaravelLocalization::getURLFromRouteNameTranslated('en', \Request::route()->getName())
```

**Comment by JimLfe** [comment]
Thanks, but it's not working, Result:
> www.domain.com/en

I managed the links in the nav with this:
```
<a href="{{ LaravelLocalization::getLocalizedURL(LaravelLocalization::getCurrentLocale(), 'firma/abdeckung/{firma}', ['firma' => $firma->id]) }}">Gebietsabdeckung</a>
```

But it's not usable for the Language switcher, because of different model binding parameters in different routes.. Then I would have to get dynamically the name of the model binding parameter, I don't like that.. **I'm sorry i've read my posts again and realized that I didn't wrote clearly that the problem is just with the language switcher.**

Thank you all for any help

**Comment by arcanedev-maroc** [comment]
I don't know exactly why this is not working but i'm curious about this issue.

I've created my own localization package and i don't if i've the same issue.

You can try it if you want : https://github.com/ARCANEDEV/Localization

I can assist you to find out the issue and also to improve my package.

**NOTE :** My package was based on `mcamara/laravel-localization`, so they're gonna be only some minor changes to do.

**Comment by JimLfe** [comment]
Wow great, thank you very much for your support. I'll take a look at your package.

**Comment by arcanedev-maroc** [comment]
You're welcome :+1:

**Comment by arcanedev-maroc** [comment]
I fixed the issue in my localization package.

To fix it, you need to update this method:
https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/LaravelLocalization.php#L546-L558

This is what i've done to fix it: https://github.com/ARCANEDEV/Localization/pull/21

**Comment by JimLfe** [comment]
Thanks, your package works great.
