### ISSUE TITLE
LaravelLocalization::setLocale() prefix, incompatible with route caching

### ISSUE THREAD

**Issue by martialc** [mcamara/laravel-localization#269]
Hello,

Thanks for this great package !
However, I've noticed that when I use the `'prefix' => LaravelLocalization::setLocale()` prefix, the route caching system cannot cache the pages in that group.

Is there any way to make it compatible with that system without having to write 'n' times the same routes ('n' being the number of locales we use in the project) ?

**Comment by nivv** [comment]
:+1:  Wondering this too

**Comment by codefuhrer** [comment]
404 if using route:cache. Please, fix!

**Comment by datashaman** [comment]
Not possible - the route cache does not allow closures.

**Comment by datashaman** [comment]
The only way this could be made to work is to remove the dynamic routing, loop through each configured locale and generate explicit routes for each.

**Comment by jaoued** [comment]
Hi,

Any way to resolve this issue ?

Regards.

**Comment by lucasff** [comment]
+1 here too!

**Comment by kovalc0mrade** [comment]
+1

**Comment by iwasherefirst2** [comment]
Caching is now build in: https://github.com/mcamara/laravel-localization#caching-routes
