### ISSUE TITLE
Laravel 5.2 support

### ISSUE THREAD

**Issue by abueldahab** [mcamara/laravel-localization#272]
Hi,
Taylor released Laravel 5.2 yesterday  we need update to fix Middleware contract that has been deprecated

- The Illuminate\Contracts\Routing\Middleware contract has been deprecated. No contract is required on your middleware. In addition, the TerminableMiddleware contract has also been deprecated. Instead of implementing the interface, simply define a terminate method on your middleware.
http://laravel.com/docs/5.2/upgrade#upgrade-5.2.0

**Comment by dennisoderwald** [comment]
+

**Comment by mcamara** [comment]
Thanks to @okaufmann and his pull request ( https://github.com/mcamara/laravel-localization/pull/271 ) there is a new version of the plugin (1.1) that supports Laravel 5.2 .

**Comment by arcanedev-maroc** [comment]
The build is failing, you need to [update this line](https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/LaravelLocalization.php#L607)

Instead of:

```php
$path = str_replace(url(), "", $path);
```

Try this:

```php
$path = str_replace(url('/'), "", $path);
```

**Comment by dennisoderwald** [comment]
+1

**Comment by mcamara** [comment]
Fixed! Thanks @arcanedev-maroc  !

**Comment by arcanedev-maroc** [comment]
You're welcome :+1:

**Comment by okaufmann** [comment]
Thank's for your work guys ! And welcome ;)
