### ISSUE TITLE
Authorization header not persisting

### ISSUE THREAD

**Issue by Propaganistas** [mcamara/laravel-localization#273]
Hi

When a route is being redirected to the localized url, the `Authorization` request header (e.g. used in `tymon/jwt-auth`) is not persisted throughout the redirect, resulting in non-authorized requests.

**Comment by Pawlox** [comment]
Is this problem also affecting standard authentication in Laravel 5.2? Because with localization redirect middleware logining in and registering don't work for me :/

**Comment by MarcGaumont** [comment]
@Pawlox  Can you post an example of your auth routes ? I tried moving my post paths out of the localized routes and still I get no saved session !

**Comment by Pawlox** [comment]
@MarcGaumont I have something like that:
```
Route::group([
    'prefix' => LaravelLocalization::setLocale(), 
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]
    ], function () {
        Route::group([
            'middleware' => ['auth']
            ], function () {
                Route::get('/', 'PagesController@home');
                (...)
            });
        Route::get('/register', 'Auth\AuthController@getRegister');
        Route::get('/login', 'Auth\AuthController@getLogin');
        Route::get('/logout', 'Auth\AuthController@logout');
    });

Route::post('/login', 'Auth\AuthController@postLogin');
Route::post('/register', 'Auth\AuthController@postRegister');
```

**Comment by 4unkur** [comment]
@Pawlox Thanks, man.
