### ISSUE TITLE
Named routes

### ISSUE THREAD

**Issue by koichirose** [mcamara/laravel-localization#274]
Like in this issue here: https://github.com/mcamara/laravel-localization/issues/34
I'd like to use named routes and keep the routes.php files tidy, so I came up with this which is currently not working:

``` php
//resources/lang/en/routes.php
return array(
    'events' => [
        'index' => [
            'method' => 'get',
            'as' => 'events.index',
            'uses' => 'EventController@getIndex',
            'translated_route' => 'events',
        ],
        'show' => [
            'method' => 'get',
            'as' => 'events.show',
            'uses' => 'EventController@getShow',
            'translated_route' => 'events/{slug}',
        ],
    ],
);

//similar file in resources/lang/it/routes.php, with a different 'translated_route' key
```

``` php
//routes.php
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [
            'localize', // Route translate middleware
            'localizationRedirect', //redirect if there's no locale segment
            'localeSessionRedirect', //redirect if there's a locale in session (and no segment, I think)
        ]
    ],
    function()
    {
        $localized_routes = LaravelLocalization::transRoute('routes');
        foreach ($localized_routes as $routes) {
            foreach ($routes as $route) {
                Route::{$route['method']}($route['translated_route'], [
                    'as' => $route['as'],
                    'uses' => $route['uses'],
                ]);
            }
        }
}
);
```

This works and correctly shows my translated routes when I execute php artisan route:list.
However, running the application shows this error:

```
Array to string conversion
in LaravelLocalization.php line 536
at HandleExceptions->handleError('8', 'Array to string conversion', '/home/koichirose/public_html/new_dev/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php', '536', array('attributes' => array('template' => 'it', 'input_id' => 'it'), 'route' => array('events' => array('index' => array('method' => 'get', 'as' => 'events.index', 'uses' => 'EventController@getIndex', 'translated_route' => 'eventi'), 'show' => array('method' => 'get', 'as' => 'events.show', 'uses' => 'EventController@getShow', 'translated_route' => 'eventi/{slug}'))), 'key' => 'input_id', 'value' => 'it'))
at preg_replace('/\/{[^)]+\?}/', '', array('events' => 'Array')) in LaravelLocalization.php line 536
at LaravelLocalization->substituteAttributesInRoute(array('template' => 'it', 'input_id' => 'it'), array('events' => array('index' => array('method' => 'get', 'as' => 'events.index', 'uses' => 'EventController@getIndex', 'translated_route' => 'eventi'), 'show' => array('method' => 'get', 'as' => 'events.show', 'uses' => 'EventController@getShow', 'translated_route' => 'eventi/{slug}')))) in LaravelLocalization.php line 598
```

I guess this is because LaravelLocalization still refers to the translated 'routes' file and doesn't expect a multi-dimensional array in there.
I could simply use trans('routes') and avoid using LaravelLocalization for routes, but then I think I'd lose the language switcher functionality, unless I build something myself.

Could you put an example with named routes and controllers in the documentation? I only see closures.

Thanks

**Comment by koichirose** [comment]
Anyone?

**Comment by datashaman** [comment]
You shouldn't be using *resource/lang* files that way, IMO. You're going to wedge yourself into an very specific non-Laravel way of dealing with routes and translations. You have already run into incompatibilities with your approach and are looking for workarounds. Your approach is the problem, change it.

**Comment by mindeleven** [comment]
I also would like to know how to use named routes in a blade template.

{{ LaravelLocalization::getLocalizedURL('en', 'posts.create') }} translates to 

/en/posts.create

not to 

/en/posts/create

 as expected.

Routes definition:

`Route::group(
 
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ],
        'middleware' => ['web'], 
    ], 

    function () {
    
        Route::resource('posts', 'Posts\PostsController', ['names' => [
            'index' => 'posts.index',
            'create' => 'posts.create',
            'store'  => 'posts.store' 
        ]]);

});`

I'm not using translation files with routes.

**Comment by datashaman** [comment]
@mindeleven you've answered your own question. You're using localized URLs without translation files for the routes.

As with any translation in Laravel: if no translation is available, it falls back to using the translation key, which is literally 'posts.create'.

getLocalizedURL does exactly that, it works with URLs, not Laravel route names. You could try turning the route name into a URL first:

    LaravelLocalization::getLocalizedURL('en', route('posts.create'))

**Comment by mindeleven** [comment]
@datashaman thank you for your answer. I'm rather new to Laravel (coming from Symfony) and had some misconceptions about named routes in Laravel. My mistake. 

Turning the route name in a URL first (with route() or URL::route()) is a solution that works quite well. Thanks again.

**Comment by kamil-kielczewski** [comment]
here is helper function: https://stackoverflow.com/q/50569893/860099

**Comment by iwasherefirst2** [comment]
Closing this as the OP issue seems to be a feature request for his own very specific usage of language file. Integrating this as a build-in solution would probably mess up a lot of the code-base too.
