### ISSUE TITLE
Ajax API request to unlocalized url

### ISSUE THREAD

**Issue by ballaevi** [mcamara/laravel-localization#275]
I want to make a POST request to an unlocalized url (/api/getPosts), but all my request are going with locale prefix (/en/api/getPosts) which returns 404. All my api routes are outside the route group of localized routes.
Is there any way to skip or blacklist url with "/api/"?

**Comment by BojanKogoj** [comment]
Localization only works for those you set. Show your route

**Comment by ballaevi** [comment]
This is the route group with localization:
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]], function()
{
    /* Home */
    Route::get('/', 'HomeController@index');
    
    /* Contact */
    Route::get('/contact', 'HomeController@contact');
    
    /* About */
    Route::get('/about', 'HomeController@about');
    
    Route::get('/admin/login', 'Auth\AuthController@getLogin');
    Route::get('/admin/logout', 'Auth\AuthController@getLogout');
    
    /* Category Frontend */
    
    Route::get('/category/{slug}', 'CategoryController@show');
    Route::get('/categories', 'CategoryController@view');
    Route::get('/{category}/{post}',[
        'as'            => 'category.post',
        'uses'          => 'PostController@show',
    ]);

    /* Brochure Frontend */
    Route::get('/brochure/{slug}', 'BrochureController@show');
    
});
Here are the API routes
/* API */
Route::get('/api/iataSearch', 'BaseController@iataSearch');
Route::get('/api/hotelDestinationSearch', 'BaseController@hotelDestinationSearch');

**Comment by megadola** [comment]
i've the same problem here, and i didn't see any asnwers and you closed the issue!

**Comment by megadola** [comment]
@ballaevi !!

**Comment by DigitalCoder** [comment]
hi!
any solutions ?

**Comment by arcanedev-maroc** [comment]
I think this may helps you: https://github.com/ARCANEDEV/Localization/issues/88

**Comment by DigitalCoder** [comment]
Thx
I'm going to try !
