### ISSUE TITLE
Not switching back to default locale

### ISSUE THREAD

**Issue by mxmtsk** [mcamara/laravel-localization#276]
I have hideDefaultLocaleInURL set to true. When I am at a page (for example /de/preise) and click on english (default) as language it doesn't change the language, when I click on another language like french it's working. If I call /en directly without a route it's switching language. 

What am I doing wrong?

I  implemented the language switcher like this:

```php
@foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
  <a hreflang="{{$localeCode}}" href="{{LaravelLocalization::getLocalizedURL($localeCode) }}" class="dropdown-item language-link">
    <img src="{{ asset('assets/img/shared/flags/'. strtoupper($localeCode) .'@2x.png') }}" border="0" alt="" />
    <span>{{{ $properties['native'] }}}</span>
  </a>
@endforeach
```

My routes look like this:
```php
Route::group(
['prefix' => LaravelLocalization::setLocale(), 
 'middleware' => [ 'localeSessionRedirect', 'localize', 'localizationRedirect' ]
], function() {
  Route::get('/', 'HomeController@index');

  Route::get(LaravelLocalization::transRoute('routes.imprint'), 'PagesController@imprint');
  Route::get(LaravelLocalization::transRoute('routes.pricing'), 'PagesController@pricing');
});
```

Thanks
Max

**Comment by Pawlox** [comment]
I have the same problem and I think it's got something with
>IMPORTANT - When hideDefaultLocaleInURL is set to true, the unlocalized root is treated as the >applications default locale app.locale. Because of this language negotiation using the Accept->Language header will NEVER occur when hideDefaultLocaleInURL is true.

from the documentation, but I don't know how to fix it yet.

**Comment by arcanedev-maroc** [comment]
IMO, leaving hideDefaultLocaleInURL to false is good for Search Engine Optimization (SEO).

**Comment by mxmtsk** [comment]
I guess it's just a bug, I hope @mcamara can say something about it!

**Comment by arcanedev-maroc** [comment]
@mxmtsk, yep it is : https://github.com/mcamara/laravel-localization/issues/219

**Comment by kkumar123** [comment]
@mcamara & @mxmtsk  I can see that the bug has been fixed back in 2016 but today I'm facing the same issue with Laravel 5.8 and mcamara 1.32. Can you guys please help? Thanks.
