### ISSUE TITLE
Laravel 5.2 Route::auth()

### ISSUE THREAD

**Issue by asisti2-pruebas** [mcamara/laravel-localization#278]
Hello I have a doubt. This doesn't work with the new Laravel 5.2

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect' ]], function() {
Route:auth();
}

If Ï change the language of the app /es/login not found and /en/login not found. Which is the best way to achieve this?

Thank you

**Comment by arcanedev-maroc** [comment]
Try the explicit routes: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/Router.php#L346-L361

**Comment by asisti2-pruebas** [comment]
Thanks it works!! 
Sorry I just started with Laravel 5.2 no experience with previous versions. I am used to work with Rails.
