### ISSUE TITLE
Ajax POST Route::group

### ISSUE THREAD

**Issue by lucaslimasouza** [mcamara/laravel-localization#280]
Why can't I do a ajax POST to host/pt-BR/profile/send-exam

Can someone help me? 

thks
route.php

Route::controllers([
    'auth'      => 'Auth\AuthController',
    'password'  => 'Auth\PasswordController',
    'payment'   => 'PaymentController',
]);

Route::get('/555', function () {
    $user = App\Models\User::find(56);
    $user->requestPlan(1);
});

Route::group(    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]
    ],function(){

        Route::group(['middleware' => 'auth.user'], function () {
            Route::controllers([
                'profile'   => 'UserProfile'
            ]);
        });

 });

**Comment by commandantp** [comment]
did you figure it out @lucaslimasouza  ?

**Comment by lucaslimasouza** [comment]
@commandantp I didn't undertand.

**Comment by commandantp** [comment]
@lucaslimasouza did you find the solution to your problem? :)

**Comment by lucaslimasouza** [comment]
@commandantp no

**Comment by lucaslimasouza** [comment]
I put out of:

Route::group( [
'prefix' => LaravelLocalization::setLocale(),
'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]
],function(){}

and work
