### ISSUE TITLE
It's not changing Application Locale

### ISSUE THREAD

**Issue by zgabievi** [mcamara/laravel-localization#283]
When I'm using `LaravelLocalization::getLocalizedURL($localeCode)` to change website language, and then trying to get locale with `app()->getLocale()`, I'm getting default value, set in `config/app.php`.
 Has anyone any idea?
Thanks

**Comment by gkhachidze** [comment]
Same problem on me.

**Comment by gitllermopalafox** [comment]
+1

**Comment by aligator28** [comment]
Have the same problem

**Comment by m7ammad7assan** [comment]
the sam problem but in my case it get the browser lanuage

**Comment by aligator28** [comment]
I just implemented localization from this article: http://mydnic.be/post/laravel-5-and-his-fcking-non-persistent-app-setlocale
Very simple and absolutely working example.
