### ISSUE TITLE
Remove localized assets

### ISSUE THREAD

**Issue by predorock** [mcamara/laravel-localization#284]
Hi I just included your lib and I have a strange problem. All my assets urls (css,img,js) have been localized, and consequently the browses raises a not found. If I use the method ´URL::asset() ´ on the URL's there are no problems. I am asking if there's some workaround to get assets out of localization.
Thanks

**Comment by InToSSH** [comment]
Hi, I don't have problem with this, installed the most recent version, and if the asset does exist, it doesn't change the url to one with locale, only if the asset doesn't exist or I have typo in URL. (tested with URL of asset which otherwise would get caught in a translated route)
