### ISSUE TITLE
How write phpunit integrational tests for multiple locales?

### ISSUE THREAD

**Issue by rafis** [mcamara/laravel-localization#289]
Hi
In integration tests `app/Http/routes.php` are called on `createApplication` and thus `$this->request` is a CLI request, the routes getting generated for default locale. If I make request in non-default locale, app obliviously throws 404.

**Comment by alexandcote** [comment]
+1

**Comment by Krato** [comment]
Yes, how to do it?

I'm trying this: 
```php
$this->visit('es/contacto')
```

But is not working. How to fix it?

**Comment by alexandcote** [comment]
I found a temporary fix into a other issue #161. 
`'prefix' => (env('APP_ENV') === 'acceptance' ? 'en' : LaravelLocalization::setLocale())`

**Comment by Krato** [comment]
But I want to test all locales....

**Comment by fcaivano** [comment]
+1

**Comment by SeoFood** [comment]
+1

**Comment by alexandcote** [comment]
@mcamara any update on this ? Could we help to something ?

**Comment by xoco70** [comment]
+1. I'm stuck!

**Comment by biblicalph** [comment]
@alexandcote I went with `LaravelLocalization::setLocale() ?? 'en'` for now. I'll look around into the code to see if I can come up with a fix

**Comment by swingingtom** [comment]
+1

**Comment by zarapico** [comment]
+1

**Comment by grund3g** [comment]
+1

**Comment by timkolm** [comment]
+1

**Comment by iwasherefirst2** [comment]
How to do test for multilanguage routes is now explained in the docs: https://github.com/mcamara/laravel-localization#testing
