### ISSUE TITLE
Cant switch to default language if hiding default locale in URL

### ISSUE THREAD

**Issue by LastTemplar** [mcamara/laravel-localization#293]
If I have this
`'hideDefaultLocaleInURL' => true,`
in the config file, then this
`@foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
        <li>
            <a rel="alternate" hreflang="{{$localeCode}}" href="{{LaravelLocalization::getLocalizedURL($localeCode) }}">
                {{{ $properties['native'] }}}
            </a>
        </li>
    @endforeach`

generates correct links for all the other languages except for the default one, is there a better way to fix this except for manually creating the links?

**Comment by ittikorns** [comment]
+1

**Comment by herzzanu** [comment]
Thank you @ittikorns Having the same problem and this workaround works great. +1

**Comment by stgalkin** [comment]
Have the same problem. 
This is nice solution for language select, but what will be if someone change locale from '/' to '/en' and after what try to get url without locale:
1. join homestead.com/about
2. change locale  homestead.com/ to homestead.com/en
3. Join homestead.com/about get homestead.com/en/about
I have an idea how to fix it, but for now i can't get route prefix in routes.php.

**Comment by denniskoster** [comment]
Having the same issue, would be nice to have the option to force the locale in the generated URL from `getLocalizedURL()`. After that you're being redirected to the URL without the locale in it anyway, but then the locale is stored in the session.

**Comment by ctf0** [comment]
@ittikorns i believe this is equal to not using the option at all, because we now prefix the removed locale which makes no sense.

the problem is within the `LocaleSessionRedirect` middleware

**Comment by ctf0** [comment]
@ittikorns a better fix
open `LaravelLocalization.php` and go to line `300` then add

```php
elseif ( !empty($locale) && $this->hideDefaultLocaleInURL()) {
	$parsed_url[ 'path' ] = $this->getDefaultLocale() . '/' . ltrim($parsed_url[ 'path' ], '/');
}
```

**Comment by phillchill** [comment]
@ashatrov Thank you for #439 ! 
With this fix in place, could I suggest updating the example language selector given in the readme?

**Comment by ashatrov** [comment]
@phillchill I created PR with updated README.md.
