### ISSUE TITLE
Routes with wildcards don't translate

### ISSUE THREAD

**Issue by Morinohtar** [mcamara/laravel-localization#294]
Hi,

I'm having an issue only with the routes that have wildcards, where the route doesn't get translated, well, more accuratly the prefix does but not what comes next. All the other type of routes do translate well.
Example:
English file will have this: 'jobs/{job_offer_slug}'
Portugues file: 'empregos/{job_offer_slug}'

When i change the language from EN to PT, this will happen for example:

www.example.com/en/jobs/medical-offer -> www.example.com/pt/jobs/medical-offer
when it should be:
www.example.com/en/jobs/medical-offer -> www.example.com/pt/empregos/medical-offer

but the project works well from "normal" pages, like for example:

www.example.com/en/about-us -> www.example.com/pt/sobre-nos

Can anyone help me out? Thanks.

**Comment by Morinohtar** [comment]
Ok, after a couple more tests the problem is this: the translation doesn't work if the route has wildcards that have a model binding.

Routes with "normal" wildcards work fine. Routes that have wildcards that are binded to models don't work.

**Comment by arcanedev-maroc** [comment]
You can try my Localization package: https://github.com/ARCANEDEV/Localization

It's based on `mcamara/laravel-localization` package, with more enhancements and features.

I think this may helps you: https://github.com/ARCANEDEV/Localization/issues/19

**Comment by Morinohtar** [comment]
Ok, thanks, im going to check that.
