### ISSUE TITLE
Non-lang-prefixed route only redirects to translated lang-prefixed version if the URI matches the translation of the current language

### ISSUE THREAD

**Issue by ghost** [mcamara/laravel-localization#297]
```
# app/Http/routes.php

Route::group(
[
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localize', 'localeSessionRedirect', 'localizationRedirect' ]
],
function()
{
    Route::get(LaravelLocalization::transRoute('routes.login'), [
        'as'   => 'login',
        'uses' => 'PagesController@login'
    ]);
});
```

```
# resources/lang/en/routes.php

return [
    'login' => 'login'
];
```

```
# resources/lang/nl/routes.php

return [
    'login' => 'inloggen'
];
```
### Scenario 1 - Current locale is **EN**

example.org/login
  ->  redirects correctly to example.org/en/login

example.org/inloggen
  ->  results in 404 not found
  ->  SHOULD redirect to example.org/nl/inloggen
### Scenario 2 - Current locale is **NL**

example.org/inloggen
  ->  redirects correctly to example.org/nl/inloggen

example.org/login
  ->  results in 404 not found, or a MethodNotAllowedException when you also have a POST /login route
  ->  SHOULD redirect to example.org/en/login

**Comment by pablocrs** [comment]
+1

**Comment by k-zakhariy** [comment]
+1 is there way to get page translated with last applied language, and not use fallback language ?
for example why i need to prefix such routes: /login .   /checkout .  /account 
actually translation is needed, but without prefixes

**Comment by iwasherefirst2** [comment]
The behavior posted by OP is correct.

The redirect middleware will redirect to url with current locale, thus in scenario 1, you get redirected to `example.org/en/inloggen` which does not exists. Similar in scenario 2, you get redirected to `example.org/nl/login` which also does not exists.

You can prevent this issue by the `localizeURL($url = null, $locale = null)` helper in you blade files.
