### ISSUE TITLE
Use with gettext

### ISSUE THREAD

**Issue by simplenotezy** [mcamara/laravel-localization#298]
How could this package be used with gettext?

**Comment by mgarciadelojo** [comment]
Here you can find my RouteServiceProvider.php file in order to get it working with [Laravel Gettext](https://github.com/xinax/laravel-gettext):

```
<?php

namespace App\Providers;

use Gettext;
use Illuminate\Routing\Router;
use Illuminate\Http\Request;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use LaravelLocalization;

class RouteServiceProvider extends ServiceProvider
{
    /**
     * This namespace is applied to the controller routes in your routes file.
     *
     * In addition, it is set as the URL generator's root namespace.
     *
     * @var string
     */
    protected $namespace = 'App\Http\Controllers';

    /**
     * Define your route model bindings, pattern filters, etc.
     *
     * @param  \Illuminate\Routing\Router  $router
     * @return void
     */
    public function boot(Router $router)
    {
        //

        parent::boot($router);
    }

    /**
     * Define the routes for the application.
     *
     * @param  \Illuminate\Routing\Router  $router
     * @return void
     */
    public function map(Router $router, Request $request)
    {
        $groupOptions = [
            'namespace' => $this->namespace,
            'prefix' => LaravelLocalization::setLocale(),
        ];

        $regionalCode = LaravelLocalization::getCurrentLocaleRegional();
        Gettext::setLocale($regionalCode);

        $router->group($groupOptions, function ($router) {
            require app_path('Http/routes.php');
        });
    }
}
```

**Comment by canfiax** [comment]
That is awesomd @mgarciadelojo.

Can you somehow disable the prefix, if it is the default language? I.e.

    http://domain.com/about-us (for english)
    http://domain.com/da/om-os (for danish)

**Comment by mgarciadelojo** [comment]
Sure, in one hand, you need to follow the instructions when installing LaravelLocalization. Execute the following command in order to publish the config file for your project.

```
php artisan vendor:publish --provider="Mcamara\LaravelLocalization\LaravelLocalizationServiceProvider"
```

As you could see, a file is created in your `config` directory called `laravellocalization.php`. Modify it to fit your needs. Refer to the documentation for more info. 

https://github.com/mcamara/laravel-localization#config-files

On the other hand, this is my `Kernel.php` file. You can see that I added the **Gettext** middleware after starting the session:

```
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Xinax\LaravelGettext\Middleware\GettextMiddleware::class,
        ],

        'api' => [
            'throttle:60,1',
        ],
    ];

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
    ];
}
```

Hope this helps you to find the right solution :)

**Comment by canfiax** [comment]
Nice. I have already followed the instructions in Laravel gettext. It works more or less, except I have some issues with some strange caching (a current open issue).

Do you think that setting locale both in the RouteServiceProvider and then as middleware will have any technical overhead/performance issues? Since technically language is set twice.

**Comment by mgarciadelojo** [comment]
About caching, you just need to restart your homestead/machine to clear the gettext cache. That's the best method I tried. It's a bit annoying but convenient.

Well, performance. That's a good question I faced a few weeks ago, and I did realize that the Gettext Middleware only gets the locale in session. In our case, we need to override it... You can check if an override is needed by reading the session first, but, I measured it using [DebugBar](https://github.com/barryvdh/laravel-debugbar) and I didn't find any advantage from it...

If you feel that your questions have been answered, please, close this thread :)

**Comment by canfiax** [comment]
I am trying to implement your solution, but first thing I stumble into is on routes using Route::ressource, the name of the route is: `en_US.admin.crm.pages.store` instead of `admin.crm.pages.store`. That will cause the app to say that the route is not defined, because I call them like this `route('admin.crm.pages.store')`.

Is there a way to prevent the prefix from being prepended when using `Route::ressource`?

**Comment by mgarciadelojo** [comment]
Ouch, I forgot to mention you need to create the file `ResourceNoPrefixRegistrar.php` and add it to the list of providers:

```
<?php

namespace app\Providers;

use Illuminate\Routing\ResourceRegistrar;
use Illuminate\Routing\Router;

class ResourceNoPrefixRegistrar extends ResourceRegistrar
{
    public function __construct(Router $router)
    {
        parent::__construct($router);
    }

    /**
     * Get the resource name for a grouped resource.
     * Don't add prefix to the route name, if you want a prefix added
     * to the route name add 'as' => 'prefix.' to the group options.
     *
     * @param  string  $prefix
     * @param  string  $resource
     * @param  string  $method
     * @return string
     */
    protected function getGroupResourceName($prefix, $resource, $method)
    {
        return trim("{$prefix}{$resource}.{$method}", '.');
    }
}
```

**Comment by canfiax** [comment]
Hi @mgarciadelojo great - where do you want me to include this provider? I guess I need to put it in `App/Providers`. Then I tried to include it into the providers array at config/app.php but that causes the app to crash.

**Comment by canfiax** [comment]
I checked the laravel.log and this is what I found: 

	[2016-03-09 19:04:05] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to MyApp\Providers\ResourceNoPrefixRegistrar::__construct() must be an instance of Illuminate\Routing\Router, instance of Illuminate\Foundation\Application given, called in /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146 in /home/vagrant/Projects/myApp/app/Providers/ResourceNoPrefixRegistrar.php:9
	Stack trace:
	#0 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(146): MyApp\Providers\ResourceNoPrefixRegistrar->__construct(Object(Illuminate\Foundation\Application))
	#1 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(114): Illuminate\Foundation\ProviderRepository->createProvider('MyApp\\Provide...')
	#2 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(60): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
	#3 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(507): Illuminate\Foundation\ProviderRepository->load(Array)
	#4 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
	#5 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
	#6 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(232): Illuminate\Foundation\Application->bootstrapWith(Array)
	#7 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(127): Illuminate\Foundation\Http\Kernel->bootstrap()
	#8 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
	#9 /home/vagrant/Projects/myApp/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
	#10 {main}  
	[2016-03-09 19:04:05] local.ERROR: ReflectionException: Class view does not exist in /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
	Stack trace:
	#0 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('view')
	#1 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('view', Array)
	#2 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('view', Array)
	#3 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('view')
	#4 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(144): Illuminate\Container\Container->offsetGet('Illuminate\\Cont...')
	#5 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(735): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Application), Array)
	#6 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build(Object(Closure), Array)
	#7 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
	#8 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(105): Illuminate\Foundation\Application->make('Illuminate\\Cont...', Array)
	#9 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(594): app('Illuminate\\Cont...')
	#10 /home/vagrant/Projects/myApp/app/Exceptions/Handler.php(100): response()
	#11 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(112): MyApp\Exceptions\Handler->convertExceptionToResponse(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
	#12 /home/vagrant/Projects/myApp/app/Exceptions/Handler.php(67): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
	#13 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(291): MyApp\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
	#14 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(107): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
	#15 /home/vagrant/Projects/myApp/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
	#16 {main}  
	[2016-03-09 19:04:05] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ReflectionException: Class view does not exist in /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
	Stack trace:
	#0 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('view')
	#1 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('view', Array)
	#2 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('view', Array)
	#3 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('view')
	#4 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(144): Illuminate\Container\Container->offsetGet('Illuminate\\Cont...')
	#5 /home/vagrant/Projects/myApp/vendor/laravel/framework/src/ in /home/vagrant/Projects/myApp/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
	Stack trace:
	#0 {main}

**Comment by canfiax** [comment]
I found the issue. I needed to add it inside the AppServiceProvider.php under `register()` like this:

		$this->app->bind(
			'Illuminate\Routing\ResourceRegistrar',
			'App\Providers\ResourceNoPrefixRegistrar'
		);

This link helped me: http://laravel.io/forum/06-21-2014-resource-route-names-without-prefix

However, that removes prefixes from ALL my other routes. I.e. I have a route group that looks like this:

    Route::group(['prefix => 'api'], function() {....

**Comment by canfiax** [comment]
I solved it. I just had to read the full answer at http://laravel.io/forum/06-21-2014-resource-route-names-without-prefix

So solution would be to do:

    Route::group(['prefix => 'api', 'as' => 'api.'], function() {....

And that will solve it.

Thank you so much @mgarciadelojo for your help!

**Comment by mgarciadelojo** [comment]
I am glad you found the solution :)

Cheers,
