### ISSUE TITLE
install with composer :(

### ISSUE THREAD

**Issue by athamid** [mcamara/laravel-localization#302]
Your requirements could not be resolved to an installable set of packages.

Problem 1                                                                                                                               
  - mcamara/laravel-localization 1.1.2 requires laravel/framework ~5.2 -> no matching package found.                                    
  - mcamara/laravel-localization 1.1.1 requires laravel/framework ~5.2 -> no matching package found.                                    
  - mcamara/laravel-localization 1.1.0 requires laravel/framework ~5.2 -> no matching package found.                                    
  - Installation request for mcamara/laravel-localization ^1.1 -> satisfiable by mcamara/laravel-localization[1.1.0, 1.1.1, 1.1.2].     

Installation failed, reverting ./composer.json to its original content.

**Comment by rtucek** [comment]
Your trying to installing mcamara/laravel-localization on v1.1.*
This version is dedicated to laravel/framework v5.2.* (which you obviously don't have).

Check out [this table](https://github.com/mcamara/laravel-localization#laravel-compatibility) and install the appropriate version for your Laravel framework. You'll get the version of your current Laravel app either by looking into your composer.json file or by typing `php artisan --version`.

In case of using Laravel v5.0.* or v5.1.* you'll have to run `composer require mcamara/laravel-localization:1.0.*`.

**Comment by athamid** [comment]
yes :100: 
my laravel version is  v5.1.*  

this is :  composer require mcamara/laravel-localization:1.0.* worked :)

im sorry for open this issues and thanks for your response.

**Comment by rtucek** [comment]
Don't worry - we all started from scratch sometime.
If you rely on opensource software, distributed via Github or packagist, in PHP you should definitely learn to understand composer. This is a mandatory tool.
I'd recommend you to read the [https://getcomposer.org/doc/](documentation). At least the first 4 chapters (Introduction, Basic usage, Libraries and CLI).

Same goes for npm in the JavaScript world and git in context of Github.
You don't need to study the whole material, but at least you should know the basics and follow a common convention/workflow.
