### ISSUE TITLE
getLocalizedURL + translated routes = wrong URLS

### ISSUE THREAD

**Issue by simplenotezy** [mcamara/laravel-localization#307]
If I use `LaravelLocalization::getLocalizedURL($localeCode)` it returns the wrong URL if I have localized the routes as described here: https://github.com/mcamara/laravel-localization#translated-routes

Say I am on the danish version:

```
http://myapp.com/da/{slug}/om-os
```

And I call getLocalizedURL('en'), it will return:

```
http://myapp.com/{slug}/om-os
```

Instead of the intended:

```
http://myapp.com/{slug}/about-us
```

So the bug is: it still uses the danish translated route name.

I have also noticed some bugs when using getLocalizedURL and with `Route::groups(['prefix' => '/{slug}'`. It will then, for some strange reason, remove the `/{slug}` from the URL, when using `getLocalizedURL` on the default language. So english URL:

```
http://myapp.com/{slug}/about-us
```

When 'translated' to a danish route, it will become:

```
http://myapp.com/da/om-os
```

Instead of the intended:

```
http://myapp.com/da/{slug}/om-os
```

If I don't use translated routes, everything works as expected.

**Comment by nadj** [comment]
Hi, I have some similar problem. 
I'm using `getLocalizedURL` for creating the lang selector. The problem appears when it needs to create translated route with a parameter (slug). I'm using the `routes.translation` event listener but in there I have no access to the locale sent by `getLocalizedURL` and because of that I don't know to which language to translate the slug.
I found one solution in an older thread, but that looks not that elegant.
[https://github.com/mcamara/laravel-localization/issues/135](https://github.com/mcamara/laravel-localization/issues/135)

**Comment by encodia** [comment]
We've got the same identical issue here.

I'd like to use: 
`@foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
        <link rel="alternate" href="{{LaravelLocalization::getLocalizedURL($localeCode) }}" hreflang="{{$localeCode}}" />
    @endforeach`

in my _header_ view, but it returns the current not translated slug. Anyone here? 

Thank you

**Comment by encodia** [comment]
@canfiax did you find any solution for you?
Thank you

**Comment by j0k3rabg** [comment]
Does anyone have a solution for the bug?

**Comment by simplenotezy** [comment]
No unfortunately not.

**Comment by richestsoft** [comment]
Has anybody find the solution for above issue?

**Comment by riccardo993** [comment]
I have the same problem.
If I dump the $url variable in the getLocalizedURL static method:
`if ($this->checkUrl($url)) {
     return $url;
}`
It dumps a correct url (except for the missing locale) but when it echoes in the view, the url is totally different. I can't understand what goes wrong in the middle.. Any idea on how to fix this?

**Comment by riccardo993** [comment]
Hello guys,

I've found my mistake. Well, I don't know why but even if you are looping it in your blade view, you need to add the **localize** middleware in your route file:

`Route::group(['prefix' => LaravelLocalization::setLocale(), 

'middleware' => [ 'localize', 'localeSessionRedirect', 'localizationRedirect' ]

], function()
{	
	Route::get(LaravelLocalization::transRoute('routes.groups'), 'PostController@showByGroup');
});`

Now it works! Hope it helps!

Byee
