### ISSUE TITLE
Caching routes

### ISSUE THREAD

**Issue by mgarciadelojo** [mcamara/laravel-localization#308]
Hi guys,

Is there any plan for caching routes? If not, I offer my help in order to implement it. I noticed that response times are a lot higher when routes are not cached.

Best regards,

**Comment by rtucek** [comment]
No it's not possible in it's current implementation.
The problem resists in that part of code in our routes file:
```php
Route::group([

        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [
            'localeSessionRedirect',
            'localizationRedirect',
        ],

    ], function () {
        ...
    }
];
```

So when a HTTP request arrives, `Laravellocalization::setLocale()` will return something dynamically to prefix (a language code like 'en' for example). And depending on the next HTTP request you may get a different language code. So the prefix gets dynamically resolved.

If you call `php artisan route:cache` Laravel will only try to resolve once every route in one language combination and caches that result.

In order to achieve this we would need to generate every route combination foreach language.
Something like that would work possibly.
```php
foreach(LaravelLocalization::getLanguageList() as $language) {

    Route::group([

            'prefix' => $language,
            'middleware' => [
                'localeSessionRedirect',
                'localizationRedirect',
            ],

        ], function () {
            ...
        }
    ];

}
```
And obviously such an implementation would require a major version update.

**Comment by mgarciadelojo** [comment]
I tried with no luck before your message... the thing I am transalating the routes as well using the `transRoute` function...

**Comment by rsdev000** [comment]
@mgarciadelojo See this old issue #201

**Comment by lucasff** [comment]
This is a must. I'm having the same problem.

**Comment by scorpionick** [comment]
I found a fix!!!!

**routes.php**

`foreach(LaravelLocalization::getSupportedLocales() as $language => $properties) {
Route::group(
[
  'as' => $language.".",
  'middleware' => ['localeSessionRedirect', 'localizationRedirect'],
  'prefix' => $language,
],
function () use ($language){

...

});
}`

**Controller.php**
`class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
    public function __construct()
    {
      \LaravelLocalization::setLocale();
    }
}`

**vendor\laravel\framework\src\Illuminate\Foundation\helpers.php**

`if (! function_exists('route')) {
    /**
     * Generate a URL to a named route.
     *
     * @param  string  $name
     * @param  array   $parameters
     * @param  bool    $absolute
     * @return string
     */
    function route($name, $parameters = [], $absolute = true)
    {
        return app('url')->route(LaravelLocalization::getCurrentLocale().'.'.$name, $parameters, $absolute);
    }
}`

Afterward php artisan route:cache  works like a charm! ENJOY!

**Comment by rsdev000** [comment]
Hi. You should not change core files. See the solution in #201. 
Cheers

**Comment by lucasff** [comment]
You can override 'route' function declaration so it gets loaded before the core one. Should be better this way.

**Comment by czim** [comment]
If anyone's interested, I wrote a simple solution that works fine for our company's projects:

https://github.com/czim/laravel-localization-route-cache

This allows you to use `artisan route:trans:cache` to set a cache for all supported locales in separate files, and it loads the cached file corresponding to the relevant locale. 

Additionally, you can list the routes for a specific locale with `artisan route:trans:list {locale}`.

It's not pretty, a bit of a hack-job (using a `putenv()` trick), but it doesn't mess with core files and it should be transparent to the rest of the app. 

Your mileage may vary, but I very much welcome feedback & suggestions.

**Comment by rsdev000** [comment]
@czim Tried your solution but found a problem.
When a user types site.com he's redirected to site.com/en or whatever is the default locale. With you soltution the redirect doesn't happen. It works ok if the user types site.com/en. 

Cheers

**Comment by czim** [comment]
Can you make an issue out of it in my repo, with some snippets from the routes file, so I know how you've set it up? I'll try to reproduce and fix it then.

**Comment by rsdev000** [comment]
@czim Thank you. Sure I will. Let me get some time to perform another test with a fresh project and then I create the issue if needed.

Cheers

**Comment by czim** [comment]
The problem mentioned by rsdev000 has been fixed in a new version, thanks to MrVokia.

**Comment by nicklasos** [comment]
@mcamara Hey! You should merge this package https://github.com/czim/laravel-localization-route-cache

What do you think about it?

**Comment by mcamara** [comment]
I've added a section in the README.md redirecting the user to czim's package. Thanks for your help!
