### ISSUE TITLE
Erro route resource

### ISSUE THREAD

**Issue by WeltonLSantos** [mcamara/laravel-localization#309]
the default language comes standard on the page.
http://prntscr.com/ah3yov

If the error in the language change
http://prntscr.com/ah3yvi

Error route resource
http://prntscr.com/ah3z6w

<form action="{{ route('orderOfService.store') }}" method="post"></form>

**Comment by arielstt** [comment]
+1 in Laravel 5.2

**Comment by fdusautoir** [comment]
+1  please  :)

**Comment by arielstt** [comment]
Hi Everyone,I've ended up using arcanedev/localization which works OK with Laravel 5.2.

**Comment by arcanedev-maroc** [comment]
Thanks @arielstt for using my localization package :+1:

**Comment by WeltonLSantos** [comment]
Gracias.

**Comment by arcanedev-maroc** [comment]
BTW, if anyone want to know about this issue, check this: https://github.com/mcamara/laravel-localization/issues/260#issuecomment-159065103

**Comment by arielstt** [comment]
Just in case anyone is interested, I'm using https://github.com/micheleangioni/laravel-js-lang-converter to handle Laravel messages from javascript.
