### ISSUE TITLE
  Fatal error: Class 'LaravelLocalization' not found after composer install in production

### ISSUE THREAD

**Issue by xoco70** [mcamara/laravel-localization#312]
Hi, 

In local, I could use it well, your plugin helped me a lot.
But when I installed it in production with composer install, I got:

> composer install
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Nothing to install or update
> Generating autoload files
> php artisan clear-compiled

                                                           
 > [Symfony\Component\Debug\Exception\FatalThrowableError]  
 > Fatal error: Class 'LaravelLocalization' not found        >                                                         
>
>Script php artisan clear-compiled handling the post-install-cmd event returned with an error

                      
>  [RuntimeException]  
>  Error Output:       
                      

Any Idea why is it happening???

**Comment by xoco70** [comment]
Solved removing:

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect']], function () {
 
from routes.php

running composer install, and then adding again

**Comment by BafS** [comment]
I have the same error but your fix does not work for me. In route.php `$this->app['laravellocalization'];` is not found but I have follow the instructions and added `LaravelLocalizationServiceProvider`.
