### ISSUE TITLE
Detect browser locale and redirect

### ISSUE THREAD

**Issue by herzzanu** [mcamara/laravel-localization#314]
Is there an option so that when mysite.com is visited to redirect to mysite.com/en if the browser language is set to English and to mysite.com/es when browser language is set to Spanish? 

I know this should be an easy one but I just can't find the easy solution.

**Comment by kusmierz** [comment]
https://github.com/mcamara/laravel-localization#middleware

**Comment by herzzanu** [comment]
Thank you @kusmierz. I have these settings in place but for some reason it doesn't redirect. I still think that something is missing.
