### ISSUE TITLE
The change language is not working correctly

### ISSUE THREAD

**Issue by cona88** [mcamara/laravel-localization#315]
Hi,
When i clicked the change language is not affect immediately, need to click again or press F5 to affect.
i am using Laravel 5.2
Please help!

**Comment by hamzstramgram** [comment]
I'm having the same issue. Anyone found a solution ?

**Comment by hamzstramgram** [comment]
I commented the middleware "\App\Http\Middleware\LocaleMiddleware::class," in Kernel.php

Now it is working fine but is it safe to do that ? Might break something else ?

**Comment by cona88** [comment]
in the file Kernel.php, i don't find "\App\Http\Middleware\LocaleMiddleware::class,", can you attached the Kernel.php?

**Comment by cona88** [comment]
thanks @hamzstramgram , you suggest me solution, my root cause: before i created middle locale so it impact with this. I remove it, system working ok.
