### ISSUE TITLE
Using 302 for language redirect

### ISSUE THREAD

**Issue by Jordy-A** [mcamara/laravel-localization#324]
According to 
- https://webmasters.googleblog.com/2014/05/creating-right-homepage-for-your.html (search for '302')
- https://moz.com/community/q/language-detection-redirect-301-or-302
- https://productforums.google.com/forum/#!topic/webmasters/mRhxglSbOdY
- https://developers.google.com/webmasters/mobile-sites/mobile-seo/configurations/separate-urls

it is better for SEO to redirect users based on their language with a 302 redirect instead of a 301. It doesn't happen now when a user hasn't specified a language parameter in the URL.

So change `Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFiler.php` on line 48 from _301_ to _302_.

**Comment by Jordy8** [comment]
#325

**Comment by core45** [comment]
My SEO specialists want me to change to 301 instead of 302. Wouldn't it be better to make it possible to change in configuration file `config/laravellocalization.php`? So you could choose which redirection you like.
Eg.:
```
...
useRedirectResponse => '302',
...
```

**Comment by iwasherefirst2** [comment]
301 is a permanent redirect https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections - so maybe 302 is really the better choice. Also interesting: https://stackoverflow.com/questions/8325784/http-status-code-for-language-redirect

Why does your SEO specialists recommend 301? Until there is no benefit, I am not sure why such an option would be necessary to implement.

Bytheway, you can just copy and paste the RedirctMiddleware and change the request to 301:

 https://github.com/mcamara/laravel-localization/blob/13f418e481ed06f482e4fca87ec5ff67c2949373/src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php#L61
