### ISSUE TITLE
extend path for languages

### ISSUE THREAD

**Issue by mexme** [mcamara/laravel-localization#326]
hi

I have 2 languages (de-CH & fr-CH) and i'm trying to implement a solution like this:

site.com/ch/german
site.com/ch/french

so the language prefix would consist of "ch/german" and "ch/french". 

is this in any way possible?

**Comment by amenk** [comment]
Why don't you use de-CH and fr-CH for the path ?

**Comment by medom** [comment]
I ended up using de-CH and fr-CH. Question originated from a clients' request, I personally didn't mind. :)
