### ISSUE TITLE
a solution-ish for the forms not picking up the locals

### ISSUE THREAD

**Issue by ctf0** [mcamara/laravel-localization#333]
1- follow the docs to add the middleware and the prefix, if you are using the latest release of laravel remove the first `route::group` as the **web middleware** is now included by default.
```php
Route::group(['middleware' => 'web'], function () {

    Route::group([
        'prefix'     => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect']
    ], function () {
       // app routes
    });

    // anything that shouldnt be localized ('ex.api calls')
});
```

2- go to App/Providers/AppServiceProvider `@ boot`
```php
view()->composer('*', function ($view) {
      $view->withLanguage(App::getLocale());
});
```

3- now in your form view
```php
{{ Form::open(['url' => $language.'/login']) }}
   ...
{{ Form::close() }}
```

**Comment by arcanedev-maroc** [comment]
How about using the [named routes](https://laravel.com/docs/5.1/routing#named-routes) ??

**Comment by ctf0** [comment]
yeap that could work, but if u r using something like route resource, or even the route auth that come with laravel by default, it will be kinda messy to have names for them
