### ISSUE TITLE
unlocalized URLs is not working

### ISSUE THREAD

**Issue by megadola** [mcamara/laravel-localization#335]
Dears, 

i tried to search in all issues but i didn't found a solution here, my problem is:

i've unlocalized group called 'api/v1' always redirected to 'en/api/v1'.

check my routes:
``
<?php
include('shares.php');

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]
    ],
    function(){
        /*\* ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
        Route::get('/', function()
        {
            return LaravelLocalization::getCurrentLocale();
        });

```
    // Listing
    Route::get('{catType}', 'ListingController@listProp'); // All catType's Properties
    Route::get('{catType}/{unitType}', 'ListingController@listProp'); // All unitTypes in specfic catTypes
    Route::get('{catType}/{unitType}/{adType}', 'ListingController@listProp'); // All unitTypes in specfic catTypes for rent or for sale
    Route::get('{catType}/{unitType}/{adType}/{locA}', 'ListingController@listProp'); // All unitTypes in specfic catTypes for rent or for sale in Loc A
    Route::get('{catType}/{unitType}/{adType}/{locA}/{locB}', 'ListingController@listProp'); // All unitTypes in specfic catTypes for rent or for sale in Loc A
    Route::get('{catType}/{unitType}/{adType}/{locA}/{locB}/{unitId}', 'ListingController@listProp'); // Detail
```

});

Route::group(['prefix' => 'api/v1'], function(){
    Route::get('List/{type}/{parentID}', 'ListController@index'); // Get List
    Route::post('getUrl', 'ListingController@getUrl'); // Get List

```
Route::get('cacheflush', 'CacheController@clear');
```

});
``

**Comment by megadola** [comment]
up!

**Comment by ncarreno** [comment]
I have the same problem. I have a website that is running under Laravel 5.2.31 and this package is working fine. However I have problems with another website that is running under Laravel 5.2.39. If I change the language from mydomain.com to mydomain.com/en and then I try to change the language again it doesn't work and the website redirect me to mydomain.com/en version every time. It only works if I remove localeSessionRedirect middleware from my route but I think this is not the best solution

**Comment by maunoxyd** [comment]
Same here!

**Comment by cmarfil** [comment]
+ 1

**Comment by cmarfil** [comment]
I found a solution:

In Kernel.php remove middlewares from $routeMiddleware and create new middleware group, then put the package middlewares in the new group, named "localized" for example.

```php
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Xinax\LaravelGettext\Middleware\GettextMiddleware::class,
        ],

        'localized' => [
            'localize' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
            'localizationRedirect' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
            'localeSessionRedirect' => \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class
        ],

        'api' => [
            'throttle:60,1',
        ],
    ];

```

Then, in your routes.php put the middleware group:

```php
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localized', 'web']], function() {
...
}
```

Regards.

**Comment by Ossuary** [comment]
I still can't get NonLocalizedURL to work... the /en, or whatever language i use, messes my paths and I really don't want it to show.

I tryed @cmarfil 's solution but i either didn't understand it or i'm messing something up...

I thought all i had to do was change getLocalizedURL to getNonLocalizedURL on my language selection menu, that atm is like this: 
`            @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                <li>
                    <a rel="alternate" hreflang="{{$localeCode}}" href="{{ LaravelLocalization::getLocalizedURL(false, $localeCode) }}">
                        {{ $properties['native'] }}
                    </a>
                </li>
            @endforeach
`
Am i totally wrong?
Can anybody explain or give a working solution please?
