### ISSUE TITLE
upgrade to 5.2.39 lost session url.intended

### ISSUE THREAD

**Issue by fzhan** [mcamara/laravel-localization#336]
After upgrade to 5.2.39, the LocaleSessionRedirect middleware would not redirect carrying session with url.inteded, conflicting with auth and https://github.com/lucadegasperi/oauth2-server-laravel middleware.

**Comment by fzhan** [comment]
I found it here:
[LaravelLocalizationRedirectFilter.php](https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php#L40)

where $request->path() should be $request->fullUrl()

**Comment by fzhan** [comment]
This turns out to be a multiple issue:

1. after upgrading to 5.2.39, some how redirect won't remember the correct url.intend:
2. See here: [mcamara/laravel-localization](https://github.com/mcamara/laravel-localization/issues/336) when using localization on oauth/authorize, the request parameter was lost during the redirect from oauth/authorize to  /en/oauth/authorize.
3. /en/oauth/authorize is asking to check the auth middleware, without carrying the correct request (client_id etc.) redirect to login, causing 'url.intende' to record only '/en/oauth/authorize'

I'm not entirely sure what's causing the issue here. It seems the logic in middleware has changed after 5.2.39. I'm posting my findings in all three package.

**Comment by mikenolimits** [comment]
I'm having a similar problem, have you found a solution to this @fzhan fzhan?
