### ISSUE TITLE
hideDefaultLocaleInURL + getLocalizedURL

### ISSUE THREAD

**Issue by atouzard** [mcamara/laravel-localization#337]
Hi,

using hideDefaultLocaleInURL my routes work without any locale as prefix (example : host.com/home). With substitutes languages the locale shows (host.com/fr/maison).

When i'm trying to get the english route with getLocalizedURL it returns me the URL without the locale (host.com/home), so when I visit the url it redirect me immediately back on /fr/maison and doesn't change the language.

Do you have a solution ?

Best regards.

**Comment by diegorodriguezvidal** [comment]
Hi, I think there are some problems with version 1.1.4. This morning I run composer update so mcamara/laravel-localization was update from 1.1.2 to 1.1.4. This update broke my routes and I couldn't get my default locale having 'hideDefaultLocaleInURL' set to true. I installed again version 1.1.2 and everything worked fine again.

Another solution: have a look at the bottom of this: (https://github.com/mcamara/laravel-localization/issues/192), this solution also works.

**Comment by atouzard** [comment]
This solution works fine for me, thanks pal
