### ISSUE TITLE
Project folder name is appended in url twice

### ISSUE THREAD

**Issue by chayansarker** [mcamara/laravel-localization#338]
Hi,
I found it is one of the best package for localization in Laravel.

When I clicked or typed project root folder in my development server, I get project folder  name in twice. Like if i hit enter or type such http://localhost/obtrs it redirects me to http://localhost/obtrs/obtrs/en.

So, what the solution of this kind of issue?

**Comment by allantatter** [comment]
Same issue here.

**Comment by arcanedev-maroc** [comment]
This is a known issue, you need to use a vhost like `http;//obtrs.dev` instead of `http;//localhost/obtrs`.
