### ISSUE TITLE
validation messages translation only on primary language

### ISSUE THREAD

**Issue by atouzard** [mcamara/laravel-localization#339]
Hello,

I'v noticed that validation messages are not translated in the current languages but always follow the primary language set in `config/app.php`

I'v imported custom validation messages for additional locales like **fr** or **de** but the validation messages never translate themselves according to Laravel translation documentation.

The only way to display the proper translation is to change the locale in `config/app.php`but then again it sticks to this locale, ignoring the locale currently set.

Do you have a solution ?

**Comment by vvatitv** [comment]
Hello, i'm know that been so much time from date post, but I have the same problem, and I haven't found a solution, so this my test solution:

I'm using laravel 5.3

In routes/web.php

>     Route::group(
>     [
>         'prefix' => LaravelLocalization::setLocale(),
>         'middleware' => [ 'localize', 'localeSessionRedirect', 'localizationRedirect' ]
>     ],
>     function()
>     {
>         $curent_language = ''; // hideDefaultLocaleInURL => true
> 
>         if(LaravelLocalization::getCurrentLocale() != config('app.locale')){
>             $curent_language = '/'.LaravelLocalization::getCurrentLocale();
>         }
> 
>         .......
> 
>         // Registration Routes...
>         Route::post($curent_language.'/register', [
>             'as' => 'post.registration',
>             'uses' => 'Auth\RegisterController@newregistration'
>         ]);
> 
>         .......
>     });

PS. Sorry for my bad english... :)

**Comment by ctf0** [comment]
there must be something stopping the session from being saved, i also have the same problem from time to time and believe it or not the solution was

1- create a clean laravel project
2- make sure the validation msgs are working (the default is enough)
3- clean browser cache & session data for the localhost
4- clean the (project in question) session store (file or db)

and it should work again.

**Comment by antoine1003** [comment]
I am getting the same problem and still looking for and answer :/

**Comment by anaisabel19886** [comment]
Same here :s

**Comment by thomasInes** [comment]
same here.
Using Laravel 5.5.40/Php 7.

I  cleared my cache using
`php artisan cache:clear
php artisan view:clear`
I also made sure the correct locale is used in my controller using `App::getLocale()`

The validation error message used are always the english ones :(

**Comment by iwasherefirst2** [comment]
This happens if you do not localize your post url and if your not using sessionRedirect middleware.

If you don't localize your post route,  the default locale is set while validating, and when returning it shows the validation message in default locale.

Simply make sure to localize the action route like this:

<form action="{{ \LaravelLocalization::localizeURL('/your_post_route')}}" method="post">
     @csrf
    <button>Send</button>
</form>
