### ISSUE TITLE
How to localize controller/resource methods?

### ISSUE THREAD

**Issue by goosechaser** [mcamara/laravel-localization#34]
Re,

I have a `::controller` route that's localized. How do I further localize methods inside the controller?

```
class Cars extends BaseController {
   public function getIndex() { }
   public function getCompact() { }
   public function getMinivan() { }
}
```

Doesn't seem like a trivial thing since generating function names dynamically is not easy (gotta use `eval()`, etc.). Perhaps some other clever way? Obviously, a workaround would be to cram all translated methods inside a controller and also map them inside route. That will defeat the purpose of `::resource` and `::controller` route methods.

**Comment by iwasherefirst2** [comment]
Closing this issue as its with 6 years completly outdated and didn't receive much attention either.

If the problem can't be solved with [route parameters](https://laravel.com/docs/7.x/routing#route-parameters) nor translated routes, please just create a new issue.
