### ISSUE TITLE
Laravel default locale is not in the supportedLocales array.

### ISSUE THREAD

**Issue by xitude** [mcamara/laravel-localization#341]
Reopened Issue #198

Could you please look into this.

**Comment by floodedcodeboy** [comment]
So I've managed to figure this out. 

It appears that this package does not take into account the 'app.fallback_locale' value, and relies solely on the app.locale value. 

I'll try make an update and submit a PR with checks added in.

**Comment by xitude** [comment]
@floodedcodeboy If you could that would be brilliant. I know quite a few people are having this issue and I couldn't find it (and didn't have the time to hunt it).

Cheers.

**Comment by lucasff** [comment]
I had a lot of this problems and ended up doing a very dirty hackish solution. We need to help this package!

**Comment by muuucho** [comment]
I had the same problem I tried to put this line firt in routes.php
   App::setLocale('en');
...and it works, english is my fallback language.

**Comment by tomvo** [comment]
I'm also hitting this error, almost half a year later, is there already a fix for this? Or any pointers so that we might be able to make a PR? Somebody has some workarounds other than @spitfire64 because that doesn't seem to work for us.

**Comment by tomvo** [comment]
So I checked the code and it seems this might do the trick: https://github.com/mcamara/laravel-localization/compare/master...tomvo:fix-redirect-to-fallback-locale?expand=1

Would be great if some of the maintainers could chime in on this
