### ISSUE TITLE
redirect from unlocalized to localized URLs

### ISSUE THREAD

**Issue by ZedanLab** [mcamara/laravel-localization#343]
hey, thanks for your awesome package.

I got invalid urls when redirect from unlocalized to localized URLs.

e.g.
`http://localhost/enngezshirt/public/` 
redirects to
`http://localhost/enngezshirt/public/enngezshirt/public/en`

@mcamara please help me..

**Comment by Mohamed-Zedan** [comment]
@mcamara

**Comment by arcanedev-maroc** [comment]
Try to use a vhost, like `http://enngezshirt.dev/` instead of ` http://localhost/enngezshirt/public/ `.

**Comment by bs-thomas** [comment]
@arcanedev-maroc That would be a pretty stupid limitation.  Btw, I'm having the same problem ever since 1.1.2.  So there was something fishy going on.

**Comment by kvlknctk** [comment]
is there another solution without vhost?

**Comment by lucasff** [comment]
If you're not using vhosts, you're doing it wrong. In production you need to deploy to public anyway.
