### ISSUE TITLE
Route::auth() post do not work when locale is other than default

### ISSUE THREAD

**Issue by alex0082ass** [mcamara/laravel-localization#344]
`Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ] ], function() {

    ### laravel default authentification routes
    Route::auth();

});`
I have hideDefaultLocaleInURL = true
When I have english as default locale the the login url is like this site.com/login and all work fine.
When I change to other locale, the route is found e.g: site.com/de/login, but when I submit the form, the route::post is not working

Do you have a solutin for this? 
Thanks!

**Comment by AmrAlfoly** [comment]
i had the same problem and let me explain why it is behaving like this :
in the login view the form method is pointed to '/login'
and this route is not accessible if the Route::Auth() is inside the localization group
and you can't hack into the Auth routes to give it a name so you can point the form to
so it leaves you with one only solution which worked with me 
just get the Route::Auth(); out of the 
`Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'localeSessionRedirect', 
doing so will make the Auth routes work just fine using the default language for these routes

**Comment by zeravcic** [comment]
Look at **MY\PACKAGE\App\Http\Controllers\Auth\LoginController.php**:

``` php
<?php 
namespace MY\PACKAGE\App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

class LoginController extends Controller 
{
    use AuthenticatesUsers;

    protected $redirectTo = "/admin";
    protected $locale;

    public function __construct()
    {
        $this->middleware('guest', ['except' => 'logout']);
        $this->locale = LaravelLocalization::setLocale() ? "/" . LaravelLocalization::setLocale() : "";

    }

    public function showLoginForm()
    {
        $title = trans('bytenet-admin-base::base.login'); // set the page title
        return view('bytenet-admin-base::auth.login', compact('title'))
            ->with('locale', $this->locale);
    }

    public function redirectTo()
    {
        return $this->locale . $this->redirectTo;
    }

    // public function login()
    // {}
}
```

**Pay attention at ``` redirectTo() ``` method!**
(linked to trait code ``` Illuminate\Foundation\Auth\RedirectsUsers ``` lines 14-16)

I have ``` hideDefaultLocaleInURL = true ``` 

It seems to be working fine...
Im new to laravel so please help me solve - is this correct solution?

**Comment by alexleonard** [comment]
I've been having issues with this as well. Having the default `Auth::routes()` in my `routes/web.php` just results in login POST redirecting back to login GET somewhere in the middleware end of things.

I found the solution was 

1. Split all the auth routes out into manual declarations as suggested by AmrAlfoly
2. Create an auth.php routes file and place the POSTed routes into that
3. Keep the GET auth routes in your web file (which has the localization middleware). 

This seems to be working well for me.

## App\Http\Kernel

```
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
        'allLocalize' => [
            \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
            \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
            \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
        ],
    ];
```

## App\Providers\RouteServiceProvider

```
    public function map()
    {
        $this->mapAuthRoutes();
        $this->mapWebRoutes();
    }

    protected function mapAuthRoutes()
    {
        Route::group(
            [
                'middleware' => ['web'],
                'namespace' => $this->namespace,
            ],
            function ($router) {
                require base_path('routes/auth.php');
            }
        );
    }

    protected function mapWebRoutes()
    {
        Route::group(
            [
                'middleware' => ['web', 'allLocalize'],
                'namespace' => $this->namespace,
                'prefix' => LaravelLocalization::setLocale(),
            ],
            function ($router) {
                require base_path('routes/web.php');
            }
        );
    }
```

## routes/auth.php
```
Route::post('login', 'Auth\LoginController@login')->name('login.post');
Route::post('logout', 'Auth\LoginController@logout')->name('logout.post');
Route::post('register', 'Auth\RegisterController@register')->name('register.post');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::post('password/reset', 'Auth\ForgotPasswordController@reset');
```

## routes/web.php
```
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::get('password/reset/{token?}', 'Auth\ResetPasswordController@showResetForm');
```

I haven't actually gotten around to testing whether this separation of GET/POST is required for forgot password etc, but it certainly worked straight off on the login POST.
