### ISSUE TITLE
Redirect Users to Their Languages After Login 

### ISSUE THREAD

**Issue by cihankusmez** [mcamara/laravel-localization#347]
I store user languages in database. When they visit my site they can see other language. I want to redirect users to their own languages. I have an event listener UserLoggedIn

`LaravelLocalization::setLocale($user->language);`

What should i do ? Normally after login it is redirecting depends on laravel system. I want to redirect users to their languages.

**Comment by cihankusmez** [comment]
After digging google i got some ideas. And i build the redirection method. I want to share.

In AuthController we should override redirectPath method. You can write code below. It redirects user to different language depends on user's language choice in database.

`public function redirectPath()
    {
        if (property_exists($this, 'redirectPath')) {
            return $this->redirectPath;
        }
        /**
         * Kullanıcıyı kendi diline yönlendiriyoruz.
         */
        if(auth()->check())
        {
            LaravelLocalization::setLocale(auth()->user()->language);
            return LaravelLocalization::getLocalizedURL();
        }

        return route('home');
    }`

**Comment by ctf0** [comment]
a simpler solution "not tested"
```php
// because this fires after the user is logged in so the "auth()->user()" is ready to be used
// the package by default makes the urls like "abc.com/{locale}"
// so all we have to do is to just append the user locale to the root url

protected $redirectTo = '/'.auth()->user()->lang // the column u save the user locale;
```

**Comment by screenager** [comment]
That won't work, you can't set dynamic values in a protected field
