### ISSUE TITLE
Posible fix to wrong redirect from unlocalized to localized URLs

### ISSUE THREAD

**Issue by ealfonso93** [mcamara/laravel-localization#350]
Just replace `$request->path()` on this [file](https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php#L40) on line 40 with `$request->fullUrl()` with that now is working for me

**Comment by eanoriega20** [comment]
great job ealfonso, now is working to me too after that fix
