### ISSUE TITLE
Redirect to session('locale')?

### ISSUE THREAD

**Issue by Luddinus** [mcamara/laravel-localization#352]
Hi,

I have my example.com and the user change the current language to "es".

The user logins and enter in example.com/es/dashboard

Then, If I enter example.com, I have a middleware that redirects to the dashboard page, but unfortunately, it always redirects to example.com/dashboard... (no lang prefix),

I have already the "localeSessionRedirect" middleware in the routes file but still not working.

What can I do?

Thx.

**Comment by Luddinus** [comment]
Any ideas?

**Comment by jerik** [comment]
Did you activate the middleware from ``laravel-localization´´? 

> So, if a user navigates to http://url-to-laravel/test and the system has this middleware active and 'en' as the current locale for this user, it would redirect (301) him automatically to http://url-to-laravel/en/test.

If, is the locale available in your session?

> Once the locale is defined, the locale variable will be stored in a session (if the middleware is enabled), so it is not necessary to write the /lang/ section in the url after defining it once, using the last known locale for the user. If the user accesses to a different locale this session value would be changed, translating any other page he visits with the last chosen locale.
