### ISSUE TITLE
Laravel 5.3 support ?

### ISSUE THREAD

**Issue by difuse** [mcamara/laravel-localization#353]
Laravel 5.3 is out ! Do you plan to support this version?

**Comment by emil126a** [comment]
I'm keen to know response as well.

**Comment by difuse** [comment]
Obviously, everything works well under 5.3. I think some adaptations are necessary. Can do we rely on maintenance of this version ? (Sorry for my approximately english ! 😄 )

**Comment by ctf0** [comment]
already install in here without any issues, we just need to update `composer.json`

**Comment by goowikns** [comment]
Do we need to modify any files to support Laravel 5.3?

**Comment by ctf0** [comment]
nop
