### ISSUE TITLE
How can i get (/en) in controller?

### ISSUE THREAD

**Issue by Hangsat** [mcamara/laravel-localization#354]
I has use HomeController like: 

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]
    ],

```
function()
{       
    Route::get('/home', 'HomeController@index');

    Route::get(LaravelLocalization::transRoute('routes.about'),function(){
          return View('about');
    });

    Route::get(LaravelLocalization::transRoute('routes.view'),function($id){
          return View('view',['id'=>$id]);
    });
}
```

);

//

class HomeController extends Controller
{  
     public function index($locale)
     {  
        echo $locale;

```
    return view('welcome');
 }
```

}

How can i get /en in HomeController?
Please help thanks...

**Comment by Propaganistas** [comment]
use Illuminate\Http\Request;
    
    class HomeController extends Controller
    {
        public function index(Request $request)
        {
            $locale = $request->segment(1);

            return view('welcome');
        }
    }
