### ISSUE TITLE
When changing the language, the attributes are not passed through

### ISSUE THREAD

**Issue by Christophvh** [mcamara/laravel-localization#355]
Link inside my view :

 `<a href="{{ LaravelLocalization::getLocalizedURL(null, trans('routes.account-edit'), ["id" => Auth::user()->id]) }}"> Edit Link</a>`

routes.php files inside Lang/fr & Lang/nl 

```
    <?php
    return [
        'account-edit'      => "account/wijzig-gegevens/{id}", 
    ];

    <?php
    return [
        'account-edit'      => "donnees/modifier-donnees/{id}", 
    ];

```

Laravel routes file:

```
  Route::group([

        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localize','localeSessionRedirect', 'localizationRedirect' ]

        ], function()
        {

    Route::get(LaravelLocalization::transRoute('routes.account-edit'),'AccountController@edit');

    });
```

When i look at the link in my default language (nl) i get the correct link like so:
`<a href="http://blabla.dev/nl/account/wijzig-gegevens/1">Edit Link</a>`

But when i change my language to french i get following link:
`<a href="http://blabla.dev/fr/donnees/modifier-donnees/{id}">Edit Link</a>`

This seems like a bug, since every singular part is working as intended

**Comment by Luddinus** [comment]
Are you using model binding? I had the same issue

**Comment by Christophvh** [comment]
This error is ocuring before model binding. This is just the routes and translations only, not getting to the controller part yet.

**Comment by aFluxx** [comment]
Is there a way to solve this issue?

**Comment by iwasherefirst2** [comment]
@aFluxx I cannont reporduce this issue. If I do the steps as explain above, I get the currect url for each language.
