### ISSUE TITLE
Laravel 5.2 - Class localeSessionRedirect does not exist

### ISSUE THREAD

**Issue by emil126a** [mcamara/laravel-localization#356]
How can I fix this error:
`Class localeSessionRedirect does not exist`

**Comment by fcaivano** [comment]
Read the docs "Middleware" section:
https://github.com/mcamara/laravel-localization#middleware

Adding:

```
'localizationRedirect' => 'Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter',
'localeSessionRedirect' => 'Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect'
```


To **app/Http/Kernel.php**

Run **composer dump-autoload** afterwards just in case

Will probably solve your issue

**Comment by brada1703** [comment]
Thanks @fcaivano for your suggestion, but I'm still having the same issue. Does anyone else know what this could be?

Thanks!

**Comment by budgetteknologies-spree-contrib** [comment]
hi i am having a same issue with same problem what is the solution
i even ran  composer dump-autoload

**Comment by edurodriguesdias** [comment]
I have the same issue :(

I'm using Laravel 5.4

**Comment by hsntngr** [comment]
same here +1 laravel 5.7

**Comment by aFluxx** [comment]
Hello there,

I'm wondering.

I'm also using these $routeMiddleware (Laravel 5.7 and laravel-localization 1.3
I'm not having this issue?

I am subbed to these issues and I saw this one pop up, just wondering...

**Comment by hsntngr** [comment]
@aFluxx actually in my stuation, debugbar caused that error, I run php artisan debugbar:clear  and now its ok. But still I'm having crucial issues. My routes under the app/http/routes.php can not recognize by laravel localization either laravel. I tried with empty laravel project and laravel localization and got same error again. So I moved all routes under to /routes directory..Probably I made serious mistake in somewhere but still I couldn't figure out where it is.

**Comment by hsntngr** [comment]
as I know routes directory has been using since 4.2 (or may be more than that) and in the docs it says all localized routes should be in routes.php (`// app/Http/routes.php` just above it specify the routes.php path). But it doesn't work at all for me.

Also instead of stucking all routes in web.php I use separate files in /routes directory.. I created new middleware group in `App\Http\Kernel::$middlewareGroups` called by localized, and added localization middlewares here.. I think this is more clean with that way
```php
//Kernel.php::$middlewareGroups
        'translate' => [
            \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
            \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
            \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
        ],
//RouteServiceProvider::mapWebRoutes();
        Route::group([
            'middleware' => ["web","localized"],
            'namespace' => $this->namespace,
        ], function ($router) {
            require base_path('routes/store.php');
            require base_path('routes/posts.php');
            require base_path('routes/users.php');
        });
```

**Comment by tatgv** [comment]
These might be silly of me but this problem happened in my project when I changed the Kernel.php from the console folder

Have to add these:

`'localize' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
		'localizationRedirect' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
		'localeSessionRedirect' => \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
        'localeViewPath' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationViewPath::class`

in
`App\Http\Kernel`

**Comment by hsntngr** [comment]
@tatgv I think it should be in Http/Kernel.php where the route middlewares stored in

**Comment by tatgv** [comment]
@hsntngr Exactly, that's what I'm saying. I didn't pay attention and put it in the wrong Kernel file.

**Comment by tanyakuleshova** [comment]
you need to delete bootstrap cache
