### ISSUE TITLE
I can't send Session flash messages

### ISSUE THREAD

**Issue by slzr** [mcamara/laravel-localization#358]
when i try to send a flash message to a view, it never reaches the view
in my routes:

```
Route::group([
  'prefix'          => LaravelLocalization::setLocale(),
  'middleware' => [ 'localize', 'localeSessionRedirect', 'localizationRedirect']
], function(){
  Route::get(LaravelLocalization::transRoute('routes.contacto'), [
    'as'   => 'contacto',  
    'uses' => 'PagesController@contacto'
  ]);
}
```

in controller:

```
Session::flash('message' , 'contacto.true');
return redirect('contacto');
```

**Comment by fcaivano** [comment]
This has probably nothing to do with this package...

Have you tried without the package first, does it work?

If not, can you check if the StartSession class is inside the "web" middleware route.

And check, depending on your Laravel vesion, if you need to manually add the "web" middleware... if it's not being applies, then probably that's the issue.

Where's the code that actually echo's the flashed "message"? Maybe that's your issue.
