### ISSUE TITLE
https problem using localizeURL()

### ISSUE THREAD

**Issue by nkvorn** [mcamara/laravel-localization#360]
Hi, using localizeURL() I get links starting with "http://". However the site is served through https so I would like to get links starting with "https://".

What is the way to fix this?

**Comment by vvatitv** [comment]
If you want, you can change "boot" function in your app\Providers\AppServiceProvider.php:

```
    public function boot()
    {
        if (!\App::environment('local')) {
            \URL::forceSchema('https');
        }
    }
```

and you can control urls with .env file

`APP_ENV=local - http`

and 

`APP_ENV=production - https`

But, you needs use links with "url()"

Example: 

`<a href="{{ url( route('/home') ) }}"> or <a href="{{ url('/home') }}">`

**Comment by ctf0** [comment]
@nkvorn this is not related to the package, the protocol is handles by ur server , this package only change the value that comes after the first `/` ex `www.abc.com/en`
