### ISSUE TITLE
Cant switch to default language

### ISSUE THREAD

**Issue by chadidi** [mcamara/laravel-localization#364]
if `'hideDefaultLocaleInURL' => true,`
the suported languages url inside `href` looks like that  : 

```
- test.dev/home

- test.dev/ar/home
```

and it should be like this : 

```
- test.dev/en/home

- test.dev/ar/home
```

than if i choose the default language wich is english it should redirect me to this

`- test.dev/home`

Can you add this to your method please

**Comment by chadidi** [comment]
## You can fix it by going to this file 
`/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php`
## and search for 
`$parsed_url[ 'path' ] = $locale . '/' . ltrim($parsed_url[ 'path' ], '/');` 
## you will find something like this

`if ( !empty( $locale ) && ( $locale != $this->defaultLocale || !$this->hideDefaultLocaleInURL() ) )
        {
            $parsed_url[ 'path' ] = $locale . '/' . ltrim($parsed_url[ 'path' ], '/');
        }
        $parsed_url[ 'path' ] = ltrim(ltrim($base_path, '/') . '/' . $parsed_url[ 'path' ], '/');`

## replace the code with this
`$parsed_url[ 'path' ] = $locale . '/' . ltrim(ltrim($base_path, '/') . '/' . $parsed_url[ 'path' ], '/');`

_** Soory for my bad english **_

**Comment by ctf0** [comment]
`'hideDefaultLocaleInURL' => true,` from its name it means that the default lang which is `en` will be hidden, which mean that any other locale will be visible **except** the default `en`

**Comment by lordantonelli** [comment]
I can not get back to the default language when I use `'hideDefaultLocaleInURL' => true`
The system language remains with the one that was previously selected.
How to solve this problem?

**Comment by ctf0** [comment]
Yes, this is currently a prob with the package & there is more than one pr
made to fix it but no response from @mcamara on any yet
