### ISSUE TITLE
On Language Change Event

### ISSUE THREAD

**Issue by alex0082ass** [mcamara/laravel-localization#366]
Hello,

Can you tell me how to make an event that triggers when an user changes the default locale to a different one? I need to edit the users table and set the user's default_language to the selected language and use this value when he logs in and do Session::put( 'locale', $user->default_lang );

Any help would be appreciated. Thank you in advance!

**Comment by macikgoz25** [comment]
Session::set('lang',"en/es/tr/etc");

**Comment by alex0082ass** [comment]
Thank you, but it does not help me. I need to know when an user changes the language.

**Comment by ctf0** [comment]
u instead get the session key that gets changed by the middleware https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php#L44 `session('locale')`
