### ISSUE TITLE
when 'hideDefaultLocaleInURL' => true ,  error session

### ISSUE THREAD

**Issue by congkevin** [mcamara/laravel-localization#372]
I want to make my basic language shows without /language
eg. http://domain.com  -> not http://domain.com/en
so i made 'hideDefaultLocaleInURL' => true

It worked indeed. My basic language shows become http://domain.com
Then I click link to indonesian langauge so url became http://domain.com/id
However, when I click back to default language, it didnt want to return into default language.

Can anybody solve this bug?

**Comment by itsmattm** [comment]
It seems that you have to visit `http://your-domain.com/en` to change to your default locale despite having set the `hideDefaultLocaleInURL` to `true`. You will be redirected immediately to `http://your-domain.com`.

---
Just as a note:

I had the same problem when I added the middlewares in wrong order.

Contrary to the docs I copy&pasted the middleware directly to the web middleware group and removed the array keys:

```php
class Kernel extends HttpKernel {
    // Taken from the docs:
    // protected $routeMiddleware = [
    //     /**** OTHER MIDDLEWARE ****/
    //     'localize' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
    //     'localizationRedirect' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
    //     'localeSessionRedirect' => \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class
    //     // REDIRECTION MIDDLEWARE
    // ];
    //  
    // How I did it (Laravel 5.3):
    protected $middlewareGroups = [
        'web' => [
            /**** OTHER MIDDLEWARE ****/
            // \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
            //
            // The following two are in the wrong order:
            \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
            \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
        ],
        'api' => [
            // ...
        ]
}

```

When I changed the order of the two middlewares to the order stated in the docs it worked:
```php
// Docs: 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]
\Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
\Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
```

To change to the default language (en), you have to visit `http://your-domain.com/en`, though.

**Comment by congkevin** [comment]
Thanks for the opinion.
I tried changing the order of Kernel.php, but still doesnot work.
\Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
\Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,

my default langauge is en. When I access indonesia page http://your-domain.com/id, i can access it well. However, when i change language back to default language by inputting url http://your-domain.com, it still redirect me to http://your-domain.com/id

**Comment by itsmattm** [comment]
Yes, I guess this behavior is intentional. Otherwise, your user's preferred language would be set to English every time they hit your home page. (I guess almost everybody likes enter a site on the home page and then get redirected to the preferred language)

To switch back to en, try inputting `http://your-domain.com/en`, just to switch the language. You should be redirected to `http://your-domain.com/` then.

**Comment by congkevin** [comment]
aa, finally i got what you mean! this solves the problem.
Thank you very much for your suggestion. It really helped!!!

However I am looking for solution of fixing 'hideDefaultLocaleInURL' => true  session problem.
Seems this is this package bug and not yet been resolved yet.

I will you your suggestion until this issue been solved

**Comment by chadidi** [comment]
You can fix it by going to this file 
`/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php`
and search for `$parsed_url[ 'path' ] = $locale . '/' . ltrim($parsed_url[ 'path' ], '/');` 
you will find something like this
`if ( !empty( $locale ) && ( $locale != $this->defaultLocale || !$this->hideDefaultLocaleInURL() ) )
{
    $parsed_url[ 'path' ] = $locale . '/' . ltrim($parsed_url[ 'path' ], '/');
}
    $parsed_url[ 'path' ] = ltrim(ltrim($base_path, '/') . '/' . $parsed_url[ 'path' ], '/');`
replace the code with this
`$parsed_url[ 'path' ] = $locale . '/' . ltrim(ltrim($base_path, '/') . '/' . $parsed_url[ 'path' ], '/');`

**Comment by congkevin** [comment]
@chadidi 
Thank you for your suggestion!
Your suggestion is okay is the document root is in public.
However if the document root is not in public, it will route to 
eg. "id/.../public/file"

However, I think I found the solution.
just change code below
`if ( !empty( $locale ) && ( $locale != $this->defaultLocale || !$this->hideDefaultLocaleInURL() ) )`
into
`if ( !empty( $locale ) )`

I have checked and it solved my problem

**Comment by congkevin** [comment]
please see my previous comment

> congkevin commented on Nov 18, 2016

**Comment by aries84ct** [comment]
Thanks, I saw it and it works, but I want to switch the language to default (en) without visiting the page containing '/en'.
Using your solution, I have to visit a link containing "/en", in order to switch the language to en.

**Comment by congkevin** [comment]
i dont know how to fix your problem. meanwhile, you can use other solution.
Happy coding

**Comment by aries84ct** [comment]
Thanks, I'm trying to solve it :)

Happy coding to you

**Comment by congkevin** [comment]
> I would like to simply visit a link like http://your-domain.com/ (without /en inside the URL) and switch language to en.

Regarding your problem, as i mentioned in previous comment, it should be solved.
> just change code below
> if ( !empty( $locale ) && ( $locale != $this->defaultLocale || !$this->hideDefaultLocaleInURL() ) )
> into
> if ( !empty( $locale ) )

eg. http://test.com/id/item  -> when you click english button, it should return into http://test.com/item.
I just tried with my codes and it works.

**Comment by aries84ct** [comment]
Yes I know, but I thought there might be problems with Google webmaster tools and hreflang attribute, but I verified and it's not that case, so I will use your solution :)
Regards
