### ISSUE TITLE
error when using optional params in route file

### ISSUE THREAD

**Issue by nickbr5** [mcamara/laravel-localization#373]
Hi,

I'm having troubles with the package when using optional parameters in my translated routes.

I use {{LaravelLocalization::localizeURL('partners')}} in my view.

I have a route file NL which contains "partners" => "partners/{confirmed?}".
I have a route file FR which contains "partners" => "partenaires/{confirmed?}".
The result of localizeURL always returns the default url => dev.localhost/fr/partners.
If i delete the optional params or i make them required everything works perfectly. 
I'm using the lastest version of the package and L5.2.

Any ideas?

thx

**Comment by afontcu** [comment]
Have you tried passing `null` or empty values as optional parameter? Can't find where I used it but I recall doing it.

Hope it helps.

**Comment by nickbr5** [comment]
@afontcu Yes, i also tried {{LaravelLocalization::getLocalizedURL(null,'partners',array('confirmed'=>1)}}.
This gives the same result => dev.localhost/fr/partners, no translation took place.

**Comment by lukasfiala** [comment]
Same problem like @nickbr5.  I'm using the latest version of the Laravel 5.3.

**Comment by iwasherefirst2** [comment]
This issue has been open for a long time and is likely outdated due to changes and updates in the package since it was reported. I'll close this ticket for now, but if this problem persists with the latest version of the package, please feel free to reopen it or create a new issue with updated details. Thank you for your understanding!

**Comment by niels-numbers** [comment]
See https://github.com/mcamara/laravel-localization/issues/933, its a duplicate
