### ISSUE TITLE
Set language default by cookie in laravel

### ISSUE THREAD

**Issue by dzung1nguyen** [mcamara/laravel-localization#374]
Hi ,

I want to hide language ("en", of .... ) on URL, and set default language at cookie.

How to i can set a language by cookie in laravel 5. My config:

Config:
....
'useAcceptLanguageHeader' => true,
'useCookieLocale' => true,
'hideDefaultLocaleInURL' => true,
...

Laravel:
$systemLanguages = \LaravelLocalization::getSupportedLocales();
$language = \Cookie::get("language_default");
if($language && isset($systemLanguages[$language])){
    LaravelLocalization::setLocale($language);
}

But it dose not work.

Can you help me?

Thank you so much.

**Comment by chadidi** [comment]
## You can fix it by going to this file 
`/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php`
## and search for 
`$parsed_url[ 'path' ] = $locale . '/' . ltrim($parsed_url[ 'path' ], '/');` 
## you will find something like this

`if ( !empty( $locale ) && ( $locale != $this->defaultLocale || !$this->hideDefaultLocaleInURL() ) )
        {
            $parsed_url[ 'path' ] = $locale . '/' . ltrim($parsed_url[ 'path' ], '/');
        }
        $parsed_url[ 'path' ] = ltrim(ltrim($base_path, '/') . '/' . $parsed_url[ 'path' ], '/');`

## replace the code with this
`$parsed_url[ 'path' ] = $locale . '/' . ltrim(ltrim($base_path, '/') . '/' . $parsed_url[ 'path' ], '/');`

**Comment by phpspider** [comment]
Mentioned line is already there after the if condition. Still not working.

**Comment by chadidi** [comment]
## replace this .

`if ( !empty( $locale ) && ( $locale != $this->defaultLocale || !$this->hideDefaultLocaleInURL() ) ) { $parsed_url[ 'path' ] = $locale . '/' . ltrim($parsed_url[ 'path' ], '/'); } $parsed_url[ 'path' ] = ltrim(ltrim($base_path, '/') . '/' . $parsed_url[ 'path' ], '/');}`

## with this
`if ( !empty( $locale ){
$parsed_url[ 'path' ] = $locale . '/' . ltrim(ltrim($base_path, '/') . '/' . $parsed_url[ 'path' ], '/');
}`

**Comment by chadidi** [comment]
@phpspider and remove the line you are talking about

**Comment by ctf0** [comment]
actually this is included but not documented https://github.com/mcamara/laravel-localization/search?utf8=%E2%9C%93&q=cookie
