### ISSUE TITLE
Database stored slug support

### ISSUE THREAD

**Issue by anaisabel19886** [mcamara/laravel-localization#379]
Hi! is there a way to get slug translations from de database? 

I am using [laravel-translatable](https://github.com/dimsav/laravel-translatable) build a cms and we intend every page to have a slug in the laguages supported by the website; so our slugs are dinamic, and it' wouldn't be very functional to keep editing the translation files in laravel.

Is there already a way to do this?

**Comment by ctf0** [comment]
there a way around it 
1- dont use the translated routes from this package
2- make a table that hold ur routes names + translation
3- in ur routes.php make a loop that go through that table and creates a route dynamically according to the names in it

the good thing about this is that u can save/edit ur route translation as u want and its dynamic because its gets generated through the loop, however the only drawback is you will have to create the controller methods manually or come up with a way to append them to the controller each time you have a new route.

**Comment by anaisabel19886** [comment]
Hi, to anyone with this problem, as ctf0 suggested, I resolved it this way (probably not the best, but it works).
I am using dimsav/laravel-translatable, and there is a slug field on my page_translations table.

On my web routes:
```

//localized routes
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localize', 'localeSessionRedirect', 'localizationRedirect'] 
        ], function() {

    Route::get('/', 'FrontController@index');

    Route::get('/{slug}', 'FrontController@resolver');

    Route::get('/{parent}/{slug}', 'FrontController@resolver2levels');

    Route::get('{grandparent}/{parent}/{slug}', 'FrontController@Resolver3levels');
});
```
(we'll only accept 3 levels of subpages)

On my FrontController:

  ```
public function resolver($slug) {

        //trying to find translation on current locale
        $translation = \App\PageTranslation::with('page.menu.menuItems')->where('slug', $slug)->where('locale', \App::getLocale())->first();

        if (is_null($translation) || !$translation->page->isActive()) {
            abort(404);
        }

        $page = Page::findOrFail($translation->page_id);

        $view = $this->getViewName($page->view_id);

        return XXX;
    }

    public function resolver2levels($parent, $slug) {

        return $this->resolver($parent . '/' . $slug);
    }

    public function resolver3levels($grandparent, $parent, $slug) {

        return $this->resolver($grandparent . '/' . $parent . '/' . $slug);
    }

    public function notificationsTest() {
        $page = Page::first();

        Auth::user()->notify(new \App\Notifications\NewPage($page));
    }`


```

**Comment by ctf0** [comment]
here is a sample of what i mean
https://gist.github.com/ctf0/001342eb07eb513659507c84f9b1271b you can also use https://github.com/spatie/laravel-translatable instead of making a bazillion columns for different langs

**Comment by anaisabel19886** [comment]
I will take a look, thanks!!

And btw there are no bazillion columns, i use dimsav/laravel-translatable, witch seems to be similar to spatie/laravel-translatable.
My page-translations table:

![pages](https://cloud.githubusercontent.com/assets/12087482/22459634/553af386-e799-11e6-8ce5-7cc4dfd534ef.png)

**Comment by ctf0** [comment]
oh okay, i prefer the spatie package more as all u need is to only include the trait and specify the attribute that will be localized & thats about it (no migration, no extra method call)

**Comment by anaisabel19886** [comment]
That's what I figured you where saying ;)

Humm, nice, when I was browsing for a translation package I also saw spatie's, but went for dimsav's.. perhaps on another project!

**Comment by moakkaya** [comment]
@ctf0 Hi,
Can you share your gist again?

**Comment by ctf0** [comment]
@moakkaya hi there, honestly i cant remember what exactly was it but maybe you can tell me what u r after and i can help you 👍

**Comment by moakkaya** [comment]
@ctf0 You did recommend the spatie's package but it has no support for translated slug & route binding. so i have to move on with dimsav's package.. Now my models have translated but i have to do that on static strings, routes etc. I'm trying to find a compact way to merge two packages. 

I saw this issue but dist has removed. ( Thanks to Murphy! ) 

When you have time, a real example would be appreciated :)

**Comment by moakkaya** [comment]
@ctf0 

just i need 

/news/translated-slug-for-en
/nouvelles/translated-slug-for-fr


slugs coming from database but 'news' and 'nouvelles' are static strings. They located in anywhere. I just wanted to achieve that problem.

PS. arabic suggestion made me upset :)

**Comment by ctf0** [comment]
lol , certainly didnt mean to 🌮 

- anyhow the slug will be returned depend on the app current local.
- for the route link, thats one of the reasons i made the above package but if you are fine with the current option LL offer then you should go with it.

here is how spatie/laravel-translatable works
```php
NewsItem::create([
   'name' => [
      'en' => 'translated-slug-for-en'
      'fr' => 'translated-slug-for-fr'
   ],
]);

NewsItem::first()->name
// if app()->getLocale(); == 'en' 
// name == translated-slug-for-en
// if app()->getLocale(); == 'fr' 
// name == translated-slug-for-fr
```

**Comment by moakkaya** [comment]
@ctf0 Ah, okay. Then i will handle the binded slugs in RouteServiceProvider, nice. 
But what about 'news' and 'nouvelles' prefix.. Where should i keep them and can this package help me on this ?  

This was the last question i promise :) 

Thanks.

**Comment by ctf0** [comment]
either go manually with https://github.com/mcamara/laravel-localization#translated-routes
or go automatically through db with https://github.com/ctf0/SimpleMenu
