### ISSUE TITLE
Using session switching instead of prefix

### ISSUE THREAD

**Issue by nhg2016** [mcamara/laravel-localization#383]
Hi,

I have been going round on the documentation for this package and I have a small question.  Is it possible not to use a local prefix and instead rely on a session variable to switch languages?

Thanks

Nhg

**Comment by ctf0** [comment]
the reason this package is made this way is for better seo, however if u prefer to solely depend only on the session keys without the url prefix, u can easily do it ur self, a simple workflow would be
1. create a lang switcher link
2. this link call a method that set a session key equal to the switcher value
3. set the app locale to the switcher value

now everywhere in ur app , u simply relay on the app.locale to serve ur data

**Comment by k-zakhariy** [comment]
i am searching solution for specific routes to be translated without prefixes , for example: 
/login, /checkout , /account - all these routes could be without prefix but still translated with current locale, instead of reseting it to fallback locale, any idea have to implement this ?

**Comment by iwasherefirst2** [comment]
As ctf0 explained, the purpose of this package is to avoid having different pages showing to the same uri.
I would highly recommend to localize /login, /checkout , /account etc.

If you don't want to, create a custom route group for those routes and add a middleware that sets

    App::setLocale(session('locale', 'en'));
