### ISSUE TITLE
Add support for route exception list

### ISSUE THREAD

**Issue by kkomelin** [mcamara/laravel-localization#385]
## Problem/Motivation

We apply localization redirect middlewares to the entire **web** route group. It means that [laravel-localization](https://github.com/mcamara/laravel-localization) package redirects route **broadcasting/auth** to **en/broadcasting/auth**, which crashes Event Broadcasting.

The problem is related to the fact that Laravel Echo Server does not support redirects (HTTP statuses other than 200) https://github.com/tlaverdure/laravel-echo-server/blob/master/src/channels/private-channel.ts#L60 of the Laravel authorization service **broadcasting/auth**. 

It is probably possible to improve Laravel Echo Server in order to support redirects, but from my point of view it is easier to solve the problem from the Laravel side.

## Proposed Resolution

Laravel core includes **VerifyCsrfToken** middleware which is used as a base class for local **VerifyCsrfToken** middleware. The local midleware contains **$except** property which is taken into account by the parent class.

```
<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;

class VerifyCsrfToken extends BaseVerifier
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        //
    ];
}
```

Unfortunately, **laravel-localization** middlewares do not support such exception list.

My idea is to make **laravel-localization** middlewares take into account **$except** property of child classes.

**Comment by kkomelin** [comment]
Implemented the proposed change https://github.com/mcamara/laravel-localization/pull/386

**Comment by kkomelin** [comment]
The new version of the package includes the proposed change https://github.com/mcamara/laravel-localization/releases/tag/1.1.11

Read how to use the new feature: https://komelin.com/articles/mcamaralaravel-localization-middlewares-now-support-route-exceptions

**Comment by emilv** [comment]
The blog article [is moved](https://komelin.com/articles/laravel-localization-middlewares-now-support-route-exceptions/).

**Comment by kkomelin** [comment]
Thank you @emilv. I've corrected the link in my comment.
