### ISSUE TITLE
Custom language detection rules

### ISSUE THREAD

**Issue by Nyratas** [mcamara/laravel-localization#388]
I store language preference information in the user's model, and I'm not really sure how to handle this with this package. Basically, I was thinking of extending [the LaravelLocalizationRedirectFilter middleware](https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php) and add a condition with the connected user's language preference.

But this doesn't feel "clean", since I think it should be detected in [the language negociator](https://github.com/mcamara/laravel-localization/blob/master/src/Mcamara/LaravelLocalization/LanguageNegotiator.php). Am I wrong ?

Any thought on this subject would be much appreciated !

**Comment by ctf0** [comment]
what happens is that the package reads the segment out of the url and add it to the session, so maybe u can make a middleware that check what is the user pref and redirect to the localized version of that pref, this ofcourse is needed once as from next request on , the package will save that into session
