### ISSUE TITLE
Adding active class to menu item

### ISSUE THREAD

**Issue by goowikns** [mcamara/laravel-localization#391]
Usually I use the following approach to add urls and set the active class on a menu item:

`<li class="{{ Request::is('home') ? 'active' : '' }}"><a href="{{URL::to('home')}}">Home</a></li>`

How can this be achieved when I have **translated routes** & the **middleware** active to redirect all "non-localized" routes to the corresponding "localized"?

**Comment by jeff-h** [comment]
I have the same issue as described above. What are others doing to resolve this? `Request::is()` is simply unaware of any potential language-prefix.

**Comment by jeff-h** [comment]
In case it helps anyone else, I have used a custom blade directive:

```php
Blade::directive('isactiveroute', function ($routeName) {
    return "<?php echo ($routeName == \Route::currentRouteName()) ? 'active' : ''; ?>";
});
```

and use it like so:

```blade
<a href="{{ routeRel('user.profile.personal', $user) }}" id="personal-details" class="nav-link @isactiveroute('user.profile.personal')">{{ __('Personal') }}</a>
```

(Note, `routeRel` is unrelated; it's simply a version of the `route` helper that provides relative URLs)
