### ISSUE TITLE
getLocalizedURL() returns FALSE

### ISSUE THREAD

**Issue by itxp2008** [mcamara/laravel-localization#393]
Hi,

I have laravel 5.1 and "mcamara/laravel-localization": "1.0.13" 

`'locale' => 'ro', 'fallback_locale' => 'ro', `

and

```
'supportedLocales' => [
'ro'          => ['name' => 'Romanian',               'script' => 'Latn', 'native' => 'română'],
'en'          => ['name' => 'English',                'script' => 'Latn', 'native' => 'English'],
],
```

With

'hideDefaultLocaleInURL' => false

everything works great but i need  

'hideDefaultLocaleInURL' => false

on _domain.com/en/products/xxx_ in the language selector **getLocalizedURL($localeCode)** returns
_domain.com/en/products/xxx_ for **EN** and for **RO** _domain.com/produse/xxx_

but on _domain.com/produse/xxx_ it returns for **EN** just _domain.com/en_

**Comment by itxp2008** [comment]
Correction i need 'hideDefaultLocaleInURL' => true

**Comment by svkmedia** [comment]
same problem
