### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by rsdev000** [mcamara/laravel-localization#395]
Hi. Laravel 5.4 is scheduled to be released next week. In the upgrade guide https://laravel.com/docs/5.4/upgrade we can see that the share method was removed from the container and the laravel localization service provider needs to be updated accordingly.

A possible solution is:
```php
$this->app->bind(LaravelLocalization::class, function () {
    return new LaravelLocalization();
 });
```
Method getUri() was removed from route.

In LaravelLocalization.php line 753
```php
$path = $route->getUri();
```
Should be
```php
$path = $route->uri; 
```

Best

**Comment by chadidi** [comment]
@mcamara can you please upgrade this package to work with `laravel 5.4.*` thanks.

**Comment by sasin91** [comment]
Since it's a shared instance atm, i suggest using singleton, like so:
$this->app->singleton(LaravelLocalization::class); instead :)
