### ISSUE TITLE
Laravel Localization getLocalizedURL() with token

### ISSUE THREAD

**Issue by mirbatworks** [mcamara/laravel-localization#400]
How to create properly url with token as parameter. I try
{{ LaravelLocalization::getLocalizedURL(App::getLocale(), "register/activation/", [$user->token]) }}
also
{{ LaravelLocalization::getLocalizedURL(App::getLocale(), "register/activation/", $user->token) }}
but this doesn't work. I get url without token.

**Comment by ctf0** [comment]
maybe try 
```blade
{{ LaravelLocalization::getLocalizedURL(App::getLocale(), "register/activation/", ['token' => $user->token]) }}
```
