### ISSUE TITLE
Query the other language post URL

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [mcamara/laravel-localization#403]
Hi,

I have two languages website English and Arabic my current route to display the post is:

`Route::get('post/{post_slug}', 'PostController@show');`

Currently using this package I got two URLs:

```
http://mydomain.dev/ar/post/post_english_slug
http://mydomain.dev/en/post/post_english_slug
```

But the Arabic version of this post have an entirely different slug saved into the database, how can I retrieve it?

Thank you in advance,
Mohammed

**Comment by MohammedAl-Mahdawi** [comment]
Any help please?

**Comment by villeneuve-michael** [comment]
I also have an issue with this. Any ideas ?

**Comment by ctf0** [comment]
to get this package to work as u expect, always use route names, now you can work with ur forms/urls without any issues
