### ISSUE TITLE
Can i translate resource routes?

### ISSUE THREAD

**Issue by ElioMS** [mcamara/laravel-localization#404]
Hello,
I'm using your package and works greate with routes like:

```
Route::get(LaravelLocalization::transRoute('routes.about'), function () {
        return view('about');
    })->name('about');
```

But what about with Resource::route

`Route::resource('articles', 'ArticlesController');`

It's possible to translate this kind of routes? Please let me know.

Thanks your package is really awesome!!

**Comment by ahmedbally** [comment]
is there any answer !
