### ISSUE TITLE
Custom order for getSupportedLocales languages switch bar

### ISSUE THREAD

**Issue by beeInteractive** [mcamara/laravel-localization#405]
Hi!

I was wondering how to customize the order the languages in the "switch bar" in a specific order? For now, it is ordered alphabetically. How can I change this?

Thanks in advance!

**Comment by sarotnem** [comment]
Quick workaround is to go to `config/laravellocalization.php` and from there select the enabled locales and sort them as you want. 

I think it would be nice if in this file there is a field for example 'localesOrder' and then we can set the order without messing with the order in 'supportedLocales'. Something like: 

`'localesOrder' => [el, en, pl]`

**Comment by sarotnem** [comment]
Custom order is now supported in the new version! Be sure to update to the newest version and check the documentation.

**Comment by svkmedia** [comment]
localesOrder is not working for getSupportedLocales(). Had the same issue. I solved it by reorder supportedLocales array. This caused reorder also in getSupportedLocales().

**Comment by bertheyman** [comment]
@mcamara as I user, I expected getSupportedLocales() to follow the specified order by default.
I now solved it by using getLocalesOrder().

Would you accept a pull request to have getSupportedLocales() follow the custom order by default?
