### ISSUE TITLE
hideDefaultLocaleInURL doesn't work on Laravel 5.1.11

### ISSUE THREAD

**Issue by yangliurea** [mcamara/laravel-localization#408]
Hi,

I am using Laravel 5.1.11 with laravel-localization 1.0.x, and do set hideDefaultLocaleInURL to true, but when I query the default language, it still give me locale in url.

**Comment by iwasherefirst2** [comment]
Are you using the redirecting middleware as stated in the [docs](https://github.com/mcamara/laravel-localization#middleware)?

```
Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
```
