### ISSUE TITLE
Package 1.1.* language switcher works with Laravel 5.3 but 1.2.* does not

### ISSUE THREAD

**Issue by Luis-Goncalves-Searchprof** [mcamara/laravel-localization#409]
Hello,

Just had an issue with the v1.2.* regarding a laravel 5.3.* project. Thought it might have something to do with my stuff but then i did a clean install of laravel 5.3.* and just used 2 simple routes tests.
```
Route::get(LaravelLocalization::transRoute('routes.home'), function () {
          return 'home';
});
        
Route::get(LaravelLocalization::transRoute('routes.about-us'), function () {
          return 'about us';
});
```

I define just 2 languages, pt and en. Using v1.2.* the language switcher always creates the url translation with the current locale. For example, if im in the english version seeing the "about us" page, the url shows "domain.dev/en/about-us" and the language switcher for the portuguese version shows "domain.dev/pt/about-us"; if im in the portuguese version, the url shows "domain.dev/pt/sobre-nos" and the language switcher for the english version shows "domain.dev/en/sobre-nos". 
The "LaravelLocalization::getLocalizedURL()" function doest not work properly.
But using the v1.1.* package version, the function works well and the switcher does what is expected of him.

Because of this i had to return to 1.1.* version. I havent tested in laravel 5.2.* and 5.4.* to see if this issue with v1.2.* also happens, maybe it does, no idea.

**Comment by Okipa** [comment]
Oops, it seems that we opened the same issue : https://github.com/mcamara/laravel-localization/issues/410

**Comment by TheOneWhoKnokks** [comment]
There is one error in LaravelLocalization file, line 327.
Missing one parameter, must be 
`$translation = $this->translator->trans($transKeyName, [], null, $locale);`
actually there is,
 `$translation = $this->translator->trans($transKeyName, [], $locale);`

**Comment by Okipa** [comment]
Have considered a pull request to fix this ?

**Comment by TheOneWhoKnokks** [comment]
Somebody already make a pull request #407

**Comment by Luis-Goncalves-Searchprof** [comment]
It seems to be working now.

Though an ancient problem still remains, which is the fact that the routes with wildcards dont seem to be getting translated properly in the code that generates the language switcher. Any fix or hack for this?
