### ISSUE TITLE
Change default locale

### ISSUE THREAD

**Issue by Cyber-host** [mcamara/laravel-localization#412]
Hi, all. I need change default locale for admin panel in my middleware. How can I do it?

I need something like:
```
setDefaultLocale('en')
```
or
```
public function getDefaultLocale()
    {
        return $this->configRepository->get('app.locale');
    }
```

thx.

**Comment by ctf0** [comment]
u can use `LaravelLocalization::setLocale(optional string $locale)`

**Comment by Cyber-host** [comment]
@ctf0 it doesn't work after register LaravelLocalization in the container. I use container resolving event for it

**Comment by mtx-z** [comment]
@ctf0, does `LaravelLocalization::setLocale(optional string $locale)` change the default locale ? The default local is taken from app.locale ? thx

**Comment by ctf0** [comment]
@mtx-z it changes the session locale, then the middleware check it and change the `app.local` accordingly
