### ISSUE TITLE
Routes with parameters dont get translated - Laravel 5.3.* with package 1.2.*

### ISSUE THREAD

**Issue by Luis-Goncalves-Searchprof** [mcamara/laravel-localization#413]
Hi,

`{!! LaravelLocalization::getLocalizedURL('en', route('frontend.tips.show', [$tip->slug])) !!}`

The function doesnt work, cant seem to translate the routes that have parameters.

It wasnt working also with the v1.1.* . But i have a project with Laravel 5.0.* using the package v1.0.* and the function works well.
Something to do with laravel version or the package version or both?

Thanks

**Comment by ctf0** [comment]
not sure if it would work or not, but have u tried 
```php
{!! LaravelLocalization::getLocalizedURL('en', route('frontend.tips.show'), ['slug'=>$tip->slug]) !!}
```

**Comment by Luis-Goncalves-Searchprof** [comment]
Yeap, i did, but it doens't work either.

**Comment by dviluk** [comment]
#409
