### ISSUE TITLE
Non-persistent sessions using laravel-localization

### ISSUE THREAD

**Issue by phandevit** [mcamara/laravel-localization#416]
I'm having issues where sessions are not persistent. On each refresh, new sessions are created (can overload a server if setting session driver to 'path'; error out after 8-9 cookies created using session driver 'cookie'). I believe this issue is related to middleware, similar to https://github.com/laravel/framework/issues/13000.

The usage requires adding middleware to the route group. My route looks like the following:

```
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localize', 'localeSessionRedirect', 'localizationRedirect']
    ],...
```

If I commented out the ```'middleware' => ['localize', 'localeSessionRedirect', 'localizationRedirect']``` line, no new sessions are created on refresh, but my site would not be localized.

Anybody experiencing this? If so, any solutions? Thank you in advance.

**Comment by phandevit** [comment]
I realized that I have to change the middleware to:

```'middleware' => ['localeSessionRedirect', 'localizationRedirect']```

to fix that issue. Any ideas why?

**Comment by icodeforyou** [comment]
+1

**Comment by bouldrini** [comment]
Hey guys, 

i got a similar issue, 
the package works and translates my routes correctly.

since i use it the session is not persistent anymore, except the locale attribute.

custom attributes are not stored or unreachable via \Session::get('attribute_name').

I am using 

`'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]`

changing the session_driver to cookie or any other option didn't succeed

**Comment by bouldrini** [comment]
hey buddy, i would really appreciate some help, because i am kind of stucked with this.

did i overread something in the documentation, or am i using it wrong or something.
i cant figure it out

**Comment by bouldrini** [comment]
Nevermind, i found a solution.
To regain Sessionpersistancy you will have to add the 'web' middleware to the list of used middlewares.

'middleware' => ['web', 'localeSessionRedirect', 'localizationRedirect' ]

For custom attribute support add them in the LocaleSessionRedirect.php like this in the handle function line 30:

...
session(['locale' => $params[0]]);
session(['cst_attr' => $request->session()->get("cst_attr")]);
...

**Comment by iwasherefirst2** [comment]
@phandevit is this issue still present?
