### ISSUE TITLE
Localizing login after auth redirect

### ISSUE THREAD

**Issue by mattbartel** [mcamara/laravel-localization#417]
I have a translated login route at /login.  I can see the translated versions of it by browsing to them directly (e.g. /es/login), but when I am not logged in and try to visit the translated homepage (e.g. /es), it always redirects me back to the default language (English) login page at /login instead of /es/login.  

My routes file:

```
Route::group(
  [
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]
  ],
  function()
  {

    // Auth Routes
    Auth::routes();

    // Home
    Route::get('/', 'HomeController@index'); // Uses 'auth' middleware inside controller
  }
);
```

I assume this is because the auth middleware is executing before the localization middleware so the locale is never being set, but I'm not sure the best way to correct that.

**Comment by ctf0** [comment]
this is probably because the view is using the url not the route name for login.

to get the most of this package u should avoid using urls and always use route names.

**Comment by mattbartel** [comment]
Which view are you referring to?  The login view?  All the default auth routes are named.  I've also updated the home route to be named and it didn't help: 

```
Route::get('/', 'HomeController@index')->name('home');
```

It seems to me that the locale is never being set before the auth middleware redirects to the login page.  If my locale is set to English and I'm not logged in, then I try to browse to /es, I get redirected to the /en/login page.  What should happen is that browsing to /es should set my locale to Spanish, then direct me to the login view, which would render in Spanish, given that my locale had changed. What am I missing?

**Comment by ctf0** [comment]
this is strange, its working without issues on my machine, can u make a repo with ur current copy ?

**Comment by pleone** [comment]
I've got the same issue.

**Comment by leanderlindahl** [comment]
Using Laravel 5.4.36 and macamara/laravel-localization 1.3.10 I had this problem too, but once I put Auth::routes(); inside my Route::group it worked as expected:

`Route::group(
	[
		'prefix' => LaravelLocalization::setLocale(),
		'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
	],
	function()
{
	/** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
        Route::get('/', 'ContentsController@home')->name('home');
        Auth::routes();
});

/** OTHER PAGES THAT SHOULD NOT BE LOCALIZED **/
`
