### ISSUE TITLE
SetLocale() does not look for cookie or session as stated in the docs

### ISSUE THREAD

**Issue by andycansdale** [mcamara/laravel-localization#422]
Contrary to what is stated in the documentation, SetLocale does not in any place retrieve cookie or session locales.

> This function will change the application's current locale. If the locale is not passed, **the locale will be determined via a cookie (if stored previously), the session (if stored previously)**, browser Accept-Language header or the default application locale (depending on your config file).

**Comment by andycansdale** [comment]
The docs seem not to have been updated since version 0.15  at which time the cookie and session functionality was indeed there. The functionality disappeared in 0.1, although it's not clear why. I'm beginning to think I may have to roll my own localisation solution.

**Comment by Jeroenvanderholst** [comment]
Bummer, I was looking for an update that did just that. Can we turn it back on again?

**Comment by willemwollebrants** [comment]
I know this issue is old, but I managed to get retrieving the locale from session working in Laravel 5.8 by adding the \Illuminate\Session\Middleware\StartSession to my middleware stack:
```
class Kernel extends HttpKernel
{
 // ...
    protected $middleware = [
        //...
        \Illuminate\Session\Middleware\StartSession::class,
        'localize' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
        'localizationRedirect' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
        'localeSessionRedirect' => \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
        'localeViewPath' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationViewPath::class,
];
```

**Comment by iwasherefirst2** [comment]
You have to use `SessionRedirect` and `CookieRedirect` middleware for that. Take a look at the updated [docs](https://github.com/mcamara/laravel-localization#redirect-middleware).
