### ISSUE TITLE
hide locale prefix of any route

### ISSUE THREAD

**Issue by bunhann** [mcamara/laravel-localization#425]
I want to my route clean without any local lang in the url. For example, I have 2 languages: English and French. I want it to be http://example.com when the user change the language. I don't want like this http://example.com/fr or http://example.com/en. Even your package can hide default locale, but it will show other lang in the url. How to solve this? Sorry for my bad English.

**Comment by tontonsb** [comment]
You should implement it yourself, it's easy if you don't want anything in the routes.

Just save the chosen locale in session or even in the database if you only have registered users. For example, you could `Session::put('locale, '$locale);` on change

Then add middleware to set locale according to the session: `App::setLocale(Session::get('locale'));`.
