### ISSUE TITLE
LaravelLocalization::getDefaultLocale(); value change on artisan config:cache

### ISSUE THREAD

**Issue by mtx-z** [mcamara/laravel-localization#429]
Hello !

I encountered a little problem: 
- My default locale (`config('app.locale')`) is DE. 
- if I `php artisan config:clear`, dump of `LaravelLocalization::getDefaultLocale();` is DE
- if I `php artisan config:cache`, dump of `LaravelLocalization::getDefaultLocale();` is EN
- after a `config:clear`, it is back to DE

My app config file get a value from .env using `env('APP_LOCALE')`, and is re-setted nowhere. Also, my application code don't use once a `env('APP_LOCALE')` to get the value, but only `LaravelLocalization::getDefaultLocale();`

I found this [thread ](https://laracasts.com/discuss/channels/laravel/configcache-makes-variables-in-env-null), but i cannot figure it out...

It seems that `LaravelLocalization::getDefaultLocale();` use the app.locale value, and my test are done in top of my locale middleware. I dont get why the value change if I cache my config...

Thx !

**Comment by mtx-z** [comment]
New issue opened #448

**Comment by iwasherefirst2** [comment]
You have to use [cache of the package](https://github.com/mcamara/laravel-localization#caching-routes)

    php artisan route:trans:cache
