### ISSUE TITLE
getLocalizedURL execution time is quite long

### ISSUE THREAD

**Issue by Okipa** [mcamara/laravel-localization#432]
Hi there,

I am also using your nice package to generate a multilingual sitemap and I realized that the use of the `getLocalizedURL` method repeatedly could trigger a max execution time exception.
Wouldn't be a way to optimize a bit this method execution time ?

I am using this method to declare each page alternate languages for example.  
On sites that contains about 50 pages, this become problematic because you have to execute the following loop for each declared page.

```
$alternate = [];
foreach (LaravelLocalization::getSupportedLocales() as $alternate_locale => $prop) {
    $alternate[] = "    <xhtml:link rel='alternate' hreflang='$alternate_locale' href='" . LaravelLocalization::getLocalizedURL($alternate_locale, route('pages.show', ['slug' => $page->translate($alternate_locale)->slug])) . "' />";
}
```

Right now I can't use your method, the sitemap would take something like more than 120 seconds to generate and I am messing around stuffs like this to improve performances :
```
$alternate = [];
foreach ($supported_locales as $alternate_locale => $alternate_properties) {
    $alternate[$alternate_locale] = "    <xhtml:link rel='alternate' hreflang='$alternate_locale' href='" . url($alternate_locale . '/' . str_replace(['{slug}'], [$page->translate($alternate_locale)->slug], trans('routes.pages.show', [], $alternate_locale))) . "' />";
}
```
This way, I generate my sitemap almost instantly but that's not pretty at all ...  
Would anybody have a solution to improve performances from this method ?

**Comment by kaidoj** [comment]
This method is slow. I can confirm.

**Comment by lucasff** [comment]
I found out that we have 70000 calls to preg_match in a pretty normal Laravel application (eCommerce). We generate around 400~ links each request.

**Comment by kaidoj** [comment]
Anyone has a fix for this or a replace method?

**Comment by Doomkyn** [comment]
BUMP I got an header with localizedurls and it takes forever...

**Comment by iwasherefirst2** [comment]
Is this still an issue?

I just measured the execution time for
```
$alternate = [];
foreach (LaravelLocalization::getSupportedLocales() as $alternate_locale => $prop) {
    $alternate[] = "    <xhtml:link rel='alternate' hreflang='$alternate_locale' href='" . LaravelLocalization::getLocalizedURL($alternate_locale, route('test', ['slug' => $page->translate($alternate_locale)->slug])) . "' />";
}
```
and it took 0.0096086101531982 seconds with 50 activated languages.

If you just worry about the fact that your code isn't pretty you could move 
`
 url($alternate_locale . '/' . str_replace(['{slug}'], [$page->translate($alternate_locale)->slug], trans('routes.pages.show', [], $alternate_locale))` into a helper function?

**Comment by Okipa** [comment]
I couldn't tell you right now, I will need to re-implement this soon for a client so it will be a good opportunity to check this. It may have been optimized since april 2017 ?

**Comment by iwasherefirst2** [comment]
Maybe, I am new to this package so I can't tell.

**Comment by satoved** [comment]
This helper made 1.4 seconds response to 0.4

```
function localized_url($url): string
{
    $locale = LaravelLocalization::getCurrentLocale();

    return Cache::remember("url-$locale-$url", now()->addDay(), function () use ($url, $locale) {
        return \LaravelLocalization::getLocalizedURL($locale, $url);
    });
}
```
