### ISSUE TITLE
Using laravel localization with Resource controller.

### ISSUE THREAD

**Issue by dazzcreations** [mcamara/laravel-localization#440]
I have multiple routes using resource:: method of laravel. But when i try laravel localization to localise the views the post method stop working.
The forms which post data just came back without updating anything.
Kindly help.

**Comment by karneaud** [comment]
+1

**Comment by iwasherefirst2** [comment]
You need to localize your post route, see https://github.com/mcamara/laravel-localization#post-is-not-working
