### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by wipit** [mcamara/laravel-localization#441]
Hello, peeps. Can somebody please help me to find out inside a controller which language I am in? I need to make a consult to the database and I just want to retrieve the proper language texts (not all of them and then just use a few of them in the view). Thanks in advance to you all!

**Comment by afontcu** [comment]
Hi wipit,

Your question is quite broad, so you could youse [CurrentLocale()](https://github.com/mcamara/laravel-localization#get-current-locale) to get your current language code.

If you need any other language information (such as name, regional...) check out the docs.

Hope it helps.
