### ISSUE TITLE
NotFoundHttpException when there is only a prefix

### ISSUE THREAD

**Issue by aghayeff** [mcamara/laravel-localization#443]
I installed this useful package as described. The only thing I get an error, while entering:

`www.site.com/az`

But it works if there is a slug name, after a prefix.

`www.site.com/az/contact`

I use Laravel 5.4

**Comment by gerardreches** [comment]
@aghayeff Did you find out what caused your problem?

**Comment by aghayeff** [comment]
Yes. my index route wasn't inside route group with middleware `[ 'localeSessionRedirect', 'localizationRedirect' ]`

**Comment by gerardreches** [comment]
@aghayeff And everything is working for you in Laravel 5.4? I get the `NotFoundHttpException` for all my translated routes. Which package version are you using? Thanks.

**Comment by aghayeff** [comment]
Be sure that you added middleware to your routes.
