### ISSUE TITLE
Get the link for the current page but with different locale - using translated routes

### ISSUE THREAD

**Issue by dbr0** [mcamara/laravel-localization#444]
In my routes I have

```
Route::get(LaravelLocalization::transRoute('routes.aaa'), ['as' => 'something_else_1, 'uses' => 'MyController@methodAaa']);
Route::get(LaravelLocalization::transRoute('routes.bbb'), ['as' => 'something_else_2, 'uses' => 'MyController@methodBbb']);
Route::get(LaravelLocalization::transRoute('routes.ccc'), ['as' => 'something_else_3, 'uses' => 'MyController@methodCcc']);
```

Routes files

```
[
  'aaa' => 'en_aaa',
  'bbb' => 'en_bbb',
  'ccc' => 'en_ccc',
]
```
Of course, for the `es` locale it's

```
[
  'aaa' => 'es_aaa',
  'bbb' => 'es_bbb',
  'ccc' => 'es_ccc',
]
```

How do I get the link in some view to return to the same place but with different locale?

```
<a href="{{ LaravelLocalization::getLocalizedURL('en') }}">English</a>
<a href="{{ LaravelLocalization::getLocalizedURL('es') }}">Spanish</a>
```

The code above gives routes as

```
example.com/en/en_aaa
example.com/es/en_aaa
```

But I want it to give me

```
example.com/en/en_aaa
example.com/es/es_aaa
```

I was thinking of using `getURLFromRouteNameTranslated` but for that I would need to get the translation key for route (aaa from something_else_1) but I don't know how can I do that.

UPDATE:

I tried the `getURLFromRouteNameTranslated` adding the route translation key manually but I still get wrong route names:

```
getURLFromRouteNameTranslated('es','route.aaa')
```
produces

```
example.com/es/en_aaa
```

This makes no sense to me so maybe I did something wrong somewhere else.

**Comment by adileo** [comment]
#447

**Comment by francoisdusautoir** [comment]
I have the same problem, with the ```getLocalizedURL```function. What is the issue to solve it ?

**Comment by kazak71** [comment]
Yes, I have same problem.
I found a workaround.
See my post https://github.com/mcamara/laravel-localization/issues/448

Good Luck!
