### ISSUE TITLE
getLocalizedURL doesn't translate routes

### ISSUE THREAD

**Issue by francoisdusautoir** [mcamara/laravel-localization#448]
Hello.

Laravel-localization works well on my application. When I am on the homepage if I switch language and navigate on the application, all is running well, routes are translated as expected in all links, menus etc.

The problem is when I am on a page, if I click on the switch languages this is what I have : 

```
- http://app.dev/fr/titres/mon-titre
- http://app.dev/en/titres/mon-titre
- http://app.dev/es/titres/mon-titre
```

This is what I should have : 

```
- http://app.dev/fr/titres/mon-titre
- http://app.dev/en/titles/mon-titre
- http://app.dev/es/titulos/mon-titre
```

On my **header.blade.php**, this is what I have :

```php

@foreach(Localization::getSupportedLocales() as $lang => $properties)
    <a
        href="{{Localization::getLocalizedURL($lang)}}"
        @if(Localization::getCurrentLocale() == $lang) class="active" @endif
    >
        {{$lang}}
    </a>
@endforeach

```

Insofar as all is working as expected for the language when we are on a good URL ... what is the issue with that problem ? I saw many posts about similar problems with the getLocalizedURL() method, I tried many "issues" without success ...  :/

**Comment by quaidesbalises** [comment]
Any help ... ?

**Comment by kazak71** [comment]
Yes, I have the same problem.
When I made some deeper debug into the code I found that function **getLocalizedURL** returns wrong results when routes (in lang routes.php) are declared with parameters. When routes are clean (without parameters) everything is fine and working as desired.
I found problem is really in function **extractAttributes** - it returns wrong results when routes are declared with parameters.
**WORKAROUND :)**:
1. declare ALL routes as NAMED ROUTES in file app/routes/web.php (for laravel 5.3 or 5.4)
2. instead getLocalizedURL you may use getURLFromRouteNameTranslated if it is possible
3. change function **handle(...)** in file **LaravelLocalizationRoutes.php** like this:
 
 public function handle($request, Closure $next)
    {
        // If the URL of the request is in exceptions.
        if ($this->shouldIgnore($request)) {
            return $next($request);
        }
        $app = app();
        if (app()->router->currentRouteName() !== '') {
            $routeName = 'routes.'.app()->router->currentRouteName();
        } else {
            $routeName = $app['laravellocalization']->getRouteNameFromAPath($request->getUri());
        }
        $app['laravellocalization']->setRouteName($routeName);
        return $next($request);
    }

With these changes getLocalizedURL should be working.
I think this will help you!
Good Luck!

**Comment by gerardreches** [comment]
That workaround doesn't work for me, and I'm experiencing the problem without having parameterized routes.

**Comment by mrcbk** [comment]
I had this issue as well and created a pull request: [https://github.com/mcamara/laravel-localization/pull/458](url)

**Comment by gerardreches** [comment]
@mrcbk Are you using laravel-translation-manager package at the time you found that fix? There was an error in the other package.

Laravel trans function has 3 parameters, not 4:

    public function trans($key, array $replace = [], $locale = null)
    {
        return $this->get($key, $replace, $locale);
    }

[issue in vsch/laravel-translation-manager](https://github.com/vsch/laravel-translation-manager/issues/90) (fork of barryvdh/laravel-translation-manager, both can have this problem)

**Comment by mrcbk** [comment]
no, actually it's vanilla laravel 5.3: https://github.com/laravel/framework/blob/5.3/src/Illuminate/Translation/Translator.php#L235

So i guess for 5.4 it's invalid. Still if you are on 5.3.

**Comment by gerardreches** [comment]
Uhm.. Then the package will need a breakpoint between Laravel 5.3 and 5.4.

**Comment by thisprojectworks** [comment]
I have the same issue in laravel 5.4

**Comment by andrelegault** [comment]
Experiencing the same issue.

**Comment by mtx-z** [comment]
Same issue on Laravel 5.5. 

It works with 1 parameter, not with more: only locale is changing.

**Comment by fede91it** [comment]
Same here, both with Laravel 5.4 and 5.5

**Comment by mtx-z** [comment]
What's wrong with getUrlFromRouteTranslated()?
You need to provide the route name from the translation file, not the one from laravel router.

**Comment by fede91it** [comment]
Yes, I use the routes name from the translation file but both `getLocalizedURL` and `getUrlFromRouteTranslated` work as described in my previous comment.

**Comment by fede91it** [comment]
I found a working workaround:

```php
$routeName = 'routes.' . Route::currentRouteName();
$translatedParameters = current(event('routes.translation', [$localeCode, Route::current()->parameters]));
$translatedUrl = LaravelLocalization::getURLFromRouteNameTranslated($localeCode, $routeName, $translatedParameters);
```

**Comment by mtx-z** [comment]
You also matched router route name and translated route name?

**Comment by meduzen** [comment]
Hi, here’s my (temporary for the project I'm working on) [solution](https://gist.github.com/meduzen/f65a9348a7dae319eda60758106d88fd).

Please carefully read the commented documentation, and note that my fellow back-end developer colleague still has to review it.

**Comment by fede91it** [comment]
The workaround I found does not work with routes defined as resources.

@mcamara Could we find a definitive solution to this problem?

**Comment by Grupa-Leonardo** [comment]
The author apparently is no longer interested in further development of the package - it's time to look for something else.

**Comment by fede91it** [comment]
@Grupa-Leonardo any suggestion?

**Comment by Grupa-Leonardo** [comment]
@fede91it At this moment - nothing, but for next projects I'll look for somethink different. Now I must make it more 'statically' -.-

**Comment by kazak71** [comment]
take a look at this:
https://stackoverflow.com/questions/42527880/laravel-5-4-translate-routes
I think it may be useful with some changes but idea is clear
Good luck!

**Comment by fede91it** [comment]
Unfortunately it is too minimal a solution, I have more specific needs that currently only mcamara can satisfy.

I found this other project, which looks like an improved mcamara clone:

https://github.com/ARCANEDEV/Localization

**Comment by kazak71** [comment]
**fede91it**, this is great!
Thank you!

**Comment by stefkes** [comment]
Just out of curiosity, how would this package be able to translate the slug of a post if the slug is stored in the database? 

As far as I can tell there's no way this package talks to the database, only to the routes file and the translated route names.

Anyone?

**Comment by mtx-z** [comment]
@stefkes I think you should use another package. 

I use myself mcamara/laravel-localization for route translations, and [dimsav/laravel-translatable](https://github.com/dimsav/laravel-translatable) for model translations (slug, and all fields that you want translated).

**Comment by iwasherefirst2** [comment]
@francoisdusautoir  is this issue still present? `getLocalizedURL` seems to return the corrected translated urls now, even if you use parameters.

**Comment by iwasherefirst2** [comment]
Closing this as its seems to be fixed by now
