### ISSUE TITLE
Class 'App\Http\Middleware\LaravelLocalizationMiddlewareBase' not found

### ISSUE THREAD

**Issue by razvysb93** [mcamara/laravel-localization#450]
Adding  'localeViewPath'  in 
````
Route::group([
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
        ], function()
{

}
````

throw me this error:

> FatalErrorException in LaravelLocalizationViewPath.php line 10:
Class 'App\Http\Middleware\LaravelLocalizationMiddlewareBase' not found

**Comment by viktorivanov** [comment]
The namespace in LaravelLocalizationViewPath.php is set to App\Http\Middleware but should be Mcamara\LaravelLocalization\Middleware
