### ISSUE TITLE
Slug in translation locale

### ISSUE THREAD

**Issue by kiki091** [mcamara/laravel-localization#453]
Hi ..
i have url in locale english : www.example.com/en/i-am-here
and this in locale indonesia : www.example.com/id/aku-disini

in slug is dinamic with database, how i can translation slug using locale when i change language? i was try, but is does'n work, the url slug not change like it:  www.example.com/id/i-am-here

**Comment by afontcu** [comment]
Hi there,

You may find an answer in [this issue](https://github.com/mcamara/laravel-localization/issues/379).
