### ISSUE TITLE
LaravelLocalization::getCurrentLocale() gives wrong locale

### ISSUE THREAD

**Issue by Dagiral** [mcamara/laravel-localization#457]
I have two locales.  If i open a page with prefix "tr" (site.com/tr/something) , translation is right in view. But if i get an ajax request from a controller, the prefix "en" is coming and items are listed in english.  (Laravel 5.3)

`dd(LaravelLocalization::getCurrentLocale()); // output : en (but it must be tr)`

**Comment by hedii** [comment]
@Dagiral I had the same use case. Put the required local in an header field on your ajax request (for this example X-App-Locale header) and setup a middleware on your api routes.

This way, your api requests can be localized, and we also have a default locale if the locale header field is not provided with the ajax request

**/app/Http/Middleware/LocalizeApiRequests.php**

````php
<?php

namespace App\Http\Middleware;

use Closure;
use LaravelLocalization;

class LocalizeApiRequests
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        // default to app.locale if no locale header is set on the request
        LaravelLocalization::setLocale($request->header('X-App-Locale') ?: config('app.locale'));

        return $next($request);
    }
}
````

**/app/Http/Kernel.php**

````php
/**
 * The application's route middleware groups.
 *
 * @var array
 */
protected $middlewareGroups = [
    'web' => [
        // ...
    ],
    'api' => [
        // ...
        \App\Http\Middleware\LocalizeApiRequests::class,
    ],
];
````

**Comment by marijoo** [comment]
Problem here is that `LaravelLocalization::setLocale()` will take the first request url segment to detect the locale, which is undesirable in some cases.

This approach will work with urls like `/api/v1/en/some/action` where `locale` is the third parameter.

```
Route::prefix('v1')->group(function() {
    
    Route::prefix((function() {
        $locale = request()->segment(3); // use third segment as locale
        return LaravelLocalization::setLocale($locale);
    })())->group(function() {
        
        …
```

**Comment by iwasherefirst2** [comment]
@marijoo thats a nice hack, but unfortunately this makes it impossible to use 90% of this package, like all redirecting middlewares, the caching functionality, and the localization helpers etc.
