### ISSUE TITLE
Redirect seems to conflict with the auth

### ISSUE THREAD

**Issue by krecebli** [mcamara/laravel-localization#460]
Hi. When I use `'localeSessionRedirect', 'localizationRedirect'` middlewares, app handles auth state only on the next request. When I login (or register), I see my name and avatar only on the next request, and also when I logout, can see login form only on the next request. The whole middlewares look like:

```php
[
    'prefix'     => (new LaravelLocalization)->setLocale(),
    'middleware' => ['web', 'localeSessionRedirect', 'localizationRedirect'],
]
```
The problem is caused by both `localeSessionRedirect` and `localizationRedirect`. I tried each of them without another one, and both caused the problem, without them auth works as expected.

**Comment by iwasherefirst2** [comment]
Do you localize your [post route](https://github.com/mcamara/laravel-localization#post-is-not-working) ?
