### ISSUE TITLE
getLocalizedURL problem with parameters

### ISSUE THREAD

**Issue by perffy** [mcamara/laravel-localization#461]
Hi guys,

i am trying to generate an sitemap.xml with all my urls in all four different languages of my website. As i saw many of you have the problem that getLocalizedURL() does not translate correct the url if you specify the locale. I have added the four parameter to the trans($translatedRoute, [], null, $url_locale) function. Now i am able to translate all routes, except these which accept parameters.

As I was not able to find here any working solution for that situation, I have tried to debug the code and find myself a solution. Unfortunately i haven't found such solution, but i think i know what is the problem.

In getLocalizedURL() there is an $attributes array, which i have outputted and it was wrong for my test url. If I change manually the $attributes it translates correct the url. 

Next step was to find out, how $attributes is generated. It comes from extractAttributes() function. Unfortunately i stacked here, but it seems the function is not extracting correctly the parameters for the given url and that's why it doesnt translate them correct.

I hope this will help anybody to fix that function ?

**Comment by kikky7** [comment]
The issue I ran into is that getLocalizedURL() doesn't return the exact translation when I am using route model binding.

```
route: http://localhost:8000/en/news/1
```

If I have in my controller something like this:
```
public function article(News $news)
{
...
}
```
the route won't be translated (I get wrong result: http://localhost:8000/hr/news/1),
but when I don't use model binding
```
public function article($id)
{
$news = News::findOrFail($id);
...
}
```
the route will be translated into http://localhost:8000/hr/novosti/1

**Comment by iwasherefirst2** [comment]
@kskrlin I cannot reproduce this issue. Translatable urls seem to work with model binding. See for further instructions: https://github.com/mcamara/laravel-localization/issues/502#issuecomment-546670758

If its still not working, then please create a new issue including all your settings and reproducible steps (as explained in the new template.
