### ISSUE TITLE
hideDefaultLocaleInURL not working in Laravel 5.3

### ISSUE THREAD

**Issue by svkmedia** [mcamara/laravel-localization#465]
I set hideDefaultLocaleInURL = true but it's not working.
Locale is set to 'sk'
fallback_locale is set to 'sk'

It's working when I access domain.app or domain.app/sk but I want to hide /sk as default locale.
Even when I set hideDefaultLocaleInURL = false 
I can access domain.app and there is no redirect to /sk

**Comment by Sebi94nbg** [comment]
Hey,

all settings in each config file within the `config/` directory are cached by Laravel.

So if you change any setting there, make sure, that you update your application cache:

`$ php artisan config:cache`

Further information regarding configuration caching: https://laravel.com/docs/5.3/configuration#configuration-caching

**Comment by iwasherefirst2** [comment]
@svkmedia  Did you figure out the problem? Is this issue still present?

**Comment by iwasherefirst2** [comment]
You need to use the [Redirect middleware](https://github.com/mcamara/laravel-localization#redirect-middleware) to get redirected.
