### ISSUE TITLE
Language selector in root (index)

### ISSUE THREAD

**Issue by svkmedia** [mcamara/laravel-localization#467]
I'm having issue switching language on my index but don't understand why...

When I access domain.app and switch language it redirect me to domain.app/en
But locale doesn't switch. I have to access link domain.app/en/ (slash at the end) and then it's working fine. But why?
I can solve this by having index URL: domain.app/home but I don't want to have any slug on index.

**Comment by iwasherefirst2** [comment]
Do you still have this issue? If so, can you please provide us your `routes.php` file?
