### ISSUE TITLE
getDefaultLocale() have wrong value after config:cache

### ISSUE THREAD

**Issue by mtx-z** [mcamara/laravel-localization#468]
Hello ! 
Again, thanks for this great package. 
I'm running into a issue with the method getDefaultLocale().

From what I see, the `defaultLocale `is setted in `LaravelLocalization.php constructor`, and use `$this->configRepository->get('app.locale')`, and so the` config/app.php` locale value, wich is taken from my `.env` file. Default Locale (.env value) is "**de**".

The issue appear when i do a php artisan config:cache. After a `config:cache`, the value of `getDefaultLocale()` is "**en**". If i run a php artisan config:clear, value is "**de**". So i cannot cache my config, or the `defaultLocale `is wrong, and so cause issue on SEO alternates meta. 

Do you have any idea why caching the config would lead to a wrong value of `getDefaultLocale()`, but value is ok if I clear config ? (after `config:clear`, the DefaultLocale value is always ok for next requests, and always wrong after the config:cache).

My locale middleware update the app.locale on the fly depending user requested language, backend routes etc... So maybe updating this value change the default one ? But why only if I cache the config ? 

Thanks !

**Comment by rscotten** [comment]
I have this same problem.  Route and config caching don't work for me when using localization.

**Comment by alifattahi** [comment]
I have the same problem...
