### ISSUE TITLE
Set default language from database instead of config/app.php

### ISSUE THREAD

**Issue by aghayeff** [mcamara/laravel-localization#471]
Hi. I am using this package for a long time. I know that this package chooses default language from `config/app.php`. 

The website was built with multiple language: en, ru, tr. Default language in `config/app.php`.  is `en`.

So, using `www.site.com` this displays the website into English language. It is perfect.

However, the owner of the website sometimes want to set default language from his admin panel. I have created a middleware, something like this:

```
 class SetLocale
{

    public function handle($request, Closure $next)
    {
        $config = Config::first();

        app()->setLocale($config->lang_id);  // I set it into ru language

        return $next($request);
    }
}
```
After this middleware, when I try to open an url: `www.site.com`, it is redirected to`ru` language. I am looking for the way to make it without redirection. Except this one, when I am entering the url, which had been set a default language from `config/app.php`, it is also redirected to `ru` language.

I tried to use `LaravelLocalization::setLocale($locale)` it didn't work.

**Comment by lucasff** [comment]
You need to use both `App::setLocale()` and `LaravelLocalization::setLocale()`

**Comment by iwasherefirst2** [comment]
If you use `useAcceptLanguageHeader` then the locale will be detected by the browser. If no matching locale is found, then the default locale from `config/app` is used. 

So if you asking how to switch default locale, do you mean the above behavior? If so, you would need to create the functionality to rewrite the config file and re cache.

If your question is how to switch the language, then its simply be accessing the url with locale, so `www.site.com/en` switches to English and `www.site.com/ru` switches to Russian.
