### ISSUE TITLE
The requested URL /en was not found on this server.

### ISSUE THREAD

**Issue by brada1703** [mcamara/laravel-localization#473]
Hi guys,

I'm deploying my first laravel app with laravel-localization. Unfortunately, I am currently getting the error, 

> Not Found
> 
> The requested URL /en was not found on this server.
> 
> Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

I have searched the web trying to find others who had the same problem and see if they had a viable solution for me. I found at least [one](https://www.munderwood.ca/index.php/2016/03/16/testing-routes-with-laravel-localization/#comment-1602), but it looks like he wasn't able to solve it either.

When I change  (in the config/laravellocalization.php file)
`    'hideDefaultLocaleInURL' => false,`
from False to True
`    'hideDefaultLocaleInURL' => true,`
I can see the homepage, but only that. All other pages are redirected to the 404 error.

I have also changed the index.php file to reflect my folder structure as the public folder for this site is within a folder within the public_html folder:

```
require __DIR__.'/../../myapp/bootstrap/autoload.php';
$app = require_once __DIR__.'/../../myapp/bootstrap/app.php';
```

Note: everything worked on my localhost. There seems to be a problem in deployment.

Any idea what the problem could be? 

I appreciate all ideas, comments, and criticism. 👍

**Comment by lucasff** [comment]
Are you using cPanel?

**Comment by hugofabricio** [comment]
I am having the same problem, when redirecting to the directory, of error 404

**Comment by coppee** [comment]
Someone found a solution ?

**Comment by viewplatgh** [comment]
I was hit by this issue too, and I solved it.
The solution to me is to change the nginx config, not to use the default one but refer to this one: https://github.com/laradock/laradock/blob/v5.9.0/nginx/sites/default.conf

**Comment by tylerteh** [comment]
I encountered the same issue and I solved it by following the suggestion at:
[https://stackoverflow.com/questions/45105261/laravel-localization-deployment-the-requested-url-en-was-not-found-on-this-se/47528589#47528589](https://stackoverflow.com/questions/45105261/laravel-localization-deployment-the-requested-url-en-was-not-found-on-this-se/47528589#47528589)

**Comment by iwasherefirst2** [comment]
> Note: everything worked on my localhost. There seems to be a problem in deployment.

Are you automatically using cache in deployment? For LaravelLocalization you need to use 

    php artisan route:trans:cache

instead of 

    php artisan route:cache


See [docs](https://github.com/mcamara/laravel-localization/blob/master/CACHING.md) for more.

**Comment by iwasherefirst2** [comment]
Closing this as it was probably a caching issue
