### ISSUE TITLE
findTranslatedRouteByUrl doesn't work on utf-8 paths because it compares urlencoded and non-urlencoded paths

### ISSUE THREAD

**Issue by jnvsor** [mcamara/laravel-localization#475]
The `$this->getNonLocalizedURL($routeName) == $this->getNonLocalizedURL($url)` condition in the if on line 670 doesn't work for UTF-8 routes, since they are likely to end up urlencoded. You should compare both `$url` and `urldecode($url)` to `$routeName`.

Since `findTranslatedRouteByUrl` is called by `getLocalizedUrl` it can be an issue.

**Comment by lucasff** [comment]
should use `mb_*`?

**Comment by jnvsor** [comment]
No, I mean if you have a path `/véhicule` then `$this->getNonLocalizedURL($routeName)` will equal `/véhicule` and `$this->getNonLocalizedURL($url)` will equal `/v%C3%A9hicule`
