### ISSUE TITLE
Small spelling error in config file

### ISSUE THREAD

**Issue by BonBonSlick** [mcamara/laravel-localization#476]
`        'jp'          => ['name' => 'Japanese',               'script' => 'Jpan'`

also
`zh'          => ['name' => 'Chinese (Simplified)',  ` i think should be **cn**, according to 
https://en.wikipedia.org/wiki/Country_codes:_C#.C2.A0China

**Comment by fisharebest** [comment]
`ja` is the Japanese language.
`jp` is the country Japan.

`zh` is the Chinese language.
`cn` is the country China.

I think these are correct.

**Comment by BonBonSlick** [comment]
If this way, you are right, but i want to notice that:
steamdb.info, steam api calls, and other many websites use **cn/jp** modificators. Some  use something like that **/?___store=japanese**  or else, it seems it prefered. 
Thanks anyway for good package.
