### ISSUE TITLE
Bug getURLFromRouteNameTranslated

### ISSUE THREAD

**Issue by dhiman252** [mcamara/laravel-localization#479]
Since the function make use of the laravel's translator's `trans` function it just supply the wrong list of parameters. see the Image attached.
![screenshot_5](https://user-images.githubusercontent.com/8954468/29398004-89fc218e-833f-11e7-87d1-b8caf17871c1.png)

The problem is that it supplies the wrong list of arguments so the URLs are not translated

**Comment by andrelegault** [comment]
You're using Laravel 5.3 whose `trans ` function has [4 parameters](https://github.com/illuminate/translation/blob/6c56cc0c319bb932e7bdaeaed0c4a3f6befbb37f/Translator.php#L235). The package assumes its users are using Laravel 5.4 which, in this version, has [3 parameters](https://github.com/illuminate/translation/blob/1fdf763ab7f07319752541ba13d1c4a450d88365/Translator.php#L99).

**Comment by dhiman252** [comment]
I am using the laravel version 5.2.*

**Comment by dhiman252** [comment]
In the documentation it is also provided to make use of version 1.2 if using the laravel 5.2

**Comment by ilgala** [comment]
**Tell me if I have to open a new issue**

This function doesn't care about route prefixes. And I was wondering how from a default route with prefix get the correct translation. For example, I have a route like this:

`http://my.app/{locale}/{admin_prefix}/my_admin_route`

but when I use this method I receive back this URL:

`http://my.app/{locale}/my_translated_admin_route`
