### ISSUE TITLE
Route not defined

### ISSUE THREAD

**Issue by BrunoMCTeixeira** [mcamara/laravel-localization#480]
**Routes**
`Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
], function()
{
	Route::get(LaravelLocalization::transRoute('routes.categories'), 'CategoryController@index');
});`

Blade
`<a href="{{ LaravelLocalization::getLocalizedURL(LaravelLocalization::getCurrentLocale(), route('routes.categories')) }}"></a>`

{lang}/routes.php
`return [
	"categories" 	=> 	"categories",
];`

Gives me 'Route ... not defined'

**Comment by KaiserFrederick** [comment]
First my English is bad hehe but, You need to put in your routes like the next code:
`Route::get(LaravelLocalization::transRoute('routes.categories'), 'CategoryController@index')->name('categories') ;`

Next in your Blade you have to put this:
`<a href="{{ route('categories') }}">{{ trans('routes.categories) }}</a>`

And that's all, LaravelLocalization it's going to do the else.
You don't need to put the LaravelLocalization in your links in Blade, only put the name of the route.
