### ISSUE TITLE
Post method not working

### ISSUE THREAD

**Issue by harunB10** [mcamara/laravel-localization#483]
I have a post method which returns error "Method not allowed" when it is selected with prefix /en/myRoute or /de/myRoute... Since my default language is english, I can hide "en" prefix to be just /myRoute, and it works, but the problem rermains with /de/ and other language prefixes...

**Comment by KrisBobLea** [comment]
It became a get method after redirection.

**Comment by harunB10** [comment]
How can I "force" it not to become GET?

**Comment by Datalink-Wouter** [comment]
I think the easiest solution is naming your routes.
https://laravel.com/docs/5.5/routing#named-routes

If you call {{route('your-route')}} in the form action, you won't redirect because the language would stay in the URL.

**Comment by harunB10** [comment]
Works fine! Thx!

**Comment by baltun** [comment]
is it possible to automatically exclude any other than GET methods urls from middlewares to not do anything with these kinds of urls?
