### ISSUE TITLE
Make prefix language always show even if i remove from url

### ISSUE THREAD

**Issue by marcelosantos89** [mcamara/laravel-localization#484]
Is it possible to make the prefix always show ... lets say i'm at page example.com/en and i change it to example.com/pt it translate to pt but if i put the url example.com/ it should work how can i make this happen ? cause if people can access the page via example.com/ my $request()->segment(2) sometimes wont work

**Comment by balakan** [comment]
In laravellocalization.php config file there is a 'hideDefaultLocaleInURL' key. Set it to false (by default). It should work?

**Comment by iwasherefirst2** [comment]
Disable `hideDefaultLocaleInURL` and use redirect middleware.
