### ISSUE TITLE
Class 'App\Providers\LaravelLocalization' not found

### ISSUE THREAD

**Issue by CicciMTS** [mcamara/laravel-localization#485]
Hello to everybody, i'm newbie in laravel so be patient please. 
I've installed the packpage with command `composer require mcamara/laravel-localization`, configured `config/app.php` with providers and aliases, but when i run the application i have a fatal error:
`FatalThrowableError
Class 'App\Providers\LaravelLocalization' not found`

Same error appears when i attempt command `php artisan serve`. The folder mcamara is present in vendor and when i remove the prefix 
`['prefix' => LaravelLocalization::setLocale()]`
the application run fine.

I'm using laravel 5.4, can someone help me?

**Comment by lucasff** [comment]
your entry for the path of the provider is wrong... also

**Comment by leMaur** [comment]
Hi @CicciMTS,
try to import the facade on top of your routes.php file, like this:
```
<php

use \Mcamara\LaravelLocalization\Facades\LaravelLocalization;

... the rest of the code ...
```
or you can try to call the facade name with path like this:
```
['prefix' => \Mcamara\LaravelLocalization\Facades\LaravelLocalization::setLocale()]
```
This should resolve your issue!

Sometimes happens that the alias is not well loaded at first installation time.

By the way, it's always good to double check the installation files. 
Check this paragraph: https://github.com/mcamara/laravel-localization#installation and to be sure, try to run `$ composer dump-autoload` from your terminal (or Cmd), this reload the autoloader collection.

Hope this help you. 
Bye

**Comment by CicciMTS** [comment]
Thank you! That's worked for me! It was the use of facade.
