### ISSUE TITLE
Wrong url back to the original language

### ISSUE THREAD

**Issue by luisdiaswiz** [mcamara/laravel-localization#487]
I am having an issue in a project i am working on:

When in a page in a language(default), the link to the english route is correct [siteUrl]/en/brand/7/[brandName], however, when in the english page, the route back to the original language is incorrect ([siteUrl]/marca//7/[brandName]), it comes with "//" before a param.

I have many other translated routes in this site and this only happens with this one. I have checked the routes and controllers and everything seems ok and consistent with all the other routes. The template that displays the language switcher is always the same and works for everypage with the exception of this one.

We are using Laravel 5.3 and laravel localization 1.1.12.

Can you provide some insight on why this may be happening?

Thanks in advance,

Luis Dias

**Comment by iwasherefirst2** [comment]
Do you still have this issue?

**Comment by iwasherefirst2** [comment]
Closing is because I assume its outdated.
