### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by valh1996** [mcamara/laravel-localization#488]
Hi,

Is an update planned for laravel 5.5 please :) ?

Best regards,

**Comment by nWidart** [comment]
You can install it on 5.5.

However, I'm having issues where cookies aren't stored. I'm thinking it might be related to this package somehow.

**Comment by n00el** [comment]
I get this message with this package in laravel 5.5 
`ErrorException (E_ERROR)
array_merge(): Argument #2 is not an array 
`

Bold lines are errors in this file:
/var/www/laravel/vendor/laravel/framework/src/Illuminate/Translation/FileLoader.php
`    protected function loadJsonPaths($locale)
    {
        return collect(array_merge($this->jsonPaths, [$this->path]))
            ->reduce(function ($output, $path) use ($locale) {
                return $this->files->exists($full = "{$path}/{$locale}.json")
                    **? array_merge($output,
                        json_decode($this->files->get($full), true)
                    ) : $output;**
            }, []);
    }
 `

Any future plan to update package to Laravel 5.5? It work really well in 5.4, and I love it :)

**Comment by mcamara** [comment]
The master branch (and 1.3.1 release) should fix all problems with Laravel 5.5.

Thanks all for your help!
