### ISSUE TITLE
Loading content with ajax, loads old, previous local langugage.

### ISSUE THREAD

**Issue by PhPPgAdminBug** [mcamara/laravel-localization#496]
3 controllers.
1 - st loads page
2 - loads more content to page with ajax request
3 - draws, builds html of content.  

In second  controller we can get locale this way
` $locale = new LaravelLocalization();
  $localLang = $locale->getCurrentLocale(); // ru
 $localLangAPP = App::getLocale() // en
`

but ` Lang::get('general.word')` will return  word in `$localLangAPP`  language **en**.
if we try to set language, it will load different ways in 3-d controller. Like we set english, it loads ru, we set de, it loads ru, we set ch, it loads de and so on.

Main issue, when loading through ajax, in controllers there is default language "en", not from `$locale->getCurrentLocale()` so all localization will be in **en**, not **ru**

` 'hideDefaultLocaleInURL' => false,`
does not helped.

Possible issue is [here](https://stackoverflow.com/questions/38229369/why-is-laravels-appgetlocale-method-inconsistent), that our post Route:: is not in that middleware, but if we get route to middlewares from package, we got error, because url changes from `domain.com/more/content` to `domain.com/ru/more/content`, that /ru/ prefix fails post request.

` Route::group(['middleware' => ['localeSessionRedirect', 'localizationRedirect'], 'prefix' => LaravelLocalization::setLocale()], function () {
            Route::post('more/content', LoadMoreController@func')->name('more_content');
        });`

**Error**

`
 MethodNotAllowed
`
Because route prefixex  and method due to this middlewares `'localeSessionRedirect', 'localizationRedirect' ` has changed

Yup, question from stack with this middleware helped a lot. I think you should add to your package.
My code:
`class LocalizationPostRequests
{
    public function handle($request, Closure $next)
    {
        App::setLocale(Session::get('locale'));
        return $next($request);
    }
}`

Only for **POST** requests, because GET requests work fine with App::getLocale(), but in POST we must pass our current locale.

**Comment by iwasherefirst2** [comment]
We have this issue now marked in the [docs](https://github.com/mcamara/laravel-localization#common-issues).

We cannot skip `POST` request in middleware, because there are use-cases where post should be localized. 

If you don't want your post route to be redirected, you can instead move it outside the `Route::group`
