### ISSUE TITLE
I want the feature for each country language change 

### ISSUE THREAD

**Issue by techpoints** [mcamara/laravel-localization#499]
Hello

I want select country like USA, Spanish
and I want the feature for each country a change language "english (EN) and Spanish (ES)"

like this url
http://domain.com/en/es

I know there is a method currently available
http://domain.com/en-es
http://domain.com/es-es

But in the show
Not a good idea

Spanish EN
Spanish ES
USA EN
USA ES

in another meaning
I want languages independent from the Countries

:)

**Comment by iwasherefirst2** [comment]
This package only supportes locales. There are some locales coupled with countries, if there exists different versions of the locale. Like British, Australian and US- English. But what is Spanish-English? This locale does not exist.

If you want to couple countries with English & SPanish, simply and the countries to your `Route::group`.
