### ISSUE TITLE
Disable negotiator

### ISSUE THREAD

**Issue by Chrysanthos** [mcamara/laravel-localization#500]
Is there any way to disable the negotiator?

It seems like it overrides my default locale when the browser is in a secondary locale. 
For example, if my default locale is Spanish but the browser is in English, the site is displayed in English instead. (Both in the supported Locales btw)

I want to force the locale to Spanish always unless the user changes it himself.

**Comment by mcamara** [comment]
There is an option in the config file for this: https://github.com/mcamara/laravel-localization/blob/master/src/config/config.php#L302
