### ISSUE TITLE
The `localize` middleware is registered but not being used

### ISSUE THREAD

**Issue by grrnikos** [mcamara/laravel-localization#501]
On the _Middleware_ section of the `README.md` file, we register 4 route middleware:
```php
protected $routeMiddleware = [
  /**** OTHER MIDDLEWARE ****/
  'localize' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
  'localizationRedirect' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
  'localeSessionRedirect' => \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class, 
  'localeViewPath' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationViewPath::class
  // REDIRECTION MIDDLEWARE
];
```

But then in `routes/web.php` we only use 3 of them:

```php
Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
```

Is the `localize` middleware optional, or just omitted by fault?

**Comment by Sebi94nbg** [comment]
I read it as it is applied by default:

> Moreover, this package includes a middleware object to redirect all "non-localized" routes to the corresponding "localized".

**Comment by iwasherefirst2** [comment]
Its only required if you use [translatable routes](https://github.com/mcamara/laravel-localization#translated-routes). All middlewares are optional.
