### ISSUE TITLE
Issue with translated URL with parameter

### ISSUE THREAD

**Issue by latiosaxe** [mcamara/laravel-localization#504]
Hello, I'm usin laravel-localization and everything is working great, excepet with urls translated with parameters.

For example, if I Use /about it works with /acerca
en/about
es/acerca

Nice!!, the problem comes when I use 'studio/{slug}" and "estudio/{slug}", in english I get
/en/studio/asdf which is fine but in spanish is /es/estudio/{slug}, as did not read the parameter.

I'm printing the anchor like this:

`<p><a href="{{ LaravelLocalization::getLocalizedURL(null, LaravelLocalization::transRoute('routes.studio'), ['slug' => 'asdf'])       }}">{{ __("home.Studio") }}</a></p>`

Can you guys help me please?

Thank you!!

**Comment by iwasherefirst2** [comment]
You have to put the slug in `routes.php`: https://github.com/mcamara/laravel-localization/issues/502#issuecomment-546670758
