### ISSUE TITLE
Language negotiation does not support the standard format for country codes (hyphen)

### ISSUE THREAD

**Issue by erdmenchen** [mcamara/laravel-localization#506]
Browsers usually send the Accept-Language-Header with country code in the hyphen notation e.g.  `de-DE`, but the language negotiator only matches against `de_DE` in the current version of the config file.

https://github.com/mcamara/laravel-localization/blob/bafd681d717d1ad28e0ba7afa745590956c0c53c/src/Mcamara/LaravelLocalization/LanguageNegotiator.php#L63

In the current version of the config file all country aware languages are formatted with the underscore character.

https://github.com/mcamara/laravel-localization/blob/bafd681d717d1ad28e0ba7afa745590956c0c53c/src/config/config.php#L38

This results in a bad match and the requested language `de-DE` is not set because it does not match `de`  and it does not match `de_DE`.

**Comment by ansata2001** [comment]
Also, there is no the "lang" property in any line of the the bundled config.php https://github.com/mcamara/laravel-localization/blob/master/src/config/config.php although the languageNegotiator is trying to check if it matches with the key. Maybe it makes sense to to add the "lang" property on the fly when doing the negotiation, taking the Locale::canonizalize() of the key? If the property is not set manually.

**Comment by ansata2001** [comment]
There was an accepted pull request addressing this issue: https://github.com/mcamara/laravel-localization/pull/507

**Comment by erdmenchen** [comment]
Thank you very much @ansata2001. 
I have not yet tested your fix, but it looks promising what I see in the pull request.
