### ISSUE TITLE
Performance comparision hideDefaultLocaleInURL and not

### ISSUE THREAD

**Issue by hoangnguyen291** [mcamara/laravel-localization#508]
Hi, I'm facing problem with the czim cache, I have checked sample project with and without route cache, sometimes cached run faster but sometimes without cache run faster, does anybody try czim cache and does it really help?

![image](https://user-images.githubusercontent.com/26863160/32639587-313b8058-c5f7-11e7-84f4-cd9b8d284987.png)
left: without cache - right: with cached

**Comment by iwasherefirst2** [comment]
czim cache is now build in and has been updated recently. How many routes did you specify in your tests? And how is that related with `hideDefaultLocaleSetting`?

**Comment by iwasherefirst2** [comment]
Czim cache is a build-in package that makes it possible to cache routes (without the package, caching would not be possible). It only effects if you have a lot of routes. Route caching is known for increasing the performance up to 100x (see https://voltagead.com/laravel-route-caching-for-improved-performance/ for example).
