### ISSUE TITLE
Change locale in controller or middleware using database entry

### ISSUE THREAD

**Issue by Sebi94nbg** [mcamara/laravel-localization#509]
Hey,
my users can save their favourite language / locale code in the database. In case, if they update it from 'en' to 'de' for example, I would like to change the applications language.

Here is my controller:
```
<?php

namespace App\Http\Controllers\Customer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Auth;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

class AccountController extends Controller
{
	public function updateAccount(Request $request)
    {
        if(!User::where('id', '=', Auth::user()->id)->update(['language' => $request->language,])) {
            return redirect()->route('dashboard')->with('status', "Your settings could not be updated. Please contact an administrator.");
        }
        
        LaravelLocalization::setLocale($request->language);
        
        return redirect()->route('dashboard')->with('status', "Your settings were updated.");
    }
}
```

Unfortunately it doesn't change the language.

From your documentation:

> This function will change the application's current locale. If the locale is not passed, the locale will be determined via a cookie (if stored previously), the session (if stored previously), browser Accept-Language header or the default application locale (depending on your config file).
> 
> The function has to be called in the prefix of any route that should be translated (see Filters sections for further information).

Due of that, I've created a middleware, which also doesn't change the language:
```
<?php

namespace App\Http\Middleware;

use Closure;
use App\User;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

class SetLocaleFromDatabase
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $localeCode = User::where('id', '=', Auth::user()->id)->pluck('language')->first();
        
        app()->setLocale($localeCode);
        LaravelLocalization::setLocale($localeCode);

        return $next($request);
    }
}
```

What exactly does "has to be called in the prefix of any route" mean? Any ideas for a solution?

**Comment by Sebi94nbg** [comment]
Does really nobody have any idea? :(

**Comment by dreamid27** [comment]
The problem is with your cookie,,

you active 2method database and cookie....
and your locale, override with cookies, 

you have to deactive cookies in Middleware..

**Comment by dreamid27** [comment]
Can i see your route with middleware ?
