### ISSUE TITLE
Translate current route on all available/support languages

### ISSUE THREAD

**Issue by onward-web** [mcamara/laravel-localization#510]
I did not find a method by which I can get the current router / url on all available languages. Is there such a realization in the plans. This would be very handy when deriving, for example in the Language Switche widget.

For example:
`<ul>
<li><a href = "http://example.com/en/page1">English</a></li>
<li><a href = "http://example.com/es/page1">Spain</a></li>
<li><a href = "http://example.com/de/page1">German</a></li>
</ul>`

**Comment by iwasherefirst2** [comment]
We have a snippet for exactly this purpose [here](https://github.com/mcamara/laravel-localization#creating-a-language-selector)
