### ISSUE TITLE
Website not change to second language if we redirect from website

### ISSUE THREAD

**Issue by dreamid27** [mcamara/laravel-localization#511]
Hi, thank for the awesome Composer..

but i have problem, when i apply in my project..
i apply two localization English and Indonesia, ...

![image](https://user-images.githubusercontent.com/22621375/33411606-2cc4dcd2-d5b9-11e7-99d8-700718b3f715.png)
default language

i'm type to browser url,, like : http://mywebsite.com/id ,, that's good work ! 
![image](https://user-images.githubusercontent.com/22621375/33411745-d833489c-d5b9-11e7-9c55-0c35865c4f59.png)

but if i click in tag or redirect in website, from english to Indonesia, that's not work 
![image](https://user-images.githubusercontent.com/22621375/33411638-532df976-d5b9-11e7-8bfd-c7e17b3e8af6.png)

i'm need refresh to get the effect  language,, 

but if i convert from indonesia to english,, that's work..

you have solution ?

Thanks Brother .

**Comment by Sebi94nbg** [comment]
Which code do you use to switch the language?

In this projects README.md, you can find a sample code for a language switcher, which is just working out of the box, when you've configured everything like Middlewares correct: https://github.com/mcamara/laravel-localization#creating-a-language-selector

So, in your case, you need something like this:
```
<a rel="alternate" hreflang="id" href="{{ LaravelLocalization::getLocalizedURL("id", null, [], true) }}">Bahasa Indonesia</a>
|
<a rel="alternate" hreflang="en" href="{{ LaravelLocalization::getLocalizedURL("en", null, [], true) }}">English</a>
```

When you hit one of these links, `laravel-localization` does automatically apply the selected language to your application. You don't have to refresh the page after it, because the language switch happens in the middleware, so even before you're redirected to the page.

**Comment by dreamid27** [comment]
i just follow the instruction, and this is my code for get localization.. tell me if i wrong :) .. thank brother.

![image](https://user-images.githubusercontent.com/22621375/33421577-163676b6-d5e5-11e7-9116-eeb21133a880.png)

**Comment by dreamid27** [comment]
@Sebi94nbg i try same trick and code in my new project,.. and not problem..hahaha..

maybe something wrong with project or composer and make conflict ?

**Comment by Sebi94nbg** [comment]
Did you configure the Middlewares? https://github.com/mcamara/laravel-localization#middleware

Instead of `app/Http/routes.php` it's maybe `routes/web.php`. Depends on your Laravel version.

**Comment by Sebi94nbg** [comment]
You also need to configure them in your `app/Http/Kernel.php` at `protected $routeMiddleware`. Did you?

**Comment by dreamid27** [comment]
@Sebi94nbg 
![image](https://user-images.githubusercontent.com/22621375/33429363-26d298aa-d5ff-11e7-979d-fdf9f95455a0.png)

sure brother :) ..
i'm sure not skip anything the tutorial..

**Comment by dreamid27** [comment]
![image](https://user-images.githubusercontent.com/22621375/33429955-438c3a94-d601-11e7-86d4-88041d759220.png)

i try to change position like , you say, but issue still going.  .. but thank :)

**Comment by Sebi94nbg** [comment]
No problem. I'm familiar with your English - I have colleagues in Kathmandu. ;)

@dreamid27 please take a look at my last mentioned example how it looks like in my case. This is, how it should look like for you.

// Ok, you changed it. :D

Is it maybe cached?

```
php artisan clear-compiled
php artisan cache:clear
php artisan route:clear
```

**Comment by dreamid27** [comment]
![image](https://user-images.githubusercontent.com/22621375/33430262-881bf9be-d602-11e7-93ed-22dfed0edeb5.png)
Ohh haha okey..

I try to clear cache, but hehehe still going..

**Comment by dreamid27** [comment]
you know what different if i type in browser address and if i click on tag <a href="blabla.com">

maybe i think need to know how this work in laravel.. and maybe i can find where this mistakes...

**Comment by Sebi94nbg** [comment]
You can check, if it's even changing your locale.

Just add this code to your view:
`{{ LaravelLocalization::getCurrentLocale() }}`
This should return `id` or `en`.

When you switch to `EN`, it should display `en` for example.

Does it always return the correct one? If yes, it's working fine and you may have a different issue.

**Comment by dreamid27** [comment]
@Sebi94nbg i think not problem about that,,

i get mywebsite/en and mywebsite/id when i change localization..

**Comment by dreamid27** [comment]
@Sebi94nbg thanks brother,  this is fix :) ..

not problem in composer, but problem with my Custom Middleware make this happen !

![image](https://user-images.githubusercontent.com/22621375/33537876-b4f51fe2-d8f0-11e7-957b-b199fccaee9e.png)

**Comment by mikepgc** [comment]
@dreamid27 

I got the same problem, How is you file looks like?
