### ISSUE TITLE
laravel-localization and translated slug stored in database

### ISSUE THREAD

**Issue by Jimmylet** [mcamara/laravel-localization#512]
Hello all ! 

I try to make a multilingual laravel. To do this, I use :

 - **[spatie/laravel-translatable][1]** to store my translation data in the same column under a JSON array
 - **this package** to define my translatable routes.

My slugs are translated and stored in database as follows:

    {
       "fr": "a-propos",
       "en":"about"
     }

And all my other translatable data are also like that. And to access one of my data, I use for example, `$page->slug` or `$page->title`.

My translations work well. But now, I'm trying to build a menu of languages with the right URLs.

I want, if I am on the page "about" have two links in the menu :

 - `http://myapp/en/about`
 - `http://myapp/fr/a-propos`

Here is my code :

    <ul>
    	@foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
    		<li>
    			<a rel="alternate" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getURLFromRouteNameTranslated($localeCode, $page->slug, [], true) }}">
    				{{ $properties['native'] }}
    			</a>
    		</li>
    	@endforeach
    </ul>

Unfortunately my urls are bad. If I am on the page "about" in English I have in my menu :

 - `http://myapp/en/about`
 - `http://myapp/fr/about`

And I would like `http://myapp/fr/a-propos`. The data is stored in my database. 

Is there a way to make sure to collect data from other languages while in a different locale (here I am in EN and I would like to have the slug FR).

Can you help me ? Thank you very much !

  [1]: https://github.com/spatie/laravel-translatable/
  [2]: https://github.com/mcamara/laravel-localization

**Comment by ardiwirawan** [comment]
@Jimmylet have you found the solution about this question?  i also search the solution, im facing same issue with you.

**Comment by martin-ro** [comment]
I'd be interested in a solution as well.

**Comment by simar88** [comment]
Any news about it? :)

**Comment by indecenti** [comment]
I'm also facing the problem, and I solve with escamotage but I do not find a correct and sensible way to proceed. Can someone help us?

**Comment by iwasherefirst2** [comment]
Its already a build in feature. If you want instead of `http://myapp/fr/about` the translated route `http://myapp/fr/a-propos` then just define them in  `/resources/lang/fr/route.php` as explained at https://github.com/mcamara/laravel-localization#translated-routes . If your translated routes are stored in DB or json doesn't matter, you can just iterate them whereever they come from with PHP and add to your array.

**Comment by indecenti** [comment]
in the routes.php file in the lang folder:
return [
     'prodotti_with_slug' => 'products / {category} / {slug}',
];
Slug is in the database table called products where I have the slug in one language.
Category is in the category table where I have the slug of the category both in Italian and in English.
How can I translate category when I'm in a route products / category_1 / product_1.
the problem occurs when from the 
products/category_1/ product_1
route I pass to the italian version or vice versa and macamara translates
prodotto/category_1/product_1

thank you

**Comment by iwasherefirst2** [comment]
You have to write in /en/routes.php 
```

return [
     'prodotti_with_slug' => 'products / {category} / {slug}',
];
```

And in in /it/routes.php 
```

return [
     'prodotti_with_slug' => 'prodotto / {category} / {slug}',
];
```

In your App/route/web.php your need something like this:

```
Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localize' ] // Route translate middleware
],
function() {
	/** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
		Route::get(LaravelLocalization::transRoute('prodotti_with_slug'), 'ProductCategoryController@index');
```

**Comment by uaibo** [comment]
@iwasherefirst2 that's ok for the fixed part of the url that in this case is "products" or "prodotti" but what about translating the {category} and {slug} as well? That's what I'm trying to achieve (and I think that's the original question here as well).

So for English we need to have 
/products/english-category-name/english-slug-name
and for French will have 
/products/french-category-name/french-slug-name

translated category names will need to be saved in DB. 
I've tried several ways with relative success but not a complete robust solution yet. Any suggestion?

**Comment by iwasherefirst2** [comment]
@uaibo the case for translating {category} and {slug} is working perfectly fine and is document in the docs here: https://github.com/mcamara/laravel-localization#translated-routes

At the end of the docs, I have even linked to a video where I explained step by step how to set it up: https://www.youtube.com/watch?v=B1AUqCdizgc&feature=youtu.be

**Comment by uaibo** [comment]
@iwasherefirst2 thanks, I hadn't noticed the video link and couldn't clearly understand how to implement those methods. After watching the video I was able to make translatable url slugs (stored in db) and also translatable content (other content fields) with the help of https://github.com/astrotomic/laravel-translatable 

So it's perfectly fine now. Thanks.

> @uaibo the case for translating {category} and {slug} is working perfectly fine and is document in the docs here: https://github.com/mcamara/laravel-localization#translated-routes
> 
> At the end of the docs, I have even linked to a video where I explained step by step how to set it up: https://www.youtube.com/watch?v=B1AUqCdizgc&feature=youtu.be

**Comment by iwasherefirst2** [comment]
Awesome!

Altin <notifications@github.com> schrieb am Di., 4. Feb. 2020, 03:11:

**Comment by temo-redberry** [comment]
@uaibo How did you solve the language switcher issue?
For example:
If there are routes like:
`/en/article/{english-slug}`  ID in DB = 1
`/fr/article/{french-slug}` ID in DB = 1

When I click to change language from English to French only the `en` changes to `fr` not the {slug}
