### ISSUE TITLE
Problem with switching to default locale with hideDefaultLocaleInURL = true

### ISSUE THREAD

**Issue by Briareos17** [mcamara/laravel-localization#513]
When I trying to change locale to default one, nothing happens, I just staying at current locale.
My default language: ru
switch url is: website.loc/ru|en|uk

**Comment by andrii-trush** [comment]
Have the same issue

**Comment by andrii-trush** [comment]
@Briareos17  look at #439

**Comment by zeravcic** [comment]
Hi,

I looked at #493 (the last entry on Dec 21, 2017) but it seems that there is some serious SEO problem...I would ask for comment please, I'm sorry if I'm wrong.

### Environment
- [Laravel Framework v5.8.28](https://github.com/laravel/framework/tree/v5.8.28) (fresh Laravel installation),
- [mcamara/laravel-localization 1.3.20](https://github.com/mcamara/laravel-localization/tree/1.3.20)

### Description
For example, it looks like scary if Google recognize sometimes 302 redirection from Homepage, but sometimes not. User unequivocally must be sent on the requested page. It seems wrong if I have to call default locale (server return 302 redirection) to move in default content.

What if I looked `/es/contact-me` page and then someone send me e-mail with `/contact-me` link (eg. default hidden locale 'EN')? I will be redirected (302!) immediately at current locale page version...but `/contact-me` page can hold an ABSOLUTELY different type of data, different content (eg, for specific country and I have to see exactly that information)...

Plus, it seems much more serious problem if Google recognize user(s) whom request sometimes return content (200) but sometimes return redirection (302) - if he/she just simple put custom string inside browser URL field.

Yea, I think you should leave on developers to implement business logic...?
