### ISSUE TITLE
language selector

### ISSUE THREAD

**Issue by mikepgc** [mcamara/laravel-localization#514]
Hi, 

I have to click 2 time to get on the right language. is this common issue?

<ul>
    @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
        <li>
            <a rel="alternate" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
                {{ $properties['native'] }}
            </a>
        </li>
    @endforeach
</ul>

also is it possible to create a link manually? 
href to: locale 'en'
href to: locale 'de'

so I can put it in a dropdown list. 

thanksssss

**Comment by balakan** [comment]
Try using the getLocalizedUrl() method... like this:
{{ url(LaravelLocalization::getLocalizedURL($localeCode)) }} on your href attribute.

**Comment by mikepgc** [comment]
thankss @balakan 

do you know also the issue that you have to refresh to get on the right locale?

**Comment by dreamid27** [comment]
@mikepgc u mention me ?

**Comment by johnef** [comment]
@balakan what if I don't want drop down list of languages I just need the <li>English</li> or <li>Arabic</li>
thanks

**Comment by mams2002** [comment]
use following :          
   <div class="hidden fixed top-0 right-0 px-3 py-4 sm:block">
                @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                    <li><a rel="alternate" hreflang="{{ $localeCode }}" 
                             href="{{LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
                            {{ $properties['native'] }}
                        </a>
                    </li>
                @endforeach
            </div>

**Comment by mams2002** [comment]
<div class="hidden fixed top-0 right-0 px-3 py-4 sm:block">                @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)<li><a rel="alternate" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}"> {{ $properties['native'] }}</a></li>@endforeach </div>

**Comment by mams2002** [comment]
`            <div class="hidden fixed top-0 right-0 px-3 py-4 sm:block">
                @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                    <li>
                        <a rel="alternate" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
                            {{ $properties['native'] }}
                        </a>
                    </li>
                @endforeach
            </div>`
