### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by johnef** [mcamara/laravel-localization#516]
I am using the package with laravel 5.4
installed the package, added the providers, aliases 
setup my group (`Route::group(['prefix' => LaravelLocalization::setLocale()], function()`)
and even added my `Middleware` 
but not working with me
I try patch/en --> working
Try path/ar --> `Sorry, the page you are looking for could not be found.`
do I miss something here

**Comment by dreamid27** [comment]
maybe u skip this part.

![image](https://user-images.githubusercontent.com/22621375/34379506-21e2d79e-eb2e-11e7-97ef-45bdb899a2ff.png)

**Comment by dreamid27** [comment]
u need uncomment,, part of 'ar' in that's files.

**Comment by dreamid27** [comment]
or This @johnef 

![image](https://user-images.githubusercontent.com/22621375/34379578-7e665644-eb2e-11e7-862a-4a78e4eb3107.png)

**Comment by dreamid27** [comment]
in Vendor->Mcamara

**Comment by johnef** [comment]
@dreamid27  thanks very much it helped

**Comment by mcamara** [comment]
@dreamid27 never never never change the config file inside the package, it will cause problems when the packages is updated or it will be overwritten. (And it's usually ignored by control version system).

You should run 
`php artisan vendor:publish --provider="Mcamara\LaravelLocalization\LaravelLocalizationServiceProvider"
`, it will create a new config file in your own folder. This should be the file to edit for your own project.

Hope it helps.

**Comment by dreamid27** [comment]
@mcamara ahh i'm so sorry, i'm not read fully the tutorial..

for suggestion, i think you need change part tutorial of 'Config' to the top. it will be easy to read.
