### ISSUE TITLE
how to change default language

### ISSUE THREAD

**Issue by whyrukter** [mcamara/laravel-localization#519]
Hi,
 
My website have two languages are Thai and English. it's working.
when i enter url http://project.test.local and then url change to http://project.test.local/en 

i'd like to change default en to th  

My config/app.php  
`'locale' => 'th',
'fallback_locale' => 'th',`

My route
`<?php
Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function()
{
	
	Route::get('/', function()
	{
		return View::make('auth.login');
	});

});
?>`

Please help.

Thank you.

**Comment by dehumanise** [comment]
just set the this in the config file :)

'useAcceptLanguageHeader' => false
