### ISSUE TITLE
Call to undefined method Mcamara\LaravelLocalization\Facades\LaravelLocalization::setLocale()

### ISSUE THREAD

**Issue by amaliathess** [mcamara/laravel-localization#522]
Hello there ! Im using laravel 5.4 and mcamara 1.3 and I am getting this error
Call to undefined method Mcamara\LaravelLocalization\Facades\LaravelLocalization::setLocale()
when i add  LaravelLocalization::setLocale() to my roots it seems like it cant read any method because any method i add i am getting the same error.
I have added `'locale' => 'el',` to config app the facade and the provider l also added the laravellocalization.php file .
any  ideas please !!

**Comment by iwasherefirst2** [comment]
You need to register the service provider in `config/app.php` 

See https://github.com/mcamara/laravel-localization/blob/master/ADDITIONS.md#for-laravel-54-and-below for instructions.
