### ISSUE TITLE
Laravel 5.5 Default language 

### ISSUE THREAD

**Issue by DineeshDS** [mcamara/laravel-localization#523]
I have added Laravel-localization , its works perfect but i am unable to set arabic as my default language

**Comment by OGhawsi** [comment]
@DineeshDS in Config folder App.php just set 'locale' => 'ar'. I have done the same for Pashto and Persian which has Arabic script.

**Comment by DineeshDS** [comment]
Yes , same way i have tried . I put  'locale' => 'ar' in App.php but first time site is loaded language is marked as English(default)

**Comment by OGhawsi** [comment]
Have you activated Arabic in localization file...check the docs... publish vender files

**Comment by DineeshDS** [comment]
Yes i have activated arabic , Language is changing english to arabic when enter ar in the url , both language switching is working but i can't change default from english to arabic

**Comment by ahmedalmulki** [comment]
Hi did you find a solution for your problem , I can't make the Arabic language default .

**Comment by johnef** [comment]
Same here

**Comment by johnef** [comment]
@mcamara you are very good at one thing just closing issues as soon as some one says how to do it without double check if it's working fine or not!!

**Comment by Ahmadgoma** [comment]
just set this in the laravellocalization.php config file 

'useAcceptLanguageHeader' => false

**Comment by MahmoudSayed96** [comment]
@Ahmadgoma Thanks, it's working
