### ISSUE TITLE
Collection of countries?

### ISSUE THREAD

**Issue by xitude** [mcamara/laravel-localization#530]
I'd ideally like to use `EU` for `europe` in general instead of support each country any suggestions on approaching that?

**Comment by fisharebest** [comment]
I'm not sure I understand what you are asking?

This package is about *language* negotiation and route localisation.

What are you trying to achieve?

**Comment by xitude** [comment]
Im wondering if it's possible to join multiple languages into a main one. So i can generalize the EU countries as `/eu/`

**Comment by xitude** [comment]
Soooo I guess thats a no?
