### ISSUE TITLE
Redirection to a default locale for unsupported language

### ISSUE THREAD

**Issue by FrostBy** [mcamara/laravel-localization#531]
Hi! I didn't found any solution in the docs.
For an example, I have the only 2 acceptable locales: en and ru.
How can I redirect a user to a default locale if this user tries to access url/**es**/page?

**Comment by dmarcoFC** [comment]
I'm also looking for a solution, did you find something ?

**Comment by Nuranto** [comment]
Interested in this too.

**Comment by iwasherefirst2** [comment]
I think its unlikly that a user rewrites manually a url of a website, and if he does, a 404 response should be the right response in my opinion. But anyway, if you want to redirect any url where the first parameter is a string of length 2 to the current locale, you could create a custom middleware like this:
```
$params = explode('/', $request->getPathInfo());
// Dump the first element (empty string) as getPathInfo() always returns a leading slash
array_shift($params);

if (\count($params) > 0) {
    $locale = $params[0];

    if (strlen($locale)== 2 && !app('laravellocalization')->checkLocaleInSupportedLocales($locale)) {
        if (app('laravellocalization')->isHiddenDefault($locale)) {
            $redirection = app('laravellocalization')->getNonLocalizedURL();

            // Save any flashed data for redirect
            app('session')->reflash();

            return new RedirectResponse($redirection, 302, ['Vary' => 'Accept-Language']);
        }
    }
}
```
