### ISSUE TITLE
getLocalizedURL does not translate my routes

### ISSUE THREAD

**Issue by perffy** [mcamara/laravel-localization#532]
Hi guys,

i have again problem with the translation of routes. Now i have installed Laravel 5.6.12 and laravel-localization ^1.3. As described in the documentation I have created a routes.php in all language folders.

Here is my Kernel.php:

```
protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'cache.headers' => \Illuminate\Http\Middleware\SetCacheHeaders::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'signed' => \Illuminate\Routing\Middleware\ValidateSignature::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
		'localize' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
		'localizationRedirect' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
		'localeSessionRedirect' => \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
		'localeViewPath' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationViewPath::class,
    ];
```

Here is short version of my web.php

```
Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function()
{

	Route::group(['namespace' => 'Front'], function () {

		Route::get(LaravelLocalization::transRoute('routes.casinos'), ['as' => 'casino.index', 'uses' => 'CasinosController@index']);
		
	});
});
```

I am trying to change the url for each language like this:

`$url = LaravelLocalization::getLocalizedURL($lang, null, [], true);`

I just get only the language prefix changed.

Am I doing anything wrong ?

**Comment by perffy** [comment]
I found the problem.
I was calling getLocalizedURL() in the AppProvider and that causes the problem. If i call it in the view, it works

**Comment by sornbarang** [comment]
Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localize' ] // Route translate middleware
],
function()
{

	Route::group(['namespace' => 'Front'], function () {

		Route::get(LaravelLocalization::transRoute('routes.casinos'), ['as' => 'casino.index', 'uses' => 'CasinosController@index']);
		
	});
});
