### ISSUE TITLE
Set locale upon user profile language

### ISSUE THREAD

**Issue by iz5clj** [mcamara/laravel-localization#533]
In my user settings I have a language field.
How can I set the Locale to the user's language?
I suppose somewhere in a middleware.
I can get the user preference with $language = $user->language.
Where do I put the setCurrentLanguage?

Thank in advance.

**Comment by user0017** [comment]
it already covered in the documentation
[use this function here](https://github.com/mcamara/laravel-localization#set-locale)

**Comment by ronrun** [comment]
If the user's language setting is es, but the url is http://xxx.com/en/product/1, obviously you should not provide es content, because the current url is en. I think you can redirect.

**Comment by iwasherefirst2** [comment]
Closed as this has been answered now in #550
