### ISSUE TITLE
Routes with dynamic parameters

### ISSUE THREAD

**Issue by dily86** [mcamara/laravel-localization#535]
Hi,
How could I translate routes with dynamic parameters ?
For example : 
https://mon-site/en/page/my-title
https://mon-site/fr/page/mon-titre
https://mon-site/es/page/mi-titulo

Thanks in advance.

**Comment by user0017** [comment]
I think that you have to define translated column on your `post` table
`title_en, title_fr, title_es`  (it recommanded to use separete table like `translated_post_table` )

and use function that deteced the localization on` index()`  for ex to get the tanslated params ,  such as `title , body`.

and for common words,pragraphs is already defined on your `/lang/es.json` file or `/lang/es/something.php`

**Comment by iwasherefirst2** [comment]
Closing as this is a duplicate of #502
