### ISSUE TITLE
Exclude current locale with getSupportedLocales(true)

### ISSUE THREAD

**Issue by gsgarin** [mcamara/laravel-localization#536]
Laravel-localization version: 1.3.6
Laravel Version: 5.5.39
PHP Version: 7.2.3
I tried to get supported locale exclude current locale, it was fine in 1.3.4 & 1.3.5 version. But it doesn't work in 1.3.6 version. 
https://github.com/mcamara/laravel-localization/pull/521

**Comment by iwasherefirst2** [comment]
This question refers to a very old version (1.3.6). If you’re still experiencing this issue with the current version (2.2.1), please reopen it with more details. Thanks!
