### ISSUE TITLE
Problem with getLocalizedURL - removes slashes between the parameters

### ISSUE THREAD

**Issue by Krasimir-Todorov** [mcamara/laravel-localization#537]
When passing the following URL - **http://localhost/poll/80/4** and a valid locale **no** the method returns **http://localhost/no/poll804**

I'm unable to pass non absolute URL, because it's named route which is having required parameters.
Any solutions or workarounds?

**Comment by jeremy379** [comment]
I got the same issue.
It was caused by the value of APP_URL I setup in my .env. This value can't finished by a /.

Removing it fixed my issue.
