### ISSUE TITLE
Making multiple language search box

### ISSUE THREAD

**Issue by aozen** [mcamara/laravel-localization#539]
Search query with localization. 
Right now, when i am search something, results are coming with different languages. But i can just search with my main language. After results are came translation happening. This is related with my blade. 
{!! $news->translate($localeCode)->title !!}

But main question is before the search. How can i search something with selected language. I can switch language easily. This is my search scope. 

```
public function scopeSearch($query, $search) {
         $localeCode = LaravelLocalization::getCurrentLocale();
        return $query->translate($localeCode)->where('title', 'LIKE', '%' .$search. '%')
            ->orWhere('sub_body', 'like', '%' .$search. '%')
            ->orWhere('body', 'like', '%' .$search. '%');
    }
```

Also this is my controller

```
public function index (Request $request){

        $localeCode = LaravelLocalization::getCurrentLocale();
        $updates = Update::latest()->take(3)->get();
        $query = $request->get('q');
        $new = $request->filled('q') ? News::search($query) : News::query();
        $new = $new->orderBy('id', 'desc')->paginate(10);
        

        return view('frontend.news', compact('localeCode', 'updates', 'new', 'query'));
    }
```

I'll be glad if anyone help. Thanks advance.

**Comment by iwasherefirst2** [comment]
You should use `App::getLocale()` instead of `LaravelLocalization::getCurrentLocale();` in `scopeSearch` to access current locale.
