### ISSUE TITLE
Set language

### ISSUE THREAD

**Issue by n00el** [mcamara/laravel-localization#540]
How to set language from controller?
`LaravelLocalization::setLocale($this->lang);` just not working.

**Comment by ronrun** [comment]
What is your $this->lang? Did you define it, give it a value?

**Comment by ronrun** [comment]
Maybe you forgot to set the value for $this->lang

**Comment by iwasherefirst2** [comment]
If you want to change the language inside of an controller, you may just call

    \App::setLocale($this->lang);
