### ISSUE TITLE
app.locale not changing

### ISSUE THREAD

**Issue by GitzJoey** [mcamara/laravel-localization#541]
have the drop down selector
>
                    @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
                        <a class="dropdown-item" hreflang="{{$localeCode}}" href="{{LaravelLocalization::getLocalizedURL($localeCode) }}">
                            @if (App::getLocale() == $localeCode)
                                <strong>{{ $properties['native'] }}</strong>
                            @else
                                {{ $properties['native'] }}
                            @endif
                        </a>
                    @endforeach
>

and write this somewhere in your blade
> 
    {{ LaravelLocalization::getCurrentLocale() }} 
    {{ env('APP_LOCALE') }}
>

try changing the language using the drop down selector back and forth
you will see the app.locale will persist

> 
on load
en
en

after clicking the change language
id
en
>

"php": "^7.1.3",
"laravel/framework": "5.6.*",
"mcamara/laravel-localization": "^1.3",

**Comment by alireza2281** [comment]
i have the same problem did you find any thing?
