### ISSUE TITLE
About config

### ISSUE THREAD

**Issue by ronrun** [mcamara/laravel-localization#543]
Hi, I just used this package. I tried some time.  "en" can work, but other language cannot work.
Finally, I found the section at the bottom

php artisan vendor:publish --provider="Mcamara\LaravelLocalization\LaravelLocalizationServiceProvider"
then edit this file
config/laravellocalization.php

This step should be put into installation, this is the most basic setting.

**Comment by iwasherefirst2** [comment]
Config setting follows directly the installation, so I think it should be clear. If you think there is a better way of writing the instruction in the readme.md, please send a PR.
