### ISSUE TITLE
What does script mean in config file

### ISSUE THREAD

**Issue by ronrun** [mcamara/laravel-localization#544]
/config/laravellocalization.php
`'en'          => ['name' => 'English',                'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB'],`

when will we use this variable?

**Comment by bs-thomas** [comment]
I wonder what this is for as well.  Quite curious.

**Comment by fisharebest** [comment]
Some fonts work better with different scripts.  For example, a font that works well for `Latn` may not work well for `Japn`.  An application may choose different fonts for different scripts.

In my application, I use it to prioritse results when searching for data.  I have user-submitted data in many langauges.  If a user has selected a language that uses the `Cyrl` script, then I will show results in Cyrillic ahead of results in Latin.

But I guess most people will not need to use it.
