### ISSUE TITLE
When redirecting from non-localized URLs to localized URLs, it never redirects with a trailing slash 

### ISSUE THREAD

**Issue by bs-thomas** [mcamara/laravel-localization#548]
When I type this:
www.domain.com/

It redirects me to this:
www.domain.com/en

I hope to achieve this:
www.domain.com/en/

I understand I can tweak this to add trailing slash using htaccess, but that adds an extra request to the server.

-----

While I understand that laravel by default strips off trailing slashes at the end of URL, it's also a better practice (know it's not a mandatory practice) to include the trailing slash.

There are also a lot of discussions on how to support this on laravel and many other frameworks, so it seems like it's a common use-case for a fair amount of community.

I was wondering if there is a config (or if there "can be" can config, when doing non-localized url to localized url redirects, it will immediately add the trailing slash redirection?

Your kind assistance is appreciated.

**Comment by iwasherefirst2** [comment]
Maybe you could get this behaviour simply by adding a slash in the redirect middleware. You could create your own custom `LocaleSessionRedirect` and change

    $redirection = app('laravellocalization')->getLocalizedURL($locale);

to

    $redirection = app('laravellocalization')->getLocalizedURL($locale) . '/'; 

If you use `hideDefaultLocaleInURL` you may do the same for `LaravelLocalizationRedirectFilter`.
