### ISSUE TITLE
Change language when user logged in

### ISSUE THREAD

**Issue by aozen** [mcamara/laravel-localization#550]
Hello localizations. I am trying to do something, but can't made it out. I hope you guys found my problem. In my users table, i have a lang column. Saving original language with "en" or "es" or "ru" something like that. Also i am trying to when user logged in, change the language with users lang. In my login controller i made: 

```
if (Auth::guard('customer')->attempt(['email' => $request->email, 'password' => $request->password], $request->remember)) {
            if(Auth::guard('customer')){
                $id = Auth::guard('customer')->id();
                $lang = Customer::where('id', '=', $id)->first()->lang;
                LaravelLocalization::setLocale($lang);

                return redirect()->route('homepage');
            }
        }
        return redirect('/')->with('error_login', 'Login Fail');
```

`dd(LaravelLocalization::setLocale($lang));` give me the correct "lang". Like "en", "es" ... 
but 
`LaravelLocalization::setLocale($lang);`

doesnt work. Any solution? Thanks in advance.

**Comment by iwasherefirst2** [comment]
If you have `useAcceptLanguageHeader` enabled, then your users are redirected anyway to the language according to their browser. I would prioritize the browser language over the language of the db. However, if you still want to redirect a user to its locale from db, you could create a custom middleware that sets the locale if its not set and if the user is logged in. Something like this:

```
if(empty(session('locale')) && \Auth::check()){
    session(['locale' => \Auth::user()->getLocale()]);
} 
```
