### ISSUE TITLE
 language selectors with VueJS application 

### ISSUE THREAD

**Issue by masabni** [mcamara/laravel-localization#555]
Hello, I'm having trouble on creating a language selector on my [Vue](https://vuejs.org/) application.
I tried doing a get request to my laravel backend like this:
```
Route::get('/localize', function (){
    return LaravelLocalization::getSupportedLocales();
});
```
but i want it with the getLocalizedURL for each local, maybe something like this : 
```
 LaravelLocalization::getSupportedLocales($withLocalizedURL = true);
```
or is there another way i can get the language selector inside a vue component 
(please note that i'm not using the blade template).

Thanks

**Comment by iwasherefirst2** [comment]
There is a snipped for a language selector in the docs: https://github.com/mcamara/laravel-localization#creating-a-language-selector
