### ISSUE TITLE
Documentation lack: where is `supportedLocales` ?

### ISSUE THREAD

**Issue by kamil-kielczewski** [mcamara/laravel-localization#557]
I have laravel 5.5.39 project and unfortunatley autodiscovery don't find LaravelLocalization after I run 

`composer require mcamara/laravel-localization`

So i update `config/app.php` as documentation say but I get this error:

> Laravel default locale is not in the supportedLocales array.

In documentation is writen that you need put languages to `supportedLocales` - but where the hell is it?!

I found on internet that I should do:

`php artisan vendor:publish --provider="Mcamara\LaravelLocalization\LaravelLocalizationServiceProvider"`

But that infomation should be in documentation...

**Comment by fisharebest** [comment]
> But that infomation should be in documentation...

It is.  It is on the front page of the project

https://github.com/mcamara/laravel-localization#config-files

When you have calmed down, perhaps you can apologies for your offensive language.

**Comment by kamil-kielczewski** [comment]
Sorry, I was frustrated because I push "CTRL+F" in browser, type `supportedLocales` and cannot find any connection with configuration... so I think currently in this element docummentation Is User unfriendly :( .

My proposition: Cange text below header **Config file**:  

> In order to edit the default configuration for this package you may execute:

to:

> In order to edit the default configuration (where for e.g. you can find `supportedLocales`) for this package you may execute:

**Comment by iwasherefirst2** [comment]
> > But that infomation should be in documentation...
> 
> It is! It is on the front page of the project
> 
> https://github.com/mcamara/laravel-localization#config-files
> 
> When you have calmed down, perhaps you can apologise for your offensive language.

Thank you! That helped. 

I would also recommend to add a link in the section https://github.com/mcamara/laravel-localization#usage to  https://github.com/mcamara/laravel-localization#config-files since it says you have to edit `supportedLocales` but its only explained at the very bottom of the page how to actually do that.
