### ISSUE TITLE
Redirect non-localized URLS to default URL

### ISSUE THREAD

**Issue by igerslike** [mcamara/laravel-localization#564]
Basicly i have been playing around all day trying to make this work.

We have a group of routes that we want to be translated. But there are other groups that does not require translation. The problem is your function getLocalizedURL tries to generate the URL for a non-existing route in the group.

Lets say we have a "/blog" route that we wanna keep out of translation group, this will generate a 404 , because "/en/blog" doesnt  exists. when it should still serve the page with a default layout and dont throw a 404.

Does anyone have solution for this ?

**Comment by dadaismus** [comment]
Did you verify that mod_rewrite is enabled on your server?

**Comment by igerslike** [comment]
Obviously, it is :) 
The problem is getLocalizedUrl doesn't ignore the routes that are not in the localized group, trying to get a route for /en/blog when this route doesn't exist, so will throw a 404.

The only solution I found was to place the translated routes at the end of the file ( web.php ), but definitely, getLocalizedURL should evaluate if the current URL is on the middleware group "localize" or others in order to ignore these non-localized routes.

My approach was a creating a specific controller for switching languages without relying on getLocalizedUrl to actually switch the language.

**Comment by iwasherefirst2** [comment]
You should add the middleware only to the localized `Route::groups`:
```

Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function()
{
	//...
});

```

This way, you routes outside the group are not redirected.

**Comment by igerslike** [comment]
It's been a long time, I believe the package was already updated to ignore certain URLs :) anyways my solution still working smoothly since then. I believe you can either close this issue/question as it should be already resolved in the newer versions.
