### ISSUE TITLE
Question: Why app/Http/routes.php ?

### ISSUE THREAD

**Issue by pmochine** [mcamara/laravel-localization#567]
Sorry for opening this issue, I'm still new. But this confuses me a lot. Why should I create a new routes.php? Since we are all using /routes/web.php?

**Comment by pmochine** [comment]
I see... I'm I came with laravel 5.4... so it was before that... am I right? (After that I'm closing)

**Comment by zedentox** [comment]
routes.php was replaced by web.php and api.php in newer versions of Laravel.
