### ISSUE TITLE
Default Locale is not showing in the url

### ISSUE THREAD

**Issue by PointfullDevelopers** [mcamara/laravel-localization#569]
`'hideDefaultLocaleInURL' => false`

Still the default language only shows on the URL if I switch to another language and then comeback to the default

**Comment by coding-sunshine** [comment]
I am facing the same issue. Did you find the solution?

**Comment by DmitrySkibitsky** [comment]
Similar problem.

**Comment by DmitrySkibitsky** [comment]
This parameter is not taken into account. And get duplicate URL. SEO is not good at all. How to fix?

**Comment by DmitrySkibitsky** [comment]
Here's the solution [#585](https://github.com/mcamara/laravel-localization/issues/585)

**Comment by iwasherefirst2** [comment]
Was fixed with #599
