### ISSUE TITLE
LaravelLocalization::getCurrentLocale() should not be called statically

### ISSUE THREAD

**Issue by NicolaeCasir** [mcamara/laravel-localization#575]
Hello. I never used this plugin, but because now i have big problems with laravel default localization i choosed to use this one. Here is my problem:
`Non-static method 
Mcamara\LaravelLocalization\LaravelLocalization::getCurrentLocale() should not be called statically`
and code is:
` public function index () {
        $lang = LaravelLocalization::getCurrentLocale();
        ...
  }
`
**PHP** 7.2.6 (cli)
**Laravel** 5.6.28

Thank you.

**Comment by NBZ4live** [comment]
You should call it statically only on the Facade, not the real class.

Just use \Mcamara\LaravelLocalization\Facades\LaravelLocalization or \LaravelLocalization

**Comment by vicodeveloper** [comment]
use \Mcamara\LaravelLocalization\Facades\LaravelLocalization work for me! Thx!
