### ISSUE TITLE
French accents not working, all other languages OK

### ISSUE THREAD

**Issue by xlcrr** [mcamara/laravel-localization#579]
Hi,

I am trying to convert a platform into multiple languages. The only one giving me trouble is French. I have 'fr' commented out in the localization file however any sentences containing accents are not showing up in the blade template. 

This is only true for French, and all other languages seem to be okay. If I remove the accents, it works as expected. 

In my main app.blade.php file, I already have the meta tag
`<meta charset="utf-8">`

Anyone know how I can resolve this ? Thanks

**Comment by xlcrr** [comment]
This works

` {{ utf8_encode(__('messages.welcome1')) }}`

but is the correct approach? Do I need to do this for all my keys in HTML or is there another way?

**Comment by iwasherefirst2** [comment]
Looks like your `app.blade.php` file or `message.php` file is not encoded correctly. There is no need to use `utf8_encode`, it should work out of the box without.

Make sure that `app.blade.php` file and `**/message.php` files are stored with UTF-8 (without BOM).
