### ISSUE TITLE
set default locale to ar in route without hiding default locale

### ISSUE THREAD

**Issue by bishoywagih** [mcamara/laravel-localization#580]
i want to change the default locale to other language rather than English and already defined in the supported locales,

i defined the main website language in config/app.php file (locale =>'ar'),
but,  when i open the website without setting any locale mywebsite.com
it redirects to mywebsite.com/en instead of mywebsite.com/ar

**Comment by iwasherefirst2** [comment]
Maybe your browser language is `en` and not `ar` ? By default, if no locale is given in the url, the app will try to get your default language from browser. If you want everyone to be redirected to `ar` despite your browser language you need to disable `useAcceptLanguageHeader` in `config\laravelocalization.php` 

```
// Negotiate for the user locale using the Accept-Language header if it's not defined in the URL?
// If false, system will take app.php locale attribute
'useAcceptLanguageHeader' => false,
```
