### ISSUE TITLE
where clause in route doesn't work when using a localization route group

### ISSUE THREAD

**Issue by alewolf** [mcamara/laravel-localization#582]
My code structure looks like this:

```

Route::group( 
mcmara localization route group
}

Route::get('/de', 'FrontpageController@index');

Route::get('/fr', 'FrontpageController@index');
```

Both language routes work fine when used as single functions like above. 
The plan is to combine those two language routes after the route group with following route: 

`Route::get('/{url}', 'FrontpageController@index')->where('url', 'de|fr');`

But it doesn't work **as long as I use the localization route group above that new route**.

I get a `This page isn’t working. example.test redirected you too many times.` error. 

Now, I've got the following route within my route group:

```
	Route::get('/', function()
	{
		return redirect(LaravelLocalization::getCurrentLocale());
	});
```

When I remove **that**, suddenly 

`Route::get('/{url}', 'FrontpageController@index')->where('url', 'de|fr');`

starts working. 

I am not sure if I misunderstand something, or if this a bug. But my intuition tells me that it is a bug, since the single language routes do work (with the `/` route within the route group above). 

It seems like `/{url}` is not being parsed correctly anymore once I define a route for `/`.

**Comment by iwasherefirst2** [comment]
Your route inside the group translates to:

```
Route::get('/de, function()
	{
		return redirect('/de');
	})
```
which will indeed create a redirect loop.

When you added the route

    Route::get('/de', 'FrontpageController@index');

below, you were overwritting the first "infinive-loop" route, and thus everthing was working.

However, the dynamic route 

    Route::get('/{url}', 'FrontpageController@index')->where('url', 'de|fr');

did not overwrite your "infinive-loop" route and thus causes the crash. 

What are you trying to do with 

```
Route::get('/', function()
	{
		return redirect(LaravelLocalization::getCurrentLocale());
	});
```

?

Maybe [this](https://github.com/mcamara/laravel-localization#localesessionredirect) is what you looking for instead?
