### ISSUE TITLE
Default localization does not appear in the URL

### ISSUE THREAD

**Issue by DmitrySkibitsky** [mcamara/laravel-localization#585]
```php
config.hideDefaultLocaleInURL =  false

```
But the default localization did not appear in the URL

**Comment by DmitrySkibitsky** [comment]
Solved the problem this way

![deepinscreenshot_select-area_20180905003639](https://user-images.githubusercontent.com/20288556/45059249-08966800-b0a4-11e8-99ad-23264c39c566.png)

![deepinscreenshot_select-area_20180905003754](https://user-images.githubusercontent.com/20288556/45059250-092efe80-b0a4-11e8-8062-c52d62e57d18.png)

I don't know why it works like that. But it is very strange.

**Comment by DmitrySkibitsky** [comment]
In the end I had to add the crutches. As I have shown above works only if the sessions has a record of localization. And if not, the default localization is not displayed.

![deepinscreenshot_select-area_20180911115602](https://user-images.githubusercontent.com/20288556/45349334-ab297c00-b5b9-11e8-93c5-e783e4c9a503.png)

**Comment by romansidorov** [comment]
Hm. I found out that if I use v. 1.3.9 of this package it works nice, but with 1.3.13 not.

**Comment by DmitrySkibitsky** [comment]
@romansidorov, извиняюсь. Я поспешно сделал вывод что это решает проблему. В итоге если в сессии нет записи о локализации, то оно все так же игнорирует отображение дефолтной локализации. Но если в сессиях есть запись о локализации и ты не передаешь данные в роуте касательно локализации а активная локализация = дефолтная локализация то если ставим localeSessionRedirect в самый конец цепочки миддлваров (как я показал на скрине) в таком случае оно отобразит дефолтную локализацию (лично у меня. Я из-за этого решил что все исправилось, но потом скорее всего очистил все данные в браузере и столкнулся с тем что уже работает не так как надо. Плюнул и быдлокодить начал). 

Можно в \App\Providers\AppServiceProvider::boot написать что-то типа 
```php
if (session('locale') === null) {
    session('locale', app()->getLocale());
}
```
Ну и сохранить последовательность миддлваров которые на скрине 
![screean](https://user-images.githubusercontent.com/20288556/45059482-da655800-b0a4-11e8-8cca-c19fa0cfcd3e.png)

В таком случае должно отображать дефолтную локализацию.

А хотя... Я сейчас точно не помню ситуацию когда оно перестает работать. Не могу вспомнить.

**Comment by romansidorov** [comment]
Думаю, это баг, родившийся с апдейтом либы. Спасибо за возможное решение по фиксу :)

**Comment by romansidorov** [comment]
> Hm. I found out that if I use v. 1.3.9 of this package it works nice, but with 1.3.13 not.

@mcamara Could you check it please?

**Comment by mcamara** [comment]
It should be fixed now thanks to @iwasherefirst2

**Comment by romansidorov** [comment]
> It should be fixed now thanks to @iwasherefirst2 . Can you confirm @romansidorov?

Yes, with 1.3.14 it works as expected. Thanks :)

**Comment by mcamara** [comment]
Cool! Thanks a lot @romansidorov !

**Comment by fede91it** [comment]
I'm on 1.3.16 and doesn't work

Any ideas?
