### ISSUE TITLE
Url 400 for functional test

### ISSUE THREAD

**Issue by BonBonSlick** [mcamara/laravel-localization#586]
```
// auth system
Route::group([
                 'prefix' => LaravelLocalization::setLocale(),
                 'middleware' => [
                     'localeSessionRedirect',
                     'localizationRedirect',
                     'localeViewPath'
                 ],
             ], function()
{
    /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
    Route::get('/forgot-password/', 'LoginController@forgotpassword');
});
```
And all other routes will fail for functional test. Their status will be 400.
Tried 

```
 'en/forgot-password',
 '/en/forgot-password',
 'forgot-password',
 'en/forgot-password/',
 '/en/forgot-password',
```

all are 400 error code

**Comment by ahmadmayahi** [comment]
I have the same issue here. any idea?

**Comment by ahmadmayahi** [comment]
One solution is to disable the redirection middleware if the running environment equals to `testing`.
This is a bit tiresome, but it is the only way to solve the issue.

All you need to do is to create three middlewares `localizationRedirect`, `localeSessionRedirect` and `localeViewPath` and then extend to have the base middlewares.

Inside the `handle` method just do the following
```php
        if (true === App::environment('testing')) {
            return $next($request);
        }

        return parent::handle($request, $next);
```

**Comment by BonBonSlick** [comment]
@ahmadmayahi 2 years since then, I do not use laravel already for production sites.
