### ISSUE TITLE
How to config to include all routes of all locales?

### ISSUE THREAD

**Issue by scil** [mcamara/laravel-localization#591]
I use [LaravelFly](https://github.com/scil/LaravelFly) to speed up Laravel. It can include routes on server worker process ,that, before any requests arrive at server.

I use [laravel-localization](https://github.com/mcamara/laravel-localization) and defined all routes for all locales in routes/web.php.( [config for LaravelFly and laravel-localization](https://github.com/scil/LaravelFly/blob/master/config/package_config_examples/laravel-localization.md) )

But this way has a weakness: if I support lots of locals, I will have lots of routes.

I wonder if there any good way to make laravel router find a route for an url as quickly as possible?

**Comment by iwasherefirst2** [comment]
Hi, I have no idea what LaravelFly, but this package can cache the localized routes, see the [docs](https://github.com/mcamara/laravel-localization#caching-routes) for more.
