### ISSUE TITLE
 (1/1) FatalErrorException  syntax error, unexpected '?' in LaravelLocalization.php line 896

### ISSUE THREAD

**Issue by Hervera** [mcamara/laravel-localization#592]
Everything was working well but after doing composer update, I am facing this error  -> FatalErrorException  syntax error, unexpected '?' in LaravelLocalization.php line 896, what wrong with this package?

**Comment by Astatroth** [comment]
There' nothing wrong with this package, it's wrong with your PHP version/

**Comment by Hervera** [comment]
I am using PHP 7.1.22

**Comment by fisharebest** [comment]
> I am using PHP 7.1.22

The `??` (null coalesce) operator was introduced in PHP 7.0.

The error message suggests that you are using PHP 5.6 (or earlier).

**Comment by Hervera** [comment]
I am seeing 2 different versions of PHP, when i put phpinfo() in test.php file i created in public folder, I see that the webserver has php 5.6.37, but in putty terminal using ssh the php version is 7.1.22
The php version being used by the webserver is different version to the terminal. I've even chosen the version that i want in cpanel but the same problem occurs again, What can i do?

**Comment by koarng** [comment]
@Hervera you should disable php5.6 by : sudo a2dismod php5.6
https://askubuntu.com/questions/761713/how-can-i-downgrade-from-php-7-to-php-5-6-on-ubuntu-16-04
