### ISSUE TITLE
Url generation issue

### ISSUE THREAD

**Issue by uzwebline** [mcamara/laravel-localization#593]
Hi!
Some  problem with url generation, some times url is generating with IP address instead of domain name. How to fix that?

**Comment by iwasherefirst2** [comment]
Do you still have the issue? Can you reproduce the issue, or does it happen randomly?

**Comment by uzwebline** [comment]
Hi!
Steps to reproduce:
1) Create web server with one domain name
2) Open the page by domain name, urls wil be generated with domain name
3) Open the page by IP address, now urls will be genearated with ip address, even if you write domain name at APP_URL parameter in .env file.

I think it should generate urls according to APP_URL parameter.

**Comment by iwasherefirst2** [comment]
This is not expected behavior and it would break all multi-domain Laravel applications.

If you want to redirect every url/ip to the url from `APP_URL` then maybe its best to create a custom middleware for this.
