### ISSUE TITLE
Cookies Auto Redirect

### ISSUE THREAD

**Issue by AmirAmin** [mcamara/laravel-localization#594]
Hello,

I am using this package almost two years back, and it is doing a great job.

I have a main concern, How can I redirect the user who open a page to the language he selected when he browsed the website before?

For example, a user was browsing the website in Arabic, and he closed the website and the browser. I would like whenever he open the website again to be redirected to the Arabic language not to the default (English). How can I do that?

**Note**: This has to be applied for all the pages. So, for example if he opened a direct link for any page to be redirected to the same one but in his previous selected language.

Regards,

**Comment by simar88** [comment]
Hi @AmirAmin ,
i wrote minutes ago how i'm using cookies for this.
You can find it here #613 
I hope can be useful for you! :)

**Comment by AmirAmin** [comment]
Hi @simar88,

Thanks and I really appreciate your reply.

Let me give a try with your solution and I will let you know the results :).

Regards,

**Comment by iwasherefirst2** [comment]
This can be solved by middleware `LocaleCookieRedirect` see #613
