### ISSUE TITLE
Changing language automatically with current location

### ISSUE THREAD

**Issue by aozen** [mcamara/laravel-localization#604]
Hello there, 
What i want to try is chaging language with users location, if users change language they can continue with that. But if user visiting website first time language must change automatically. 
Detecting language is easy, 
`$lang = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);`

With that i can get like "en", "ru", "fr", "tr", "es" or something like that. 
How can i change in the controller? I don't know the this package usage. 
I am getting current language with $request->segment(1) in all page in the website. But changing this is wrong and i cant set cookies for that. 

My main question is how to change default website language for user. Also needs cookie. 
For example a russian guy can visit website and redirecting www.example.com/ru
But he changed language to the "en". He must use "en" all the time of course. But if he visits website after two days. He must visit www.example.com/ru again. 

Any idea would be great. Thanks in advance.

**Comment by iwasherefirst2** [comment]
You can use LocaleSessionRedirect and LaravelLocalizationRedirectFilter from https://github.com/mcamara/laravel-localization#middleware 

This detects the language automatically from browser (note that this is more complicated then just `
$lang = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);` you can set multiple languages for a single browser and rank them). This stores the language in the session, not as a cookie, unless you use 

``expire_on_close` => false`

in `config/session.php`

If you want the session to expire on close, you may store and load it in a cookie with a custom middleware. Something like this:

  ```
  public function handle($request, Closure $next)
    {

      $params           = explode('/', $request->path());

     if (\count($params) > 0 && Language::isAllowed($params[0])) {
          $requestedLocale  = $params[0];
          session(['locale' => $requestedLocale]);
          Cookie::queue('locale', $requestedLocale , (60 * 24 * 30 * 12), '/');
      }

     $lang = session('locale', false);

    	if(empty($lang) && Cookie::has('locale'))
    	{
    		if(Language::isAllowed(Cookie::get('locale')))
    		{
    			$lang = Cookie::get('locale');
          $request->session()->put('locale', $lang);
    		}
    		else{
          Cookie::queue(
    			     Cookie::forget('locale')
          );
    		}
    	}

    	if(empty($lang))
    	{
    		$allowed_langs = \Config::get('constants.lang')[getOrga()];
    		$lang = $this->detectLangFromBrowser($allowed_langs);
    $request->session()->put('locale', $lang);

    	}
```
