### ISSUE TITLE
Adding the prefix leads to 404 with NOVA package installed

### ISSUE THREAD

**Issue by merlinresponse** [mcamara/laravel-localization#607]
I have used your package succesfully in a couple of Laravel projects (even with Voyager). It works like a charm. However with the latest build I'm using the new Laravel Nova and although I used the same code for the translation functionality it seems when I leave the default language (eg. 'nl' and hidden) to another one http://www.somedomain.com/fr it renders a 404? Could it be because of the way NOVA dynamically generates routes?

**Comment by merlinresponse** [comment]
Seemed to be a cached route issue. Followed the cache instructions and used the artisan cache/trans feature on the server. Perfect fix.

**Comment by namnh06** [comment]
I've got this issue, run clear cache but no luck.
