### ISSUE TITLE
localesMapping doesn't work

### ISSUE THREAD

**Issue by lidoma** [mcamara/laravel-localization#610]
I use this config
```php
'localesMapping' => [
    'en-US' => 'us',
]
```
But when navigate to the http://url-to-laravel/us/test get 404 error. the en-US is also enabled in `supportedLocales`.

**Comment by lidoma** [comment]
Any help here!

**Comment by AandD** [comment]
AS i looked at code, it simply not implemented

**Comment by lidoma** [comment]
This issue seems to be fixed. It works on version 1.4.1.
