### ISSUE TITLE
How i auto redirect to lang by current country language.

### ISSUE THREAD

**Issue by singhpappu** [mcamara/laravel-localization#611]
Hi Team,
I have implemented this package it's working fine.
But i have one problem when i set locale from middleware then language changed but language prefix (http://web-url/nl) not changed.
`
  \LaravelLocalization::setLocale('nl');
`
In that case language changed but url not changed to http://web-url/nl.

Please give me any suggestion.
Thanks

**Comment by aFluxx** [comment]
Have you implemented these two things:
https://github.com/mcamara/laravel-localization#laravel-compatibility

First you have to register the four redirection middleware in Kernel.php
```
'localize' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
		'localizationRedirect' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
		'localeSessionRedirect' => \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
                'localeViewPath' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationViewPath::class

```
And after that you have to specify the right prefix and middleware for the routes:

```
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]], function () {
   // Here be all your routes that you want automatically redirected.
});
```

I've implemented it like this and this works for me, hope this could shed you some light!

**Comment by singhpappu** [comment]
Thanks @aFluxx.
