### ISSUE TITLE
Laravel 5.7.19, all localized routes returns 404

### ISSUE THREAD

**Issue by hsntngr** [mcamara/laravel-localization#612]
I installed package with laravel v5.7.19. Iplemented requirement configuration in readme file. But all routes in app/http/routes.php returns 404 error. 

I'm using 1.3.16 version of laravel-localization

**Comment by aFluxx** [comment]
Try updating to laravel-localization 1.3, I can see in the docs that 1.1x is not supported for laravel 5.7
https://github.com/mcamara/laravel-localization#laravel-compatibility

**Comment by hsntngr** [comment]
@aFluxx  I made a typo, it's 1.3.16

**Comment by justmahdisadeghi** [comment]
I have this problem

**Comment by Legoraccio** [comment]
I solved by deleting all the cache files inside bootstrap/cache.
Try it this way.

**Comment by ALTELMA** [comment]
@Legoraccio Thanks for your help :) It works.

**Comment by lucasdcrk** [comment]
Had the same problem, @Legoraccio 's solution worked
Thanks!

**Comment by matthijs-neijenhuijs** [comment]
deleting cache is no solution, because its back when you do php artisan optimize

**Comment by matthijs-neijenhuijs** [comment]
i still have this problem. I only can solve it to remove routes.php, is there another solution?

**Comment by iwasherefirst2** [comment]
@matthijs-neijenhuijs `php artisan optimize` is deprecated as of 5.5 and removed in 5.6. If you want to use cached routes (which is recommended) you have to call `php artisan route:trans:cache` instead of `php artisan route:cache`.

**Comment by merdiano** [comment]
same problem on laravel 5.6.39 with version 1.4.2
solved by downgrading to version 1.3.20

**Comment by iwasherefirst2** [comment]
@merdiano  are you using php artisan route:trans:cache ?

**Comment by merdiano** [comment]
> @merdiano are you using php artisan route:trans:cache ?

sure i run route:trans:cache before downgrade on v1.4.2 it caches routes properly but gives 404 on requests

**Comment by iwasherefirst2** [comment]
@merdiano  do you mean post requests? If that is the case, try [this](https://github.com/mcamara/laravel-localization#post-is-not-working). The cache is working in v1.4.2 for me.
