### ISSUE TITLE
Edit for cookies usage

### ISSUE THREAD

**Issue by simar88** [mcamara/laravel-localization#613]
Dear all,
i'm writing to describe how i'm using cookies with this package in order to let the user select a default language for the website and mantain it during navigation or other future visits. 
Maybe can be useful for someone else.
At line 172 of **/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php** replace the code:
`$this->currentLocale = $this->getCurrentLocale();`
with the following:
`if (request()->cookie('locale')) {
                    response()->json(['s' => true]);
                    $cookieLocale = \Crypt::decrypt(request()->cookie('locale'));
                    if (!empty($this->supportedLocales[$cookieLocale])) {
                        $this->currentLocale = $cookieLocale;
                    } else {
                        $this->currentLocale = $this->defaultLocale;
                    }
                } else {
                    $this->currentLocale = $this->getCurrentLocale();
                }`
After that set cookie 'locale' using the way you prefere between server side or client side.
I hope that this code can be integrated by default in the next release of the package. :)

**Comment by iwasherefirst2** [comment]
The middleware  `LocaleCookieRedirect` does already that. However, it seems that its not mentioned in the readme.md. I will create a PR for that, after its merged this issue will be closed.
