### ISSUE TITLE
Translated Routes

### ISSUE THREAD

**Issue by malde11** [mcamara/laravel-localization#616]
Hi,

I got a problem with the translated routes, when I click for example on:
```
<a href="tutorials/ubuntu-first-login-via-ssh">Ubuntu start</a>
example.com/en/tutorials/ubuntu-first-login-via-ssh
```

In the "en" version everthing is perfect and I can switch languages, but when I visite from the german "de" version first the link I get a 404 error (page not found).
```
<a href="tutorials/ubuntu-first-login-via-ssh">Ubuntu start</a>
example.com/de/tutorials/ubuntu-first-login-via-ssh
```
He is only switching the url, when I am on the "en" version and click the language switcher. But when I visite the "de" version first, it is the "en" link(url).

**I am not sure, which of the url/route(link) I have to insert in my html, maby someone can help me?**

**Here is my code:**

Routes(web.php):
```
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localize', 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function()
{
	/** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
	Route::get('/', function () {
    return view('home');
	});

	Route::get('/profil', 'ShowProfil@show');
	Route::get('/tutorials', 'ShowTutorials@show');
	Route::get(LaravelLocalization::transRoute('routes.ubuntustart'), 'ShowTutorialsUbuntu@showStart');

});

/** OTHER PAGES THAT SHOULD NOT BE LOCALIZED **/

Route::get('/work', 'ShowWork@show');
```
My controller:
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use View;

class ShowTutorialsUbuntu extends Controller
{
    // Show Ubuntu Start Page
    public function showStart() {

    	return View::make('tutorials.server.ubuntu.ubuntu_start');
    }
}
```
Translation "en"(routes.php)
```
<?php

// resources/lang/en/routes.php
return [

	'ubuntustart' 	=> 	'tutorials/ubuntu-first-login-via-ssh'
	
];
```
Translation "de"(routes.php)
```
<?php

// resources/lang/de/routes.php

return [

	'ubuntustart' 	=> 	'tutorials/ubuntu-erster-login-via-ssh'

];
```

And my html(I am not sure, which route/url I have to insert there)
```
<li class="list-group-item">
    <a class="sub-navi" href="tutorials/ubuntu-first-login-via-ssh">Start</a>
</li>
```

I hope someone can help me, I am a bit confused!!  :)

**Comment by malde11** [comment]
**I fixed it like this:**
`href="{{ App::isLocale('de') ? 'tutorials/ubuntu-erster-login-via-ssh' : 'tutorials/ubuntu-first-login-via-ssh' }}"`

**Can I use the same for hreflang?**
`hreflang="{{ App::isLocale('de') ? 'de' : 'en' }}"`

**Comment by plamenst** [comment]
Hello,
You should use:
`{{ LaravelLocalization::getLocalizedURL($locale, $url, $attributes) }}`
(take a look at the documentation)

For example in your case:
`<a href="{{ LaravelLocalization::getLocalizedURL(LaravelLocalization::getCurrentLocale(), '/tutorials/ubuntu-first-login-via-ssh') }}">`

Or even better solution would be to put names on the routes and use them to generate URLs.

**Comment by iwasherefirst2** [comment]
Yes plamenst solution is the recommended way of doing it. Especially when you have more then 2 languages.
