### ISSUE TITLE
If you put Auth::routes() into the localization middleware group, the logout POST method won't work properly

### ISSUE THREAD

**Issue by aFluxx** [mcamara/laravel-localization#618]
Hello there,

When I put `Auth::routes();` via the middleware of this package, the logout doesn't work, probably because the POST request becomes a GET request.

My workaround atm is that I commented out `// $this->post('logout', 'Auth\LoginController@logout')->name('logout');` in my Routing/router.php

and I added the route in my web.php myself, but this will break if laravel ever gets updated.

I was wondering if anyone here had a workaround for this problem.

I've tried this article https://komelin.com/articles/laravel-localization-middlewares-now-support-route-exceptions/, but this doesn't seem to work.

**Comment by iwasherefirst2** [comment]
The simplest solution is to localize your logout url.

Somewhere in your blade you probably have something like this:

```
<form action="/logout" method="POST">
<button>Logout</button>
</form>
```
this would get redirected. You need to localize your post route to prevent it from beeing redirected. This should work:

```
<form action="{{  \LaravelLocalization::localizeURL('/logout') }} " method="POST">
<button>Logout</button>
</form>
```
---

Alternatively, if you don't want `/logout` to be localized,  remove `Auth::routes();` from you `web.php` and simply copy the routes manually to your route:
```
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
```

and decide for each route individually if you want to add them in or outside your `Route::groups`.

**Comment by vahidalvandi** [comment]
not work

**Comment by vahidalvandi** [comment]
you can create an manual logout  - work fine

Route::group(['middleware' => [ 'web']], function()
{
	Route::post('logoutAdmin', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
});
