### ISSUE TITLE
Wrong routes after setLocale

### ISSUE THREAD

**Issue by uchamb** [mcamara/laravel-localization#620]
Thanks for this awesome package.

I have a very strange problem and I couldn't find a solution yet.

I'm trying to send a bunch of emails from one request.
Each email could have different language because each subscriber has a different language.

So I'm trying to do:
```
\App::setLocale($subscriber->language);
LaravelLocalization::setLocale($subscriber->language);
Mail::to($subscriber->email)->send(new NewsletterEmail($newsletter, $subscriber));
```

After that, everything works fine except route prefixes. So the urls must be:
/en/article-title-in-english
/ka/article-title-in-georgian

But the prefix remains same and every URL starts with first set locale:
/en/article-title-in-english
/en/article-title-in-georgian

There is interesting note in the documentation:
"The function has to be called in the prefix of any route that should be translated (see Filters sections for further information)."
But I couldn't find Filters section for more info.

Thank you very much for your attention

**Comment by Daniyal-Javani** [comment]
Have you tried the getLocalizedURL function like this:
`\LaravelLocalization::getLocalizedURL('es', route('about'))`
while the route definition is:
```
Route::group(
[
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localize' ]
],
function() {
    Route::get(LaravelLocalization::transRoute('routes.about'), 'WelcomeController@index')->name('about');
});
```

**Comment by uchamb** [comment]
Yes, it works. Thanks a lot.

**Comment by sukiyanen85** [comment]
The above solution works, however, I can't understand why the route is not translated automatically inside the email like in every other links on the website
