### ISSUE TITLE
Support for Laravel 5.8

### ISSUE THREAD

**Issue by lsfiege** [mcamara/laravel-localization#622]
Laravel 5.8 was released :smiley:

**Comment by ahmeddabak** [comment]
I have a problem with the package dependencies.

```
The requested package laravel/framework (locked at v5.7.28, required as 5.8.*) is satisfiable by laravel/framework[v5.7.28] but these conflict with your requirements or minimum-sta
bility.
```

i will try to make a pr, after i am done upgrading

**Comment by mcamara** [comment]
I've updated the package to be compatible with the newest version of Laravel :)

Let me know if you find any issue working with it!
