### ISSUE TITLE
Route caching on Laravel 5.8

### ISSUE THREAD

**Issue by satoved** [mcamara/laravel-localization#625]
Laravel version: 5.8.2
laravel-localization version: 1.3.18

Thank you for a great package 👍 

All routes start to return 404 after I run php artisan route:trans:cache

I have a trait on RouteServiceProvider.

Caching used to work fine before upgrade to laravel 5.8

**Comment by lucasdcrk** [comment]
Laravel version: 5.8.26
laravel-localization version: 1.3.20

I have the same problem described above, even with the updated version
Whenever I run php artisan optimize 
All routes return 404, I have to delete bootstrap/cache/* and run composer dump-autoload to make it work again.
And if I run php artisan optimize everything is broken again

**Comment by lucasdcrk** [comment]
Also see #612

**Comment by TayZ3r** [comment]
I have the same problem!

**Comment by matthijs-neijenhuijs** [comment]
me too! after optimize its broken again

**Comment by lucasdcrk** [comment]
@matthijs-neijenhuijs see https://github.com/mcamara/laravel-localization/blob/master/CACHING.md

**Comment by matthijs-neijenhuijs** [comment]
Thnx!! was using php artisan optimize.
