### ISSUE TITLE
Login Helper trans returning keys from AuthenticatesUsers

### ISSUE THREAD

**Issue by doubleprincez** [mcamara/laravel-localization#630]
After installing and running LaravelLocalization, I realize my AuthenticatesUsers  trans('auth.failed') started emitting the key to the $errors=>first('email'), portion of auth.login view.
Please is there any way i can troubleshoot this myself because everything looks fine to me.
![auth user](https://user-images.githubusercontent.com/37469720/56586713-1cadbc00-65d8-11e9-80c2-5e077d1d2059.png)
![lang trans folder](https://user-images.githubusercontent.com/37469720/56586732-220b0680-65d8-11e9-83cb-39b851d5b66b.png)
![login page](https://user-images.githubusercontent.com/37469720/56586740-26372400-65d8-11e9-86d4-eb520573894b.png)

**Comment by iwasherefirst2** [comment]
Do you still have the issue? What is the current locale `Auth:getLocale()` ? Do you have an `auth.php` file in the language folder?
