### ISSUE TITLE
Route Model Binding doesn't work with translated routes

### ISSUE THREAD

**Issue by aFluxx** [mcamara/laravel-localization#632]
Hello there,

I'm wondering if there might be a bug with route model binding for translated routes.

I have the following setup:

routes.php
```
<?php

return [
    'pigeon_show'       => 'pigeon/{pigeon}',
];
```

web.php
```
Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [
        'localeSessionRedirect',
        'localizationRedirect',
        'localeViewPath',
        'localize'
    ]
], function () {
    Route::get(LaravelLocalization::transRoute('routes.pigeon_show'), 'PigeonController@show')->name('pigeon.show');
});
```

controller.php method
```
/**
     * Show the specific resource
     *
     * @param Pigeon $pigeon
     * @return view show
     */
    public function show(Pigeon $pigeon)
    {
        return redirect()->route('pigeon.show')->with('pigeon', $pigeon);
    }
```

When I dd() the Route Model Binding variable it seems like no Model is found:
https://i.gyazo.com/d7c44d819eba0728a2d4ba6af0e2873f.png

Any idea what could be causing this?

**Comment by iwasherefirst2** [comment]
What you posted looks correct, it should work like this. I tried to reproduce your issue but I can't, it works when I try it https://github.com/mcamara/laravel-localization/issues/502#issuecomment-546670758

However, what strikes me is that you model `Pigeon` does not exist:

![grafik](https://user-images.githubusercontent.com/1765602/67631784-f7f21400-f89a-11e9-855d-749c48aa6fcc.png)

If there is no model with a given slug, then the route should return `404` error, not sure why you get a new `Pigeon` model. Do you have setup a custom model-binding method?

**Comment by aFluxx** [comment]
I'm using `"version": "1.4.6"`.

I will try this out in a fresh install, I did some testing in the project and it seemed to be working.
I'll let you know once I found the time to try it out! Thanks for looking into this.
