### ISSUE TITLE
Question about trailing slash for SEO

### ISSUE THREAD

**Issue by InfinityWebMe** [mcamara/laravel-localization#633]
Hello,

i have a dummy question ^^ 

I use the package but this route works on the same content :
=> **http://example.test/en/** and **http://example.test/en**
=> **http://example.test/en/about/** and **http://example.test/en/about**

It's normal ? It's not a issue to SEO with duplicate content on the same uri ? 

Thanks a lot :)

**Comment by iwasherefirst2** [comment]
Its not a dummy question, but this has nothing to do with this package.

In the `public/.htaccess` file urls with trailing slashes should be redirected to the same url without trailing slashes:
```
# Redirect Trailing Slashes If Not A Folder...
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} (.+)/$
RewriteRule ^ %1 [L,R=301]
```

Thus http://example.test/en/ should redirect to http://example.test/en. Thus you do not have duplicate content.

Another thinks to avoid duplicate content is to make sure that you also have a redirect set from  http://www.example.test/en to  http://example.test/en (or the other way around). Also if you use an SSL you should also always redirect to https:/ version.

**Comment by InfinityWebMe** [comment]
Thanks ;-)
