### ISSUE TITLE
Query string is not maintained when hideDefaultLocaleInURL is true!

### ISSUE THREAD

**Issue by adrienne** [mcamara/laravel-localization#634]
## Behavior: 

When I have a URL of the form `/en/products?filter=1` , and `/en/` is my default locale, I am redirected to `/products` (with no query string). 

## Steps to reproduce:

1. Set `hideDefaultLocaleInURL` set to `true`
2. Set your default locale to `en`
3. Set up a localized GET route
4. Visit `/en/yourNewRoute?test=1`

## Desired behavior:

When I visit `/en/products?filter=1`, I should be redirected to `/products?filter=1`.

## Other info:

Here is my `/routes/web.php` file:

```
<?php

Route::group(
    [
      'prefix' => LaravelLocalization::setLocale(),
      'middleware' => ['localize', 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
    ],
    function () {

      // PRODUCTS SECTION
      Route::get(LaravelLocalization::transRoute('routes.products'), 'ProductController@showIndex');

// END LOCALIZED ROUTES GROUP
});


```

**Comment by adrienne** [comment]
Never mind, I think this was user error. There's a related issue that I will submit separately.

**Comment by adrienne** [comment]
Ping @mcamara - any help for this?

**Comment by iwasherefirst2** [comment]
This can be solved quickly by the `LaravelLocalizationRedirectFilter.php` middleware.

**Comment by iwasherefirst2** [comment]
For forms that I have to localize I created a `getLocaleBeforeUrl` helper:

```
function getLocaleBeforeUrl()
{
    $locale = session('locale');
    $locale = ($locale == 'en' || empty($locale)) ? null : '/' . $locale;

    return $locale;
}
```

and use it forms like this

    <form method='GET' action='{{getLocaleBeforeUrl()}}/products` >

This works for both POST & GET and they won't get redirected.

**Comment by iwasherefirst2** [comment]
This issue only seems to happen with translated routes. Btw, if you would localize your url's inside your blade, there would be no redirect in the first place.

The call

    {{  \LaravelLocalization::localizeURL('/en/products?filter=1') }} 

would produce the url

    /products?filter=1
