### ISSUE TITLE
unexpected order of languages keys

### ISSUE THREAD

**Issue by BramEsposito** [mcamara/laravel-localization#637]
```LaravelLocalization::getSupportedLanguagesKeys()``` does not respect ```localesOrder``` from laravellocation.php config file.

## How to reproduce
Activate 'fr' and 'nl' languages ```supportedLocales``` but set ```localesOrder``` as ```['nl','fr']``` in  laravellocation.php 

## Expected result
```LaravelLocalization::getSupportedLanguagesKeys()``` returns ```['nl','fr']``` as defined in ```localesOrder```

## Actual behaviour 
```LaravelLocalization::getSupportedLanguagesKeys()``` returns ```['fr','nl']```. This is the order in which the items appear in ```supportedLocales```

## Workaround: 
reorder the items in the ```supportedLocales``` array

**Comment by ergonomicus** [comment]
It's not very intuitive, but you should call `LaravelLocalization::getLocalesOrder()` instead of getSupportedLanguagesKeys().

**Comment by BramEsposito** [comment]
thanks @ergonomicus ! ```LaravelLocalization::getLocalesOrder()``` returns the Language objects, but ```array_keys(LaravelLocalization::getLocalesOrder())``` is a drop-in replacement, with ordered languages 😃
