### ISSUE TITLE
Method Illuminate\Routing\UrlGenerator::segment does not exist.

### ISSUE THREAD

**Issue by JuhG** [mcamara/laravel-localization#641]
Hello!

Somehow the `$request` property isn't properly set, so all the related methods fail.
`/src/Mcamara/LaravelLocalization/LaravelLocalization.php:159`

Everything works locally, this happened after deploying to a server. (forge+do)
I tried to follow the documentation closely.

Any idea what could have gone wrong here?

Thank you!

**Comment by iwasherefirst2** [comment]
Sorry I am not using `forge`. Did you manage to fix it ?

**Comment by JuhG** [comment]
I'm not entirely sure about this one. It's fixed, probably was related to another package. But it's definitely unrelated, sorry about that.

**Comment by asterism612** [comment]
How to solve this problem?
