### ISSUE TITLE
Wrong mapping to localesmapping in negotiateLanguage

### ISSUE THREAD

**Issue by jacobnijgh** [mcamara/laravel-localization#652]
In het example of the config for localesMapping the following is used:
`['de-AT' => 'at']`

Which maps `at` to `de-AT` in the supported languages array.

When a request is received with the Accept-Language `de-AT` it is getting reversed to `at`:
`$key = ($this->configRepository->get('laravellocalization.localesMapping')[$key]) ?? $key;`

Which results in a unsupported language and thus makes a fallback to the default locale is this supposed to happen?

**Comment by iwasherefirst2** [comment]
Yes this is supposed to happen. If you use `'localesMapping' => ['de-AT' => 'at'],` it simply means that  `url.com/de-AT/about` wont work anymore, you can only access Austrain German through `url.com/at/about`. Also if the language from the browser is recognized as `Austrain German`, you will be redirected to the url containing `/at/`
