### ISSUE TITLE
Map locale in negotiation to another available locale

### ISSUE THREAD

**Issue by gsabater** [mcamara/laravel-localization#663]
Hello,

I have been searching a lot of issues, but i havent been able to find anything similar to my needs.
My website has two available locales, `ES` and `EN`, and `EN` is the default locale.

Everything is working as expected and all, but my client has asked me to set the default locale as `ES` instead of `EN` when the client has set `CA` in his browser.

Setting a mapping from ca to es has worked on the homepage but breaks all the other urls.
```
'localesMapping' => [
        'ca' => 'es',
    ],
```

How can I achieve this?
Thanks

**Comment by iwasherefirst2** [comment]
`

> but breaks all the other urls.

What exactly is not working when you setup the mapping? Do you experience the same issue as in #652 ?

**Comment by gsabater** [comment]
Hello @iwasherefirst2 

Without the mapping, my website has this structure:
```
web.com/es/about
web.com/es/contact
web.com/en/about
web.com/en/contact
```

The default locale for my website is `en`, but my client wants the special case that if the browser locale is `ca` set the default locale to `es`.

With the mapping, the package replaces all the `/es/...` urls to `/ca/...` and accessing a page like `web.com/ca/about` returns 404

I hope its more clear now

**Comment by onemoreahmad** [comment]
@gsabater what if you duplicate the es language and just change the key to 'ca' and add it as a third language in the supportedLocales, but in reality it's just 'es', so then you'll have three language en, es and ca 

`         'es'          => ['name' => 'Spanish',                'script' => 'Latn', 'native' => 'español', 'regional' => 'es_ES'],
`
to 

`         'ca'          => ['name' => 'Spanish',                'script' => 'Latn', 'native' => 'español', 'regional' => 'es_ES'],
`

Haven't tested it but I think it may work.

**Comment by iwasherefirst2** [comment]
> The default locale for my website is `en`, but my client wants the special case that if the browser locale is `ca` set the default locale to `es`.
> 
> With the mapping, the package replaces all the `/es/...` urls to `/ca/...` and accessing a page like `web.com/ca/about` returns 404

In this case, you can't use `localesMapping`. It only works for renaming locales, not for redirecting them to other locales.

I would suggest you enable `ca` in `supportedLocales` and that you write a custom middleware that redirects `ca` to `es`:

```
public function handle($request, Closure $next)
    {
        $locale = session('locale', false);

        if ($locale == 'ca') {
            session(['locale' => 'es']);
            $redirection = app('laravellocalization')->getLocalizedURL('es');

            return new RedirectResponse($redirection, 302, ['Vary' => 'Accept-Language']);
        }

        return $next($request);
    }
```
