### ISSUE TITLE
Get supportedLanguages from DB instead of config file 

### ISSUE THREAD

**Issue by mucskaati** [mcamara/laravel-localization#680]
Hello,

Is there any solution to get supportedLanguages from database and not directly from config file?

Thanks.

**Comment by Briareos17** [comment]
I made it using folowing approach:

I made CRUD for language management and added followind lines in `AppServiceProvider::boot()`

     if (Language::getItems()->count()) {
            \Illuminate\Support\Facades\Config::set('app.locale', Language::getDefault('code'));
            \Illuminate\Support\Facades\Config::set('app.fallback_locale', Language::getDefault('code'));
            \Illuminate\Support\Facades\Config::set('translatable.fallback_locale', Language::getDefault('code'));
            \Illuminate\Support\Facades\Config::set('laravellocalization.localesOrder', Language::getList('code')->toArray());
            \Illuminate\Support\Facades\Config::set('translatable.locales', Language::getList('code')->toArray());
    }

**Comment by iwasherefirst2** [comment]
The problem is, if you set locales dynamically you can't cache the routes. And the number of your routes is multiplied by the number of languages, so its not recommended to do it without caching the routes.

If you want to add this feature in admin dashboard, best option is probably to actually rewrite config file and re-cache routes. If you can live without cache, then Briareos17's solution is the way to go.

**Comment by Briareos17** [comment]
> The problem is, if you set locales dynamically you can't cache the routes. And the number of your routes is multiplied by the number of languages, so its not recommended to do it without caching the routes.
> 
> If you want to add this feature in admin dashboard, best option is probably to actually rewrite config file and re-cache routes. If you can live without cache, then Briareos17's solution is the way to go.

I'm using redis caching for database queries, also using cache for routes and recommended package for translations route cache, All work fine for about 4 years on three big projects.

**Comment by iwasherefirst2** [comment]
> > The problem is, if you set locales dynamically you can't cache the routes. And the number of your routes is multiplied by the number of languages, so its not recommended to do it without caching the routes.
> > If you want to add this feature in admin dashboard, best option is probably to actually rewrite config file and re-cache routes. If you can live without cache, then Briareos17's solution is the way to go.
> 
> I'm using redis caching for database queries, also using cache for routes and recommended package for translations route cache, All work fine for about 4 years on three big projects.

Are you saying that you change dynamically `supportedLocales`  like this

     \Illuminate\Support\Facades\Config::set('laravellocalization.supportedLocales', $newLocales);

and then you are able to re-cache the translations route? If so, I would be interested how that works without modifying `supportedLocales`

**Comment by Briareos17** [comment]
Simply call artisan command `php artisan route:trans:cache` from Language model observer on saved event.

**Comment by iwasherefirst2** [comment]
If you just use it from memory, then the languages will be overwritten the next time that you cache - or how do you avoid this? I guess most people recache automatically during deployment process.

Thus I think the proper solution to this is to have something like this is `config/laravellocalization.php`:

```
<?php

return [

    // Uncomment the languages that your site supports - or add new ones.
    // These are sorted by the native name, which is the order you might show them in a language selector.
    // Regional languages are sorted by their base language, so "British English" sorts as "English, British"
    'supportedLocales' => json_decode(file_get_contents(base_path('stubs/supportedLocales.json')), true);
```

and then recache from memory + reqrite `supportedLocales.json` or something.
