### ISSUE TITLE
Translated route with optional parameter doesn't work.

### ISSUE THREAD

**Issue by pawelsome** [mcamara/laravel-localization#681]
Hi, do you support optional parameters in translated routes?
I declared the route like this:
`
"results" => "results/{lottery_draws?}",
`

But I can't make it working, the route "/results" is working, but when i go to "/results/1" - i get 404 page.

Package: 1.4.7
Laravel: 5.8

**Comment by niels-numbers** [comment]
See https://github.com/mcamara/laravel-localization/issues/933, its a duplicate
