### ISSUE TITLE
Translatable route parameters: what am I missing ?

### ISSUE THREAD

**Issue by jbajou** [mcamara/laravel-localization#682]
Hello,

Laravel: 5.8
laravel-localization: 1.4.7
php: 7.3

I'm using this package since a long time ago and I decided to upgrade to 1.4.7 to use the new translatable route parameters, which I have issue to get working.

My route is defined as follow (routes/web.php):
```php
Route::group([
	'prefix'		=> LaravelLocalization::setLocale(),
	'middleware'	=> ['localize', 'localeSessionRedirect', 'localizationRedirect', 'localeCookieRedirect']
], function () {
	Route::get(LaravelLocalization::transRoute('routes.help-article'), ['uses' => 'HelpArticleController@show']);
});
```

My language specific translation file contains the following line for english:
```php
	'help-article'					=> 'help/article/{slug}',
```
and the following for french:
```php
	'help-article'					=> 'aide/article/{slug}',
```

My `HelpArticle` models implements `LocalizedUrlRoutable` and I overwrote the `resolveRouteBinding` methods as per [the docs](https://github.com/mcamara/laravel-localization#translatable-route-parameters).

Problem is that the link generated is:
`https://localhost/en/help/article/what-if-i-need-to-cancel-because-of-an-emergency-or-unavoidable-circumstance?helpArticle=22`
which leads to issues like model binding not being resolved. Both `resolveRouteBinding` and `getLocalizedRouteKey` are not called from my model when generating the route.

Any help would be much appreciated. What am I missing ?
Thanks in advance

**Comment by iwasherefirst2** [comment]
How did you implement `resolveRouteBinding` and `getLocalizedRouteKey` ?

The first one needs to return the model,
the other needs to return a string. I just created an example and everything seems to work

**Comment by iwasherefirst2** [comment]
I created a youtube video how to set it up [here](https://youtu.be/B1AUqCdizgc ) maybe it helps

**Comment by iwasherefirst2** [comment]
Readme of [translatable url](https://github.com/mcamara/laravel-localization#translated-routes) has been improved.

**Comment by jbajou** [comment]
Hi, sorry to reopen this, I have a related problem, though slightly different (your update helped a lot thanks for that, btw).

Here is the english url: `domain.tld/en/eshop/category/clothing/men/sweaters`

Here is the route related to this page:
```php
[...]
Route::get(
	LaravelLocalization::transRoute('routes.eshop-category'), 
		['uses' => 'Eshop\CategoryController@show'])
	->where('path', '[a-zA-Z0-9\-\/_]+');
```
routes.php contains the following line:
```php
'eshop-category'				=> 'category/{path}',
```
I need the where() here to make sure the complete slug `clothing/men/sweaters` is given to the stack.

The `Category` model implements '\Mcamara\LaravelLocalization\Interfaces\LocalizedUrlRoutable' properly and the followings are defined:

```php
public function getLocalizedRouteKey($locale)
public function resolveRouteBinding($slug)
```

For some reasons, they are never called! I think the issue is related to the route as other routes with slugs not containing any `/` are working properly but I cannot put my finger on it.

Any idea ?
