### ISSUE TITLE
Sharing localized link to social media

### ISSUE THREAD

**Issue by mucskaati** [mcamara/laravel-localization#685]
Hello,

I have troubles with sharing localized link for example to Facebook.
When I am debugging link with FB Share debugger it throws that I have too many redirects.

Route which I am debugging is in following route group:
`Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]], function()
{
Route::get('/projects-reference/{id}/{slug}', 'Frontend\ReferencesController@showReference')->name('references.show');
}`

I have correctly defined OG:URL to subpage url.

Here is the FB debugger screen:
[https://imgur.com/25BQRAh](https://imgur.com/25BQRAh)

Thanks.

**Comment by iwasherefirst2** [comment]
I believe such questions should rather be posted on StackOverflow or similar sites, we would like to keep the issues here only for bugs and features.

Still, maybe you can explain whats the url that you try to call and where does it get redirect to? Is it a url to your page or to facebook?
