### ISSUE TITLE
Default locale prefix in URL with 'hideDefaultLocaleInURL' enabled in tests

### ISSUE THREAD

**Issue by dobrik-ardas** [mcamara/laravel-localization#686]
**Describe the bug**

**To Reproduce**
1. Write test by this documentation https://github.com/mcamara/laravel-localization#testing
2. call refreshApplicationWithLocale method with default locale prefix
3. call route('some_route_name')
4. See generated URL with default locale prefix, which must be hidden.

**Expected behavior**
See generated URL without default prefix.

**More info:**
- Version of Laravel 5.8.35
- Version of the Laravel-localization package 1.4.7
- Which middleware is used in `Route::groups` web
- Copy of the config file ( or at least setting of `supportedLocales`, `useAcceptLanguageHeader` and `hideDefaultLocaleInURL`). 
 'hideDefaultLocaleInURL' => true,
'useAcceptLanguageHeader' => true,

- Minimal steps to reproduce on a clean Laravel installation.

**Additional context**

**Comment by iwasherefirst2** [comment]
Sorry I don't understand the problem. Please provide the code from your `test` and specify what is not working.
