### ISSUE TITLE
Add support for en_CA

### ISSUE THREAD

**Issue by xitude** [mcamara/laravel-localization#687]
**Describe the bug**
Cant find en_CA in the list of locale for English Canada

**To Reproduce**
Review config

**Expected behavior**
To See en_CA

**More info:**
[Google Search that en_ca or en-ca is default lang](https://www.google.com/search?q=canada+default+url+locale&oq=canada+default+url+locale&aqs=chrome..69i57.8202j0j7&sourceid=chrome&ie=UTF-8)

**Additional context**

**Comment by mcamara** [comment]
Even if it's not in the default config file, it can be added in your app config file and will work flawlessly 😄

**Comment by xitude** [comment]
> Even if it's not in the default config file, it can be added in your app config file and will work flawlessly 😄

Would you like me to add it in a PR and submit it?

**Comment by mcamara** [comment]
That would be really nice 🎉 

Thanks!

**Comment by xitude** [comment]
Closing the issue as PR is submitted feel free to continue commenting on that if I miss understood whats needed for supporting it.
