### ISSUE TITLE
Route model binding is not work

### ISSUE THREAD

**Issue by ExsyDev** [mcamara/laravel-localization#690]
**Describe the bug**
Route model binding is not working, why?

**To Reproduce**
In web.php:

`Route::get('/page/{page}', function (App\Page $page) {
   return $page;
});`

return is not exists model. When I remove middleware `localize` all working. How I can fix it?

My model Page:

     use Spatie\Translatable\HasTranslations;

     class Page extends Model
    {
          use HasTranslations;

          protected $guarded = [];
          protected $translatable = ['title', 'description', 'keywords', 'body'];

          public function getRouteKeyName()
          {
               return 'slug';
          }

          public function path()
          {
               return "/" . app()->getLocale() . "/page/{$this->slug}";
          }
      }

**Comment by iwasherefirst2** [comment]
I think you posted this in the wrong repository. You seem to use https://github.com/spatie/laravel-translatable

**Comment by Dronax** [comment]
@iwasherefirst2 no. When I remove this middleware:

            ->middleware(['localize', 'localeCookieRedirect', 'localizationRedirect', 'localeViewPath'])

all working good.

**Comment by iwasherefirst2** [comment]
Still having the issue? Did you follow the steps and the video from https://github.com/mcamara/laravel-localization#translated-routes ?
Can you show us the relevant code sections that are mentioned in the guide/video?

**Comment by iwasherefirst2** [comment]
Hi, since there hasn’t been any follow-up to my last question, I’ll go ahead and close this issue for now. If you’re still encountering the problem, feel free to reopen. Thanks!
