### ISSUE TITLE
how to add prefix

### ISSUE THREAD

**Issue by mertbuldur** [mcamara/laravel-localization#691]
Hello ,  i am using this package  but i want to add prefix in url 
example;

https://siteadi.com/en/avusturalia 
https://siteadi.com/en/france
or 
 https://siteadi.com/avusturalia/en/
https://siteadi.com/france/en/

how to make this prefix ? thanks for help

**Comment by iwasherefirst2** [comment]
Prefixes are only possible directly after your domain. So

    https://siteadi.com/en/avusturalia
    https://siteadi.com/en/france

will work.

See https://github.com/mcamara/laravel-localization#usage for an example.

**Comment by mertbuldur** [comment]
@iwasherefirst2  okey i am using this but session not working  prefix ?

**Comment by mertbuldur** [comment]
Route::group(['prefix'=>\App\Helper\mHelper::getCountryCode()],function () { not working
\App\Helper\mHelper::getCountryCode() returned "france , avusturalia"

**Comment by iwasherefirst2** [comment]
You have to use 

```
Route::group(['prefix' => LaravelLocalization::setLocale()], function()
{
```
