### ISSUE TITLE
make public method LaravelLocalization::useAcceptLanguageHeader()

### ISSUE THREAD

**Issue by Cyrille37** [mcamara/laravel-localization#692]
Hello,
And thanks a lot for your really great work.

Please, could the method LaravelLocalization::useAcceptLanguageHeader() be public, to permit LaravelLocalization's configuration access from other classes ?

Cheers, Cyrille.

**Comment by iwasherefirst2** [comment]
You can access it from outside like this:

    LaravelLocalization::getConfigRepository()->get('laravellocalization.useAcceptLanguageHeader');
