### ISSUE TITLE
Domain based locale and hide default locale in URL

### ISSUE THREAD

**Issue by koichirose** [mcamara/laravel-localization#693]
I'm currently using my own middleware to determine the locale (based on the domain name).

I'm then calling `LaravelLocalization::setLocale($my_locale)` to set it, but if `$my_locale` is not the default one (set in `app/config.php`), then all URLs have `$my_locale` as the first segment.

Is there a way to avoid that? I tried setting the config entry `app.locale` but it seems that LaravelLocalization comes before that and "caches" the default locale before I can update it.

I tried searching around but could not find anything.

**Comment by Nuranto** [comment]
Hello @koichirose 
Have a look here : #609 
However my solution does not work for caching translated routes... 
So it would be great to have some config setting for this. 

@mcamara If I work on this functionnality and PR, would you accept it ?

**Comment by mcamara** [comment]
@Nuranto yes, of course! Any help is welcomed 🙂

**Comment by Nuranto** [comment]
Ok @mcamara :) I just investigated my issue, and found the issue.
However, I will need your help here, before I can PR any fix.
I will create a new issue for this.

**Comment by Nuranto** [comment]
#712

**Comment by iwasherefirst2** [comment]
Closing this as the cache modification is discussed in #712
