### ISSUE TITLE
Tests not working

### ISSUE THREAD

**Issue by sukiyanen85** [mcamara/laravel-localization#694]
**Can't run tests using localization**

After reading your documentation I have added the following code to the /tests/TestCase.php file:

    protected function refreshApplicationWithLocale($locale)
    {
        self::tearDown();
        putenv(LaravelLocalization::ENV_ROUTE_KEY . '=' . $locale);
        self::setUp();
    }

    protected function tearDown()
    {
        putenv(LaravelLocalization::ENV_ROUTE_KEY);
        parent::tearDown();
    }

When I run the test it returns:

`Fatal error: Declaration of Tests\TestCase::tearDown() must be compatible with Illuminate\Foundation\Testing\TestCase::tearDown(): void`

**Expected behavior**
According to the documentation, we should be able to run tests with localization after adding this code

**More info:**
- Version of Laravel 6.12.0
- Version of the Laravel-localization package: 1.4

**Comment by yamenarahman** [comment]
```
protected function tearDown() : void
```

**Comment by sukiyanen85** [comment]
I have added the :void to tearDown() function

protected function tearDown() : void

I'm trying to test that an email is sent when we fill the contact form. However when I run this test:

```
class ContactsControllerTest extends TestCase
{
    public function test_contact_email_is_sent(){
        $this->refreshApplicationWithLocale('en');
        Mail::fake();

        $response = $this->post(route('contacts.store'), [
            'name'       => 'Test',
            'country_id' => 1,
            'phone'      => '123456789',
            'email'      => 'email@email.com',
            'message'    => 'This is the message, with 15 characters',
            '_token'     => Session::token()
        ]);

        $response->dump();
        $response->assertSessionHasErrors();

        Mail::assertQueued(ContactMail::class);
    }
}
```

The dump() is showing:

> Redirecting to <a href="http://localhost">http://localhost</a>.

This is my store function:

```
    public function store(ContactAddRequest $contact){
        Mail::send(new ContactMail($contact));

        session()->flash('success', __('Thank you for your contact. We will reply you as soon as possible'));

        return redirect(route('contacts.index'));
    }
```

And my route:
`Route::post(LaravelLocalization::transRoute('routes.contacts'), 'ContactsController@store')->name('contacts.store');`

**Comment by kenmaclord** [comment]
Same problem here, the Redirect Response Url is empty. Let's imagine this story :
url: /order
localized url : /fr/order
redirect url (if unauthenticated) : /fr/login

In my tests, I expect a testing workflow like this :
$this->get('/order')
   ->assertStatus(302)
   ->assertRedirect('/login');

But it doesn't work. The response location says '/fr'

I find this package very difficult to test. Anyone has an idea to make that easier ?

**Comment by iwasherefirst2** [comment]
It’s difficult to determine what’s happening without seeing the code being tested. One possible pitfall could be related to the hideDefaultLocaleInURL option. If this is enabled, you may encounter redirects that need to be followed during testing.

Testing with the current setup is indeed challenging. However, there are plans to simplify this in version 3, as outlined in [Issue #921](https://github.com/mcamara/laravel-localization/issues/921).

Since this issue is more than 4 years old and the OP's questions appear to have been addressed, I’ll close this for now. If new questions or issues arise, feel free to open a new discussion.
