### ISSUE TITLE
After logout locale is changing

### ISSUE THREAD

**Issue by araspel** [mcamara/laravel-localization#698]
#Laravel **Framework 6.16.0**
Every time I log out of the app the language changes, I have to keep the language that the user has chosen.

Notice* **useAcceptLanguageHeader** and **hideDefaultLocaleInURL** both of these are true

However, I have resolved this issue to save the session language data before leaving the app. When the session is invalidated I reset the previously saved language setting to the session like this

File path

> vendor\laravel\framework\src\Illuminate\Foundation\Auth\AuthenticatesUsers.php

```
 public function logout(Request $request)
    {
        $this->guard()->logout();
        
        //saving current lang param
        $currentLang = app()->getLocale();

        $request->session()->invalidate();

        $request->session()->regenerateToken();

        //putting back lang param after invalidate session
        $request->session()->put('locale', $currentLang);

        return $this->loggedOut($request) ?: redirect('/');
    }

```

**Comment by iwasherefirst2** [comment]
You need to localize your logout route. See https://github.com/mcamara/laravel-localization#post-is-not-working
