### ISSUE TITLE
Laravel 7.x support

### ISSUE THREAD

**Issue by vladimirzhukov** [mcamara/laravel-localization#699]
Laravel 7.x is so close to release, so it would be great if Laravel Localization will support it.

**Comment by rjsworking** [comment]
Laravel 7 is now released

**Comment by EmreCaliskan1** [comment]
when will support come ?

**Comment by gsabater** [comment]
There are already multiple pull requests open.
Someone should tell @mcamara about it

**Comment by mcamara** [comment]
I released version 1.5 a few hours ago, it supports the latest version of Laravel 🎉
