### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by Meti27** [mcamara/laravel-localization#707]
`"mcamara/laravel-localization": "^1.4"`

laravel : `6.5`

thanks for awesome package.
i have some problem with `localizeUrl` method.
when is say : 
```
LaravelLocalization::localizeUrl('partner/بخش');
// return {locale}/partner/بخش
LaravelLocalization::localizeUrl('partner/orSomeOtherPesianCharachters');
//  works good
```
but if i use a word that contains  'ح' charachter : 
```
LaravelLocalization::localizeUrl('partner/محمد')

//return  this error 
Malformed UTF-8 characters, possibly incorrectly encoded
```
and in ` laravelLocalization.php ` the `utf8suffix` :
```
'utf8suffix' => env('LARAVELLOCALIZATION_UTF8SUFFIX', '.UTF-8'),
```
thanks in advance.

Edited : 
i cahnge `utf8suffix` to `utf8` and on centos its ok and the result is like this: 
![image](https://user-images.githubusercontent.com/11253027/76089148-67f17300-5fce-11ea-81f1-bea9763ad42c.png)

and for windows i change the `utf8suffix` to blank as the document say : 
```
'utf8suffix' => '',
```
but the result is not good: 
![image](https://user-images.githubusercontent.com/11253027/76089374-c880b000-5fce-11ea-9678-5edf495baff0.png)

and one windows if i set the `utf8suffix` on `.UTF-8` or `.utf8` the result is the same.

**Comment by iwasherefirst2** [comment]
I am not familiar with this characters, sorry. For windows, you are using a different url (localhost) then for centors (production url). You sure you didn't mix it? The encoding should not rely on the OS. 

Maybe you just returned the url in development with out setting the proper content-type. Please show source code. It needs `<meta http-equiv="Content-Type" content="text/html; charset=utf-8">`
