### ISSUE TITLE
Cache route issue

### ISSUE THREAD

**Issue by Nuranto** [mcamara/laravel-localization#712]
Caching route does not work when using priority of routes.
For instance, having : 

```
some/route
{var1}/{var2}
```
The route /some/route works fine without cache, but will fail in 404 with cache.

The issue seems to be caused by the routes.php cache file, produced by this line : 
```array_push($allLocales, null);``` in RouteTranslationsCacheCommand class.
When removing that line, the routes.php cache file is not generated, and the route works fine again.

The problem is probably that loading both of thoses files will load two list of routes  : 
```
some_default_lang/route_default_lang
{var1}/{var2}
some_other_lang/route_other_lang
{var1}/{var2}
```
And so, `some_default_lang/route_default_lang` route will works fine but `some_other_lang/route_other_lang` will never match.

So I wanted to PR a fix where we just remove this line ```array_push($allLocales, null);```... But there must be a reason why you put it in the first place, right ?

**Comment by iwasherefirst2** [comment]
`null` is for the urls that are created when no locale is given. 

So assuming you only use `en` your routes should look like this:

en/some_default_lang/route_default_lang
en/{var1}/{var2}
some_other_lang/route_other_lang
{var1}/{var2}

**Comment by Nuranto** [comment]
no locale given ? Is that possible ?

And your example would work indeed, but you're assuming that `hideDefaultLocaleInURL` is set to false.

**Comment by Nuranto** [comment]
I should have precised : 
I have multiple-domain app. Each domain has a different default locale. And hideDefaultLocaleInURL is set to true.

**Comment by iwasherefirst2** [comment]
If you don't pass any locale in your url, then `App::getLocale()` is empty, giving your a route without locale.

It is described in the docs here: https://github.com/mcamara/laravel-localization#usage

The setting of `hideDefaultLocaleInURL` is something different. If set to true, it means `example.net/en/article` is redirected to `example.net/article` if no locale is given. 

If you use the Middleware `LocaleSessionRedirect` as recommended, then accessing a url without locale would redirect it to an url with locale.

**Comment by Nuranto** [comment]
> If you don't pass any locale in your url, then `App::getLocale()` is empty, giving you a route without locale.

Hmmm. If I don't pass any locale in my url, then `App::getLocale()` is `config('app.locale')`, isn't it ?

> 
> It is described in the docs here: https://github.com/mcamara/laravel-localization#usage
> 
> The setting of `hideDefaultLocaleInURL` is something different. If set to true, it means `example.net/en/article` is redirected to `example.net/article` if no locale is given in url and if `en` is the default locale.
> 
> If you use the Middleware `LocaleSessionRedirect` as recommended, then accessing a url without locale would redirect it to an url with locale.

I do use `localeSessionRedirect` and `localizationRedirect` (and `localize`) middlewares.
Thing is I don't use `/{lang}` for all areas of my app.
I have this  : 

First area : 
www.main-domain.com  (fr - app.locale = fr)
www.main-domain.com/en (en - app.locale = fr)

Second area :
www.other-domain.com (en - app.locale = en)
www.autre-domaine.com (fr - app.locale = fr)
www.anderer-domainname.de (de - app.locale = de)

To use again my previous example, I have this : 
www.other-domain.com/some/route
www.autre-domaine.com/une/route
www.anderer-domainname.de/eine/route

So, concatenating the routes files for DE for instance, I get 
```
some/route
{var1}/{var2}
eine/route
{var1}/{var2}
```

So www.anderer-domainname.de/eine/route fall in 404.


In my first area, which is a more common case, if I remove the `array_push($allLocales, null);`, I still have `routes_fr.php` and `routes_en.php` which seems enough too ?

**Comment by Nuranto** [comment]
Ok, just see that comment... I read multiple times, and missed it multiple times -_-

```// Set application language to English or Spanish (depending on browsers default locales)
// if nothing found set to default locale
http://url-to-laravel
http://url-to-laravel/test```

That seems like a bug to me....  Why does It not directly use the default locale ?

Well, anyway that's another issue.

**Comment by iwasherefirst2** [comment]
> > If you don't pass any locale in your url, then `App::getLocale()` is empty, giving you a route without locale.
> 
> Hmmm. If I don't pass any locale in my url, then `App::getLocale()` is `config('app.locale')`, isn't it ?

Whoups sorry, I meant `LaravelLocalization::setLocale()` instead of `App::getLocale`.

Its in the docs of the function: https://github.com/mcamara/laravel-localization/blob/13f418e481ed06f482e4fca87ec5ff67c2949373/src/Mcamara/LaravelLocalization/LaravelLocalization.php#L153

> @return string Returns locale (if route has any) or null (if route does not have a locale)

Thus, if the url has no locale, then Route group has no prefix:

```
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect'],],function () { 
...
});
```


> Ok, just see that comment... I read multiple times, and missed it multiple times -_-
> 
> ```
> // Set application language to English or Spanish (depending on browsers default locales)
> // if nothing found set to default locale
> http://url-to-laravel
> http://url-to-laravel/test
> ```
> 
> That seems like a bug to me.... Why does It not directly use the default locale ? No one would want that kind of behaviour.
> 
> Added to that, that behaviour is only true if `useAcceptLanguageHeader` is set to true, right ?

Yes. So if you want to auto-detect the language from browser (most people want that behaviour) than this what you do. If you disable `useAcceptLanguageHeader`, it will use default locale and possibly redirect.

**Comment by iwasherefirst2** [comment]
> I do use `localeSessionRedirect` and `localizationRedirect` (and `localize`) middlewares.
> Thing is I don't use `/{lang}` for all areas of my app.
> I have this :
> 
> First area :
> [www.main-domain.com](http://www.main-domain.com) (fr - app.locale = fr)
> [www.main-domain.com/en](http://www.main-domain.com/en) (en - app.locale = fr)
> 
> Second area :
> [www.other-domain.com](http://www.other-domain.com) (en - app.locale = en)
> [www.autre-domaine.com](http://www.autre-domaine.com) (fr - app.locale = fr)
> [www.anderer-domainname.de](http://www.anderer-domainname.de) (de - app.locale = de)
> 
> To use again my previous example, I have this :
> [www.other-domain.com/some/route](http://www.other-domain.com/some/route)
> [www.autre-domaine.com/une/route](http://www.autre-domaine.com/une/route)
> [www.anderer-domainname.de/eine/route](http://www.anderer-domainname.de/eine/route)
> 
> So, concatenating the routes files for DE for instance, I get
> 
> ```
> some/route
> {var1}/{var2}
> eine/route
> {var1}/{var2}
> ```
> 
> So [www.anderer-domainname.de/eine/route](http://www.anderer-domainname.de/eine/route) fall in 404.
> 
> In my first area, which is a more common case, if I remove the `array_push($allLocales, null);`, I still have `routes_fr.php` and `routes_en.php` which seems enough too ?

Could you provide a minimal example and show us the code in `routes/web.php` ?

Are you using [translatable routes](https://github.com/mcamara/laravel-localization#translated-routes)?

I don't understand why the cache should not work on your app.

**Comment by drakakisgeo** [comment]
I have also a problem with caching routes, I get 404 for route that is there.

**Comment by Nuranto** [comment]
(sorry, i don't have time for a minimal example right now because of recent events, but I will do as soon as I can..)

**Comment by iwasherefirst2** [comment]
Fixed with https://github.com/mcamara/laravel-localization/commit/0ec9e75c551ce9e5fa094e4c8034bdad13c59b3b
