### ISSUE TITLE
Translatable route parameters with multi-level slug

### ISSUE THREAD

**Issue by jbajou** [mcamara/laravel-localization#716]
Hi, I'm having issues with [translated routes](https://github.com/mcamara/laravel-localization#translated-routes) with a slug containing `/`.

Here is the english url: `domain.tld/en/eshop/category/clothing/men/sweaters`

Here is the route related to this page:
```php
[...]
Route::get(
	LaravelLocalization::transRoute('routes.eshop-category'), 
		['uses' => 'Eshop\CategoryController@show'])
	->where('path', '[a-zA-Z0-9\-\/_]+');
```
I need the where() here to make sure the complete slug `clothing/men/sweaters` is given to the stack.

routes.php contains the following line:
```php
'eshop-category'				=> 'category/{path}',
```

The `Category` model implements `\Mcamara\LaravelLocalization\Interfaces\LocalizedUrlRoutable` properly and the followings are defined:

```php
public function getLocalizedRouteKey($locale)
public function resolveRouteBinding($slug)
```

For some reasons, they are never called! I think the issue is related to the route as other routes with slugs not containing any `/` are working properly but I cannot put my finger on it.

Any idea ?

**Comment by simeonbugarija** [comment]
Is it maybe because your URL starts with "eshop" and your trans value for the key "eshop-category" starts with "category"?

**Comment by jbajou** [comment]
URL is in a group with the prefix set to "eshop" so I doubt it

**Comment by simeonbugarija** [comment]
It's not working with route group prefixes. You need to remove that route group with prefix and add that prefix to the translation file, then it will work. 

Instead of
`'eshop-category'				=> 'category/{path}',`
you need to use
`'eshop-category'				=> 'eshop/category/{path}',`

I have a similar use case in my project and it's working when you use it this way.

**Comment by jbajou** [comment]
Thanks @simeonbugarija you were completely right. I haven't seen anything related to this in the docs though.
Anyway, I'm one step further now, and having an issue with the following routes:
```
'eshop-product' => 'eshop/category/{eshopCategory}/{eshopProduct}',
```
where the route is defined as follow:
```
Route::get(
        LaravelLocalization::transRoute('routes.eshop-product'),
        ['uses' => 'Eshop\ProductController@show'])
        ->where('eshopCategory', '[a-zA-Z0-9\-/_]+')->where('eshopProduct', '[a-zA-Z0-9_-]+');
```

Did you manage to make this work ?

**Comment by jbajou** [comment]
Ok, found a good-enough solution.
If someone's looking at this, here is the issue. 

Product page with the given url:
`domain.tld/en/eshop/category/clothing/men/sweaters/my-product`
trying to find a product with the slug 'my-product' -> works

On the category page:
`domain.tld/en/eshop/category/clothing/men/sweaters`
trying to find a *product* with the slug 'sweaters' instead of a category with the all path.

## Here is how I fixed it

### Route definition
- Make sure the product page as a slight difference with the category page. my product url is now as follow:
`domain.tld/en/eshop/category/clothing/men/sweaters/p-my-product` (starts with `p-`)

### Controller
- In your controller, double check that the product corresponds to the given category, retrieve the correct one if needed (if you want to handle multiple products with the same slug but in different categories

Thanks for the help @simeonbugarija I have a good enough solution for my project now. Let's move on! (NOT 100% PERFECT, but good enough)
