### ISSUE TITLE
Missing redirect  if hideDefaultLocaleInURL=false

### ISSUE THREAD

**Issue by marcoax** [mcamara/laravel-localization#717]
**Home page  don't redirect to the default locale**
if hideDefaultLocaleInURL=false   the home page is not redirect. to the default  locale

**Expected behavior**
domain.com  -> domain.com/en

**More info:**
- Laravel 7
- Laravel-localization package 1.5
- Which middleware is used in `Route::groups`
localizationRedirect

'useAcceptLanguageHeader' => true,
'hideDefaultLocaleInURL' => false,

**Comment by iwasherefirst2** [comment]
Which middleware are you using?

**Comment by marcoax** [comment]
Hi Adam
I've add all the Middleware  as reported in your documantation
Now work fine

Marco

Il lun 20 apr 2020, 19:02 Adam Nielsen <notifications@github.com> ha
scritto:

**Comment by iwasherefirst2** [comment]
Then everything works fine. Redirects only work with redirecting middleware,
