### ISSUE TITLE
Choose redirection HTTP status code

### ISSUE THREAD

**Issue by aldanux** [mcamara/laravel-localization#724]
It would be nice if there an option to set up the http redirection code in the configuration file: `config/laravellocalization.php`

Example:
```
/* 
 * You can choose here the Redirect Response HTTP Code 
 *
 * Available redirection HTTP Status code: 
 * Permanent: 301
 * Temporary: 302 (by default)
 */
'redirect_response_code' => 301 
```

**Comment by iwasherefirst2** [comment]
You can change the response_code simply by creating your own LaravelLocalizationMiddleware. But why would you ever want to change it to `301` ? That means to SEO's that it is a permanent redirect and it wont considered anymore. And usually, our redirects are based on the users current session language - which is not permanent.
