### ISSUE TITLE
Livewire

### ISSUE THREAD

**Issue by gizburdt** [mcamara/laravel-localization#727]
I'm using Livewire. When I click a wired element, a call is made. When the component refreshes, it uses the default locale.
So I think Livewire isn't aware of the current locale. Do you maybe know  a solutions to this? :)

**Comment by gizburdt** [comment]
I used the mount function within a component to set the locale and then passed it to the render function

**Comment by DanDvoracek** [comment]
I think I face a similar issue. Can I ask you to show an example maybe ? Would be very kind and helpful.

My auth routes are all broken and I feel I have the same issue with wired components.

**Comment by gizburdt** [comment]
Livewire Component:

```
public function mount()
{
        $this->locale = App::getLocale();
}
```

**Comment by DanDvoracek** [comment]
Nice thanks. Unfortunately, that was pretty much what I tried to do without success. I wanted to check if you had another solution. I feel like my problem is related to the Authorization guards in livewire.php config file:

/*
    |--------------------------------------------------------------------------
    | Livewire Endpoint Middleware Group
    | This value sets the middleware group that will be applied to the main
    | Livewire "message" endpoint (the endpoint that gets hit everytime
    | a Livewire component updates). It is set to "web" by default.
    |
    */

Like you I have an error when the component tries to refresh as you can see on the screenshot attached.
![Screenshot 2020-10-05 at 09 56 12](https://user-images.githubusercontent.com/1983331/95053987-7719da00-06f1-11eb-850e-4e1abff282c5.png)

It looks like it is requesting for a http://project.test/**fr**/livewire/message/auth.login , so it's adding the locale here and I guess this is where the error comes from. I might miss a config I am not sure yet.

Also, this all became messy after I installed mcamara localisation package. If I remove it in the Kernel and from the route file, everything is just fine. So I wonder how to make them play together nicely.

Any idea ? I know it's far from your issue, but maybe you have an idea. Do you have some kind of auth on your site too?

**Comment by DanDvoracek** [comment]
I may have found a way to make it all work. I needed to add the following ignored routes in the laravellocalization.php config file:

```
// URLs which should not be processed, e.g. '/nova', '/nova/*', '/nova-api/*' or specific application URLs
// Defaults to []
'urlsIgnored' => ['/livewire/message/auth.login', '/livewire/message/auth.register'],
```

Then I had to amend redirects in Login.php and Register.php. So far, the app behaves as expected.

**Comment by Brouilles** [comment]
I have the same problem. Any fix?
