### ISSUE TITLE
Language flags

### ISSUE THREAD

**Issue by janmoes96** [mcamara/laravel-localization#728]
I'm not sure if it's in your package, but is it possible to have language flag icons to change languages instead of text?

**Comment by johnef** [comment]
I think it's helpful.
 
https://github.com/mcamara/laravel-localization/pull/371#issuecomment-258438015

**Comment by johnef** [comment]
I have worked around this issue by doing this

```
@foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
      <a class="dropdown-item" rel="alternate" hreflang="{{ $localeCode }}"
                href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
                       @if($properties['native'] == "English")
                        <i class="flag-icon flag-icon-gb"></i>
                      @elseif($properties['native'] == "العربية")
                        <i class="flag-icon flag-icon-sa"></i>
                      @endif
              {{ $properties['native'] }}
       </a>
@endforeach
```

I know it's not the best solution but I got what I need. :D

**Comment by amir-habibi-dev** [comment]
i used a simple way and it worked in laravel 7


<li class="dropdown dropdown-language">
        <a data-toggle="dropdown" href="fa" id="dropdown-flag">
            <i class="flag-icon flag-icon-ir"></i>
            <span class="selected-language">{{__('Persian')}}</span></a>
        <div aria-labelledby="dropdown-flag" class="dropdown-menu">
            <a class="dropdown-item" data-language="en" href="en">
                <i class="flag-icon flag-icon-us">
                </i> {{__('English')}}</a>
            <a class="dropdown-item" data-language="fr" href="fr">
                <i class="flag-icon flag-icon-fr">
                </i> {{__('France')}}
            </a>
            <a class="dropdown-item" data-language="de" href="de">
                <i class="flag-icon flag-icon-de"></i>
                {{__('Germany')}}</a>
        </div>
    </li>

**Comment by amir-habibi-dev** [comment]
<li class="dropdown dropdown-language">
        <a data-toggle="dropdown" href="fa" id="dropdown-flag">
            <i class="flag-icon flag-icon-ir"></i>
            <span class="selected-language">{{__('Persian')}}</span></a>
        <div aria-labelledby="dropdown-flag" class="dropdown-menu">
            <a class="dropdown-item" data-language="en" href="en">
                <i class="flag-icon flag-icon-us">
                </i> {{__('English')}}</a>
            <a class="dropdown-item" data-language="fr" href="fr">
                <i class="flag-icon flag-icon-fr">
                </i> {{__('France')}}
            </a>
            <a class="dropdown-item" data-language="de" href="de">
                <i class="flag-icon flag-icon-de"></i>
                {{__('Germany')}}</a>
        </div>
    </li>
