### ISSUE TITLE
Support Laravel 8

### ISSUE THREAD

**Issue by woodspire** [mcamara/laravel-localization#743]

**Comment by gsabater** [comment]
Does anyone know another package that serves the same purpose? 

Every time Laravel releases a major update, this is the package that takes most time to support it when there is already a pull request to adapt it.

**Comment by robinjessome** [comment]
@gsabater -  I've had good luck with https://github.com/codezero-be/laravel-localized-routes

**Comment by yaowei520** [comment]
Is anyone maintaining this project?

**Comment by marcoax** [comment]
Project has been updated to Laravel 8
