### ISSUE TITLE
Error in v1.6

### ISSUE THREAD

**Issue by mikemand** [mcamara/laravel-localization#747]
**Describe the bug**
Laravel didn't introduce `Illuminate\Support\Env` until v6. Currently, if your package is installed in a Laravel 5.8 LTS application, it doesn't work.

**To Reproduce**
1. Create a Laravel 5.x application.
2. Install this package at the latest version acceptable (currently 1.6).
3. Try to use Artisan or view any pages.

**Expected behavior**
There should be no errors.

**More info:**
- Version of Laravel: any 5.x release
- Version of the Laravel-localization package v1.6
- Which middleware is used in `Route::groups`: N/A, happens before even hitting middleware.
- Copy of the config file ( or at least setting of `supportedLocales`, `useAcceptLanguageHeader` and `hideDefaultLocaleInURL`): N/A, happens before config.

**Comment by PoLaKoSz** [comment]
I think it's fixed in #750 (v1.6.1) now.

**Comment by mikemand** [comment]
Thanks! That looks like it did it.
