### ISSUE TITLE
Route caching gives Error 404

### ISSUE THREAD

**Issue by marijoo** [mcamara/laravel-localization#749]
@iwasherefirst2 I created a minimal setup on a fresh Laravel 7 installation and put it in a repo. You can find the commit here:
https://github.com/marijoo/laravel-localization-route-cache/commit/90924fba385ab8e5074ab95a3a1c96f6d6863f36

As you can see this is a minimal setup but the problem occurs as described above:

> This happens with `php artisan optimize`, `php artisan route:cache` as well as with `php artisan route:trans:cache`. After clearing the cache with `php artisan cache:clear` routes work again.

Can you reopen this issue, please? If I can further help, please don't hesitate.

_Originally posted by @marijoo in https://github.com/mcamara/laravel-localization/issues/736#issuecomment-691221984_

**Comment by reganjohnson** [comment]
Having the same issues.

**Comment by iwasherefirst2** [comment]
@marijoo thank you for providing an example. Sorry for taking so long, I had not PHP 7.3 installed and it took me a moment to setup docker.

Anyway, I just noticed that you did not use the `LoadsTranslatedCachedRoutes` trait in your `RouteServiceProvider`. This should definitely be pointed out in the docs. I will create a MR for it.

Btw: `route:cache` will break the usage of this package. And to clear route cache one should use `route:trans:clear`

**Comment by marijoo** [comment]
Whoa, I did not notice anything like this at all. I will try this in the coming week and respond back. Thank you! 🙌🏻

**Comment by hubtraum** [comment]
> Whoa, I did not notice anything like this at all. I will try this in the coming week and respond back. Thank you! 🙌🏻

Had the same issue / did not notice the trait for the RouteServiceProvider. Added the mentioned `LoadsTranslatedCachedRoutes` trait and can confirm this works as expected.

**Comment by marijoo** [comment]
Thank you, I can now confirm this works.
