### ISSUE TITLE
Relative path in localizeURL

### ISSUE THREAD

**Issue by fr8ak2** [mcamara/laravel-localization#751]
Hi guys,

There is a way to get relative path from **localizeURL** method?

I'm using LaravelLocalization::localizeURL('/contacts') and getting absolute path https://domain.com/en/contacts instead of relative /en/contacts?

There is a simple way or need to rewrite **localizeURL** method?

**Comment by iwasherefirst2** [comment]
There is no function in the package that does it. But you can build it yourself using `LaravelLocalization::getCurrentLocale()`
