### ISSUE TITLE
Always negotiate for a redirect

### ISSUE THREAD

**Issue by dennisprudlo** [mcamara/laravel-localization#754]
Hi guys,

maybe I am missing something because it sound so simple to me yet I couldn't find a supported solution to this

**Is your feature request related to a problem? Please describe.**
I want the users always being redirected to a negotiated locale when there is no locale specified in the url. So when they request `example.com/page` they should be redirected to `example.com/en/page`. When they request `example.com/de/page` they shouldn't be redirected since there is a locale given.

I understand there is a session/cookie redirect middleware that does exactly this. But it also stores the locale in the session/cookie. And when a user requests a page again the locale is retrieved from the session/cookie. What I need is, that when a user requests `example.com/fr/page` the localized french version should be visible but when he requests `example.com/page` after that he should be redirected to his language header or the default locale, being `example.com/en/page`.

So to summarize it: The user should be redirected to the negotiated language. He should be able to visit a page in another locale, but without saving that locale as some kind of "new default". 

**Describe the solution you'd like**
An additional middleware would be great that redirects the user to a localized route without saving and retrieved a possibly stored locale from the session/cookie.

**Describe alternatives you've considered**
As of right now I had to create my own middleware that basically has the same logic as the session/cookie redirect middleware, just with a few minor changes such as removing the storing and retrieving part.

As I said, I may have just not found the right configuration for this solution and in that case, I sincerely apologize for wasting your time reading this issue.

**Comment by iwasherefirst2** [comment]
I would not recommend that setup. Instead I would recommend the way this package works, namly if no language is stored in session and you access url without locale, the browser locale will be determined and set.

Anyhow, if you want to use it the way you described, then

1. Don't use any of the redirect middle-ware of this package
2. Write your own middleware that redirects any url without locale to the same url but with locale.

Then just add your custom middleware to the routes:
`
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['yourCustomRedirectMiddleware' ] `

**Comment by dennisprudlo** [comment]
Yes thats what I did, I just wanted to prevent laravel-localization from saving the locale as a new default. I wanted to mimic the behavior of for instance https://n26.com. You get redirected to the locale fitting best for you (in my case `en-de`). You can still choose a specific locale like `de-de` when explicitly accessing https://n26.com/de-de but its not saved as your "new favorite locale".

I just thought since my middleware is basically a copy and pasted `LocaleSessionRedirect` with a few lines removed it would fit nicely in the existing codebase :)

**Comment by iwasherefirst2** [comment]
Thanks for your effort. I guess @mcamara will merge an additional middleware into the codebase, if it is documented properly in the readme

**Comment by marcelosantos89** [comment]
@dennisprudlo I know it's an old topic but can you provide your fix? I have the exact same problem. I want that the person viewing the page gets redirected to their most useful language but then let them be able to change to another language until they change languages again.

**Comment by dennisprudlo** [comment]
@marcelosantos89 I created my own middleware that I use in every project:

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Mcamara\LaravelLocalization\Middleware\LaravelLocalizationMiddlewareBase;
use Mcamara\LaravelLocalization\LanguageNegotiator;

class LocalizationRedirect extends LaravelLocalizationMiddlewareBase {

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next) : mixed {

        //
        // Skip this redirect request when the url should be ignored.
        if ($this->shouldIgnore($request)) {
            return $next($request);
        }

        $params = explode('/', $request->path());

        $localization = app('laravellocalization');

        //
        // If the url contains at least one segment and that segment is a valid and supported locale, continue with the request
        // there is no need to redirect the user hence he already requested a localized url
        if ($localization->checkLocaleInSupportedLocales($params[0])) {
            return $next($request);
        }

        //
        // In any other case (no locale specified) negotiate the user's locale
        // Create the negotiator that considers the language header
        $negotiator = new LanguageNegotiator(
            config('app.locale'),
            $localization->getSupportedLocales(),
            request()
        );

        //
        // Negotiate language using the Accept-Language header
        $locale = $negotiator->negotiateLanguage();

        //
        // If the determined locale is not supported continue the request.
        // Eventually a 404 error page will be raised.
        if (! $locale || ! $localization->checkLocaleInSupportedLocales($locale)) {
            return $next($request);
        }

        //
        // Redirect to the negotiated locale
        $redirection = (string) $localization->getLocalizedURL($locale, request()->url());
        return new RedirectResponse($redirection, 302, ['Vary' => 'Accept-Language']);
    }
}
```

**Comment by marcelosantos89** [comment]
@dennisprudlo thank you so much that will help me 👍. Since i last wrote i changed my LocalSessionRedirect so it only runs once when i enter the site from there the URLs are all translated either way and they can change language

`        // If the URL of the request is in exceptions.
        if ($this->shouldIgnore($request)) {
            return $next($request);
        }

        if(session('localeForce')) {
            return $next($request);
        }

        $params = explode('/', $request->path());
        $locale = session('locale', false);
        session(['localeForce' => true]);`
