### ISSUE TITLE
Redirect to current website

### ISSUE THREAD

**Issue by nathanael79** [mcamara/laravel-localization#755]
Hi, @mcamara 

Im using your package to my website, and after i choose to change the language. Its always redirect to homepage/base url. Can i change it? if i change the language, its stays in the current page but the language is change, i dont want it to redirect to base URL/Homepage

**Comment by iwasherefirst2** [comment]
Please show your config and routes setting

**Comment by nathanael79** [comment]
Hi @iwasherefirst2 

im using this in routes:

` Route::group(
        [
            'prefix' => LaravelLocalization::setLocale(),
            'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ,'redirector' ]
        ], function(){
`

and this is my config:
` 'useAcceptLanguageHeader' => true,
'hideDefaultLocaleInURL' => true,
  'localesOrder' => [],
'localesMapping' => [],
'utf8suffix' => env('LARAVELLOCALIZATION_UTF8SUFFIX', '.UTF-8'),
  'urlsIgnored' => ['/skipped'],`

**Comment by iwasherefirst2** [comment]
1) What is `redirector` middleware?

2) How do you switch the language? If you in lets say `/home/my-site` and you want to switch to german you would need to go to `/de/home/my-site`. Are you doing this?

**Comment by nathanael79** [comment]
@iwasherefirst2 , redirector is my custom middleware its just a middleware that used to redirect to new page (301 redirector), so you can just ignore it.

for the example, im changing from `mysite.com/newsroom` to `mysite.com/zh/newsroom`, using dropdown language selector, and the behaviour is its always be redirect to `mysite.com/zh`.

Is it the right behaviour after choose to change the language?

**Comment by iwasherefirst2** [comment]
Are you sure you accessing `mysite.com/zh/newsroom` from your dropdown and not `mysite.com/zh`? That is not the right behavior. If you start with a fresh Laravel application, then if you access `mysite.com/zh/newsroom` it stays there. Does it redirect always from `mysite.com/zh/newsroom` to `mysite.com/zh` or only on first time? Maybe try to disable your redirect middleware.

**Comment by nathanael79** [comment]
ah i got the problem! thankyou @iwasherefirst2 for helping me, i will close it right now!
