### ISSUE TITLE
Infinite redirect when using a middleware that returns redirect instead of $next($request)

### ISSUE THREAD

**Issue by ProteanCode** [mcamara/laravel-localization#764]
**Is your feature request related to a problem? Please describe.**
The whole library redirects to translated routes using either a language code in URL or by session data. This is fine, but it conflicts with middlewares that redirects somewhere else. On example whenever a new user has been created, he has to fulfill profile data in ie. 3 steps. He is locked in these routes by custom middleware as long as his profile data are not fully set.

For simplicity we may use example of middleware that redirects to /disabled if user has been disabled.

The following code should do the trick

```
public function handle($request, Closure $next)
{
    if ($this->auth->check() && $this->auth->user()->disabled) {
        return Redirect::to('/disabled')
    }
    return $next($request);
}
```

**BUT** this makes a localized redirections impossible since returning a Redirect from middleware triggers infinite loop.

It makes middleware forced to return `$next($request)`

**Describe the solution you'd like**
A something like intended redirection maybe?

**Describe alternatives you've considered**
Hacking the $request object to redirect somewhere else rather to use Redirect facade, but its not a solution that is on production level

**Comment by zippos** [comment]
I had the same big surprise when i've deployed to production.
Apparently the localeSessionRedirect middleware is causing the issue.

**Comment by iwasherefirst2** [comment]
I believe the issue here is `Redirect::to('/disabled')`.


Redirect::to('/disabled') -> redirect to `/en/disabled` -> goes to your middleware and redirects to -> '/disabled' 

which would be an infinite loop. Is it possible?

I guess

``` 
return Redirect::to( LaravelLocalization::localizeUrl('/disabled'))
```

could fix your issue.
