### ISSUE TITLE
Disabled localization for specific URL 

### ISSUE THREAD

**Issue by quentingosset** [mcamara/laravel-localization#772]
Is there a way to prevent automatic URL localization? e.g. to have unique URLs for weebhook etc? Is there a way to prevent automatic URL localization? e.g. to have unique URLs for weebhook etc? 

@mcamara  are you still active on this package ?

**Comment by renepardon** [comment]
@quentingosset Have a look at the published configuration file. There is an option called **urlsIgnored* which is an array of URLS which should be ignored. On the other hand you can just create a route without the localization middlewares.
