### ISSUE TITLE
Hot to display contry code instead of locale 

### ISSUE THREAD

**Issue by odion-cloud** [mcamara/laravel-localization#774]
Hellp please i want to display contry code instead of locale in laravel url  just like paypal e.g domain.com/us/home instead of domain.com/en/home

**Comment by standaniels** [comment]
[Use the `localesMapping` configuration option.](https://github.com/mcamara/laravel-localization#config-files)

**Comment by iwasherefirst2** [comment]
You can rename locales to whatever you want as descriped in https://github.com/mcamara/laravel-localization#map-your-own-custom-lang-url-segments
