### ISSUE TITLE
Cannot translate route

### ISSUE THREAD

**Issue by KyoRion** [mcamara/laravel-localization#775]
I had setup like your video tutorial 
![152735176_715536352657464_3728984260517415517_n](https://user-images.githubusercontent.com/26852023/108825605-d3748c00-75f5-11eb-8801-e475c22a4437.png)
![152737366_419399425793379_1772914634989782307_n](https://user-images.githubusercontent.com/26852023/108825610-d4a5b900-75f5-11eb-93aa-56dc7ba3a25a.png)

But when done and try testing on website I got this error, Can you help me? I was wrong on some step?

![152704478_158855946051040_2855295161035419601_n](https://user-images.githubusercontent.com/26852023/108825792-061e8480-75f6-11eb-8a7b-58d0ab9fdeb2.png)

**Comment by standaniels** [comment]
Your `App\Models\Blog` class extends `Illuminate\Database\Eloquent\Model`. The latter already defines the method `resolveRouteBinding()`, so when you declare the same method on your `App\Models\Blog` class it must be compatible. Look a both method signatures, you'll see that they differ.
