### ISSUE TITLE
 Laravel default locale is not in the supportedLocales array.

### ISSUE THREAD

**Issue by zoxed** [mcamara/laravel-localization#782]
i have a project that works fine, but when i copied it to another folder with everything that has, fixed my database with another name did all the basic stuff but when i tried to serve it it started giving me this error : 

**PS C:\Users\DELL\Desktop\Laravel\e-commerce> php artisan serve

   Mcamara\LaravelLocalization\Exceptions\UnsupportedLocaleException 

  Laravel default locale is not in the supportedLocales array.

  at C:\Users\DELL\Desktop\Laravel\e-commerce\vendor\mcamara\laravel-localization\src\Mcamara\LaravelLocalization\LaravelLocalization.php:145
    141|         $this->defaultLocale = $this->configRepository->get('app.locale');
    142|         $supportedLocales = $this->getSupportedLocales();
    143| 
    144|         if (empty($supportedLocales[$this->defaultLocale])) {
  > 145|             throw new UnsupportedLocaleException('Laravel default locale is not in the supportedLocales array.');
    146|         }
    147|     }
    148| 
    149|     /**

  1   C:\Users\DELL\Desktop\Laravel\e-commerce\vendor\mcamara\laravel-localization\src\Mcamara\LaravelLocalization\LaravelLocalizationServiceProvider.php:55     
      Mcamara\LaravelLocalization\LaravelLocalization::__construct()

  2   C:\Users\DELL\Desktop\Laravel\e-commerce\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
      Mcamara\LaravelLocalization\LaravelLocalizationServiceProvider::Mcamara\LaravelLocalization\{closure}(Object(Illuminate\Foundation\Application), [])       
PS C:\Users\DELL\Desktop\Laravel\e-commerce>**

**Comment by iwasherefirst2** [comment]
1. Make sure you have no cache active: `php artisan config:clear`. 
2. Please post the value of `config/app.php` for locale, also show us the corresponsing value of your `.env` file and please copy paste the complete file `config/laravellocalization.php` into here.
