### ISSUE TITLE
How i can hide default language prefix in url, but for other languages it shows prefix in url  ? , laravel 8

### ISSUE THREAD

**Issue by KaraKala1427** [mcamara/laravel-localization#783]
I want for default language be like `http://127.0.0.1:8000/press/2020` , 
but for other language like `http://127.0.0.1:8000/kz/press/2020`

This is my **web.php** file 
` Route::group(['prefix' => '{language}' ], function (){

    Route::get('/', [HomeController::class, 'index'])->name('index_page');

    Route::get('/product', [ProductController::class, 'index'])->name('product');

    Route::get('/annuitet', [ProductController::class, 'annuitet'])->name('annuitet');

    Route::get('/live', [ProductController::class, 'live'])->name('live');

    Route::get('/retirementinsurance', [ProductController::class, 'retirementinsurance'])->name('retirementinsurance')}); `

My language switcher component code ias below : 
 ` @foreach ($params as $lang =>  $data)
                    <li><a href="{{ route(request()->route()->getName(),$data ) }}">
                            {{ $lang }}
                        </a>
                     </li>
    @endforeach`

Then my setlanguage middleware file's code like this 
`public function handle(Request $request, Closure $next)
    {
        \App::setLocale($request->language);
        return $next($request);
    }`

**Comment by iwasherefirst2** [comment]
boryn is right, set hideDefaultLocaleInURL to true and it should work as expected
