### ISSUE TITLE
When you change hideDefaultLocaleInURL to true, access to the default language not working

### ISSUE THREAD

**Issue by vuongluc** [mcamara/laravel-localization#785]
When you change hideDefaultLocaleInURL to true, access to the default language not working.

My default language is 'vi' when I switch to other languages it works and from other languages to 'vi' it doesn't work. I'm talking about the case of selecting the dropdown box to change the language, not the custom case on the path
![image](https://user-images.githubusercontent.com/54711078/118780922-be3a9100-b8b6-11eb-81e8-4e2749ff0a41.png)

I am using laravel 8 and your package version 1.5.0
Thank you!!

**Comment by MuhammadSadeeq** [comment]
In laravellocalization.php file in config folder, check if the useAcceptLanguageHeader  is set to true. If it is equal to true, change it to false. Then clear your cache by running the command php artisan optimize:clear and hopefully your problem will be solved.

**Comment by vuongluc** [comment]
@MuhammadSadeeq thanks for the answer i tried and still didn't work

**Comment by iwasherefirst2** [comment]
That is the normal behaviour of of LocaleSessionRedirect. If you switch to another language, say English, then `/` is redirected to  `/en` .

From https://github.com/mcamara/laravel-localization#localesessionredirect : 

> If a locale is saved in session redirect to url with locale, unless its the default locale and hideDefaultLocaleInURL is set to true.

Thus, to change from English back to Vietnamese, you have to change url to `/vi` which will change the session and redirect to  `/`.
