### ISSUE TITLE
Issue with Google

### ISSUE THREAD

**Issue by adopteunvpn** [mcamara/laravel-localization#787]
When I search my website on Google, sometime it gives me englisg version of my website even if Im in France.
Its a big problem for me because of visitors will leave if they go on a webpage they dont understand.

I search "my website.com" and I have
page1/en
page2/fr
page3/es
etc etc

Do you have any idea for this ?

**Comment by Stelikas** [comment]
**On-page Markup**

When supporting multiple languages, you should clearly mark up with language meta-data.

Use the lang attribute in the html tag:

`<html lang="en">`
Use rel alternate links to the same page in other languages as suggested by Google:

```
<link rel="canonical" href="http://www.example.com/">
<link rel="alternate" hreflang="es" href="http://www.example.com/es" />
<link rel="alternate" hreflang="en" href="http://example.com/en" />
```

Alternately, this information can be put into sitemap files.

**Tell Google About Your Site**

You should add each language (or locale) of your site to Google Webmaster Tools. This can be done for top level domains, for sub- domains, or for sub-directories.

If your site is targeted by country, you should use webmaster tools to set the site targeting. Navigate to "Configuration" -> "Settings" -> "Geographic target" and choose to target the correct country from the drop down list.

**Comment by iwasherefirst2** [comment]
Agree with Seltikas, using html tag and hreflang keys to fix this. Also make sure that you have no English content on page1/fr etc.
