### ISSUE TITLE
Return to default locale after removing the locale from URL

### ISSUE THREAD

**Issue by Stelikas** [mcamara/laravel-localization#788]
**Describe the solution you'd like**
For example when i'm in `https://example.com/en` and manually remove` /en` the locale shall change to the default one

Is this kind of thing possible in the current stage of the package? 

Thanks and regards.

**Comment by standaniels** [comment]
If either `LocaleSessionRedirect` or `LocaleCookieRedirect` middleware is in use, the locale is stored in the session or cookie respectively. You could remove those middlewares to let the package decide which locale should be used on every request without a locale. Or, when requesting `/`, you could remove the saved locale from the session/cookie just before the package middleware is ran.

**Comment by iwasherefirst2** [comment]
If you use `LocaleSessionRedirect` middleware then this is exactly the behaviour.
