### ISSUE TITLE
Show All The Supported Locals without enabling them to be accessed

### ISSUE THREAD

**Issue by Prography-Co** [mcamara/laravel-localization#790]
What I'm building is an admin panel that can add new language to the website or delete one, so I was searching for a way to do that, and what I did is something like this:
1- added (**_allSupportedLocals_**) to the config file, which is an array of all supported locals, and left the (**_supportedLocals_**) with the website default language.
2- made a middleware which will check the enabled languages in the database, and copy their data from (**_allSupportedLocals_**) to (**_supportedLocals_**) using config();
3- in the admin panel I use data from _**allSupportedLocals**_ for the language list. **Still Making This, Not Sure If It Will Work Well Or Not**

I know there ware a lot of problems with what I made but I'm doing my best solving it, so I hope that you make us a way to do this.

thanks for your great effort helping us
Prography.Co
Ahmed Salheia

**Comment by Prography-Co** [comment]
Sorry I forgot to mention that this thing didn't work, So I'm searching for a way to do that.

**Comment by iwasherefirst2** [comment]
If you want to let an admin add/delete languages, I would suggest the following:

1) create a table wich contains the languages that your website supports
2) in the config file,  create the `supportedLocales` dynamically from the table
3) If you use caching, then you need to refresh the config cache and the [localized routes](https://github.com/mcamara/laravel-localization#caching-routes) by using Artisan::call('config:cache') and Artisan::call('route:trans:cache')

**Comment by cristian-araujo** [comment]
> If you want to let an admin add/delete languages, I would suggest the following:
> 
> 1. create a table which contains the languages that your website supports
> 2. in the config file,  create the `supportedLocales` dynamically from the table
> 3. If you use caching, then you need to refresh the config cache and the [localized routes](https://github.com/mcamara/laravel-localization#caching-routes) by using Artisan::call('config:cache') and Artisan::call('route:trans:cache')

I want to do the same thing but I think it's not a good idea put database logic inside a config file...
do you have another solutions for it?
