### ISSUE TITLE
localizeUrl not working

### ISSUE THREAD

**Issue by jatleti** [mcamara/laravel-localization#793]
Hi! it's seems that localizeUrl is not working on blade. transRoute works perfectly and detects routes.php into lang folder, but localizeUrl none

It's in a new project, in other project (last year) it works perfectly.

Thanks!!

**Comment by ArtMin96** [comment]
Same problem here.

"laravel/framework": "^7.30.4",
"mcamara/laravel-localization": "^1.6"

**Comment by jatleti** [comment]
"laravel/framework": "8.52",
"mcamara/laravel-localization": "1.6.1"

**Comment by iwasherefirst2** [comment]
Could you provide a coding example? Its very helpful for us if you use the template for issues that we have created (expected behavior, steps to reproduce, description of the bug etc.).

And what exactly is not working?

**Comment by jatleti** [comment]
I wrote a helper to use the functions that works on the project, sure I forgot a lot of things, but the work it's done till I find an official solution. It's called instead of localizeUrl

`function getUrl($url = null, $params = null) {
    $first = substr($url, 0, 1);
    if ($first === '/') { 
        $url = substr($url, 1);
    }
    if ($params){
        return LaravelLocalization::getURLFromRouteNameTranslated(LaravelLocalization::getCurrentLocale(),'routes.'.$url, $params);
    }
    return LaravelLocalization::getURLFromRouteNameTranslated(LaravelLocalization::getCurrentLocale(),'routes.'.$url);
}`

**Comment by ArtMin96** [comment]
Code:

```
@foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
    <li>
        <a class="dropdown-item" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}" data-lang="en" rel="alternate">
            <img src="../../images/flag/{{ $localeCode }}.png" class="g-lang-flag" alt="flag"> {{ $properties['native'] }}
        </a>
    </li>
@endforeach
```

**Comment by jatleti** [comment]
> Could you provide a coding example? Its very helpful for us if you use the template for issues that we have created (expected behavior, steps to reproduce, description of the bug etc.).
> 
> And what exactly is not working?

Yes!! 

return LaravelLocalization::localizeUrl(LaravelLocalization::transRoute('routes.auth/sign-in'));

localizeUrl returns a non translate url in this case.

**Comment by ArtMin96** [comment]
There is no way that I can switch locales

**Comment by ArtMin96** [comment]
Before redirect route: "services/notarized-translations"
After redirect url is: "services/notarized-translations?q=%2Fservices%2Fnotarized-translations"

**Comment by martin-ro** [comment]
Suddenly see the same problem

**Comment by iwasherefirst2** [comment]
> return LaravelLocalization::localizeUrl(LaravelLocalization::transRoute('routes.auth/sign-in'));
> 
> localizeUrl returns a non translate url in this case.
@jatleti 
transRoute and localizeUrl should not be mixed up. 

The purpose of `transRoute` is to actually translate the route in different languages, see https://github.com/mcamara/laravel-localization#translated-routes

The purpose of `localizeUrl` is to append the correct lang prefix on the url(de/en/...) but it does not translate the url into another language.

If this is still an issue, please open a new issue and fillout our template (expectation, steps to reproduce).

> There is no way that I can switch locales
@ArtMin96 locales are set depending on the url that you call?

@martin-ro Is it possible that your route `/` is named `slug-string` ? Otherwise, also please create a new issue, fill out the template with instructions how to reproduce this. If I try `LaravelLocalization::localizeURL('slug-string)` then it works for me.

**Comment by ArtMin96** [comment]
> > return LaravelLocalization::localizeUrl(LaravelLocalization::transRoute('routes.auth/sign-in'));
> > localizeUrl returns a non translate url in this case.
> 
> @jatleti transRoute and localizeUrl should not be mixed up.
> 
> The purpose of `transRoute` is to actually translate the route in different languages, see https://github.com/mcamara/laravel-localization#translated-routes
> 
> The purpose of `localizeUrl` is to append the correct lang prefix on the url(de/en/...) but it does not translate the url into another language.
> 
> If this is still an issue, please open a new issue and fillout our template (expectation, steps to reproduce).
> 
> > There is no way that I can switch locales
> 
> @ArtMin96 locales are set depending on the url that you call?
> 
> @martin-ro Is it possible that your route `/` is named `slug-string` ? Otherwise, also please create a new issue, fill out the template with instructions how to reproduce this. If I try `LaravelLocalization::localizeURL('slug-string)` then it works for me.

Yes
