### ISSUE TITLE
How we can use it to get slug from relation table

### ISSUE THREAD

**Issue by ma3achou** [mcamara/laravel-localization#802]
I explain,

I have a product table and product_translation table.

**_Product_** have information doesn't need to be translated as _ID_, _Price_ ...
**Product_Translation** have _Product_id_, _Locale_, _Name_, _Description_, _Slug_.

And others table are like that ... Categoriers relation with Category_translations.

And I have a helpers with : 

> function localized_url($locale, $url = null) {
        return LaravelLocalization::getLocalizedURL($locale, $url);
    }

How I can get the slug translated with LaravelLocalization.

**Comment by iwasherefirst2** [comment]
Did you read https://github.com/mcamara/laravel-localization#translated-routes and watched https://www.youtube.com/watch?v=B1AUqCdizgc?
