### ISSUE TITLE
Redirecting to Default Language

### ISSUE THREAD

**Issue by DilanTsasi** [mcamara/laravel-localization#803]
#### Redirecting to Default language does not work unless I add the local to the URL
---
In the config, I have set 
```bash
hideDefaultLocaleInURL' => true,
```
and my default language is EN.

I have a section in my blade view that changes languages as follows
```bash
@foreach (LaravelLocalization::getSupportedLocales() as $key => $value)
   <a href="{{ LaravelLocalization::getLocalizedURL($key, Request::url()) }}" class="p-2  mr-2 text-lg flex content-center">
      <span>{{$value['name']}}</span>
   </a>   
@endforeach
```
When I Switch to any language, it works fine. But ones I switch to the default language, it redirects me to the previously Selected Language unless I manually add 'en' to the URL

**Comment by otherprod** [comment]
Hi, how did you deal with that problem please ?

**Comment by otherprod** [comment]
I found  that by removing cookies or session middleware this work as i wanted, so if a person change language multiple time, language change correctly without defaultlocal in url
