### ISSUE TITLE
how to set the locale depending on the domain

### ISSUE THREAD

**Issue by kvinkinamoto** [mcamara/laravel-localization#808]
how to set the locale depending on the domain
say from test.com should be en, and from test1.som fr

**Comment by iwasherefirst2** [comment]
Do you mean you don't want to use `/de` or `/fr` in the url for your website? In this case, this package does not support changing locale between domains, sorry.

**Comment by MatthiasBrodelet** [comment]
Is this still the case?
I am trying to build a website that uses a different domain for each language but can't find any solution using this package.

**Comment by BrilliantItRepo** [comment]
> Do you mean you don't want to use `/de` or `/fr` in the url for your website? This package does not support changing locale between domains, sorry.

Yes you right.
