### ISSUE TITLE
Language selector is generating http links and not https

### ISSUE THREAD

**Issue by batgos** [mcamara/laravel-localization#809]
**Describe the bug**
On some pages only when I'm selecting a language in the language selector the link is in HTTP and not HTTPS
![image](https://user-images.githubusercontent.com/9460795/149165399-e1dc487c-f20d-415c-bd7e-05493020ae04.png)

**To Reproduce**
1. Go on Page (Only happens on some pages)
2. Choose a language in the selector
3. Check the link

**Expected behavior**
Should be only HTTPS link

**More info:**
- Version of Laravel : ^6.0
- Version of the Laravel-localization package : ^1.4
- Which middleware is used in `Route::groups`
- 'prefix' => LaravelLocalization::setLocale(),
   'middleware' => ['localeSessionRedirect', 'web'],
- Copy of the config file ( or at least setting of `supportedLocales`, `useAcceptLanguageHeader` and `hideDefaultLocaleInURL`) :
   'supportedLocales' => [
        'en'          => ['name' => 'English',                'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB'],
        'es'          => ['name' => 'Spanish',                'script' => 'Latn', 'native' => 'español', 'regional' => 'es_ES'],
    ],
    'useAcceptLanguageHeader' => false,
    'hideDefaultLocaleInURL' => false,

**Additional context**
Language Selector code :
`@foreach (LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
            <a rel="alternate" class="dropdown-item" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}" >
{{ ucfirst($properties['native']) }}
</a>
        @endforeach`

**Comment by marcbelletre** [comment]
I guess you have to update your .env file and set `APP_URL` with https instead of http.

**Comment by batgos** [comment]
Thanks for your answer but it's only on a few pages that it's happened...Most of the pages have HTTPS links in the selector that's why I don't understand

**Comment by marcbelletre** [comment]
Could you provide any example? Like screenshots of one of the pages showing HTTP links instead of HTTPS and another one showing HTTPS links as expected?  

Also did you update your `APP_URL` as I suggested?

**Comment by iwasherefirst2** [comment]
@batgos yes, an example would be good. Please provide a reproducible example. Also, it is possible that you sometimes open your app via http and sometimes via https and that this is the factor?

**Comment by iwasherefirst2** [comment]
It looks like an configuration issue, assuming it has been resolved if not, please post example here to reopen the ticket
