### ISSUE TITLE
Set language on queue mails

### ISSUE THREAD

**Issue by cristian-araujo** [mcamara/laravel-localization#811]
**Describe the bug**
I need set the language in the queue emails, this doesn't work `LaravelLocalization::setLocale('es');` also it doesn't work `putenv(LaravelLocalization::ENV_ROUTE_KEY . '=' . 'es');`

**To Reproduce**
send a queue email with translations, it will take the default language.

**More info:**
- Version of Laravel: Laravel Framework 8.80.0
- Version of the Laravel-localization package: ^1.6
- Which middleware is used in `Route::groups` - nothing, it's queue mail
- Copy of the config file ( or at least setting of `supportedLocales`, `useAcceptLanguageHeader` and `hideDefaultLocaleInURL`).
- Minimal steps to reproduce on a clean Laravel installation.

**Comment by mreduar** [comment]
@cristian-araujo Can you share the solution to this?

**Comment by cristian-araujo** [comment]
> @cristian-araujo Can you share the solution to this?

It worked correctly, I misspelled a word in my object-model when selecting the language.

anyway, this my `build function` inside the `mailable`, maybe it help you, if not open a new issue to try reproduce your problem

```PHP
public function build(AbstractSetting $abstractSetting, GeneralSetting $generalSetting)
{
        LaravelLocalization::setLocale($this->TrabajoLibre->lang);
        return $this->from($generalSetting->email_username, $generalSetting->name)
            ->view('abstract::mail.trabajo_libre.autor_invitation', compact('abstractSetting'));
}

```
