### ISSUE TITLE
route caching don't work in laravel 8

### ISSUE THREAD

**Issue by StefanoTesla** [mcamara/laravel-localization#813]
**Describe the bug**
Laravel route cache don't work in laravel 8

**More info:**
- Version of Laravel latest
- Version of the Laravel-localization package latest
- Which middleware is used in `Route::groups`

`Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ] <-added now for testing
    ], function()
{`

- Copy of the config file ( or at least setting of `supportedLocales`, `useAcceptLanguageHeader` and `hideDefaultLocaleInURL`).
`    'useAcceptLanguageHeader' => false,
    'hideDefaultLocaleInURL' => true,
    'localesOrder' => [],
    'localesMapping' => [],
    'urlsIgnored' => ['/skipped'],
    'httpMethodsIgnored' => ['POST', 'PUT', 'PATCH', 'DELETE'],`

**Comment by iwasherefirst2** [comment]
Which command did you use to cache the routes?

**Comment by StefanoTesla** [comment]
`php artisan route:trans:cache` the provided one, but if I get `php artisan route:list` only locale urls are listed

**Comment by StefanoTesla** [comment]
is very unstable under laravel 8, after purging cache route are aviable but not listed, I named a route and now I get 404 to all english (not locale) routes...

**Comment by StefanoTesla** [comment]
Ok ok, I found how reproduce the problem.

1) run `php artisan route:trans:cache`
2) translated pages return 404
3) `php artisan route:clear`
4) translatd pages are aviable

**Comment by StefanoTesla** [comment]
can I retrive some more information??

**Comment by iwasherefirst2** [comment]
I just installed latest Laravel app and tried it out, it works. Did you add ` use \Mcamara\LaravelLocalization\Traits\LoadsTranslatedCachedRoutes;` to your RouteServiceProvider as explained in readme?

If it still doesnt work, try if this works for you, because this is working for me:
```

<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale()], function()
{
    Route::get('/test', [\App\Http\Controllers\TestController::class, 'test']);
});

```

```

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TestController extends Controller
{
    public function test()
    {
        return 55;
    }
}

```

And no changes to config/laravellocalization.php

**Comment by StefanoTesla** [comment]
MY web.php is this:


`Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    ], function()
{
	/** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
	Route::get('/', function()
    {
		return View::make('home');
	});

    Route::get(LaravelLocalization::transRoute('slug_azienda'), function () {
        return view('azienda');
    })->name('azienda');
}
`

The slug_azienda is stored inside the local and other language json file.


My config is that I post in the first post...

**Comment by iwasherefirst2** [comment]
Okay, and did you add use \Mcamara\LaravelLocalization\Traits\LoadsTranslatedCachedRoutes; to your RouteServiceProvider as explained in readme?

**Comment by StefanoTesla** [comment]
Aaaarghh... Sorry this was missing!! Now works as expected, Thank you so
much!

Il lun 24 gen 2022, 22:13 Dr. Adam Nielsen ***@***.***> ha
scritto:
