### ISSUE TITLE
Livewire Requests change the Current Locale

### ISSUE THREAD

**Issue by fritzfr** [mcamara/laravel-localization#814]
**Describe the bug**

When a Livewire component makes a request after the page has been loaded, it changes the current locale to a different locale.

**To Reproduce**
1. Implement a Livewire component that does any kind of networking after page load, e.g.:
```php
    public function render()
    {
        return view('livewire.show-teams', [
            // does a search request via Laravel Scout
            'schools' => School::search($this->search)->paginate(8),
        ]);
    }
```
2. Go to the page containing the component, with a localized URL, e.g. `/en/schools`, then trigger the request (e.g. search in above example)
3. The locale will change to a different locale.

Showing the bug: Notice how the URL has the `de` prefix, and it changes from de to en (It's printing `{{ \Mcamara\LaravelLocalization\Facades\LaravelLocalization::getCurrentLocale() }}` in this example:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/49151885/151575899-7724765c-91d3-4379-93f1-948f19860c1c.gif)

**Expected behavior**
The locale should remain whatever is set by the URL.

**More info:**
- Version of Laravel: 8.80.0
- Version of the Laravel-localization package: 1.7.0
- Which middleware is used in `Route::groups`: localeSessionRedirect
- Copy of the config file ( or at least setting of `supportedLocales`, `useAcceptLanguageHeader` and `hideDefaultLocaleInURL`): see above
- Minimal steps to reproduce on a clean Laravel installation: see above

**Additional context**
My setup is pretty much what is recommended in the readme:
```php
'supportedLocales' => [
  'de'          => ['name' => 'German',                 'script' => 'Latn', 'native' => 'Deutsch', 'regional' => 'de_DE'],
  'en'          => ['name' => 'English',                'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB'],
],
'hideDefaultLocaleInURL' => false,
'useAcceptLanguageHeader' => true,
```

web.php:
```php
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect']], function() {
// school route is here
```

Kernel.php:
```php
    protected $routeMiddleware = [
        // ...
        'localize'                => LaravelLocalizationRoutes::class,
        'localizationRedirect'    => LaravelLocalizationRedirectFilter::class,
        'localeSessionRedirect'   => LocaleSessionRedirect::class,
        'localeCookieRedirect'    => LocaleCookieRedirect::class,
        'localeViewPath'          => LaravelLocalizationViewPath::class
    ];
```

**Comment by Mattia-Marchiorato** [comment]
We have the same problem, after the component request the language return to default.
Now we solved in the view with `LaravelLocalization::getURLFromRouteNameTranslated(App::currentLocale(), 'routes.register')`

**Comment by fritzfr** [comment]
I think the problem is that the requests are being routed through `/livewire/message/`, which probably lack the localization logic and everything breaks.

**Comment by fritzfr** [comment]
I found a solution to this. The problem is indeed the missing middleware and routing for the livewire routes. I stumbled across https://forum.laravel-livewire.com/t/post-404-with-livewire-mcamara-laravel-localization/1659, and slightly modified the solution there:

After including the livewire scripts:

app.blade.php (Root Template):
```php
        @livewireScripts // includes Livewire scripts for me
        <script>
            window.livewire_app_url = "{{ \Illuminate\Support\Facades\Request::getSchemeAndHttpHost() }}/{{ \Mcamara\LaravelLocalization\Facades\LaravelLocalization::getCurrentLocale() }}"
        </script>
```

And in web.php:
```php
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect']], function() {
    Route::post('livewire/message/{name}', '\Livewire\Controllers\HttpConnectionHandler');
    // ... other routes
});
```
