### ISSUE TITLE
Not Working Properly

### ISSUE THREAD

**Issue by zdarin** [mcamara/laravel-localization#817]
Hello,

I installed [laravel-localization] on Laravel v8.83.1 (PHP v8.1.0) and not working a lot of features for example need 2 times refresh to change locale if hideDefaultLocaleInURL true then default locale cant be switched
I deleted  \App\Http\Middleware\LocalizationMiddleware::class from $middlewareGroup and now works but not all features for example locales sorting not working

**Comment by adymilk** [comment]
I have the same problem. not working on laravel 8
