### ISSUE TITLE
in api routes localization not working  

### ISSUE THREAD

**Issue by DilmurodQurbonboyev** [mcamara/laravel-localization#818]
```


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
    ],
    function () {

        Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
            return $request->user();
        });

        Route::apiResource('menus-category', MenusCategoryController::class);
    }
);


```

**Comment by gharabaghi** [comment]
same problem. 
maybe the cause is that 'api' word is appearing before language keyword.

**Comment by GergoKormoczy** [comment]
https://github.com/mcamara/laravel-localization/issues/862#issuecomment-1488826834

**Comment by fahadapps79** [comment]
add ["Accept": "application/json"] to header of the request

**Comment by iwasherefirst2** [comment]
Thank you for raising this issue. However, the problem lacks a clear description of what is not working.

If you can provide more details, such as the expected and actual behavior, error messages, or steps to reproduce, feel free to add them and reopen the issue.

Thank you for understanding!

> maybe the cause is that 'api' word is appearing before language keyword.

Thank you for your input! Based on the provided routes file, it doesn’t appear that api is placed before the language keyword. However, if you have structured your routes such that `api` appears before the language segment, the plugin will not be able to handle that scenario as expected.
