### ISSUE TITLE
LARAVEL 9

### ISSUE THREAD

**Issue by juliangarcess** [mcamara/laravel-localization#819]
The plugin isn't working on Laravel 9

**Comment by usernotnull** [comment]
I upgraded to L9 and it's working normally...
Your issue is not helpful since it doesn't tell the author what the problem is!

**Comment by juliangarcess** [comment]
> I upgraded to L9 and it's working normally...
> Your issue is not helpful since it doesn't tell the author what the problem is!

can you help me upgrading?

juliangarces.jg@gmail.com thanks

**Comment by juliangarcess** [comment]
When importing the prefix LaravelLocalization::setLocale() to my routes, this message appears "Non static method 'setLocale' should not be called statically."
