### ISSUE TITLE
localesMapping not respected in getURLFromRouteNameTranslated()

### ISSUE THREAD

**Issue by jandol5** [mcamara/laravel-localization#831]
**Describe the bug**
When localesMapping is set, some of translated urls are incorrect.

**To Reproduce**
1. Setup Laravel and laravel-localization
2. Set localesMapping in config to something like:
`'localesMapping' => [
  'sl' => 'si',
],`

**Expected behavior**
All urls should get localized according to new mapping. Instead, I experienced some strange results:
- on english page, links to Slovenian page are /sl/slovenian-slug instead of /si/slovenian-slug
- on slovenian page, links to English page are /en/slovenian-slug instead of /en/english-slug

**More info:**
- Version of Laravel: 8.82.0
- Version of the Laravel-localization package: 1.7.0
- Which middleware is used in `Route::groups`: 'localeCookieRedirect', 'localeSessionRedirect', 'localize'
- Copy of the config file ( or at least setting of `supportedLocales`, `useAcceptLanguageHeader` and `hideDefaultLocaleInURL`):
<code>
    'supportedLocales' => [
        'en'    => ['name' => 'English',                'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB'],
        'hr'    => ['name' => 'Croatian',               'script' => 'Latn', 'native' => 'hrvatski', 'regional' => 'hr_HR'],
        'sl'    => ['name' => 'Slovene',                'script' => 'Latn', 'native' => 'slovenščina', 'regional' => 'sl_SI'],
        'sr'    => ['name' => 'Serbian',        'script' => 'Latn', 'native' => 'Srpski', 'regional' => 'sr_RS'],
    ],
 </code>
 <br>
<code>
'useAcceptLanguageHeader' => false,
 </code>
<br>
<code>
'hideDefaultLocaleInURL' => false,
 </code>
<br>
<code>
    'localesMapping' => [
        'sl' => 'si',
        'sr' => 'rs',
    ],
</code>

- Route caching is enabled ([https://github.com/mcamara/laravel-localization/blob/master/CACHING.md](https://github.com/mcamara/laravel-localization/blob/master/CACHING.md)) and works as expected.
- Minimal steps to reproduce on a clean Laravel installation: Install Laravel, Laravel-localization, setup test route, set config like stated above.

**Possible fix**
I traced down the issue to the way [$route is set in getURLFromRouteNameTranslated()](https://github.com/mcamara/laravel-localization/blob/27565315c585e90d8d93aa06afd49d6a5992fe5a/src/Mcamara/LaravelLocalization/LaravelLocalization.php#L377). To fix the issue I changed it from
`$route = '/'.$locale`
to
`$route = '/'.$this->getLocaleFromMapping($locale);`.
Since `getLocaleFromMapping()` returns locale even when mapping is not set, this fix is also suitable for cases when no localesMapping is set in config.

**Comment by iwasherefirst2** [comment]
Since this issue was posted in 2022 and hasn’t had any updates, I’ll assume it’s no longer relevant and close it for now.

If the issue persists, please feel free to reopen it. In that case, providing a minimal repository with a fresh Laravel application, your Laravel Localization setup, and the two URLs you're testing would be very helpful. With that, I’d be happy to take a closer look.
