### ISSUE TITLE
Optimize extractAttributes() for lots of translatable and regular routes

### ISSUE THREAD

**Issue by jangaraev** [mcamara/laravel-localization#840]
**Is your feature request related to a problem? Please describe.**
Method `extractAttributes()` gets extremely slow for 60+ translatable routes.

We use the `localizeUrl()` method in blade file where we render a locale switcher. Noticed in xdebug that this method takes a very long time, in particular its inner call of `extractAttributes()` method.

Calling `getLocalizedURL()` without `extractAttributes()` gives us 2x 3x faster results and doesn't brake anything for our case.

**Describe the solution you'd like**
Can we have a possibility to call the `localizeUrl()` or `getLocalizedURL()` without inner call of `extractAttributes()`?

**Describe alternatives you've considered**
()

**Additional context**
Let me recheck this a bit later today. So I will add more context here.

**Comment by iwasherefirst2** [comment]
In this case, I recommend overriding the `LaravelLocalization` class and customizing the `getLocalizedURL` method to suit your specific needs.

Regarding the performance of `extractAttributes`, have you identified the source of the slowdown? I noticed it calls `$this->router->getRoutes()`, which could be a potential bottleneck. However, this should perform efficiently if you’ve cached the routes.

If you have ideas to optimize `extractAttributes`, we’d appreciate your input—feel free to share them or submit a pull request. If you prefer to adapt it specifically for your use case, overriding the class would be the best approach.

Feel free to reopen this issue if you have further questions.
