### ISSUE TITLE
routes.translation event listen

### ISSUE THREAD

**Issue by AndriiTereshchuk** [mcamara/laravel-localization#847]
Hello! I'm not very familiar with Laravel, could you tell me how to create it correctly? I want to store the user's language in the database

**Comment by iwasherefirst2** [comment]
Thank you for your question. However, this repository is focused on issues related to the LaravelLocalization package, and general Laravel questions like this are beyond its scope. I recommend checking out the [Laravel documentation](https://laravel.com/docs) or asking your question on Laravel forums.
