### ISSUE TITLE
How to use this package to automatically redirect my site to the Web Browser's default language if my language URL is of type "get" whose language setting name is "lang"

### ISSUE THREAD

**Issue by chegmarco1989** [mcamara/laravel-localization#848]
Hello.

I don't see anywhere in the README File **how to use this package to automatically redirect my site to the Web Browser's default language if my language URL is of type `get` whose language setting name is `lang`** like this:

**French:** https://ourwebsite.com/login?lang=fr
**English:** https://ourwebsite.com/login?lang=en
**Spanish:** https://ourwebsite.com/login?lang=es
**German:** https://ourwebsite.com/login?lang=de

???

Please answer us through sample code as it is clearer with sample code.
Waiting for a favorable reply.

**Comment by iwasherefirst2** [comment]
I’m not sure how the `lang` query parameter is relevant if you’re aiming to detect the language based on the browser’s default language.

If you enable the `useAcceptLanguageHeader` option in your configuration and use the `localeSessionRedirect` middleware, your application will automatically detect the closest language supported by your app that matches the browser’s language preferences. This detection is based on the priority of languages set in the browser.

For example, if your browser’s primary language is German, visiting `your-example-website.com/login` via a GET request will redirect you to `your-example-website.com/de/login`.

Here’s how you can configure the middleware in your routes:
```
Route::group(
[
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localeSessionRedirect', /* other middlewares */],
], function () {
    // Your routes here
});

```
