### ISSUE TITLE
see routes in all language files

### ISSUE THREAD

**Issue by mertbuldur** [mcamara/laravel-localization#850]
```
 $route = collect(app('router')->getRoutes())->first(function($route) use($url){
            return $route->matches(request()->create($url));
 });
```
I'm trying to catch the current rotation at the current address with this code, but only the rotations in lang/fr/routes.php are listed. The rotations in lang/en/routes.php are not listed, so when switching from en to fr, I can't catch the current url.

**Comment by iwasherefirst2** [comment]
Not sure what you mean with rotations, but the package only loads the routes in the current locale.

If you access .../fr/... then the ../en/.,. routes are not loaded in `app('router')->getRoutes()`.


thats because the routes are loaded like this
``` 
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect'],
    ],
    function () {
```

Maybe you looking for this? Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect'],
    ],
    function () {
