### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by AndriiTereshchuk** [mcamara/laravel-localization#851]
Good afternoon! I created a backend router in RouteServiceProvider::boot():
```
Route::middleware('backend'')
                 ->prefix('backend')
                 ->group(base_path('routes/backend.php'));
```

In the 'routes/backend.php' file:
```
Route::group([
     'prefix' => LaravelLocalization::setLocale(),
     'middleware' => ['localize', 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
], function() {

     Route::get('/', function () {
         returnview('welcome');
     });
    
});
```

But I get a 404 error, what did I do wrong? Or is the system not working?

**Comment by Hani221b** [comment]
same here!

**Comment by iwasherefirst2** [comment]
Closing this as there was no response from OP, so I guess was a cache issue.

Please remember, this package is not compatible with normal route:cache artisan command. You need to call https://github.com/mcamara/laravel-localization#caching-routes instead

**Comment by turkimud** [comment]
I have the same issue. I fix it in:
mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php

change this:
`public function setLocale($locale = null)
    {
        if (empty($locale) || !\is_string($locale)) {
            // If the locale has not been passed through the function
            // it tries to get it from the first segment of the url
            $locale = $this->request->segment(1);`

to:
`public function setLocale($locale = null, $segmentNum = 1)
    {
        if (empty($locale) || !\is_string($locale)) {
            // If the locale has not been passed through the function
            // it tries to get it from the first segment of the url
            $locale = $this->request->segment($segmentNum);`

use it like this:

`Route::group([
     'prefix' => LaravelLocalization::setLocale(null, 2),`
