### ISSUE TITLE
Google Search engine

### ISSUE THREAD

**Issue by CovertError** [mcamara/laravel-localization#853]
okay isn't really a bug atleast i dont think so is there recommendations  or tips for google seo I'm getting an error with google search engine console saying Redirect error because its being redirected from the main domain url to the locale meaning its going from example.com to like example.com/en any ideas or recommendations

**Comment by arcanaer** [comment]
I can to recommend you to add href link tags to your head, to all pages. Also you can change the lang selector and use javascript ro redirect.

<link rel="alternate" href="http://example.com" hreflang="es" />
<link rel="alternate" href="http://example.com/fr/" hreflang="fr" />
<link rel="alternate" href="http://example.com/pt/" hreflang="pt" />

**Comment by iwasherefirst2** [comment]
Can you provide the exact error message from Google and maybe also show us your config, middleware, routes?

**Comment by iwasherefirst2** [comment]
Closing as not resolvable without error message
