### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by Grazulex** [mcamara/laravel-localization#858]
Hello,

When this projet will be comptabible with Laravel 10 ?

Thanks

**Comment by duikb00t** [comment]
+1

**Comment by rororomeda** [comment]
+1

**Comment by GergoKormoczy** [comment]
+1

**Comment by mozex** [comment]
+1

**Comment by kvinkinamoto** [comment]
+1

**Comment by dennisprudlo** [comment]
+1

Usually the major version was updated before release making the package compatible from the beginning. Maybe @mcamara is busy at the moment, so for now a simple fork allows us to upgrade to Laravel 10. The fork can be switched out once the package is compatible again.

**Comment by jarvis-tang** [comment]
+1

**Comment by mozex** [comment]
I think this repository is abandoned; the last release was on Jan 26, 2022.

**Comment by Grazulex** [comment]
Somebody have made a marge request for laravel 10... https://github.com/mcamara/laravel-localization/pull/857
I hope that the dev will accept this..

**Comment by mcamara** [comment]
I’ve created a new release that should be compatible with laravel 10. Thanks to @laravel-shift for his help creating the PR.
