### ISSUE TITLE
hideDefaultLocaleInURL isn't working fully?

### ISSUE THREAD

**Issue by PivanDepolo** [mcamara/laravel-localization#859]
**Describe the bug**
Hello! I have the option to hide the URL for the default locale enabled. 

**To Reproduce**
1. Open website
2. Change language
3. Change to default language
4. Check url.

**Expected behavior**
URL should be hidden after switching back to the default locale

**More info:**
- Laravel 10.1.1
- Latest
- Route::group(['prefix' => LaravelLocalization::setLocale()], function()
- `supportedLocales` has default settings, 'useAcceptLanguageHeader' => true, `'hideDefaultLocaleInURL' => true

**Comment by denkata** [comment]
Hello, try to add the `LaravelLocalizationRedirectFilter::class` middleware to your routes.

**Comment by PivanDepolo** [comment]
> LaravelLocalizationRedirectFilter::class

It works! You are genius. 
Thank you sir!
