### ISSUE TITLE
LaravelLocalizationViewPath Usage

### ISSUE THREAD

**Issue by tolgacibikci** [mcamara/laravel-localization#863]
I want to use 8 different languages (de, en, es, fr, it, pt, tr, ar). Text in 7 languages is written from left to right. But in arabic the text is written from right to left. So I just want to use a different views for arabic. It works if I create views for each language separately. But I want to use a common view for 7 languages and a different view for arabic.

My views like that(Always showing (resources/client/...) views);

resourses
-- views
--- client
---- ....
--- ar
---- client
----- ...

url: hotsname.com/ar/login => view: resources/views/client/...

If I delete the resources/views/client folder:
url: hotsname.com/ar/login => view: resources/views/**ar**/client/...

Is it possible?
If current locale views are exists shows these views.
Otherwise shows common views.

url: hotsname.com/en/login => view: resources/views/client/...

url: hotsname.com/de/login => view: resources/views/client/...

url: hotsname.com/ar/login => view: resources/views/**ar**/client/...

**Comment by iwasherefirst2** [comment]
This issue seems to be out of the scope of this package, as it's more related to handling views in your application logic. You can achieve your goal using a simple view helper in your controllers. Here's an example:

```
if (!function_exists('localized_view')) {
    /**
     * Return a localized view if it exists, otherwise fallback to the default view.
     *
     * @param string $view The base view name (e.g., 'client.login')
     * @return \Illuminate\Contracts\View\View
     */
    function localized_view(string $view)
    {
        $locale = app()->getLocale();
        $localizedView = "{$locale}." . $view;

        if (view()->exists($localizedView)) {
            return view($localizedView);
        }

        return view($view);
    }
}
```
