### ISSUE TITLE
any way to set supported langue dynamically ?

### ISSUE THREAD

**Issue by eslamsa3ed** [mcamara/laravel-localization#865]
I'm building Sass and each client has the ability to set the supported languages for their customers. I wonder if there is any clear way to override the getSupportedLocale function.

**Comment by yassinetrbls** [comment]
Hello ? any insights ?

**Comment by sgms-top** [comment]
yes i'm already done that from database

**Comment by iwasherefirst2** [comment]
To dynamically set supported languages in the mcamara/laravel-localization package, you can override the getSupportedLocales function to fetch locales from a dynamic source, such as a database. Here's how you can achieve this:

1. Extend the LaravelLocalization Class: Create a new class that extends the LaravelLocalization class provided by the package.

```
<?php

namespace App\Services;

use Mcamara\LaravelLocalization\LaravelLocalization;

class CustomLaravelLocalization extends LaravelLocalization
{
    public function getSupportedLocales()
    {
        // Fetch supported locales dynamically, e.g., from a database
        // Example:
        // return \App\Models\Locale::all()->pluck('name', 'code')->toArray();

        // For demonstration, returning a static array
        return [
            'en' => ['name' => 'English', 'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB'],
            'es' => ['name' => 'Spanish', 'script' => 'Latn', 'native' => 'Español', 'regional' => 'es_ES'],
            // Add other locales as needed
        ];
    }
}
```

2. Bind the Custom Class in a Service Provider: In your application's service provider (e.g., AppServiceProvider), bind your custom class to replace the package's implementation.
```

<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use App\Services\CustomLaravelLocalization;
use Mcamara\LaravelLocalization\LaravelLocalization;

class AppServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->singleton(LaravelLocalization::class, CustomLaravelLocalization::class);
    }

    public function boot()
    {
        //
    }
}

```

This binding ensures that when the LaravelLocalization class is resolved, your custom implementation is used. (Assuming AppServiceProvider is called after LaravelLocalizationProvider.

Please note that this approach renders the supportedLocales configuration option in config/laravel-localization.php unnecessary.
