### ISSUE TITLE
Is there any way to use country code in url?

### ISSUE THREAD

**Issue by Rohit-laravel** [mcamara/laravel-localization#866]
I want to use country code along with locale in my routes.
`e.g.: http://127.0.0.1:8000/ch-en/about, http://127.0.0.1:8000/ch-de/about`

Is there any way to handle above case ?

Thanks

**Comment by iwasherefirst2** [comment]
Sure, just add them to your laravellocalization.php and rename the language folders inside resource/lang/ accordingly
