### ISSUE TITLE
How to store users default language into database

### ISSUE THREAD

**Issue by jobasco** [mcamara/laravel-localization#883]
Hi, thanks a lot for this wonderfull pacpage, i want to dect my registred users default language from the browser and store it in database(users table).
I am new to laravel and php.
Please help.

**Comment by StefanoTesla** [comment]
create a user colum called locale and update it when user change...
And then use a middlware firing App::setLocale($locale);

**Comment by iwasherefirst2** [comment]
This functionality falls outside the scope of the package. You can achieve it by creating a middleware to check if the user is logged in, retrieve their locale, and update it in the database.
