### ISSUE TITLE
Localization not working in 1st reload Laravel

### ISSUE THREAD

**Issue by audentodigital** [mcamara/laravel-localization#886]
Once I click on the language switcher the URL changes but the website content is updated in the 2nd reload. Why?

More info:

Version of Laravel : 10
Version of the Laravel-localization package : 1.8
Which middleware is used in Route::groups : 'localize','localeSessionRedirect', 'localizationRedirect', 'localeCookieRedirect'
Copy of the config file ( or at least setting of supportedLocales : all, useAcceptLanguageHeader : true and hideDefaultLocaleInURL:false).

**Comment by audentodigital** [comment]
There are no cache issues, even in the local and live same issue happening

**Comment by audentodigital** [comment]
http:// autobahntrucking . audentodigital. in

**Comment by fonz-lu** [comment]
Did you resolve your issue @audentodigital ? I am having the same problem.

The correct locale is displayed with LaravelLocalization::getCurrentLocale() on the first page load, but the rest is just updated on the a second reload?

Thank you

**Comment by audentodigital** [comment]
Yes. It was a conflict. For my case, I also created a custom middleware for Localization. Please check if you tried any other Localization solution and the older files still present in it.

**Comment by fonz-lu** [comment]
That was it, I still had a different localisation middelware. Thanks
