### ISSUE TITLE
Wrong redirect afert login

### ISSUE THREAD

**Issue by pixsolution** [mcamara/laravel-localization#890]
Hello

I'm using Laravel 9 with jetstream, I followed this issue [https://github.com/mcamara/laravel-localization/issues/752](url) it works but the only problem I currently have is with the redirect after login, it does not add the /prefix for example /en it take me to the normal url http://localhost.com/dashboard how did you solve this?

Regards

**Comment by iwasherefirst2** [comment]
Hi there,

Thank you for reporting this issue! Unfortunately, the details provided are a bit unclear, and I’m unable to fully understand or reproduce the problem at this time. Could you please provide more information to help us investigate further? Specifically:

    The exact route you are encountering this issue with.
    The middleware you are using in your route group.
    Any additional context about your application setup that could help us pinpoint the issue (e.g., the value of LocaleSessionRedirect or other related settings).

Without these details, it’s difficult to determine whether this is related to something like the LocaleSessionRedirect middleware or another part of the setup.

I’ll temporarily close this issue for now, but feel free to reopen it once you’ve added the requested information. Thank you!
