### ISSUE TITLE
Class "Inertia\Inertia" not found error

### ISSUE THREAD

**Issue by pixsolution** [mcamara/laravel-localization#891]
Hello, I followed this issue https://github.com/mcamara/laravel-localization/issues/773 for my laravel jestream with livewire project and almost work everything but when I enter in jestream views for eg. http://localhost.com/es/user/profile it show me "Class "Inertia\Inertia" not found error" I think it's because I moved all the routes from the jetstream vendor to my routes file...do you think that's it? If so, how to solve it?

**Comment by jordyvanderhaegen** [comment]
Hi @pixsolution, I'm closing this issue as it doesn't include enough information to reproduce the problem. Please feel free to reopen it with a reproducible example.

**Comment by rahmanpoor** [comment]
Note that this path does not recognize Inertia class.
vendor/laravel/jetstream/src/Http/Middleware/ShareInertiaData.php:23

You should add this class by this command:
**composer require inertiajs/inertia-laravel**

The problem will be solved and enjoy.
