### ISSUE TITLE
Is it possible to use a different path

### ISSUE THREAD

**Issue by ronrun** [mcamara/laravel-localization#892]
My folder:
app\Sections\Admin\Http
app\Sections\Admin\Lang
app\Sections\Admin\Lang\en\...
app\Sections\Admin\Lang\zh_TW\...
app\Admin\View

app\Sections\Public\Http
app\Sections\Public\Lang
app\Sections\Public\Lang\en\...
app\Sections\Public\Lang\zh_TW\...
app\Sections\public\View

Is it possible to do like the above?

**Comment by iwasherefirst2** [comment]
The LaravelLocalization package does not support this kind of structure by default. It relies on Laravel's default localization system, which expects language files to be located in the `resources/lang` or `lang` directory (depending on Laravel Version). To make your desired structure work, you would need to customize Laravel’s translation loader and potentially adjust how translations are loaded within the application. However, this customization is outside the scope of what the package supports directly.
