### ISSUE TITLE
localization route not working after php artisan route:cache I get 404

### ISSUE THREAD

**Issue by MilanUnjiya4149** [mcamara/laravel-localization#893]
localization route not working after php artisan route:cache. It's return 404.
It's work perfect without route cache.

1. Create route in web.php
  Route::group(
      [
          'prefix' => LaravelLocalization::setLocale(),
          'middleware' => ['localize']
      ], function () {
          Route::get('/', 'HomeController@index')->name('index');
      }
  );
 2. php artisan route:cache

Localization route should work after php artisan config:cache

- Version of Laravel: 9.0
- Version of the Laravel-localization package: 1.8
- Which middleware is used in `Route::groups`: LaravelLocalizationRoutes

**Comment by ianfortier** [comment]
@juliangarcess The caching (artisan route:trans:cache) doesn't work either

**Comment by MilanUnjiya4149** [comment]
#904 

`class AppServiceProvider extends ServiceProvider
{
    use \Mcamara\LaravelLocalization\Traits\LoadsTranslatedCachedRoutes;

    public function boot(): void
    {
        RouteServiceProvider::loadCachedRoutesUsing(fn() => $this->loadCachedRoutes());
        ...
    }`

This solution is working fine. ☺
