### ISSUE TITLE
Change params on changing language

### ISSUE THREAD

**Issue by Misagh90** [mcamara/laravel-localization#896]
Hi,
Is there any way that when i use `{{ LaravelLocalization::getLocalizedURL('en') }}`, the changing language changes with the params?

my sample params:
https://127.0.0.1:8000/fa/محصولات?pack=شیشه&category=سیروپ
https://127.0.0.1:8000/en/products?pack=glass&category=syrups

or any other solution without the `{{ LaravelLocalization::getLocalizedURL('en') }}`?

**Comment by iwasherefirst2** [comment]
We have a section about translatable routes in the documentation, which should help you handle the route translation, for example:
../products (English) ↔ ../محصولات (Farsi).

For the query parameter values like pack and category, this is something you need to handle on your own, as it’s not related to the package. You’ll need to create and manage a mapping system for these values.

Here’s a brief example of how you could implement such a mapping (Example):

```
$translations = [
    'fa' => [
        'pack' => ['شیشه' => 'glass'],
        'category' => ['سیروپ' => 'syrups'],
    ],
    'en' => [
        'pack' => ['glass' => 'شیشه'],
        'category' => ['syrups' => 'سیروپ'],
    ],
];

// Detect the current and target locale
$currentLocale = app()->getLocale();
$targetLocale = 'en'; // or the desired language

// Translate query parameters
$queryParams = request()->query();
foreach ($queryParams as $key => $value) {
    if (isset($translations[$currentLocale][$key][$value])) {
        $queryParams[$key] = $translations[$currentLocale][$key][$value];
    }
}

// Generate the localized URL
$localizedURL = LaravelLocalization::getLocalizedURL($targetLocale, null, $queryParams);
```

Summary

    - Use the package’s translatable routes feature for the path translation (e.g., /products ↔ /محصولات).
    - Implement your own mapping logic for translating query parameter values like pack and category, as this is outside the scope of the package.

Let us know if you have further questions!
