### ISSUE TITLE
Laravel 11 Support.

### ISSUE THREAD

**Issue by jevantang** [mcamara/laravel-localization#899]
Laravel 11 has been released

thank you

**Comment by jevantang** [comment]
@mcamara Laravel 11 Is it still supported?

**Comment by Genius-code** [comment]
package still not support new version from laravel

**Comment by relaypilot** [comment]
After using mcamara's package for several years (that seems abandoned for the last year+), I switched today to https://github.com/codezero-be/laravel-localized-routes . The switch was very easy and it offers support for L11.

**Comment by cleargoal** [comment]
> After using mcamara's package for several years (that seems abandoned for the last year+), I switched today to https://github.com/codezero-be/laravel-localized-routes . The switch was very easy and it offers support for L11.

Thank you!

**Comment by ahmedsayedabdelsalam** [comment]
@mcamara php artisan route:cache also route:trans:cache return 404 in laravel 11

**Comment by ahmedsayedabdelsalam** [comment]
https://github.com/laravel/framework/pull/51249

**Comment by ahmedabdel3al** [comment]
https://github.com/laravel/framework/pull/51292

**Comment by ahmedabdel3al** [comment]
https://github.com/mcamara/laravel-localization/pull/902

**Comment by ahmedabdel3al** [comment]
#902

**Comment by dani-vrd** [comment]
> [laravel/framework#51292](https://github.com/laravel/framework/pull/51292)
> 
> after laravel add new method `loadCachedRouteUsing` to `RouteServiceProvider`
> 
> ```
> class AppServiceProvider extends ServiceProvider
> {  
>     use \Mcamara\LaravelLocalization\Traits\LoadsTranslatedCachedRoutes;
>     /**
>      * Bootstrap any application services.
>      */
>     public function boot(): void
>     {
>         RouteServiceProvider::loadCachedRoutesUsing(fn() => $this->loadCachedRoutes());
>         ...
>     }  
> ```

Thank you very much for your effort! Works now like a charm! 🙂
