### ISSUE TITLE
How can add alias middleware on laravel 11 

### ISSUE THREAD

**Issue by Enadabuzaid** [mcamara/laravel-localization#901]
I want to add these in laravel 11 

    'localize'                => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
    'localizationRedirect'    => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
    'localeSessionRedirect'   => \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
    'localeCookieRedirect'    => \Mcamara\LaravelLocalization\Middleware\LocaleCookieRedirect::class,
    'localeViewPath'          => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationViewPath::class

**Comment by battulga0719** [comment]
Hello. you need to put it in **bootstrap > app.php** you can find a doc in laravel https://laravel.com/docs/11.x/middleware#middleware-aliases

->withMiddleware(function (Middleware $middleware) {
        $middleware->alias([
            'PreventRequestsDuringMaintenance' => \App\Http\Middleware\PreventRequestsDuringMaintenance::class,
            'localize'                => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
            'localizationRedirect'    => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
            'localeSessionRedirect'   => \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
            'localeCookieRedirect'    => \Mcamara\LaravelLocalization\Middleware\LocaleCookieRedirect::class,
            'localeViewPath'          => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationViewPath::class
        ]);
    })
