### ISSUE TITLE
got 404 not found after using php artisan route:trans:cache

### ISSUE THREAD

**Issue by mgaber2024** [mcamara/laravel-localization#904]
**Describe the bug**
I got 404 after I used php artisan route:trans:cache command and added  
use \Mcamara\LaravelLocalization\Traits\LoadsTranslatedCachedRoutes; in route service provider as described in the docs 

**Expected behavior**
I should can access the app  routes normally

**More info:**
- Version of Laravel 10.48.11
- Version of the Laravel-localization package 2.0.1
- Which middleware is used in `Route::groups`
  'localeSessionRedirect',
  'localizationRedirect',
  'localeViewPath'
- Copy of the config file
```php
  'supportedLocales' => [
 'en'          => ['name' => 'English',                'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB'],
    'ar'          => ['name' => 'Arabic',                 'script' => 'Arab', 'native' => 'العربية', 'regional' => 'ar_AE'],
]

 'useAcceptLanguageHeader' => true,

  'hideDefaultLocaleInURL' => false,

`

**Comment by tringuyenduc2903** [comment]
Two ways to solve this problem
https://github.com/mcamara/laravel-localization/issues/899#issuecomment-2096959567
```php
class AppServiceProvider extends ServiceProvider
{
    use \Mcamara\LaravelLocalization\Traits\LoadsTranslatedCachedRoutes;

    public function boot(): void
    {
        RouteServiceProvider::loadCachedRoutesUsing(fn() => $this->loadCachedRoutes());
        ...
    }
```

(or)

https://github.com/mcamara/laravel-localization?tab=readme-ov-file#caching-routes
```php
<?php
class RouteServiceProvider extends ServiceProvider
{
    use \Mcamara\LaravelLocalization\Traits\LoadsTranslatedCachedRoutes;
```

**Comment by MilanUnjiya4149** [comment]
> ```
> RouteServiceProvider::loadCachedRoutesUsing(fn() => $this->loadCachedRoutes());
> ```

This solution is working.

@tringuyenduc2903 Thank You ☺
